### ISSUE TITLE
Spell check

### ISSUE THREAD

**Issue by NotThatSmith** [saenzramiro/rambox#10]
On OSX when words are spelt incorrectly there is no red line underneath like there usually would be in a browser.

**Comment by saenzramiro** [comment]
Nice detail! I will take a look, but maybe is an Electron bug.

**Comment by litlplastkastl** [comment]
Hi, I am using windows and I don't seem to have spell check either.

**Comment by saenzramiro** [comment]
Enabling spell check in Rambox is not easy. There are a few libraries to enable this, but are limited and only for English.

We will wait until Electron provide an easy API to enable.

Related saenzramiro/rambox#141

**Comment by aravindhp** [comment]
Have you looked at the [electron spellcheck API](https://github.com/electron/electron/blob/master/docs/api/web-frame.md#webframesetspellcheckproviderlanguage-autocorrectword-provider) or [electron-spell-check-provider](electron-spell-check-provider)?

**Comment by saenzramiro** [comment]
Yes, but if I remember the only supported language is **en_US**. Am I wrong?

I tried to add this feature but no luck. I don't remember what was the problem right now.

**Comment by aravindhp** [comment]
You might be right. It will be nice to have this feature even if only for en_US and add other languages as they become available.

**Comment by saenzramiro** [comment]
I will take a look again for a future release. SpellCheck API it is available for a while and seems like they are not adding other languages yet. 😞

**Comment by aravindhp** [comment]
After using RamBox for a month I realized how dependent I am on spell check. So I am forced to uninstall RamBox and go back to having multiple browser tabs open :disappointed: Keeping my fingers crossed that this feature will makes it way into a future release.

**Comment by agiveon** [comment]
Why in this issue closed? Has it been solved? Spellchecking (US ENG) still not working.

**Comment by litlplastkastl** [comment]
i got a message 6 days ago from somebody that stated that the spell check
does not work so they uninstalled. I have stopped using the program, i need
it for work and things need to be spelled correctly.

I still follow the emails in case it is ever fixed so i can use it again.

2016-11-01 6:28 GMT-06:00 agiveon <notifications@github.com>:

**Comment by dhornbein** [comment]
Has there been any movement on this? it's a fairly big deal for me too.

**Comment by saenzramiro** [comment]
We will add Spellcheck in v1.0.0.
