### ISSUE TITLE
Couldn't open app window if minimized (Ubuntu 16.04)

### ISSUE THREAD

**Issue by Huaba** [saenzramiro/rambox#100]
If i minimize Rambox with the indicator menu it's not possible to reopen it and show the app window again. Label in indicator always show "minimize Rambox" and click on the Rambox launcher icon opens a new app window.

Would be great to resize the app with the indicator menu.

Greetz and thx for your great work.

Huaba

**Comment by thuandt** [comment]
I have same issue.
Can we have "Show window" in indicator menu icon?

**Comment by saenzramiro** [comment]
I will fix this for the next release.
