### ISSUE TITLE
Can't install .deb Rambox_0.5.10-x64

### ISSUE THREAD

**Issue by V-Grade** [saenzramiro/rambox#1001]
I can't install the newest version of Rambox with the deb package in x64 on a Ubuntu 17.04.

### Steps to reproduce

1. sudo dpkg -i Rambox_0.5.10-x64.deb

### Actual behavior

dpkg-deb: error: `Rambox_0.5.10-x64.deb » Is not an archive of Debian format

### ENVIRONMENT

> Rambox: v0.5.10

> OS: Ubuntu 17.04

> Arch: x64

**Comment by saenzramiro** [comment]
Does anyone have this error too?

**Comment by Crystal-RainSlide** [comment]
@V-Grade Try download it again unless you sure about the file you downloaded is complete.
