### ISSUE TITLE
Unable to download images from whatsapp

### ISSUE THREAD

**Issue by galangel** [saenzramiro/rambox#1004]
go to chat 
click on image
click on download arrow

expected result 
open save prompt
actual result
nothing happens 

	
	-
	> Rambox 0.5.10
	> Electron 1.7.4
	> darwin x64 16.6.0

**Comment by FabianBeiner** [comment]
See https://github.com/saenzramiro/rambox/issues/998

**Comment by tobi-the-fraggel** [comment]
Kinda works on windows. I needed to manually append '.png' suffix. I would expect it knows the data type of what it is downloading.

**Comment by saenzramiro** [comment]
Duplicate #998
