### ISSUE TITLE
Rocketchat opening SSO in new browser window

### ISSUE THREAD

**Issue by biggestchops** [saenzramiro/rambox#1005]
### Steps to reproduce
I want to start by saying you guys are doing a great job, rambox is awesome. 
1. Connect to company's rocketchat instance (chat.consulting.redhat.com)
2. Click google auth button
3. New browser opens to handle sso

### Expected behavior
SSO should be handled within rambox

### Actual behavior

Since SSO opens in new browser, I can't auth within rambox, and thus can't connect to rocketchat.

### ENVIRONMENT

Fedora 26, rambox installed using feddy, x85_64
Version: 0.5.10
Platform: linux (x64)
Electron: 1.7.4
Chromium: 58.0.3029.110
Node: 7.9.0

> OS: XXXX

> Arch: x64 or ia32

**Comment by saenzramiro** [comment]
This is a known behaviour. That's why we display a note in the window when you want to add Rocket Chat saying:

> You have to use this service by signing in with your email or username (No SSO allowed yet).

SSO that use the popup option is not working in Rambox in any service.

**Comment by jorgemoralespou** [comment]
@saenzramiro does this mean that it will not be allowed, or there's another issue tracking this feature as a request?
