### ISSUE TITLE
Inbox and Hangouts notifications

### ISSUE THREAD

**Issue by gkurdej** [saenzramiro/rambox#1006]
I have configured Hangouts and Inbox (by Google) services in Rambox. Inbox has built in support of Hangouts. When I receive Hangouts notification, I constantly receive notifications from Inbox in the form of constantly appearing system tray notifications.

Regards,
Grzegorz

	
	-
	> Rambox 0.5.10
	> Electron 1.7.4
	> win32 x64 6.1.7601

**Comment by carlosmu** [comment]
I have the same issue.

**Comment by saenzramiro** [comment]
Please read this: https://github.com/saenzramiro/rambox/wiki/Inbox
