### ISSUE TITLE
Rambox is not initially executable in Ubuntu 15.10

### ISSUE THREAD

**Issue by jrhenderson1988** [saenzramiro/rambox#101]
Upon downloading and extracting the archive, the Rambox executable file is not executable by default. Running a `chmod a+x Rambox` on it works. Not much of an issue but could be something to look at.

Cheers.

**Comment by saenzramiro** [comment]
Well... there is a Wiki for installing it in Linux. (https://github.com/saenzramiro/rambox/wiki/Install-on-Linux)

Also, someone created a video tutorial for Linux [HERE](https://www.youtube.com/watch?v=SH6o92b7FlA).
