### ISSUE TITLE
Typos to fix

### ISSUE THREAD

**Issue by brendanjones** [saenzramiro/rambox#1012]
A couple of suggestions from a native English editor. I'm afraid I'm not a dev so I'm just going to make the issue and let some other poor sod make the changes. :)

- [ ] Mouseover text for "Don't disturb: OFF/ON": for the first sentence, change to "Disable notifications and sounds for all services." for the second sentence, I'd argue to remove it completely as it's unnecessary. If you must keep it, change to "Perfect for staying focused."
- [ ] change "Enter a temporal password to unlock it later" to "Enter a temporary password to unlock it later"...or even better, just "Enter a temporary password" as the rest of the sentence is superfluous.
- [ ] Second password window: change "Repeat the temporal password" to "Repeat the temporary password"

**Comment by cocolote** [comment]
I'll be happy to take care of this issue.

**Comment by saenzramiro** [comment]
Thank you @brendanjones.

@cocolote Thank you also, you can change it in Crowdin (https://crowdin.com/project/rambox).
