### ISSUE TITLE
Suggestion: don't show the "share your love for Rambox" popup on first session

### ISSUE THREAD

**Issue by brendanjones** [saenzramiro/rambox#1013]
I think it's bad UX to show the popup asking the user to share Rambox on social media when they open Rambox for the first time. They know precisely zero about how much they love Rambox, so why would they tweet about it? Also, it interrupts onboarding flow.

I'm talking about this popup:

![screen shot 2017-07-21 at 11 34 56](https://user-images.githubusercontent.com/16049594/28461109-6aa34cf2-6e15-11e7-8dc4-53b089c94cd3.png)

**Comment by brendanjones** [comment]
Also, don't show this after every time you refresh the app:

![screen shot 2017-07-21 at 14 13 26](https://user-images.githubusercontent.com/16049594/28470217-5a543e78-6e39-11e7-818a-8edad14f6ad4.png)

**Comment by saenzramiro** [comment]
We cannot change the UI of those modals, because we use Tooltip.io to do it and the design is restricted... but thanks.

**Comment by brendanjones** [comment]
bummer.
