### ISSUE TITLE
UI suggestion: change button text when editing a service

### ISSUE THREAD

**Issue by brendanjones** [saenzramiro/rambox#1015]
When editing preferences for an individual service, the two button options are 'cancel' and 'edit [service name]'

You already know what service you're editing, so change the longer 'edit [service name]' button text to the simpler 'Save'.

Talking about this window, FYI:

![screen shot 2017-07-21 at 13 50 48](https://user-images.githubusercontent.com/16049594/28462456-aa787a54-6e1b-11e7-9041-2ae2bcfc2867.png)

**Comment by saenzramiro** [comment]
Ok, we will consider this. Thanks
