### ISSUE TITLE
UI Suggestion: change display ratio of 'Add a new service'/'Enabled services'

### ISSUE THREAD

**Issue by brendanjones** [saenzramiro/rambox#1016]
On my 13in screen, the apps on the Add a new Service side display in two columns, which makes for a long list. The Enabled Services side doesn't need to be as wide as it is (no app name is longer than 150px), so why not make Add a new Service 2/3 width and Enabled Services 1/3, instead of 50:50? In other words, force the apps to display in 3 columns at that resolution.

How it looks on my screen:

![screen shot 2017-07-21 at 12 49 54](https://user-images.githubusercontent.com/16049594/28460815-14f77b94-6e14-11e7-8557-5ef9a78589b3.png)

**Comment by brendanjones** [comment]
Ah, just seen http://rambox.pro/100/ .  Will not be surprised if this is fixed in that release.

**Comment by saenzramiro** [comment]
I think we can change this for next release.
