### ISSUE TITLE
Bug: edit preferences window not closing, but is saving

### ISSUE THREAD

**Issue by brendanjones** [saenzramiro/rambox#1017]
### Steps to reproduce

1. Open an app's preferences.
2. Change a setting. Doesn't matter which one(s).
3. Try saving changes by clicking the 'edit [app name]' button
4. The window doesn't close, but any preferences changes are saved, even if you close the window with the 'cancel' button.
5. If you re-open the preferences after making changes but then clicking 'cancel', the changes you made were actually saved

### Expected behavior
Pref window closes when saving preferences

### Actual behavior

The button to save changes doesn't work. This only occurs for some apps, not all. (for me, Gitter, 2 of my 4 Slack teams, and Skype. Whatsapp and Messenger pref changes work fine)

### ENVIRONMENT

> Rambox: 0.5.10

![screen shot 2017-07-21 at 11 59 42](https://user-images.githubusercontent.com/16049594/28462764-04f1c2d2-6e1d-11e7-8f2c-77fa570970ec.png)

**Comment by gingerbeardman** [comment]
https://github.com/saenzramiro/rambox/issues/931

**Comment by brendanjones** [comment]
Damnit. Searched issues and didn't see anything. Obvs didn't search hard enough.
