### ISSUE TITLE
Typo in social media sharing text from http://rambox.pro/100/

### ISSUE THREAD

**Issue by brendanjones** [saenzramiro/rambox#1018]
When sharing Rambox on FB and Twitter from http://rambox.pro/100/, the text says 'the future is comming'.

Might want to change that to _coming_ (single m)

**Comment by FallenKN** [comment]
`31 <meta property="og:title" content="Rambox - The future is comming..."/>
34 <meta property="og:site_name" content="Rambox - The future is comming..."/>
202 a href="http://twitter.com/share?text=I donated to @ramboxapp team for developing the new version. The future is comming! Please, support Rambox!&amp;url=http://rambox.pro/100&amp;hashtags=rambox
" target="_blank" class="btn btn-twitter text-uppercase btn-lg">Twitter <span class="icon-twitter" aria-hidden="true"></span></a> `

**Comment by saenzramiro** [comment]
Thanks!
