### ISSUE TITLE
Link on Skype opens 8 tabs in browser

### ISSUE THREAD

**Issue by adambro** [saenzramiro/rambox#102]
When I click on link on Skype it then opens 8 tabs in browser (Chrome or Firefox). 4 of them open the link, the other 4 following address: https://web.skype.com/en/undefined

I guess what happens is there is some nasty loop and in certain cases variable is undefined, hence "/undefined" at the end of URL.

Antergos (Arch Linux) 64bit
Gnome 3.20
Rambox 0.3.0 from AUR (aur/rambox-bin 0.3.0-1)

**Comment by thuandt** [comment]
I have same issues before in old version.

In version 0.4.0 it still open https://web.skype.com/en/undefined but NOT 8 tabs

**Comment by saenzramiro** [comment]
#11

**Comment by vunhan** [comment]
I'm using rambox ver *0.4.0* and this bug is still happenned.
Now my browser open 2 tab, included https://web.skype.com/en/undefined.
