### ISSUE TITLE
[Feature Request] Add Zulip Support

### ISSUE THREAD

**Issue by geekdave** [saenzramiro/rambox#1021]
5k github stars, and a popular chat platform.  Would love to see support for Zulip in Rambox!

https://zulip.org/
https://github.com/zulip/zulip

**Comment by saenzramiro** [comment]
Nice, we can add it in a future release. Thanks!

**Comment by saenzramiro** [comment]
Seems like Zulip doesn't have a web client accessible via URL. 😢

**Comment by adambirds** [comment]
@saenzramiro Zulip does indeed have a web client accessible via URL, for example my self hosted Zulip web app is at https://chat,adbtechltd.co.uk. I believe it should be similar to the way you access the self-hosted Rocket-Chat
