### ISSUE TITLE
discord tab alert

### ISSUE THREAD

**Issue by tobi-the-fraggel** [saenzramiro/rambox#1022]
https://i.gyazo.com/df314fa9641cde76c5b84d194d81c8ab.png

Dunno why but for me the red alert tag always stays on the tab. I visited all servers chats and all private chats (that took quite some time), I marked them 'read all' but still the alert stays.

Anyone else experienced this so far?

**Generaly notice:**
I just installed rambox. So this report is created on first time usage. This means cache cannot be an issue and it also means I could be the issue but I just don't know it yet ;)
Anyhow, I don't know what else I could do to make the alert disappear. It works fine on other apps I have added like slack, skype, whatsapp and steam chat.

Thank you for your attention.
tobi

	
	-
	> Rambox 0.5.10
	> Electron 1.7.4
	> win32 x64 6.1.7601

**Comment by saenzramiro** [comment]
The red dot is for unread messages in groups, but seems like is not working correctly. I will check Discord again for next release to see what is happening.

Thanks.

**Comment by n0v3xx** [comment]
Habe the same problem. Its realy annoying :/

**Comment by n0v3xx** [comment]
I think its a problem with the friends notification.
https://abload.de/img/bildschirmfotovom20171zs0n.png

Every time i click on "Add Friends" it adds aditional 23 unread messages.

**Comment by tobi-the-fraggel** [comment]
23? Illuminati confirmed.
Well, 23 is a weird number. Is that coincidentally the total number of "friends" on your discord?

I need to say that I am not experiencing that particular issue. Friend requests do work as one would expect them to work.

Back on topic. @saenzramiro from my pov you can close this ticket. I finally found out that the alert was correct. So the whole issue is a user fault actually. I am going to explain how I solved the issue for me though, cause it's a pitfall others might also fall into.

As you expect discord notifies you if you are tagged. It also notifies you about new content. New content notifications look like the icon I linked in the OP.  Now, the issue is that some discord servers use a trick to group their channels into logical entities. E.g they would create a channel like [[---> admins <----]] and have all admin channels underneath. This trick is used to emulate a collapsable channel structure which discord lacks to this day. Therefore a real hierarchical channel structure cannot be build. Anyhow, these "separation" channels often are configured to be inaccessible for users. If a channel is inaccessible I can't join it and I won't trigger the "is read" switch (or whatever its called in discord)!
That's why I had the tag on the discord tab all the time, because I had a few of these "seperation" channels across my subscribed servers which were "unread" (bold white font). In order to get rid of these notices you need to do two things:
1. Click on the channel and tick the bell icon next to the search bar in order to mute the channel. This will prevent you from ever getting any notices again about that channel.
2. Right click on a server icon and hit the "Mark as read" option. All channels within that server will be marked read recursively, even these "seperation" channels. Check the linked image if you don't understand where to go. [https://i.imgur.com/GiW6IPm.png](url)

After I did that with all my servers the alert tag finally disappeared from the discord tab.

I am sorry @saenzramiro you had to invest some time on this. Maybe it wasn't all for nothing however. Imo you should consider to add an option allowing rambox users to suppress these kind of discord alerts. It doesn't really add much information really. The nature of discord is to have a larger number of servers you subscribe to. Therefore the chance of having a channel somewhere in some server with a new message in it is very high. I only have 6 servers in my server list and whenever I mark all servers read it usually doesn't take much longer then a minute till I see the tag on the tab again. I would prefer to only see an alert if I receive a direct notification.
Thanks for your time and good luck with Rambox. It's an adorable tool and very shortly it reached up to the top 3 programs I run on windows.

**Comment by n0v3xx** [comment]
hey tobi, 23 was the friend suggestion from discord. Since i connect discord to my LoL friend list he make me friend suggestions. This suggestions are appear as new messages?! That is total wrong and i cant remove this notification. The only way is to delete the friend suggestion. Thats is clearly a bug.
