### ISSUE TITLE
Feature Request: Unseen at Facebook Messenger

### ISSUE THREAD

**Issue by DungxNguyen** [saenzramiro/rambox#1023]
Could you please add feature to disable "seen" as a option for Facebook Messenger. 

For example, I usually use this add-on in firefox. [https://addons.mozilla.org/en-US/firefox/addon/facebook-message-seen-disable/?src=api](https://addons.mozilla.org/en-US/firefox/addon/facebook-message-seen-disable/?src=api)

**Comment by saenzramiro** [comment]
We don't have intentions to add custom functionalities to services in Rambox for now. Sorry.
