### ISSUE TITLE
Master password can be bypassed regardless of the hashing algorithm

### ISSUE THREAD

**Issue by TalatCikikci** [saenzramiro/rambox#1024]
### Steps to reproduce

I know this will not be in accordance with your issue template, but I believe it is better not to share the steps to bypass the master password here for obvious reasons. I can communicate the steps over Gitter and can edit and add steps later on if you believe it is not a big issue.

### Expected behavior

Hashed passwords should be secure enough to require a programmatic approach to be broken. 

### Actual behavior

User can bypass the hashed password using tools provided by Rambox itself.

### ENVIRONMENT

Only requirement to recreate this is two PCs that can run Rambox. I believe this issue can be recreated on any platform that can run Rambox as the piece of code that is needed is platform independent.

> Rambox: v0.5.10

> OS: Windows 7, 8.1

> Arch: x64

**Comment by saenzramiro** [comment]
I will close this because you contacted me via Gitter. Thanks!

**Comment by mirfilip** [comment]
@saenzramiro Where could an external person like me track progress of this?
