### ISSUE TITLE
Incorrect version of Sencha listed in README.md

### ISSUE THREAD

**Issue by greenred123** [saenzramiro/rambox#1026]
In the README.md Sencha Cmd 6.1.2.15  is recommended. Using this version I experienced the following error: Ext.cq1 is not a function. When I updated to latest version I had no further problems. 

### ENVIRONMENT

> Rambox:  v1.6.11 according to About Rambox 

> OS: macos sierra

> Arch: x64

**Comment by saenzramiro** [comment]
That error happens because you have to do `sencha app watch` and then run the app.
