### ISSUE TITLE
Tabs named with numbers can produce false positive on "unread notification" number

### ISSUE THREAD

**Issue by neomacedo** [saenzramiro/rambox#1029]
### Steps to reproduce

1. Start a new Service.. Anyone
2. Rename the Tab/Service putting a number on it
3. Tadaaa.. it will recognize the number as a "unread" item

### Expected behavior

Separate what is notifications and what is the name of Tab

### Actual behavior

![image](https://user-images.githubusercontent.com/4274900/28676647-8f7ba44c-72c1-11e7-87c5-ba318be58fcd.png)

### Environment

> Rambox: v0.5.10
> OS: Windows 10
> Arch: x64

**Comment by Ash258** [comment]
Yeah I am having same issue.
![Issue 1](https://image.prntscr.com/image/A1QE0yB_Rdme3GjoybaPNA.png "Issue 1")
![Issue 2](https://image.prntscr.com/image/hM-vPJusSRqZFaPiWuGX2A.png "Issue 2")

**Comment by nmat** [comment]
This is most likely the effect of: https://github.com/saenzramiro/rambox/pull/843

Where title is changed with the name of the service. Why the unread counter does show it also is odd though.

This was introduced in version 0.5.10: https://github.com/saenzramiro/rambox/commit/15cd21904ce95a09f19d013ed2ce5a13d664adac
