### ISSUE TITLE
custom code badge

### ISSUE THREAD

**Issue by CB9TOIIIA** [saenzramiro/rambox#103]
Hello! Can you help me add custom code to VK.com:

example:
`<li id="l_msg"><a href="/im" onclick="return nav.go(this, event, {noback: true, params: {_ref: 'left_nav'}});" class="left_row"><span class="left_fixer"><span class="left_count_pad left_count_persist" onmouseover="Pads.preload('msg')" onmousedown="return Pads.show('msg', event)" onclick="return (checkEvent(event) || browser.msie6) ? true : cancelEvent(event)"><span class="left_count_wrap  fl_r"><span class="inl_bl left_count">+2</span></span></span><span class="left_label inl_bl">My messages</span></span></a></li>`

How i can grab (left_count) messages to your title rambox?

**Comment by CB9TOIIIA** [comment]
In chrome (standart) browser i can give count this js code:

`var countvk = ''; document.getElementById('l_msg').innerText.replace(/\D+/g,""); `

But in RamBox not work:

`function checkUnread(){updateBadge(var countvk = ''; document.getElementById('l_msg').innerText.replace(/\D+/g,""); )}function updateBadge(e){e>=1?document.title="("+e+") "+originalTitle:document.title=originalTitle}var originalTitle=document.title;setInterval(checkUnread,3000);`

**Comment by saenzramiro** [comment]
Wel... is a bad code syntax.

Try to remove **countvk** variable. Just `document.getElementById('l_msg').innerText.replace(/\D+/g,"")` without ;

**Comment by CB9TOIIIA** [comment]
Work JS:
![172015](https://cloud.githubusercontent.com/assets/1074710/16899785/ed25a0d2-4c18-11e6-9701-da0b7e0066dc.png)

But in full code: random numbers
![172034](https://cloud.githubusercontent.com/assets/1074710/16899786/ef741d82-4c18-11e6-8072-21aa8f5943a3.png)

In Rambox not work.

**Comment by saenzramiro** [comment]
Try to embed the code with `parseInt` function.

`parseInt(document.getElementById('l_msg').innerText.replace(/\D+/g,""))`

**Comment by CB9TOIIIA** [comment]
![183549](https://cloud.githubusercontent.com/assets/1074710/16906121/498b047e-4cba-11e6-9c6c-13c5f567b59d.png)

not help

**Comment by CB9TOIIIA** [comment]
![183711](https://cloud.githubusercontent.com/assets/1074710/16906130/75576db8-4cba-11e6-8512-33c5adcd6b4a.png)

**Comment by saenzramiro** [comment]
So works now?

**Comment by saenzramiro** [comment]
The number returning is not important.

Check the title of the page if shows the unread count messages, that matters.

**Comment by CB9TOIIIA** [comment]
Title of the page - **not shows** unread count messages.

**Comment by saenzramiro** [comment]
Your code is getting the first element with ID **l_msg**, so if there are more elements (unread counters)), it will not sum the numbers.

Try this code:

```javascript
(function(){var e=document.getElementsByClassName("l_msg"),t=0;for(i=0;i<e.length;i++)t+=parseInt(e[i].innerHTML.trim()); return t;})()
```

Replace **l_msg** with a CSS class name of counter elements.

**Comment by CB9TOIIIA** [comment]
![183246](https://cloud.githubusercontent.com/assets/1074710/16922505/6cd75c2a-4d1e-11e6-90b3-942d87b7b808.png)

Does not work. VK.com - the most popular social network in Russia. There is authorization by facebook - you can see for yourself? I have a couple of bucks for the coffee you  :)

**Comment by saenzramiro** [comment]
Ok, I created a fake profile. Please add me in VK, my ID is "id372848852". Then send me a private message.

**Comment by CB9TOIIIA** [comment]
i sent you 5-8 messages :)

**Comment by saenzramiro** [comment]
Ok, I tested and works with this:

```javascript
parseInt(document.getElementById('l_msg').innerText.replace(/\D+/g,""))
```

Be sure to remove your VK services and and a new one with this JS UNREAD code. In URL I used https://new.vk.com/im.

**Comment by CB9TOIIIA** [comment]
bug for Custom Services.
The code is ok but is not runnning correctly.
You will need to wait for next release for this fix

**Comment by CB9TOIIIA** [comment]
fixed? how long wait new version? :)

**Comment by saenzramiro** [comment]
Hopefully next Friday.

**Comment by gnidorah** [comment]
End user snippet (works, but correct me if it's wrong):

`function checkUnread() {
    var t = parseInt(document.getElementById('l_msg').innerText.replace(/\D+/g,""));
    updateBadge(t);
}

function updateBadge(e) {
    e >= 1 ? document.title = "(" + e + ") " + originalTitle : document.title = originalTitle
}
var originalTitle = document.title;
setInterval(checkUnread, 3000);`

**Comment by CB9TOIIIA** [comment]
mycode:

``` function checkUnread(){updateBadge(parseInt(document.getElementById("l_msg").innerText.replace(/\D+/g,"")))}function updateBadge(e){e>=1?document.title="("+e+") "+originalTitle:document.title=originalTitle}var originalTitle=document.title;setInterval(checkUnread,3000);  ```
