### ISSUE TITLE
Too many tooltips on startup

### ISSUE THREAD

**Issue by gingerbeardman** [saenzramiro/rambox#1030]
Every time I open rambox it shows me tooltips I have already seen before.
These are a mixture of welcome, changelog, and other nags.

Today I started up rambox and there were two of them at once!
This is just too much of a bad experience.

Please make these optional!

Until then I am blocking all rambox access to tooltip.io

**Comment by CreamyCookie** [comment]
I'm having the same issue 

@saenzramiro Is there a way to disable these tooltips / notifications for all time?

**Comment by ChipWolf** [comment]
+1

**Comment by saenzramiro** [comment]
Like I explained in other thread, seems like Tooltip.io is not getting ok the messages the user read, because we put all those messages to show it once.

Blocking Tooltip.io is not a good option because sometimes we communicate important with Tooltip.

**Comment by gingerbeardman** [comment]
So is this "fixed" or "won't fix"?

**Comment by gingerbeardman** [comment]
Also, what other thread?

**Comment by CreamyCookie** [comment]
@saenzramiro What important messages? 

Thanks for creating rambox!
