### ISSUE TITLE
Master lock issue

### ISSUE THREAD

**Issue by rehannali** [saenzramiro/rambox#1031]
Hey, Master lock only shows when the application is completely locked. When I open it from the tray, it never asked me a password and open straight away. If there is a feature to prevent it or if I'm doing wrong tell to do it.
If this feature is not available in the application could you please add it because it would be very helpful for privacy.
Thanks
	
	-
	> Rambox 0.5.10
	> Electron 1.7.4
	> win32 x64 10.0.15063

**Comment by saenzramiro** [comment]
There are two passwords protections, "Lock Rambox" and "Master Password".

Lock Rambox: Blocks Rambox without closing it.
Master Password: Blocks Rambox to open using an initial password.

In your case, you can use "Lock Rambox".

**Comment by rehannali** [comment]
Is there anyway so whenever I open the application from tray it automatically asks for a password even I didn't lock it. Actually, I want to say whenever I press the close button the application should automatically password protected so when I open again it should ask password before opening it. I think now you can understand what I'm trying to say.
It would be very helpful and great feature and increase efficiency in terms of clicks or applying the password.
Thanks
