### ISSUE TITLE
No automatic login via KiwiIRC

### ISSUE THREAD

**Issue by notnsane** [saenzramiro/rambox#1037]
### Steps to reproduce

1. Add KiwiIRC service and any network
2. Input your Nickname and previously registered Password
3. Login
4. Reload Rambox

### Expected behavior

Rambox automatically logins into the specified server

### Actual behavior

We have to type the username and password again

### ENVIRONMENT

> Rambox: v0.5.10

> OS: Windows

> Arch: x64

---

I'm not sure if this is expected behaviour, but I'm raising a ticket anyways because I'm not finding anything in google.

**Comment by MrChick** [comment]
I'm pretty sure that's the expected behaviour since Kiwi doesn't store any login credentials. Once the session is gone, so are they.

If you're generally using the same IRC you can do what I did, use a custom script:


```javascript
$(document).ready(function() {
setTimeout(function() {
	$('input#server_select_nick').val('<nick goes here>');

	// password, if required. if not just remove those two lines
	$('input#server_select_show_pass').click();
	$('input#server_select_password').val('<password goes here>');

	$('button[type=submit]').click();
}, 5000);
});
```
