### ISSUE TITLE
WIN10 System Reminder keeps popping-up when receiving Google Hagouts messages

### ISSUE THREAD

**Issue by guelfoalexander** [saenzramiro/rambox#1038]
When chatting with s.o. via Google Hangouts account, Windows 10 notifies repeatedly (each second) that "You have 1 new message" (up to three different lines in lateral Windows10 message bar), and stops only if I actually open it via Rambox (I tried to quiet it by reading the message from my Smart-Phone, but it kept popping-up with alert sound of Desktop Alert on the PC).
I don't know if it's intended this way, but to me it's annoying.
GAG

	
	-
	> Rambox 0.5.9
	> Electron 1.7.1
	> win32 x64 10.0.15063

**Comment by saenzramiro** [comment]
This was fixed in latest release.
