### ISSUE TITLE
GPU clock speed

### ISSUE THREAD

**Issue by seison5** [saenzramiro/rambox#1039]
<Runs sometimes with 450mhz core clock and 1450mhz memory clock on 
![a](https://user-images.githubusercontent.com/30598963/28782932-6685ffde-7617-11e7-8fcf-eeccff909b32.JPG)
radeon hd 7870>

	
	-
	> Rambox 0.5.10
	> Electron 1.7.4
	> win32 x64 10.0.10586

**Comment by Ash258** [comment]
These resources management handle Electron based on what content is being rendered, and cannot be forced or changed.

What you can do is run with `--disable-gpu`.
