### ISSUE TITLE
Telegram doesn't scroll message window upon receiving new message

### ISSUE THREAD

**Issue by rnyberg** [saenzramiro/rambox#1041]
* Reload Rambox
* Select Telegram
* Write a message and hit enter: Message window scrolls to bottom
* Receive message: Message window displays "UNREAD MESSAGES" but the actual message is only revealed by scrolling down

> Rambox 0.5.9
> Electron 1.7.1
> win32 x64 10.0.15063
> Resolution 3840x2160 (125% screen scale)

**Comment by rnyberg** [comment]
Based on quick testing, this seems to fix the issue for me (although it's not optimal having to turn off the feature)

https://vgy.me/PGYLIG.png

**Comment by gameguy95** [comment]
I've been having the same issue. The scaling thing @rnyberg suggested fixes the scrolling, but I don't like fiddling with settings when I shouldn't need to. 
The Telegram window also doesn't fill the whole screen, either, but it did that before applying this fix. I wonder why...

**Comment by saenzramiro** [comment]
In version 0.5.12 we fixed the HDPI for Windows, please try it.
