### ISSUE TITLE
Auth0 login window does not open

### ISSUE THREAD

**Issue by NatGra** [saenzramiro/rambox#1042]
### Steps to reproduce

1. Set language to german
2. Click on Auth0 login button

### Expected behavior

Pop up window for logging in with Auth0 details should appear.

### Actual behavior

Pop up window "Something went wrong." appears.

Console Error: https://cdn.eu.auth0.com/js/lock/10.2.2/de.js 

### ENVIRONMENT

as local setup

> Rambox: v0.5.10

> OS: macOS Sierra

> Arch: x64

**Comment by saenzramiro** [comment]
Fixed in latest release.
