### ISSUE TITLE
Inconsistencies with language 

### ISSUE THREAD

**Issue by NatGra** [saenzramiro/rambox#1046]
### Inconsistencies 
1. With the changed language setting to German, the pop up window for indicating the “Do not disturb”-mode still appears to be English.

2. The settings window shows some settings in German and some in English language. 

### ENVIRONMENT

> Rambox: v0.5.10

> OS: macOS Sierra

> Arch: x64

**Comment by nmat** [comment]
You can check if there is a translation for all of those. There are links to check it. But not sure how that works to 100%

**Comment by saenzramiro** [comment]
There are messages that are not translated yet. You can help going to: https://crowdin.com/project/rambox
