### ISSUE TITLE
Lock Issue

### ISSUE THREAD

**Issue by NatGra** [saenzramiro/rambox#1047]
### Steps to reproduce

1. open Rambox local in electron
2. lock Rambox with password
3. got to console an call alert(localStorage.getItem('locked'));
4. in the alert you get the md5 hash value which is reversible with multiple websites 
5. tada, you got the value of the password

### ENVIRONMENT

> Rambox: v0.5.10

> OS: macOS Sierra

> Arch: x64

**Comment by saenzramiro** [comment]
Yes, we will change MD5 to crypt in a future release.
