### ISSUE TITLE
Can't open taskbar menu when there's a app in fullscreen

### ISSUE THREAD

**Issue by johnnyasantoss** [saenzramiro/rambox#1050]
### Steps to reproduce

1. Open Rambox and minimize it to the taskbar
2. Open another app in fullscreen
3. While in fullscreen with the second app press Windows key and try to open the taskbar menu by right clicking in Rambox icon

### Expected behavior

Open the taskbar menu

### Actual behavior

Nothing happens

### ENVIRONMENT

> Rambox: v0.5.9

> OS: Windows 10 Enterprise N 2016 LTSB

> Arch: x64

**Comment by johnnyasantoss** [comment]
It happens on Rambox v0.5.10 too

**Comment by johnnyasantoss** [comment]
Related to #409

**Comment by saenzramiro** [comment]
Seems to be an Electron bug, so please report this to https://github.com/electron/electron repo.
