### ISSUE TITLE
Openmailbox not working

### ISSUE THREAD

**Issue by WolfangAukang** [saenzramiro/rambox#1051]
### Steps to reproduce

1. Open "Openmailbox" tab
2. Shows "Not Found: The requested URL /webmail/ was not found on this server."

### Expected behavior

It should open Openmailbox login page.

### Actual behavior

It shows a Not Found page.

### ENVIRONMENT

> Rambox: v0.5.9

> OS: Windows 10

> Arch: x64

NOTES: They made a lot of changes on their service, including changing the login page web address. That's why this error appears.

**Comment by kjuanman** [comment]
The new URL is https://app.openmailbox.org/webmail/

**Comment by nmat** [comment]
https://github.com/saenzramiro/rambox/pull/1053

**Comment by saenzramiro** [comment]
I just merged @kjuanman PR, so it will be fixed in next release soon.
