### ISSUE TITLE
can not log in my yahoo email

### ISSUE THREAD

**Issue by ctspriten** [saenzramiro/rambox#1056]
Dear Sir,

Kindly let me know why i can not log in my email using ram box 
my email add is cts.reservation@ymail.com

	
	-
	> Rambox 0.5.10
	> Electron 1.7.4
	> win32 ia32 6.1.7600

**Comment by aravindhp** [comment]
Duplicate of #833

**Comment by ctspriten** [comment]
Dear Sir,
Thank you for the information. Kindly let me know how do i unauthorize it. 
Thanks & Regards,

Priten HimatsinhCAR TRACK SOLUTIONS
Operations Office :
Bharat Diamond Bourse, G-Block, Bandra Kurla Complex, Bandra (E), Mumbai 400 024

Regd. Office :
Off No 3, ‘D ‘Wing, Kamal Park, Kanakia Road, Mira Road - East, Thane – 401107. India
Mob No: +91 9702222644  I E-mail: cts.priten@ymail.com I

 

| 
 |

 

    On Thursday, 10 August 2017 11:17 PM, Aravindh Puthiyaparambil <notifications@github.com> wrote:
 

 Duplicate of #833—

**Comment by ctspriten** [comment]
Dear Sir, 

Still Awaiting help as i cant view my cts.reservation@ymail.com mail in Rambox.

**Thank you for the information. Kindly let me know how do i unauthorize it.**

**Comment by ctspriten** [comment]
Still awaiting solution

**Comment by saenzramiro** [comment]
Let's merge this with #833
