### ISSUE TITLE
Problem login into TweetDeck

### ISSUE THREAD

**Issue by Naoray** [saenzramiro/rambox#106]
Can't login into TweetDeck! When I click login in the down left corner it says 'loading', but nothing else is happening.

-
> Rambox 0.4.0
> Electron 1.2.6
> win32 x64 10.0.10586

**Comment by saenzramiro** [comment]
Yes, true, For now, just reload the service by double click on the tab and **Reload** after you enter your credentials and shows the _Loading..._ mask at the bottom-left.

**Comment by ComiR** [comment]
With 2 factor auth, the workaround doesn't work. In the dev tools network panel you can see that the request to `https://twitter.com/account/login_verification?platform=web&user_id=123456789&challenge_type=Sms&challenge_id=SomeChallengeId&remember_me=true&redirect_after_login_verification=https%3A%2F%2Ftweetdeck.twitter.com%2F%3Fvia_twitter_login%3Dtrue` gets canceled.

I already had the problem before (as custom service). I did hope the addition as default service would fix that.

**Comment by bnn-y** [comment]
I still have the issue with Tweetdeck. After i put in my credentials it shows the "loading"-indicator but nothing happens. Any Ideas?

**Comment by saenzramiro** [comment]
It will fixed for the next release.

**Comment by mmk2410** [comment]
@bnn-y You can also create a temporary Twitter password to log in (with the workaround described above).

**Comment by bnn-y** [comment]
Thanks @mmk2410 ! I will try that
