### ISSUE TITLE
Dual icon option

### ISSUE THREAD

**Issue by mk2tech** [saenzramiro/rambox#1060]
I'm going to start by saying great app! I come from Franz but after finding this gem, i never looked back. 

There is one freature though that I do miss, so I thought i'd ask to see if this might be in the road map or how complex it would be to implement. It would be to add a dual PiP icon option for a tab (without text).

For example: I have multiple accounts under the same app (slack - work & personal etc.) I like not having text in tabs and it works perfectly when I can have the company icon with the app type icon overlaid.

Having a way to do it in Javascript custom code would be ok as well.

Here is an example of a slack company tab: (company icon with slack icon bottom right on it)
![dual-icons](https://user-images.githubusercontent.com/7342511/29253815-3b6dd23e-8055-11e7-89b9-6577d68d1303.png)

**Comment by munkymack** [comment]
Doing it with JS and a custom service:
https://github.com/saenzramiro/rambox/issues/113?_pjax=%23js-repo-pjax-container#issuecomment-313770921

I can't quite get the notifications to work (due to my lack of JS chops, no doubt), but the badging works

**Comment by saenzramiro** [comment]
Fixed in latest release.

**Comment by iBobik** [comment]
Seems ike icon is not loaded immediately after login, but after Rambox restart.
