### ISSUE TITLE
Rambox Donate - Broken Bitcoin Link

### ISSUE THREAD

**Issue by borshpro** [saenzramiro/rambox#1063]
**Info**
Broken Bitcoin donation link

**Steps**
1. Launch Rambox
2. Rambox will show donation dialog
3. Choose Bitcoin option
4. Browser will pop up with link to https://www.coinbase.com/saenzramiro

**Result**: Link is broken: https://www.coinbase.com/saenzramiro (PAGE NOT FOUND, Sorry we couldn't find what you were looking for).

	
	-
	> Rambox 0.5.10
	> Electron 1.7.4
	> darwin x64 15.6.0

**Comment by saenzramiro** [comment]
Thank you so much, I just fix it.
