### ISSUE TITLE
Parse external links before opening

### ISSUE THREAD

**Issue by borshpro** [saenzramiro/rambox#1064]
When using different mail (Yandex Mail) accounts and clicking links in mail, external browser window popups with mail redirect address and login requirement (link contains mail service address instead of target link).

Proposal: Parse external links in email before opening.

	
	-
	> Rambox 0.5.10
	> Electron 1.7.4
	> darwin x64 15.6.0

**Comment by saenzramiro** [comment]
You can try to inject JS code to parse:
`jQuery('a').click(function(e){
   window.open(URL WITHOUT YANDEX MIDDLEWARE);    
   return false;   
});`
