### ISSUE TITLE
[Feature Request] Google Allo for web

### ISSUE THREAD

**Issue by Stanzilla** [saenzramiro/rambox#1066]
Now available at https://allo.google.com/web

**Comment by igreulich** [comment]
For what its worth, I went to that address in Opera, and was told to visit in Chrome...

**Comment by vivekkrish** [comment]
Hi @Stanzilla, @igreulich, please see: https://github.com/saenzramiro/rambox/pull/1067 😉

**Comment by vivekkrish** [comment]
In the interim, I was able to add Allo as a **_Custom Service** via the Rambox interface (v0.5.10). To get notifications working, add the following snippet of JS into the _Custom Code_ box within the **🔽  Advanced** section:
```
function checkUnread(){var e=document.getElementsByClassName("unreadCount"),n=0;for(i=0;i<e.length;i++){var a=parseInt(e[i].innerHTML.trim());n+=isNaN(a)?0:a}updateBadge(n)}function updateBadge(e){e>=1?document.title="("+e+") "+originalTitle:document.title=originalTitle}var originalTitle=document.title;setInterval(checkUnread,3e3);
```

HTH!

**Comment by Stanzilla** [comment]
Nice!
