### ISSUE TITLE
Error on config save when "show in taskbar" and "on close quit" options set

### ISSUE THREAD

**Issue by axelitus** [saenzramiro/rambox#1068]
### Steps to reproduce

1. Open Preferences window.
2. Select "Show in Taskbar" for option "Display behaviour"
3. Select "Quit" for option "When closing the main window"
4. Hit the "Save" button
![2017-08-16_13h09_45](https://user-images.githubusercontent.com/732441/29378576-30bb5d16-8285-11e7-99cd-7983bffb1244.png)

### Expected behavior

The configuration should be saved without a problem.

### Actual behavior

An unhandled Exception window is shown:
![2017-08-16_13h08_27](https://user-images.githubusercontent.com/732441/29378562-2160d9ae-8285-11e7-9c7e-445a8dc13899.png)

### ENVIRONMENT

> Rambox: v0.5.10
> OS: Windows 10 Pro 1703
> Arch: x64

**Comment by saenzramiro** [comment]
Is this still happening in latest release?

**Comment by axelitus** [comment]
I can gladly confirm this is no longer happening in version 0.5.13!
