### ISSUE TITLE
Line Naver Support

### ISSUE THREAD

**Issue by hsanson** [saenzramiro/rambox#1069]
In Japan the number one messaging application is [Line](https://line.me/). It would be great if Rambox could include it by default.

Since the web version of line is a [Chrome Plugin](https://chrome.google.com/webstore/detail/line/menkifleemblimdogmoihpfopnplikde) I could not find a way to add it manually to Rambox.

**Comment by unfulvio** [comment]
+1

**Comment by saenzramiro** [comment]
We can't because LINE don't have a web app to be included into Rambox. Sorry!
