### ISSUE TITLE
Add Quasselweb support pls

### ISSUE THREAD

**Issue by alien2003** [saenzramiro/rambox#1077]
https://github.com/magne4000/quassel-webserver

There is stil no way to IRC from Rambox but IRC is one of the most popular messaging services.

**Comment by johannesgunnar** [comment]
Note that Rambox both supports IRCCloud and Kiwi IRC so it is possible to IRC from Rambox

**Comment by alien2003** [comment]
Thank you. I'll try Kiwi IRC because IRCCloud is not secure

**Comment by rodneyrod** [comment]
Found out that this is fixed in a yet to be merged pull request

magne4000/quassel-webserver#240

**Comment by Ash258** [comment]
Duplicate of #704
