### ISSUE TITLE
Unexpectedly large unread message count for a Slack team

### ISSUE THREAD

**Issue by jerryjrchen** [saenzramiro/rambox#1083]
Unexpectedly large unread message count for a Slack team.
<img width="100" alt="screen shot 2017-08-21 at 22 12 58" src="https://user-images.githubusercontent.com/8547284/29549581-f38352f4-86bd-11e7-92c3-b158f2770008.png">

I'm already trying the workaround from #1072, and I believe it is working (I see notifications). However, the notification count is all wrong.

This only affects one of my Slack teams. Here's how I get this issue:
1. Switch to the affected tab.
2. Clear any unread messages.
3. Notice large number still present on Rambox badge.
4. Switch to a different tab.
5. Badge number disappears (in my case, no unread in any of my tabs).

### ENVIRONMENT

> Rambox: v0.5.10

> OS: macOS 10.12.6

> Arch: x64

**Comment by nmat** [comment]
Can you please check: https://github.com/saenzramiro/rambox/issues/1072 and https://github.com/saenzramiro/rambox/pull/1076 to see if that would solve the problem for you? There is information regarding the unread count in them and a workaround in the issue 1072

**Comment by cjerry** [comment]
Currently using the workaround from #1072. Is #1076 significantly different?

**Comment by nmat** [comment]
@cjerry its the pull request for patching rambox, its waiting on maintainer for review.

**Comment by Meaglin** [comment]
The workaround in #1072 doesn't work for me sadly, something seems still broken sadly.

**Comment by nmat** [comment]
its only in the tray icon or in the client also?

**Comment by cjerry** [comment]
Only the tray icon.

**Comment by Meaglin** [comment]
only on the dock icon(mac dock)

**Comment by saenzramiro** [comment]
What's the name of your Slack team? Have numbers? Or some member/channel...

**Comment by cjerry** [comment]
Oh yeah, it has the numbers 61 and 2017 in the name. This seems like it might be the cause.

**Comment by stevenmirabito** [comment]
This is definitely the issue, and it's not isolated to a specific service. I have numbers to differentiate my Google Voice accounts and it will show those numbers next to the unread count in the dock icon when the service is selected.

**Comment by Meaglin** [comment]
I think the culprit is in the following unread counter update logic:
https://github.com/saenzramiro/rambox/blob/668d0f8ce97110b430eef7b8263bda4ec540f1c9/electron/main.js#L276
