### ISSUE TITLE
Skype file download

### ISSUE THREAD

**Issue by nicolangr** [saenzramiro/rambox#109]
When receive files redirect on browser page saying  "Unauthenticated"

-
> Rambox 0.4.0
> Electron 1.2.6
> linux x64 3.19.0-32-generic

**Comment by saenzramiro** [comment]
Yes, is a session problem. I will try to find a way to solve this.

For now, you can start a Skype session in your default browser by going to web.skype.com (click on remember checkbox) and wait until loads Skype for Web, then close it. Now your files from Rambox will work.

**Comment by saenzramiro** [comment]
Fixed in commit 4e01724c71a5a121f867cdda9a43e1b6ad84b9a7
