### ISSUE TITLE
Don't disturb works but never changes status 

### ISSUE THREAD

**Issue by krambock** [saenzramiro/rambox#1093]
When using the Don't disturb (F1) in the client you never see it changing from unactive to active..  

	
	-
	> Rambox 0.5.10
	> Electron 1.7.4
	> win32 x64 6.1.7601

**Comment by SimJoSt** [comment]
I can confirm this behavior.

**Comment by nmat** [comment]
Can you please test this in 0.5.12?

**Comment by krambock** [comment]
Great!  Works again.. and I like the sliding notification !
