### ISSUE TITLE
Mouse right click and copy-paste functionality

### ISSUE THREAD

**Issue by AGonLen** [saenzramiro/rambox#1094]
On GMail and potentially other services, the mouse right click is not working and does not have any options. Would be good to at least have the copy-paste functionality, to copy links or some text (not using the CTRL+C & CTRL+V).

### ENVIRONMENT
> Rambox: v0.5.10
> OS: Windows 10 x64 (Creators Update)
> Arch: x64

**Comment by nmat** [comment]
This is a duplicate there is a pull request for it: https://github.com/saenzramiro/rambox/pull/1074

**Comment by AGonLen** [comment]
Perfect thanks! You can close this one then  ;)
