### ISSUE TITLE
Spell check

### ISSUE THREAD

**Issue by AGonLen** [saenzramiro/rambox#1095]
Would be really awesome to have writing spell check in multiple languages (to be chosen in the setup/configuration menu) and be able to have multiple languages active at the same time or an easy way to change from one available language to another, same or similar to what's available in browsers like Chrome.
It's pretty useful when writing emails or even chatting with people ;)

### ENVIRONMENT
> Rambox: v0.5.10
> OS: Windows 10 x64 (Creators Update)
> Arch: x64

**Comment by nmat** [comment]
Duplicate of: https://github.com/saenzramiro/rambox/issues/509

**Comment by AGonLen** [comment]
Perfect thanks! You can close this one then  ;)
