### ISSUE TITLE
On download page, link to Deb 64-bits give tar.gz file

### ISSUE THREAD

**Issue by senseicoder** [saenzramiro/rambox#1096]
### Steps to reproduce

1. go to http://rambox.pro/#download
2. clic on Deb 64-bits file
3. get Rambox-0.5.10-x64.tar.gz

### Expected behavior

get a deb file

### Actual behavior

get a tar.gz file

### ENVIRONMENT

Any browser

> Rambox: v0.5.10

> OS: any

> Arch: x64

**Comment by Simon0Harms** [comment]
By the Way:
It would be great having a repository

**Comment by jerry1970** [comment]
Not everybody is experienced with installing software from outside the common repositories. Detailed install instructions would help, adding it to the repository is even better.

And an icon for desktop launchers would be great! I copied the website icon.

**Comment by pcdog** [comment]
This download link is still wrong, even with the current release

**Comment by senseicoder** [comment]
Agreed with pcdog, the "download deb 64" button is a link to https://getrambox.herokuapp.com/download/linux_64?filetype=deb, which lead to the download of Rambox-0.5.12-x64.tar.gz

**Comment by Ash258** [comment]
Let's continue in #1401
