### ISSUE TITLE
Switch between service with keyboard shortcuts

### ISSUE THREAD

**Issue by jvdmeij** [saenzramiro/rambox#1097]
It would be great to be able to switch to another service by using a keyboard shortcut.

On OSX you can switch tabs in chrome with option-command and arrow left and right. Franz implemented this shortcut as well. As I am now switching it would be a great addon.

**Comment by Diskutant** [comment]
cmd+1 switches to the first
cmd+3 to the third and so on

also 
ctrl + tab switches to the next tab
ctrl + shift + tab to the previous tab

**Comment by nmat** [comment]
IMO this ticket can be closed since there already is a implementation for the shortcut keys.

**Comment by jvdmeij** [comment]
Thanks guys. I didn't find the keyboard shortcuts before 👍
