### ISSUE TITLE
Clicking a link on Skype opens 6 browser tabs

### ISSUE THREAD

**Issue by KixPanganiban** [saenzramiro/rambox#11]
Similar to https://github.com/saenzramiro/rambox/issues/6 but on Skype.

Running latest release of Rambox (As of 7/1/2016) on OS X Yosemite.

**Comment by benjaminspowell** [comment]
Running windows 10 and latest rambox release. 

getting same "feature" as well, Skype and messenger opening multiple tabs form link

**Comment by derSmutje** [comment]
The same here running Ubuntu Trusty with Rambox for Linux (64bit) v1.2.5

**Comment by vlameiras** [comment]
Same here 
> Rambox 0.3.0
> Electron 1.2.5
> win32 x64 10.0.10586

**Comment by saenzramiro** [comment]
Thanks! I will fix it for the next release.

**Comment by ainou** [comment]
This also happens inside any links on Gmail messages. It opens between 3 and 6 tabs of the same link.

**Comment by thuandt** [comment]
Link from Skype still open 2tabs.
- 1 is Skype undefined web page  https://web.skype.com/en/undefined
- 1 is website link.

**Comment by vunhan** [comment]
I'm using rambox ver **0.4.0** and this bug is still happenned on Skype.
Now my browser open 2 tab, included https://web.skype.com/en/undefined.

**Comment by jbbr** [comment]
I also have problems with Skype links and 0.4.0 (Arch Linux x64, github binary via AUR).
Sometimes only 1 tab opens but it's the one with https://web.skype.com/en/undefined - sometimes 2 tabs opens as mentioned already.

**Comment by saenzramiro** [comment]
Ok, I will fix it in next release.
