### ISSUE TITLE
Hide name of the service

### ISSUE THREAD

**Issue by curious-jim** [saenzramiro/rambox#110]
Want to ask to add the option, to remove the names of networks/services, to leave only icons
I added too many of them, and now I have to scroll them to select the one I need
If there would be an option to hide names (e.g. WhatsApp, Wechat), and leave only icons, it would've the solve it

Thanks

P.S. If there is such option, then I can't find it

**Comment by saenzramiro** [comment]
Sure, just remove the name of the service from the Add Dialog. You can edit your current services from the Rambox tab (right section) and remove the **Name** for each one.

**Comment by curious-jim** [comment]
thanks, didn't think about this
