### ISSUE TITLE
Tearing of user interface in i3wm archlinux

### ISSUE THREAD

**Issue by phandox** [saenzramiro/rambox#1102]
Hello, I am trying out Rambox and right after installation I notice slight lag during operation, be it typing, switching windows opening context menu. Overall, application doesn't feel "smooth", could there be something wrong with my installation? I am on Thinkpad X230 with 8GB RAM, SSD and internal graphic card if that helps. Thanks!

	
	-
	> Rambox 0.5.10
	> Electron 1.7.4
	> linux x64 4.12.8-2-ARCH

**Comment by nmat** [comment]
Have you tested to turn off the hardware accelerator? (note you have to restart the application and _maybe_ clear cache for it)

**Comment by phandox** [comment]
Disabling HW acceleration helped a lot :) Thank you! :+1:

**Comment by nmat** [comment]
did it solve your problem? (asking if this can be closed) :)

**Comment by phandox** [comment]
Oh, sorry I wasn't clear, yes it did solve the problem.
