### ISSUE TITLE
Slack notifications do not work.

### ISSUE THREAD

**Issue by Que88** [saenzramiro/rambox#1103]
Hi,

Slack notifications do not work for me - the unread counter does not show up neither in the Slack tabs nor on the Rambox icon when minimized. But I do get the windows task bar pop ups.
Everything else works - Skype, WhatsApp, FB...

Thanks!

	
	-
	> Rambox 0.5.9
	> Electron 1.7.1
	> win32 x64 10.0.14393

**Comment by nmat** [comment]
There is a fix for notifications for slack: https://github.com/saenzramiro/rambox/commit/bc8517703a3e22c8e41423ab1099ee44b8813046

This is not yet released thought but there is a workaround until the release that is in:
https://github.com/saenzramiro/rambox/issues/1072

Please try the workaround to see if it works better for you. Also please upgrade to 0.5.10 to test it out there.

**Comment by Mte90** [comment]
I confirm this issue very annoying

**Comment by Mte90** [comment]
Seems also that is impossible to patch the installed version that is like compiled...

**Comment by Que88** [comment]
I don't know how to code so can't use the patch.
I'm 'just an user'

**Comment by tbaehr** [comment]
![image](https://user-images.githubusercontent.com/8515020/29841369-7f29208e-8d05-11e7-9241-073f9d21a8bc.png)

- same problem with slack chat no notification counter 
- does work with rocketchat tho

**Comment by nmat** [comment]
Can you try to see if the issue persist in 0.5.12? There is a fix in place for notifications for slack.

**Comment by wedens** [comment]
In 0.5.12 it shows notifications on tab and tray icon but I don't get desktop notifications.

**Comment by wedens** [comment]
I can confirm that it works in 0.5.12

**Comment by nmat** [comment]
If it works. Can you please close the issue and reopen if problem occurs again?
