### ISSUE TITLE
Rmabox window does not open when clicking on tray icon

### ISSUE THREAD

**Issue by jerry1970** [saenzramiro/rambox#1105]
When I click or double click on the tray icon, I'd expect Rambox to open but it does nothing. The action "Show/Hide Window" should be the default action.

Xubuntu 17.04
Version: 0.5.10
Platform: linux (x64)
Electron: 1.7.4
Chromium: 58.0.3029.110
Node: 7.9.0

**Comment by nmat** [comment]
duplicate of: https://github.com/saenzramiro/rambox/issues/942

Please search the issues list before reporting, it helps to avoid duplicates.

**Comment by jerry1970** [comment]
Sorry, I did look but obviously not good enough...
