### ISSUE TITLE
Save inject js code

### ISSUE THREAD

**Issue by Mte90** [saenzramiro/rambox#1106]
Often for a fix or implement new stuff there are javascript snippet but I am using different website so every day I have to run the code in all of them, a system to save snippet will save my time and improve the creation of snippet with new feature.

**Comment by Mte90** [comment]
another example that can be useful: https://gist.github.com/Zemnmez/ffb5449d873d5407c7172534b762ae46

Actually inject a js inside a specific tab is not possible

**Comment by saenzramiro** [comment]
Injection code should save it with service settings. It is not saving for you?

**Comment by saenzramiro** [comment]
Try by reinstalling. =/

**Comment by Mte90** [comment]
I have no snippet for trying right now but they wasn't saved on the new start.

**Comment by Mte90** [comment]
Got it it is inside advanced on the settings modal of the service
