### ISSUE TITLE
add IRC

### ISSUE THREAD

**Issue by audacioustux** [saenzramiro/rambox#111]
please add IRC... http://kiwiirc.com/ with notification will work too :smile:

**Comment by saenzramiro** [comment]
We have FreeNode as IRC. Is it different than Kiwi?

**Comment by MrChick** [comment]
In KiwiIRC you can connect to basically any Network, Freenode is just Freenode.

Should you add Kiwi, please also add an option for Kiwi to specify a custom URL, as Kiwi can also be installed on your own server instead of using their installation.

I'm also currently working on an unread badge script for Kiwi which I'll post here once it's done

**Comment by saenzramiro** [comment]
Ok, sounds good. I will add it for the next release. 

It will be great if you can share the code for unread messages.

**Comment by MrChick** [comment]
So, here's where I am right now:

``` javascript
function checkUnread() {
    updateBadge(
        (function() {
            var activity = 0;
            $('.activity').each(function() { activity += parseInt($(this).html()) });
            console.log("0: " + activity);
            var unseen = false;
            $('.panel[style*="display: block"] .msg').each(function() {
                if(unseen) {
                    activity++;
                } else {
                    if($(this).hasClass('last_seen')) {
                        unseen = true;
                    }
                }
            });
            console.log("1: " + activity);
            return activity;
        })()
    )
}

function updateBadge(e)  {
    e>= 1 ? document.title = "("+e+") " + originalTitle : document.title=originalTitle
}

var originalTitle = document.title;
setInterval(checkUnread,3000);
```

I'm having the following issues:

1. even though this code is in the services config, it won't work from start. It does work after I paste it into the dev tools console for that service though
2. Kiwi is flashing the title with a "people are talking"-message, which gets ugly with the badge handling. Haven't found a way to disable this yet

**Comment by saenzramiro** [comment]
1. Yes, it's a bug that I fixed for next release.
2. The best way to prevent title change, is to find the function in that page that is changing it and overwrite it.

**Comment by MrChick** [comment]
1. Great :)
2. I'm looking for it, I'll post an updated script once I'm done

**Comment by MrChick** [comment]
Well, 2 will prove to be quite difficult as 

> Building takes all the development files then concatenates and minifies them into 2 files - kiwi.js and kiwi.min.js. Each file is wrapped into a closure to prevent runtime access.

I'm not sure how I can overwrite that function. Alternatively resetting the title every 50ms or so seems like an ugly hack.
Any idea how to get around this?

**Comment by saenzramiro** [comment]
I couldn't finish it, but here's a beginning:
```javascript
Object.defineProperty(document, 'title', {
  set: function(t){
            var count = t.match(/\(([^)]+)\)/); // Get text between (...)
				count = count ? count[1] : '0';
				count = Array.isArray(count.match(/\d+/g)) ? count.match(/\d+/g).join("") : count.match(/\d+/g); // Some services have special characters. Example: (•)
				count = count ? parseInt(count) : 0;
            console.info(count);
  }
});
```

**Comment by MrChick** [comment]
Ah, nice. I'll check it out in the next days and get back to you!

**Comment by MrChick** [comment]
Took a bit longer than expected, but finally, here it is:

``` javascript
var re = /\(\d+\)[ ](.*)/;

function getUnreadCount() {
    var activity = 0;
    $('.activity').each(function() { activity += parseInt($(this).html()) });
    var unseen = false;
    $('.panel[style*="display: block"] .msg').each(function() {
        if(unseen) {
            activity++;
        } else {
            if($(this).hasClass('last_seen')) {
                unseen = true;
            }
        }
    });
    return activity;
}

function updateTitle(title) {
    count = getUnreadCount();
    cleanTitle = title.match(re);

    if(cleanTitle !== null && cleanTitle.length > 1)
        cleanTitle = cleanTitle[1];
    else
        cleanTitle = title;

    if(count > 0)
        title = "(" + getUnreadCount() + ") " + cleanTitle;
    else
        title = cleanTitle;

    $('title').text(title);
}

Object.defineProperty(document, 'title', {
    configurable: true,
    set: function(title) {
        updateTitle(title);
    },
    get: function() {
        return $('title').text();
    }
});

setInterval(function() { updateTitle(document.title); }, 3000);
```

Thanks for your defineProperty hint!

**Comment by saenzramiro** [comment]
@MrChick Great! So I will add Kiwi in next release. Thank you.

**Comment by Bl4ckb0ne** [comment]
Hi, wouldn't it be good to let the user add the wanted irc server, so everybody can use its own? Because I need the mibbit irc server, and there's only freenode right now.

Thanks.

**Comment by MrChick** [comment]
@Bl4ckb0ne that's exactly what the addition of KiwiIRC is for as discussed in this thread?

**Comment by Bl4ckb0ne** [comment]
Seems like you're adding all the server one by one. What I mean is adding something like hexchat, that can let you add as many servers as you like

**Comment by MrChick** [comment]
That's exactly what KiwiIRC is...?
Give it a try: https://kiwiirc.com/client

**Comment by Bl4ckb0ne** [comment]
No, kiwiirc is a IRC server. Hexchat is a IRC client

**Comment by MrChick** [comment]
KiwiIRC is an IRC client, the hell are you talking about?!

**Comment by Bl4ckb0ne** [comment]
Ow my bad, I didn't see the server and network at the bottom of the page (damn phone screen). Si kiwiirc is a IRC client like hexchat, and not a IRC server. Sorry for the trouble

**Comment by MrChick** [comment]
No problem ;)

**Comment by MrChick** [comment]
> Should you add Kiwi, please also add an option for Kiwi to specify a custom URL, as Kiwi can also be installed on your own server instead of using their installation

Is it possible that you forgot this for 0.4.2? ;)

**Comment by saenzramiro** [comment]
Damn it! Yes... sorry @MrChick. :disappointed: 

Please create a new issue for that so I will not forget on next release.
