### ISSUE TITLE
vector.im presents security error that doesn't exist on the webpage 

### ISSUE THREAD

**Issue by tiny6996** [saenzramiro/rambox#112]
I deployed a matrix homeserver and added the vector.im client as a custom service. When I log on to the webpage I am presented with a the ability to log on to a custom server and when I fill out the server info everything works fine. When I do the same inside the rambox client I am presented with the following error when using the same server info.  
![image](https://cloud.githubusercontent.com/assets/13280132/16864242/92a6ac04-4a20-11e6-86ac-b2f237f4f983.png)

here is the output from the dev tools on that page 
![image](https://cloud.githubusercontent.com/assets/13280132/16864382/e1233f2c-4a21-11e6-9d52-c4184c56e0b8.png)

**Comment by saenzramiro** [comment]
I was investigating about Vector and seems to be a bug from them.

I think I will add Vector for the next release. :smiley:

**Comment by tiny6996** [comment]
thank you very much
