### ISSUE TITLE
The 0.5.12 tag is wrong.

### ISSUE THREAD

**Issue by flying-sheep** [saenzramiro/rambox#1124]
the tag [0.5.12](https://github.com/saenzramiro/rambox/releases/tag/0.5.12) actually points to 3c29bca49663657cb1e992746b0d1548734d93d6, the 0.5.11 commit

**Comment by saenzramiro** [comment]
That is because Travis build when I push the 0.5.12 PR and generate the artifacts, so don't worry, they were built on latest commit.

**Comment by flying-sheep** [comment]
i don’t use those, though. can you please fix the tag?
