### ISSUE TITLE
Slack tray icon 

### ISSUE THREAD

**Issue by codeweb** [saenzramiro/rambox#1125]
Private message are represented correctly with a red ball on the Rambox icon in notification area. Message received in a private or public channel are not in evidence as in Slack client.
Linked to: https://github.com/saenzramiro/rambox/issues/421

### Expected behavior

Icon in notification area changes adding a blue ball

### Actual behavior

Icon in notification area doesn't change

### ENVIRONMENT

> Rambox: v0.5.12

> OS: Windows 10

> Arch: x64

**Comment by nmat** [comment]
@codeweb there are some work in progress to change this: see https://github.com/saenzramiro/rambox/pull/806

Where the icon would change a little more generally. Still in progress
