### ISSUE TITLE
Add group icon for Slack

### ISSUE THREAD

**Issue by HuuThuan0701** [saenzramiro/rambox#113]
Would you add group icon for Slack so it should be better for managing these tabs?

![screenshot 2016-07-15 14 36 06](https://cloud.githubusercontent.com/assets/8679330/16867035/a9e649aa-4a99-11e6-8145-6953cf626564.png)

**Comment by saenzramiro** [comment]
That is great! I will try to add it for the next release.

**Comment by dbpolito** [comment]
I would love that, if doesn't automatically get from slack, simply having a icon field as we do for Custom Service already does the job.

**Comment by seza443** [comment]
It would be great to be able to customize the icon of any existing service like we do for Custom Service

**Comment by leomeloxp** [comment]
Any updates on this one?

**Comment by saenzramiro** [comment]
I will try to add it in v1.0.0.

**Comment by cedvan** [comment]
An improvement to customize the tabs images might be even better :wink:

**Comment by Haprog** [comment]
It would be really nice if Rambox could automatically get the team icon from Slack (like Franz currently does).

But also, as a more generic feature, it would be great if I could just define a custom icon for any service (either URL or local file).

I would gladly donate a small amount if these features were added. :)

**Comment by nderscore** [comment]
I have a hacky workaround for Slack team icons for until this is actually implemented as a feature:

1.  After launching Rambox, open the Rambox Dev Tools.

2.  Run this script in the DevTools console:
    ```javascript
    (() => {
      const slackWebviews = document.querySelectorAll('webview[src*=".slack.com"]');
      const slackTabs = document.querySelectorAll('.x-tab-icon-el[style*="resources/icons/slack.png"]');

      [...slackWebviews]
      .filter(webview => !webview._slackIconAdded)
      .forEach((webview, index) => {
        webview.executeJavaScript(`
          // lazy man's team icon grabbing method
          (() => {
            let teamIcon = document.querySelector('.team_icon');

            // open team menu if not already open
            if (!teamIcon) {
              const teamMenu = document.querySelector('#team_menu');

              if (teamMenu) {
                teamMenu.click();
                teamIcon = document.querySelector('.team_icon');
              }
            }

            // bail if no icon found
            if (!teamIcon) {
              return false;
            }

            // grab the background image from team icon
            const { style: { backgroundImage } } = teamIcon;

            // force menu to close after we have the goods
            const md = document.createEvent('MouseEvents');
            md.initEvent('mousedown', true, true);
            document.querySelector('.client_channels_list_container').dispatchEvent(md);

            return backgroundImage;
          })();
        `, 
        false, 
        (backgroundImage) => {
          if (backgroundImage) {
            slackTabs[index].style.backgroundImage = backgroundImage;
            webview._slackIconAdded = true;
          }
        });
      });
    })();
    ```

It will pull the team icon from each slack account you're connected to that has finished loading. 

If you log into another slack account later on in your session, you can run the script again to fill in any missing team icons.

**Comment by schwartzman** [comment]
Brilliant! Now if only there were a way to automatically run that script every time Rambox started...

**Comment by nmat** [comment]
tested on windows 10 here. Works perfect!

**Comment by TimTimNL** [comment]
Script stole my lunch and ate it. 10/10 would recommend again

**Comment by felixfischer** [comment]
Another workaround would be to add your Slack teams as Custom Services. You will have to find out the icon URL yourself and must add the [unreadCount function](https://github.com/saenzramiro/rambox/blob/master/app/store/ServicesList.js#L41) manually in the Custom Code section, but at least it will persist between restarts.

**Comment by munkymack** [comment]
@felixfischer I found my Icon URLs and added the line you linked:

js_unread: 'function checkUnread(){var a=0,b=0;$(".unread_msgs").each(function(){a+=isNaN(parseInt($(this).html())) ? 0 : parseInt($(this).html())}),$(".unread_highlights").each(function(){b+=isNaN(parseInt($(this).html())) ? 0 : parseInt($(this).html())}),updateBadge(a,b)}function updateBadge(a,b){var c=b>0?"("+b+") ":a>0?"(•) ":"";document.title=c+originalTitle}var originalTitle=document.title;setInterval(checkUnread,3000);'

but it (unread notifications) doesn't seem to be working. I'm not super JS conversant, so I'm not sure what I screwed up

**Comment by felixfischer** [comment]
You need to delete `js_unread: '` at the beginning of your snippet, and `'` at the end.

**Comment by Mte90** [comment]
The hack is very amazing and works!

**Comment by saenzramiro** [comment]
This will be available in next release thanks to @nderscore (PR #1160), so let's close it.

**Comment by Mte90** [comment]
Seems that is not working anymore

**Comment by iamcxa** [comment]
@Mte90 the script still working.

you need to open dev tool by targeting to the menu `window` and click `toggle  Developer Tool`, not the one you can open by click mouse's right button at the Slick service icon.

the effective one is the one slided in the webview, not the one open separately.

**Comment by Mte90** [comment]
as written in #1408 there are some problems right now

**Comment by Mte90** [comment]
I can confirm that this script still works.
