### ISSUE TITLE
Rambox cannout authorize against HTTP Basic Access Authentication 

### ISSUE THREAD

**Issue by K5HV** [saenzramiro/rambox#1130]
### Steps to reproduce

1. Create a new service and direct it to HTTP Basic Access Authentication (ex. http://httpbin.org/basic-auth/user/passwd)
2. Try to open this service.

### Expected behavior

Rambox should ask for login and password and authorize you against HTTP Basic Access Authentication.

### Actual behavior

Page is blank.
In Developer Tools I can see:

> GET http://httpbin.org/basic-auth/user/passwd 401 (Unauthorized)
> Navigated to http://httpbin.org/basic-auth/user/passwd

### ENVIRONMENT

> Rambox: v0.5.11 (build from 0.5.12 tag)

> OS: linux

> Arch: x64

**Comment by K5HV** [comment]
My company uses custom sign-in page with Outlook 365. Rambox cannot authorize against it.

**Comment by mkusz** [comment]
You can use custom service and add authentication data into url like this: http://user:password@url/

**Comment by cduranleau** [comment]
A couple people have tried that and failed[1]. Started some work here[2] but I don't know enough about electron to get a Username/Password prompt for the basic auth you mentioned. 


1. https://github.com/saenzramiro/rambox/issues/378#issuecomment-318927085
2. https://github.com/saenzramiro/rambox/issues/997#issuecomment-325796116

**Comment by jkischel** [comment]
And btw. storing the whole credentials in clear text is never a good idea.

**Comment by saenzramiro** [comment]
Let's relate this to #378
