### ISSUE TITLE
[Feature request] Open context menu on right click

### ISSUE THREAD

**Issue by ANDRON94** [saenzramiro/rambox#1137]
Hi, 
First of all, I am very grateful for this awesome application.
And I want to propose the next feature: open context menu on a right click. I like to copy links(native or image) from context menu a lot but I can't do it in all services that I use(telegram, Gmail, skype). Only in skype context menu works for several visual components. 

Best regards,
Andrii

**Comment by nmat** [comment]
@ANDRON94 duplicate of https://github.com/saenzramiro/rambox/pull/1074

**Comment by ANDRON94** [comment]
Sorry for duplication. I'll wait for the next release =) Thanks again.
