### ISSUE TITLE
Allow zoom in rambox

### ISSUE THREAD

**Issue by Mrrvm** [saenzramiro/rambox#114]

**Comment by jbbr** [comment]
This has been implemented in 0.4.0 with shortcut `CTRL - Numpad+/-`
See https://github.com/saenzramiro/rambox/issues/31#issuecomment-230631972

Default behavior in web browsers (At least Chrome, Firefox) is zooming also with `CTRL - +`  (not on the numpad).
It would be nice to be able to use this shortcut also in rambox.

**Comment by saenzramiro** [comment]
Ok, please create a ticket for that and I will add it for the next release.

**Comment by pgrm** [comment]
I think this can be closed now that everything is tracked in #217 or?

**Comment by saenzramiro** [comment]
@pgrm Yes, I will close this issue. Zooming will be added in next release.
