### ISSUE TITLE
Typo to fix

### ISSUE THREAD

**Issue by brendanjones** [saenzramiro/rambox#1140]
On logging out of Rambox, the text says "Closing you session..."
Should be "your" with an 'r'.

![screen shot 2017-09-11 at 18 53 44](https://user-images.githubusercontent.com/16049594/30286661-a2047e24-9722-11e7-8e2d-21a1c82eb0df.png)

**Comment by saenzramiro** [comment]
Fixed in Crowdin, thank you!
