### ISSUE TITLE
[Feature Request] Running multiple istances of the same service with different login credentials and identities

### ISSUE THREAD

**Issue by wokawoka** [saenzramiro/rambox#1143]
### Expected behavior

I (wish I could) open additional tabs of the same service (say protonmail or tutanota) and login with different credentials on any different tab

### Actual behavior

Only one tab for each service is possible 

### ENVIRONMENT

All supported OSes

**Comment by nmat** [comment]
I can run several services. Just need to add them as a different service. That is add them one and one into their own tabs.

**Comment by wokawoka** [comment]
Thanks for your reply. It indeed works by adding custom services.
But being able to select additional istances of the same service directly from the main menu would be much more practical though (and visually more clean, since for the moment it's not possible to use a local icon for the additional custom service tabs, only an icon available on a web address).

**Comment by gameguy95** [comment]
You don't need to add a custom service at all. You just click the button for the service you want to add and login like normal. 
Source: I use 2 Gmail accounts, 2 Telegram accounts, 2 Skype accounts, and 2 Facebook accounts in Rambox as my normal setup. See the screenshot below. (Covered up some personal stuff, but the point stands.) 
<img width="960" alt="screenshot 2017-09-28 13 26 02" src="https://user-images.githubusercontent.com/15315644/30988955-dd1736ba-a450-11e7-9948-cd32f07668f9.png">

**Comment by wokawoka** [comment]
Great, I don't know how I could have missed that myself. Thanks a lot!
