### ISSUE TITLE
Tabs mangled, lost or doubled when restarting the app

### ISSUE THREAD

**Issue by pcdog** [saenzramiro/rambox#115]
Due to previous reported issues with the 64bit Build on my PC (white pages only, and unable to login) I have switched to the 32bit build.

Sometimes the app locks up - some of the tabs do nothing if you click on them, it just opens another tab instead.

when you close it from the tray and open it up again, it drops some apps and doubles other.

E.g instead of having skype, now I have 2x Protonmail and 0 times skype 

Is there a way to produce debug log for you? @saenzramiro

**Comment by pcdog** [comment]
OK, this also happens on my Ubuntu with the 64bit version.

Somehow it just swaps out the tabs and doubles another one


See the doubled ZM (Zimbra) as well as the doubled PM (ProtonMail)

Missing is for example whatsapp.....and skype. and it's not even consistent. the config gui is even different.

Tabs
![2016-07-16-103628_1679x159_scrot](https://cloud.githubusercontent.com/assets/1210076/16893731/67d757ea-4b41-11e6-9302-32915cd6d44b.png)

Config gui
![2016-07-16-103852_840x791_scrot](https://cloud.githubusercontent.com/assets/1210076/16893735/a15bfe9e-4b41-11e6-85a2-8d1351b5e0d7.png)


This makes this broken. I'm suspecting it has to do with the online config sync which seems to be broken? If I have to ditch this feature, fine - but right now suddenly tabs silently disappear makes it unusable :(

**Comment by saenzramiro** [comment]
Are you using Rambox in multiples devices?

**Comment by pcdog** [comment]
Yes, 

one arch linux notebook a bit outdated
1x Ubuntu Notebook I am not sure what release
1x MacPro with Ubuntu 16.04 on it, updated since probably 14.04 only
1x Selfbuilt other box updated a few more releases than that, 13.x which is the box with the whitepages


they are all logged into the same account => Is that a not supported configuration? 

they also run simultaneously sometimes

**Comment by saenzramiro** [comment]
Well... yes, it should work.

All have Rambox 0.4.0? If yes, try to logout in all PCs and login only in one. Configure your services as you want and then, login in your others PCs.

Let me know if works ok now.

**Comment by pcdog** [comment]
I have removed all Services in the meantime and reconfigured. Seems to be stable since i did it when 0.4.0 was already out and I did not login with the older version anymore.
