### ISSUE TITLE
Quit Rambox when the window is closed and there is no tray icon

### ISSUE THREAD

**Issue by aldonogueira** [saenzramiro/rambox#1156]
Since Gnome, elementary OS and others [declared war on system tray icons](https://blog.martin-graesslin.com/blog/2014/06/where-are-my-systray-icons/), I've decided to try living without them. In the process of adjusting Rambox, a little bug became evident.

Steps to reproduce:
- Access the menu File > Preferences
- On "Display behaviour", choose "Show in TaskBar"
- On "When closing the main window", choose "Keep in tray"
- Click on Save
- Close the window

**BUG**: There is no visual indication that the program is still alive and no way to access it again. A `ps aux | grep -i rambox` shows a few processes, proving the program is still running.

The only option that makes sense for action when you close the window is 'Quit', since the other ones require the tray icon. In fact, the whole dropdown should be disabled.

	
	-
	> Rambox 0.5.12
	> Electron 1.7.5
	> linux x64 4.10.0-33-generic

**Comment by saenzramiro** [comment]
This will be fixed in next release. Thanks!
