### ISSUE TITLE
Link for .deb downloads .tar.gz

### ISSUE THREAD

**Issue by biffster** [saenzramiro/rambox#1164]
On the download section for the main website (http://rambox.pro/#download), for Linux, clicking on the "Download Deb 64-bit" option downloads a .tar.gz file instead of a .deb file.

**Comment by jbernsie** [comment]
you can convert the tarball with the `alien` command, I'm assuming this will be fixed in time
```
$ apt install alien
$ sudo alien --to-deb ~/Downloads/Rambox-0.5.13-x64.tar.gz
```

**Comment by greyfenrir** [comment]
@jbernsie 
1. yes, we can, but it is issue of site isn't it?
2. more that official deb is available now at https://github.com/saenzramiro/rambox/releases

**Comment by saenzramiro** [comment]
Yes @biffster, we have to fix that. But for now, you can download it by going to releases section like @greyfenrir said.

**Comment by biffster** [comment]
Ayup, I was able to track down the .deb, figured you would want to know about the wrong link though.

**Comment by kalsan** [comment]
The problem still persists.

**Comment by Ash258** [comment]
Let's continue in #1401
