### ISSUE TITLE
Duble click on tray does open app

### ISSUE THREAD

**Issue by Najkon** [saenzramiro/rambox#1166]
### Steps to reproduce

1.  if we choose in settings " When closing the main windows : Keep in tray "
2.  then if I want open app - clicking on icon double left mouse button - and nothing happens 

### Expected behavior
- double click on icon in tray open app 

### Actual behavior
- nothing happens

### ENVIRONMENT

Rambox: v0.5.12
OS: Deepin (based on Debian)
Arch: x64

**Comment by EruIluvatar** [comment]
#942

**Comment by saenzramiro** [comment]
Like @EruIluvatar said, it's duplicated with #942.

Let's close this one.
