### ISSUE TITLE
Rambox keyboard shortcut for lock

### ISSUE THREAD

**Issue by skandix** [saenzramiro/rambox#1168]
would be nice to have a keyboard shortcut for locking the Rambox, like CTRL+L or Mod+L. haven't seen the choice to do this, would be really nice to have

**Comment by joe776** [comment]
0.5.12 does this with F2 (on macOS at least). Shortcut is shown when hovering the Lock button.

**Comment by saenzramiro** [comment]
As @joe776 said, is F2 the shortcut.
