### ISSUE TITLE
Slack receive notification for muted channels

### ISSUE THREAD

**Issue by Tseberechts** [saenzramiro/rambox#1169]
### Steps to reproduce

1. In slack, mute a channel
2. Have someone say something in that channel

### Expected behavior
No notification on the slack logo in the top bar.

### Actual behavior
Notification on the slack logo in the top bar.

### ENVIRONMENT

> Rambox: v0.5.12

> OS: OSX 10.12.6 (16G29)

> Arch: x64

**Comment by hoelzro** [comment]
I can confirm this on my installation too (0.5.12 on x86_64 Arch Linux) - I was able to fix it with this custom JS snippet:

```js
function checkUnread() {
    var a = $('.p-channel_sidebar__channel--unread:not([class*="p-channel_sidebar__channel--muted"])').length;
    var b = 0;
    $(".p-channel_sidebar__badge").each(function() {
        b += isNaN(parseInt($(this).html())) ? 0 : parseInt($(this).html())
    });
    updateBadge(a, b)
}
```

**Comment by jcherniak** [comment]
I just saw this issue after i spent an hour getting a build working to fix it.  My pull request should fix the issue permanently.

**Comment by hoelzro** [comment]
Instead of using `setInterval` to poll for the notifications classes, perhaps Rambox could use the `MutationObserver` API?  I don't know if it's available in electron, though!
