### ISSUE TITLE
"Unsupported Browser" message in Discord

### ISSUE THREAD

**Issue by theredhood13** [saenzramiro/rambox#1177]
When trying to use the voice chat in Discord, it displays Unsupported Browser.

	
	-
	> Rambox 0.5.12
	> Electron 1.7.5
	> win32 x64 10.0.15063

**Comment by Flameofrage** [comment]
I can confirm this occurs in linux as well, it looks to be due to electron.

**Comment by Rydkey** [comment]
Same over there on windows 10 64 bit
