### ISSUE TITLE
Feature Request: Ability to set tabs to left or right side instead of top.

### ISSUE THREAD

**Issue by digitalfiz** [saenzramiro/rambox#1178]
It would be nice for people with wide monitors to be able to set the tabs to be on the left or right side since the vertical space is more precious for them.

Also how about a dark theme? That bright white tab bar is distracting :P

**Comment by lmagno** [comment]
I would like having the option of hiding it completely, as most services take up a lot of space with their own bars. Or at least set it to a smaller height.

**Comment by RYRNRY** [comment]
It could be be added to PREFERENCES section
TABS POSITION : Left / Right / Up / Down
TABS DISPLAY : Show / Hide

**Comment by omarelnaggar** [comment]
+1 on this, I can't use this Rambox unfortunately unless the tabs are on the left

**Comment by intropedro** [comment]
+1

**Comment by knw257** [comment]
+1

**Comment by maddo** [comment]
Looks like @saenzramiro did this in https://github.com/saenzramiro/rambox/pull/1622, but it's not released yet.

**Comment by Ash258** [comment]
Closed in #1622
