### ISSUE TITLE
Create repository for custom services

### ISSUE THREAD

**Issue by ArtIsResistance** [saenzramiro/rambox#118]
I think it's good idea to create repository where users could share their custom service settings via pull-requests. Something like _rambox-services-contrib_

**Comment by saenzramiro** [comment]
It's a great idea! I had in mind to allow adds services from links with special scheme. Like:

`rambox://MyCustomService#http://url.com#http://logo.com#js_code`

So users can create buttons/images to add different custom services. You click that button, it opens Rambox automatically and ask you for add that services with all pre-filled data. It's like Magnet links for Torrent Clients. Seems to be not easy to do this, but in the meantime we can use a repo! 

Let me think about it a little bit. :wink:

**Comment by saenzramiro** [comment]
New repo for this!

https://github.com/saenzramiro/rambox-services-contrib
