### ISSUE TITLE
Discord - Unsupported Browser/Can't Join Voice

### ISSUE THREAD

**Issue by Kynimer** [saenzramiro/rambox#1184]
### Steps to reproduce

Any of the following in no particular order;

1. Attempt to join a voice channel
2. Attempt to undeafen yourself
3. Attempt to unmute yourself

### Expected behavior

Actually joining a call

### Actual behavior

Pop-up explaining why I can't/telling me to update my browser or download the Discord app

### ENVIRONMENT

> Rambox: v0.5.12

> OS: Windows 10

> Arch: x64

**Comment by maxtros** [comment]
confirmed v0.5.12

**Comment by AbrarSyed** [comment]
Also confirmed on Arch Linux. Also version 0.5.12

**Comment by saenzramiro** [comment]
Let's merge this with #1177
