### ISSUE TITLE
[Slack] Unread Count displayed in ServiceTitle

### ISSUE THREAD

**Issue by dazlious** [saenzramiro/rambox#1187]
### Steps to reproduce

1. Use Slack

### Expected behavior
When I receive messages, unread count shows number of messages received. When I read them, unread count resets as expected and stays this way

### Actual behavior
When I receive messages, unread count shows number of messages received. When I read them, unread count resets as expected. But randomly unread count is shown again with no number. Just a bullet list point.

### Steps tried
1. uninstalled whole app with configs
2. logged out slack, logged back in
3. reloaded (CMD+R)
4. Set document.title to anything else -> resets for a second

All steps failed.

### Environment

Version: 0.5.12
Platform: darwin (x64)
Electron: 1.7.5
Chromium: 58.0.3029.110
Node: 7.9.0

**Comment by bhagatparwinder** [comment]
I have the same issue. I have 4 slack teams and 2 of them have all channels muted. I do see a bulleted notification.

![image](https://user-images.githubusercontent.com/6809087/30974595-9e514422-a435-11e7-8f67-3cfb416635e3.png)

**Comment by mfgea** [comment]
The issue happens because of muted channels. When you have unread messages in muted channels, the unread bullet is shown.

I solved using the following Custom Code:

```
function checkUnread() {
    var a = $(".p-channel_sidebar__channel--unread:not(.p-channel_sidebar__channel--muted),.p-channel_sidebar__link--unread").length;
    var b = 0;
    $(".p-channel_sidebar__badge").each(function() {
        b += isNaN(parseInt($(this).html())) ? 0 : parseInt($(this).html())
    });
    updateBadge(a, b)
}

function updateBadge(a, b) {
    var c = b > 0 ? "(" + b + ") " : a > 0 ? "(•) " : "";
    document.title = c + originalTitle
}
var originalTitle = document.title;
```

Hope it helps!

**Comment by mfgea** [comment]
I just found a similar question/workaround: https://github.com/saenzramiro/rambox/issues/1169

@dazlious This issue should be closed and the discussion moved there.

**Comment by dazlious** [comment]
moved to: #1169
