### ISSUE TITLE
WhatsApp unread counter don't works?

### ISSUE THREAD

**Issue by NinoDnB** [saenzramiro/rambox#1189]
Hello,

the unread counter for WhatsApp don't works, no tab no count in the dock...

### ENVIRONMENT

> Rambox: v0.5.12

> OS: Mac OS 10.13 High Sierra

> Arch: x64

**Comment by musicmunky** [comment]
I'm also seeing this same issue - The unread counter works for all other chat services except WhatsApp.  No counter on the Tab in the window, no badge counter in the dock icon.
Installed on Mac OS Sierra 10.12.6, Rambox v0.5.12

**Comment by 613TheEvil** [comment]
I have the same issue. Let me update to 12 to see if I get any improvement.

**Comment by theblazehen** [comment]
Useless comment, as it's all the same code. Same on Linux

**Comment by masterkorp** [comment]
Same issue here
```
Version: 0.5.12
Platform: linux (x64)
Electron: 1.6.11
Chromium: 56.0.2924.87
Node: 7.4.0
```

**Comment by luxlabs** [comment]
Same issue here

> Rambox 0.5.12
> Electron 1.7.5
> darwin x64 16.7.0

**Comment by saenzramiro** [comment]
Seems like WhatsApp changed the HTML code and now there isn't a `unread-count` class. 😢 

I will fix this for next release.

**Comment by musicmunky** [comment]
Thanks for looking into this @saenzramiro !

**Comment by roman-89** [comment]
Thanks! This was fast :)
