### ISSUE TITLE
App's menu opens when I change keyboard layout by Alt+Shift

### ISSUE THREAD

**Issue by DmitryNikonov** [saenzramiro/rambox#120]
When I hit Alt+Shift to change my keyboard layout, app's menu opens so I can't type anything until I close it. It's really annoying.

Also I did some research and found that it seems to be a common problem for electron-based apps. The thing is when you have some high-level menu labels without underscored letters (these ones that allow you to activate this menu item by hittimg alt+underscored_letter), they will be activated when you hit Alt+Shift. 
I don't know if it's a bug or just a feature but probable workaround is to edit app.asar file with modifying menu labels' definitions in this way: `label: 'File'` -> `label: '&File'`. This way it will add an 'underscore' to letter F and therefore prevent this menu item to be activated by hitting Alt+Shift. I fixed my Slack and GPMDP apps this way but when I tried to do it with the Ramble app I got it broken. Therefore it seems that I can't fix this by myself and send you a pull request so I hope you would look into it and make a fix.

## 

> Rambox 0.4.0
> Electron 1.2.6
> linux x64 4.6.4-1-ARCH

**Comment by romanlex** [comment]
Confirm!

**Comment by saenzramiro** [comment]
Ok, got it.

Let me take a look, I will consider your solution of this. :+1:

**Comment by Alexus230** [comment]
I found similar issue: https://github.com/RocketChat/Rocket.Chat.Electron/issues/50

And ... solution: https://github.com/RocketChat/Rocket.Chat.Electron/commit/5b684bbd4df4a583ac39a7f96a980da6feeabbe4

**Comment by justpusher** [comment]
Issue still exists in v.0.4.5, though the corresponding commit seems to be already merged.

**Comment by Alexus230** [comment]
By the way, I found that:
* Unity - not affected by this bug
* KDE - affected

Probably, to avoid this issue we need to manually set `&` on *any label*. For example this menu entries doesn't have `label:`:
* Quit
* Undo
* Redo 
* ... etc.

**Comment by oueryemchi** [comment]
I am on Windows 10 pro..I have the latest Slack and I use Alt+Tab a lot to switch apps and I have the menu popping out every single time and it is driving me insane..any help would be highly appreciated. Thanks guys.

**Comment by Ash258** [comment]
@oueryemchi: 
> I have the latest

What does have "latest Slack" to do with Rambox? Or is "latest Slack" something else than desktop slack application?

**Comment by oueryemchi** [comment]
I am simply referring the Desktop Slack application..the issue relates to it when I switch it using Alt+Tab..does it make sense?

**Comment by Ash258** [comment]
Do you know that Slack Desktop application does not have nothing to do with Rambox? So its totally irrelevant.

**Comment by Ash258** [comment]
@oueryemchi If you want to report issue to slack use their [twitter](https://twitter.com/slackhq) or even better their [Help Center](https://get.slack.help/hc/en-us).

**Comment by oueryemchi** [comment]
Thanks!

**Comment by justpusher** [comment]
@oueryemchi I reported this issue to slack support, and they resolved it in 3.2 alpha: 
https://slack-files.com/T12KS1G65-FA2R46QJH-7dafaee6be

> Two things to note are that our QA team is still testing this version and the package is unsigned.
