### ISSUE TITLE
Can't enable browser notifications for Spectrum.chat

### ISSUE THREAD

**Issue by jaminroe** [saenzramiro/rambox#1206]
I added https://spectrum.chat as a service - Similar to Slack. When I go to the notification settings to enable browser push notifications, the site says I can't. Is this a site issue or an issue with Rambox?
![31132373-9f154068-a82a-11e7-8922-5f5b094ce2fb](https://user-images.githubusercontent.com/1559447/31240723-90f1cf14-a9cf-11e7-9a5d-8a67a657c651.gif)

	
	-
	> Rambox 0.5.13
	> Electron 1.7.8
	> darwin x64 16.7.0

**Comment by saenzramiro** [comment]
I think it's because Electron don't support push notifications.
See electron/electron#6697

**Comment by wmertens** [comment]
There is now https://github.com/MatthieuLemoine/electron-push-receiver but it is something that needs to be added as a plugin to electron @saenzramiro

**Comment by saenzramiro** [comment]
@wmertens Thank you, I saw that too the other day. I will take a look.
