### ISSUE TITLE
Add possibility to reload a service

### ISSUE THREAD

**Issue by KochFolie** [saenzramiro/rambox#121]
It would be great to have a tab-specific reload-button to fix issues with a service. Sometimes a webservice is "broken" after some time, or even at program start. The only way to fix that currently is to restart Rambox, or use the reload-button from the Electron-menu, which reloads the whole Rambox app and not only the current tab.

-
> Rambox 0.4.0
> Electron 1.2.6
> win32 x64 10.0.10586

**Comment by pcdog** [comment]
Doubleclicking a tab should also offer a reload button

**Comment by KochFolie** [comment]
That works, thanks! But why doubleclick? I would suggest to also show this menu on right clicking a tab.

**Comment by saenzramiro** [comment]
Because to do right click I had to find a way to enable context menus on Electron Apps, I tried but I couldn't. :disappointed:

**Comment by KochFolie** [comment]
Ok well that's a reason. :) Thanks for the info.
