### ISSUE TITLE
Disabled service can't be removed

### ISSUE THREAD

**Issue by Sudiukil** [saenzramiro/rambox#1211]
I updated Rambox to 0.5.13 this morning and I saw that the deletion of a disabled service hangs indefinitely and the service is not removed. 

### Steps to reproduce

1. Start Rambox
2. Try removing a **disabled** service by clicking the "remove" icon in the "Enabled Services" list
3. Click "Yes" in the "Please confirm..." popup

### Expected behavior

The service is removed and the user can continue using Rambox.

### Actual behavior

A "Removing..." popup spawns (see attached screenshot) and stays forever with a never ending loading bar.

If user reloads or restart Rambox, the service is still present and **enabled**.

![2017-10-06-085746_279x143_scrot](https://user-images.githubusercontent.com/5354318/31266676-2f84eba2-aa75-11e7-8a5c-6df30a77d666.png)

### Additionnal notes

Deleting an enabled service works fine, the problem is specific to disabled services.

### ENVIRONMENT

> Rambox: v0.5.13

> OS: Debian 9/Linux 4.9

> Arch: x64

**Comment by pztrn** [comment]
Confirming for macOS 10.12.6 / Rambox 0.5.13.

**Comment by Ki11Deer** [comment]
Confirmed on  0.5.13 win32 (x64)

**Comment by sn0w** [comment]
Can reproduce with 0.5.13 on Debian Jessie and Arch Linux

**Comment by saenzramiro** [comment]
This probably happens when the service never finish loading, because I tested and works for me.

https://github.com/saenzramiro/rambox/blob/cadc64c3d5a6a4172f75c92bf2ddef4a5a85485f/app/view/main/MainController.js#L122-L124

I will use the event `did-start-loading` so we can still get the webContent and clear all cache and storage.

**Comment by ajaypayne** [comment]
Can still reproduce on 0.5.17 on Fedora 28
