### ISSUE TITLE
Only black screen with Win7

### ISSUE THREAD

**Issue by heironeous** [saenzramiro/rambox#1219]
I believe (did not try reproducing yet):
1. Have rambox running
2. Put the laptop to sleep
3. Laptop battery dies, and goes into hibernation mode before dying
4. Plug laptop to power, boot from hibernation
5. Rambox goes into black screen
5a. Quit rambox from system tray, restart -> still black screen
5b. Restart computer normally, have rambox start with windows startup -> sill black screen
5c. Quit rambox from 'File' -> 'Quit Rambox' - I could see the initial 'Add account' screen, but the tabs were all only white
5c1. Black screen happened again, quit from 'File' menu, got black screen again
5d. Clear cache / local storage -> still black screen

Solution:
Had to uninstall/install
I used RevoUninstaller to remove any leftover files as well.

Win 7, Latest version of rambox (0.5.13)

	
	-
	> Rambox 0.5.13
	> Electron 1.7.8
	> win32 x64 6.1.7601

**Comment by saenzramiro** [comment]
Thank you @heironeous for sharing the solution.

We will investigate to know why is showing a black screen.

**Comment by hughwilliams94** [comment]
Just to say that, I have also been using the latest Rambox on Win7 at work and just get a blank screen for all services. I don't have much experience debugging on windows but I am happy to help. Have switched back to 0.5.12 in the mean time.
