### ISSUE TITLE
Launching multiple Rambox instances?

### ISSUE THREAD

**Issue by piotryordanov** [saenzramiro/rambox#1230]
Is there a way to launch 2 instances of rambox, one that would be for work apps and another for chat apps for instance?

I tried running `open -n /Application/Rambox.app` but that doesn't enforce opening a new instance. Even if it did work, the two apps would probably be using the same configuration which is not what i want.
I also tried building rambox from source on mac, but that didn't work out (Something about asar missing)

**Comment by saenzramiro** [comment]
No, we disabled running multiple instances. I think you will have to wait for version 1.0. ;)

http://rambox.pro/100

**Comment by piotryordanov** [comment]
Ah, I see. So, is ther an ETA for this version, or does it depend on how the donation goes?

Cheers mate!

**Comment by pape-rone** [comment]
sorry to dig out this old ticket. I see that my current version is 0.5.17. Do you mean that version 0.1.0 is required or 1.0.0? or more precisely, any chance to run multiple instances with my current version?
