### ISSUE TITLE
Sencha app watch fails

### ISSUE THREAD

**Issue by theSoenke** [saenzramiro/rambox#124]
I tried to build rambox, but sencha app watch fails. Here is the log

>Sencha Cmd v6.1.3.42
[INF] Using GPL version of Ext JS version 5.1.1.451 from /home/vagrant/rambox/ext.
[INF] The implications of using GPL version can be found here (http://www.sencha.com/products/extjs/licensing).
[INF] Processing Build Descriptor : default
[INF] Starting server on port : 1841
[INF] Mapping http://localhost:1841/~cmd to /home/vagrant/bin/Sencha/Cmd/6.1.3.42...
[INF] Mapping http://localhost:1841/ to /home/vagrant/rambox...
[INF] Application available at http://localhost:1841
[INF] Loading app json manifest...
[INF] Appending content to /home/vagrant/rambox/bootstrap.js
[INF] Writing content to /home/vagrant/rambox/bootstrap.json
[INF] merging 309 input resources into /home/vagrant/rambox/build/development/Rambox/resources
[INF] merged 0 resources into /home/vagrant/rambox/build/development/Rambox/resources
[INF] merging 4 input resources into /home/vagrant/rambox/build/development/Rambox
[INF] merged 0 resources into /home/vagrant/rambox/build/development/Rambox
[INF] Writing content to /home/vagrant/rambox/sass/example/bootstrap.json
[INF] Writing content to /home/vagrant/rambox/sass/example/bootstrap.js
[INF] writing sass content to /home/vagrant/rambox/build/temp/development/Rambox/sass/Rambox-all.scss.tmp
[INF] appending sass content to /home/vagrant/rambox/build/temp/development/Rambox/sass/Rambox-all.scss.tmp
[INF] appending sass content to /home/vagrant/rambox/build/temp/development/Rambox/sass/Rambox-all.scss.tmp
[INF] writing sass content to /home/vagrant/rambox/build/temp/development/Rambox/sass/config.rb
[ERR] The following error occurred while executing this line:
/home/vagrant/rambox/.sencha/app/build-impl.xml:247: The following error occurred while executing this line:
/home/vagrant/rambox/.sencha/app/watch-impl.xml:61: The following error occurred while executing this line:
/home/vagrant/rambox/.sencha/app/build-impl.xml:285: The following error occurred while executing this line:
/home/vagrant/rambox/.sencha/app/sass-impl.xml:189: The following error occurred while executing this line:
/home/vagrant/rambox/.sencha/app/sass-impl.xml:235: Problem: failed to create task or type x-compass-compile
Cause: The name is undefined.
Action: Check the spelling.
Action: Check that any custom tasks/types have been declared.
Action: Check that any <presetdef>/<macrodef> declarations have taken place.

I'm using Sencha Cmd v6.1.3.42  and Node v4.4.7

**Comment by saenzramiro** [comment]
Don't know the reason.

I have been using [THIS](https://github.com/saenzramiro/rambox#environment) environment.

**Comment by theSoenke** [comment]
I now tried it with Node v4.0.0 and Sencha Cmd v6.1.2.15 and still same result

**Comment by saenzramiro** [comment]
Be sure to have Compass installed/working in your environment.

**Comment by theSoenke** [comment]
Compass was actually missing. Now i get a different error:

>Sencha Cmd v6.1.2.15
[INF] Using GPL version of Ext JS version 5.1.1.451 from /home/soenke/Repos/rambox/ext.
[INF] The implications of using GPL version can be found here (http://www.sencha.com/products/extjs/licensing).
[INF] Processing Build Descriptor : default
[INF] Starting server on port : 1841
[INF] Mapping http://localhost:1841/~cmd to /home/soenke/bin/Sencha/Cmd/6.1.2.15...
[INF] Mapping http://localhost:1841/ to /home/soenke/Repos/rambox...
[INF] Application available at http://localhost:1841
[INF] Loading app json manifest...
[INF] Appending content to /home/soenke/Repos/rambox/bootstrap.js
[INF] Writing content to /home/soenke/Repos/rambox/bootstrap.json
[INF] merging 309 input resources into /home/soenke/Repos/rambox/build/development/Rambox/resources
[INF] merged 0 resources into /home/soenke/Repos/rambox/build/development/Rambox/resources
[INF] merging 4 input resources into /home/soenke/Repos/rambox/build/development/Rambox
[INF] merged 0 resources into /home/soenke/Repos/rambox/build/development/Rambox
[INF] Writing content to /home/soenke/Repos/rambox/sass/example/bootstrap.json
[INF] Writing content to /home/soenke/Repos/rambox/sass/example/bootstrap.js
[INF] writing sass content to /home/soenke/Repos/rambox/build/temp/development/Rambox/sass/Rambox-all.scss.tmp
[INF] appending sass content to /home/soenke/Repos/rambox/build/temp/development/Rambox/sass/Rambox-all.scss.tmp
[INF] appending sass content to /home/soenke/Repos/rambox/build/temp/development/Rambox/sass/Rambox-all.scss.tmp
[INF] executing compass using system installed ruby runtime
[ERR] 
[ERR] BUILD FAILED
[ERR] com.sencha.exceptions.ExProcess: Failed creating background process
[ERR] 	at sun.reflect.DelegatingMethodAccesso
[ERR] rImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[ERR] 
[ERR] Total time: 2 seconds
[ERR] The following error occurred while executing this line:
/home/soenke/Repos/rambox/.sencha/app/build-impl.xml:247: The following error occurred while executing this line:
/home/soenke/Repos/rambox/.sencha/app/watch-impl.xml:61: The following error occurred while executing this line:
/home/soenke/Repos/rambox/.sencha/app/build-impl.xml:285: The following error occurred while executing this line:
/home/soenke/Repos/rambox/.sencha/app/sass-impl.xml:189: The following error occurred while executing this line:
/home/soenke/Repos/rambox/.sencha/app/sass-impl.xml:235: com.sencha.exceptions.ExProcess: Failed creating background process

**Comment by saenzramiro** [comment]
What version of Compass are you using?

My version is 1.0.3. Try to install the same version.

**Comment by theSoenke** [comment]
I used the one included in Sencha Cmd 6.1.2.15. But now with compass 1.0.3 installed it finally works. Thanks :)
