### ISSUE TITLE
Discord number message

### ISSUE THREAD

**Issue by MatiasMovie** [saenzramiro/rambox#1240]
Discord not show number of unreaded messages

	
	-
	> Rambox 0.5.13
	> Electron 1.7.8
	> win32 x64 10.0.15063

**Comment by terrycloth** [comment]
Same for me. The Discord tab does not show any status or count of unread messages.

* Rambox 0.5.13
* Electron 1.7.8
* linux x64 4.13.10-200.fc26.x86_64

**Comment by terrycloth** [comment]
Oh, and the Rambox system tray icon does not indicate unread messages at all when Discord is the only chat service waiting to be read.

**Comment by norswap** [comment]
Same here with Rambox 0.5.13, observed both on Windows 7 and Mac OS X. No unread counter for unread messages.

**Comment by Vanarill** [comment]
Same issue here, using:
Version: 0.5.13
Platform: linux (x64)
Electron: 1.7.8

**Comment by bhaelochon** [comment]
Same here.

* Rambox 0.5.13
* Electron 1.7.8
* win32 x64 10.0.16299

**Comment by yonilerner** [comment]
Same here. Im not sure how to get the Rambox version from the program itself, but its still happening in the newest https://github.com/saenzramiro/rambox/releases/tag/0.5.14 release

**Comment by SitoriTenshi** [comment]
Same here.

Version: 0.5.14
Platform: win32 (x64)
Electron: 1.7.8
Chromium: 58.0.3029.110
Node: 7.9.0

**Comment by RedWavez** [comment]
Also same! Please consider fixing it. Thank you!

Version: 0.5.14
Platform: win32 x64 6.1.7601
Electron: 1.7.8
Chromium: 58.0.3029.110
Node: 7.9.0

**Comment by bhaelochon** [comment]
Still having the issue with the recent update.

* Rambox 0.5.14
* Electron 1.7.8
* win32 x64 10.0.16299

**Comment by yonilerner** [comment]
Same:
Version: 0.5.16
Platform: linux (x64)
Electron: 1.8.3
Chromium: 59.0.3071.115
Node: 8.2.1

**Comment by Andreas-Schoenefeldt** [comment]
Same:
Version: 0.5.16
Platform: darwin (x64)
Electron: 1.8.3
Chromium: 59.0.3071.115
Node: 8.2.1

Would be great to fix this :)

**Comment by Ash258** [comment]
Wokraround for now (unless new rambox version)

1. Go to Discord settings
2. Click advanced
3. Past code below into Custom Code box

```javascript
function getAlertCount(badges) {
	var alerts = 0;
	for (var i = 0; i < badges.length; i++) {
		var badge = badges[i];
		if (badge && badge.childNodes && badge.childNodes.length > 0) {
			var count = parseInt(badge.childNodes[0].nodeValue, 10);
			alerts += count.isNaN
				? 1
				: count;
		} else {
			alerts++;
		}
	}
	return alerts;
}

function checkUnread() {
	var direct = 0,
		indirect = document.querySelectorAll('.guilds-wrapper .unread').length,
		guildDirect = document.querySelectorAll('.guilds-wrapper .badge'),
		channelDirect = document.querySelectorAll('[class^="nameUnreadText-"]+div>div>div');

	direct += getAlertCount(guildDirect);
	direct += getAlertCount(channelDirect);
	indirect += document.querySelectorAll('[class^="nameUnreadText-"]').length;

	updateBadge(indirect, direct);
}

function updateBadge(ind, dir) {
	var n = dir > 0
		? "(" + dir + ") "
		: ind > 0
			? "(•) "
			: "";
	document.title = n + originalTitle;
}

var originalTitle = document.title;
setInterval(checkUnread, 3e3);
```

**Comment by yonilerner** [comment]
Thats awesome, thank you so much!
