### ISSUE TITLE
Stuck at getting configuration after login

### ISSUE THREAD

**Issue by itsjef** [saenzramiro/rambox#125]
I give the app the permissions the it requested after I logged in with my Gmail. However, the connection process just runs over and over, temporarily disabling everything so I have no choice but to restart the app, but after restarting I am not logged in anymore.

![screenshot - 07182016 - 09 19 05 pm](https://cloud.githubusercontent.com/assets/1902587/16918044/4284c8da-4d2e-11e6-963c-e1f499bc3983.png)

**Comment by saenzramiro** [comment]
Are you using Rambox in more than one computer?

For now, instead of restart the app, you can Reload by going to `View -> Reload`.

**Comment by itsjef** [comment]
I'm using on one machine only

I tried as your advice but the result remains the same, I am still not signed in after reloading.

**Comment by saenzramiro** [comment]
Please, share your environment specs.

**Comment by itsjef** [comment]
My laptop runs __Debian Jessie__, kernel __3.16.0-4-amd64__

Is there other information you might need?
