### ISSUE TITLE
Grace timeout for "No Internet Connection" error, please.

### ISSUE THREAD

**Issue by Sarke** [saenzramiro/rambox#1255]
### Steps to reproduce

1. Install on Linux
2. Set rambox to autostart
3. Log in, and you will get the error message in question before the OS has had a chance to connect to the wifi.

### Expected behavior

Rambox starts on startup, but doesn't complain about no internet connectivity for a certain grace period (maybe 10 sec to 1 minute).  If it can't connect right away, sleep and try again.

### Actual behavior

Rambox complains about no internet every single login, even though the computer is in the process of connecting to wifi.

### ENVIRONMENT

Version: 0.5.13
Platform: linux (x64) Linux Mint 18.1 MATE
Electron: 1.7.8
Chromium: 58.0.3029.110
Node: 7.9.0

**Comment by rantanplan77** [comment]
+1, equally annoying on a Mac.

**Comment by muescha** [comment]
i add my Expected behavior:
no error message while startup
no modal message so it not is a "jumping icon" in dock
just write it in the app and automatic detect if there is a connection (see how franz handle this)

**Comment by muescha** [comment]
i think this PR not fix the "jumping icon" - sometimes i start my macbook without internet connection and connect later - for example with public WiFi you have to hit a connect button before you can go online. please not expect everyone is "always on" :)
