### ISSUE TITLE
Rambox starts outside of Monitor

### ISSUE THREAD

**Issue by metinkale38** [saenzramiro/rambox#1263]
Rambox stays outside of screen, if you moved it to a secondary screen while having an extra monitor and you cant move it back

### Steps to reproduce

1. Attach a second monitor (in my case: Laptop+HDMI Monitor, Monitor as Primary, Laptop Monitor as Secondary)
2. Move Rambox to secondary monitor
3. Quit Rambox
4. Detach HDMI
5. Start Rambox

### Expected behavior

Rambox starts on Laptop Monitor

### Actual behavior

Rambox starts outside of the Window (where the secondary screen would be) and i cant move it back.
I have to move it to the main screen, while i am using a second monitor.
### ENVIRONMENT

> Rambox: v0.5.13

> OS: Windows 10

> Arch: x64

**Comment by Dareiko** [comment]
You can move it using Windows Key + arrow, when you highlight rambox in taskbar and if you can run rambox on Windows machine. This solution working for me.

**Comment by ptr1120** [comment]
Same problem on my side. "Windows" + "Cursor" did not help (already tried multiple times) . Only disconnecting the monitor + restarting rambox helps.

**Comment by Tommy544** [comment]
The same issue, also on Windows 10 and keyboard shortcut Windows + Arrow Key doesn't work in this case

**Comment by saenzramiro** [comment]
@Dareiko options sometimes work, but the option that always works is [THIS](https://github.com/saenzramiro/rambox/issues/409#issuecomment-324052623).
I will try to find a solution of this in a future release.
