### ISSUE TITLE
Auto Update Feature

### ISSUE THREAD

**Issue by BastiPfa** [saenzramiro/rambox#127]
Hi,

great job so far, @saenzramiro ! :)

An auto update feature would be nice to have.
Or alternatively a menu button to check for the latest version manually.

**Comment by saenzramiro** [comment]
Version 0.3.0 had an autoUpdate feature for Windows, but I have to investigate more for make it stable.

In the meantime, in version 0.4.0, I implemented a notification when there is a new version available.

I have to study more to know how to do it for all OS and I will add it in a future version.

**Comment by BastiPfa** [comment]
Awsome, thanks! :)

**Comment by alexcroox** [comment]
This is closed, new user of Rambox, today's update didn't self update for me on OSX just downloaded the .dmg in the browser

**Comment by Andreas-Schoenefeldt** [comment]
Hi guys, 
I'm on mac os x and it also just downloads the new version - a "real" auto update would be aweseome.

Thx a lot for this amazing tool!
Andreas

**Comment by alexcroox** [comment]
@saenzramiro this is possible cross platform with [electron-builder](https://github.com/electron-userland/electron-builder) using Github releases.

See https://www.electron.build/auto-update for more info, or my implementation in my own repo:

https://github.com/alexcroox/jira-timer-menubar/blob/master/package.json#L13

https://github.com/alexcroox/jira-timer-menubar/blob/master/index.js#L176-L214
