### ISSUE TITLE
Allo Counter Doubled

### ISSUE THREAD

**Issue by thatgeek95** [saenzramiro/rambox#1270]
Description: One message in Allo is counted as two

Steps to reproduce:
1. Set up the Allo service in Rambox
2. Receive a message in Allo
3. Notice that the red message counter shows "2" rather than "1" for one new message and this trend continues regardless of how many unread messages are present (e.g. "4" for 2 unread, "6" for 3 unread, and so on).

	
	-
	> Rambox 0.5.13
	> Electron 1.7.8
	> linux x64 4.13.9-1-ARCH

**Comment by Stanzilla** [comment]
Yeah same here, always shows twice the amount of notifications on the badge

**Comment by saenzramiro** [comment]
Ok, I will take a look.

**Comment by Stanzilla** [comment]
@saenzramiro after this fix, it does not show notifications at all anymore
