### ISSUE TITLE
Allo turns Rambox tray icon to red with muted chats

### ISSUE THREAD

**Issue by racuna** [saenzramiro/rambox#1278]
### Steps to reproduce

1.  mute a chat (or group)
2. minimize Rambox
3. wait a new message in that group or chat

### Expected behavior
just turn red the tray icon with not muted chats

### Actual behavior

Allo turns Rambox tray icon to red with muted chats

### ENVIRONMENT

Version: 0.5.13
Platform: win32 (x64)
Electron: 1.7.8
Chromium: 58.0.3029.110
Node: 7.9.0

**Comment by saenzramiro** [comment]
Ok, I will try to prevent that.

**Comment by racuna** [comment]
cool, thanks
