### ISSUE TITLE
Update electron-is-dev to v0.3.0

### ISSUE THREAD

**Issue by yegortimoshenko** [saenzramiro/rambox#1280]
I'm packaging rambox for a distro and Rambox opens developer tools on launch. Could you please update electron-is-dev in `package-lock.json` to v0.3.0 so that this behavior is overridable, see this commit:

https://github.com/sindresorhus/electron-is-dev/commit/251a445362af30006b9a0d3475e778ec36ed839a

**Comment by saenzramiro** [comment]
Sure.
