### ISSUE TITLE
Don't clear current services when logging in

### ISSUE THREAD

**Issue by KixPanganiban** [saenzramiro/rambox#13]
When I login, my current services are closed. Would be neat if they won't have to be. If you need it, I can contribute to the code.

**Comment by saenzramiro** [comment]
Ok, I will take a look on this. It's great to know that you can help me, I will let you know if I need your help. 😃 

Thanks!

**Comment by KixPanganiban** [comment]
Sure. Let me know if you need anything. kixpanganiban [at] protonmail.com

**Comment by saenzramiro** [comment]
Fixed in commit 8eaf3805175b812b00fa906194f5d8862c0b95a9
