### ISSUE TITLE
[Feature Request] Starting minimized in notification area

### ISSUE THREAD

**Issue by itsjef** [saenzramiro/rambox#130]
Hey, since Rambox has become my daily app, I notice it will be real nice if I can autostart it minimized in the notification area when the system starts, instead of popping the whole window out on the desktop. 

Might there be this feature in future updates?

**Comment by saenzramiro** [comment]
Great idea! :wink:

**Comment by saenzramiro** [comment]
Related to #39.

**Comment by ruihildt** [comment]
@saenzramiro It seems that you closed the issue, but it's still not working, should it be working or not?

Thank you. :)

**Comment by saenzramiro** [comment]
@ruihildt Yes, you have to configure it in the Preferences.

**Comment by ruihildt** [comment]
Ok got it, I was looking at the menu (always shown with Elementary OS). 

Thank you

**Comment by RomuloPBenedetti** [comment]
hidden parameter stopped working in Linux at 0.5.13
