### ISSUE TITLE
Error Link de Descarga de Linux Deb 64 bits

### ISSUE THREAD

**Issue by soycamiloypunto** [saenzramiro/rambox#1304]
### Steps to reproduce

Cuando intenta desde la página oficial descargar desde el botón Linux DEB 64 descarga la versión comprimida en tar.gz

### ENVIRONMENT

> Rambox: v0.X.X

> OS: XXXX

> Arch: x64 or ia32

**Comment by Ash258** [comment]
Let's continue in #1401
