### ISSUE TITLE
[Feature Request] Implementing a kind of "auto refresh" like pushing "F5" in browser or automatic reload of site

### ISSUE THREAD

**Issue by Nogger24** [saenzramiro/rambox#131]
Hi

I am using Rambox very successful with Mattermost and Skype. Thanks for you effort.

No I also created a "custom service" to use my Web-Mail, which works as expected apart from disconnection after 10 minutes not using the client.

Is it possible to implement a kind of "auto refresh" like pushing F5-button in browser or an automatic reload (like double click on TAB and select RELOAD) of the site?

Thanks and regards
Nogger

Version: 0.4.0
Platform: win32 (x64)
Electron: 1.2.6
Chromium: 51.0.2704.106
Node: 6.1.0

**Comment by saenzramiro** [comment]
Thank you @Nogger24!

What you can do is add JavaScript code in the *Add/Edit Custom Service* window. Here's an example code:

```javascript
setInterval(function(){ location.reload(); }, 540000);
```

That code it will refresh the service every 9 minutes. The thing is that maybe you are writing an email and it will autorefresh the service.

**Comment by saenzramiro** [comment]
Thank you @Nogger24!

In this version, is not possible to do what you want to do.

In next version it will be a tweak that you can do to prevent disconnection. Because in current version (0.4.0) there is a bug for the injection of JS code in Custom Services.

Please wait for next release and ping me here and I will send you the solution.

**Comment by pcdog** [comment]
@Nogger24 @saenzramiro I'm also interested, seeing that 0.4.1 is out:


 *ping*

**Comment by saenzramiro** [comment]
Now in 0.4.1 you can add custom code to add any functionality.

https://github.com/saenzramiro/rambox/wiki/Inject-JavaScript-Code
