### ISSUE TITLE
Add Glip

### ISSUE THREAD

**Issue by Pablohn26** [saenzramiro/rambox#132]
Would be possible to add [Glip](https://glip.com/) ?

It has web interface and it is easy to add as custom service.

I am not a big fan of that service but I could be added to the list.

**Comment by saenzramiro** [comment]
Thank you for the suggestion.

I will take a look of that service and probably, add it for the next release.

**Comment by Pablohn26** [comment]
I think this issue can be closed. 
Glip was added in Rambox v 0.42
I guess this is the commit 67a77f8d9d03b511aa6d61b206ef81f28889cab1
