### ISSUE TITLE
Gmail Unread Messages Count Incorrect

### ISSUE THREAD

**Issue by keawade** [saenzramiro/rambox#1322]
I have a gmail account with a number at the end of it and that number is being displayed as the unread message count for both the Gmail integration and the Hangouts integration. The incorrect number only displays while the tab is active.

### Steps to reproduce

1. Have Gmail address with number at the end of it.
2. Add either Gmail or Hangouts service to Rambox using that address.
3. Navigate to the new tab.

### Expected behavior

The number in the address should be ignored.

### Actual behavior

The number in the address is used instead of the actual unread count.

### ENVIRONMENT

> Rambox: v0.5.13
> OS: Windows 10 and Ubuntu 16.10
> Arch: x64

**Comment by Ash258** [comment]
Resolved in #1250
