### ISSUE TITLE
Add the ability to run with the system.

### ISSUE THREAD

**Issue by Shmasya** [saenzramiro/rambox#133]
Add the ability to run with the system.

**Comment by pcdog** [comment]
Hi Shmasya, 

I think your request is a bit unclear, do you mean launching the application directly upon login / autologon of the user?

**Comment by Shmasya** [comment]
Yes.

**Comment by saenzramiro** [comment]
Thank you @pcdog to helping me.

This is duplicated #39. I will try to add it for next release.
