### ISSUE TITLE
[Request] Restart option in menu

### ISSUE THREAD

**Issue by seewaldjan** [saenzramiro/rambox#1345]
Hello,

sometimes, my WhatsApp-Images doesn't load because my internet is every few minutes broken and it seems, that WhatsApp doesn't connect to download the image anymore after the reconnect of the internet. After restarting Rambox, it works again. Maybe adding an Restart-Button under "Help" or something?

	
	-
	> Rambox 0.5.13
	> Electron 1.7.8
	> win32 x64 10.0.15063

**Comment by Simon0Harms** [comment]
Did you try to use 
Reload => CTRL + R
or
Reoload actual service => CTRL + Shift + R ?
