### ISSUE TITLE
Links don't open anymore in Tweetdeck

### ISSUE THREAD

**Issue by AdamasFR** [saenzramiro/rambox#1346]
### Steps to reproduce

1. Open Tweetdeck
2. Click a link

### Expected behavior
Link should open either in the default browser or in a Rambox browser

### Actual behavior
Links don't open at all

### ENVIRONMENT

Version: 0.5.13
Plateforme: win32 (x64) (windows 10 pro)
Electron: 1.7.8
Chromium: 58.0.3029.110
Node: 7.9.0

**Comment by saenzramiro** [comment]
Works for me... Is this still happening?

**Comment by AdamasFR** [comment]
No, you can close it, it does not happen anymore and it's so far now, I don't know what happend, really. Thanks anyway !
