### ISSUE TITLE
[Request] Suspend a tab

### ISSUE THREAD

**Issue by xurei** [saenzramiro/rambox#1347]
I'm using Rambox intensively for all my chat rooms and mail inboxes (several Slacks, Whatsapp, Mesenger, Gmail...). This leads to a lot of RAM and CPU usage. 

I thought of a feature that allows to suspend a tab (in its right click menu) until reopened.
The Chrome extension "The great suspender" is a good example of what I'm thinking of :
https://chrome.google.com/webstore/detail/the-great-suspender/klbibkeccnjlkjkiokjodocebajanakg

PS: for the record, I know that you can disable a tab in the "home" tab. My idea is to keep the tabs sort of "active", but allow the user to free resources used by some tabs.

**Comment by saenzramiro** [comment]
Hello @xurei,

Hibernation will came in Rambox Pro version. You will have the option to determine the inactivity time per service, so Rambox will hibernate that service releasing memory.
