### ISSUE TITLE
The paypal donate button isn't working

### ISSUE THREAD

**Issue by kenfallon** [saenzramiro/rambox#1348]
Help > Donate
Webbrowser opens and we get the Security Challenge
"Type the characters you see in the image for security purposes."
Fill in the challenge and we get the message
"Sorry — your last action could not be completed"

-
> Rambox 0.5.3
> Electron 1.4.15
> linux x64 4.13.16-202.fc26.x86_64

**Comment by saenzramiro** [comment]
It's seems to be a PayPal bug that maybe they already fix it.
