### ISSUE TITLE
Package .DEB

### ISSUE THREAD

**Issue by soycamiloypunto** [saenzramiro/rambox#135]
Compile Package deb for Ubuntu and Debian Users. Please

Link Compiler DEB [Debreate](http://debreate.sourceforge.net)

**Comment by cami2d** [comment]
Debreate looks very outdated but I'm agree that a deb package would be great
[Here's](https://github.com/electron-userland/electron-builder) a better option for make it.

**Comment by saenzramiro** [comment]
Yes, it will be a .deb package for next release (also rpm). So, don't worry. 😉

**Comment by soycamiloypunto** [comment]
Excelente !!! Gracias !
