### ISSUE TITLE
microsoft teams no longer wroks.

### ISSUE THREAD

**Issue by orangefult** [saenzramiro/rambox#1350]
I get an error saying that my browser isn't supported by microsoft teams... which is silly.

	
	-
	> Rambox 0.5.13
	> Electron 1.7.8
	> darwin x64 16.7.0

**Comment by gzugmeyer** [comment]
I have the same issue (whit Rambox 0.5.13 on linux)

![screenshot-2017-12-08-07-10](https://user-images.githubusercontent.com/3072249/33753429-9b10cc94-dbe7-11e7-9202-ca61d80b015a.png)

**Comment by orangefult** [comment]
I'm guessing Microsoft has blocked electron apps across the board. I've tried connecting in a couple other ones as well and get the same result.

**Comment by gzugmeyer** [comment]
same issue : https://github.com/saenzramiro/rambox/issues/1354

**Comment by saenzramiro** [comment]
Duplicates #1354
