### ISSUE TITLE
MS Teams don't work

### ISSUE THREAD

**Issue by maksimu** [saenzramiro/rambox#1354]
Seeing error when trying to add MS Teams

![image](https://user-images.githubusercontent.com/187306/33841504-c72af2f2-de4c-11e7-9a4c-3d9f2c9a7112.png)

	
	-
	> Rambox 0.5.13
	> Electron 1.7.8
	> darwin x64 16.7.0

**Comment by yebo29** [comment]
Same here. Just started today.

**Comment by mfestrada** [comment]
Same here; 0.5.13 on Fedora 27

**Comment by voda** [comment]
Same problem. After changing User-agent, Teams loaded, but chat wasn't working.

**Comment by yerminson** [comment]
Same here:
Version: 0.5.13
Platform: win32 (x64)
Electron: 1.7.8
Chromium: 58.0.3029.110
Node: 7.9.0

**Comment by voda** [comment]
Changing User-Agent to "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.89 Safari/537.36" helped. Info for how to change UA: https://github.com/saenzramiro/rambox/issues/859#issuecomment-302097150

**Comment by ppkuronen** [comment]
Even the user agent setting did not help and it resets back to auto after Rambox restart. Is there a way to apply / save the user agent setting?

**Comment by yggi49** [comment]
As a quick and dirty hack: edit the service, open the “Advanced” section, and add the following JavaScript snippet in the “Custom Code” textarea:

```javascript
navigator.__defineGetter__('userAgent', function(){
    return 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.89 Safari/537.36';
});
```

It’s ugly as hell and should be removed once the issue has been fixed, but it should work for the time being.  (At least it does so for me.)

**Comment by mbesch0711** [comment]
same here.
Mac, Chrome, Rambox 0.5.13

**Comment by smathys** [comment]
same problem

       > Rambox 0.5.10
	> Electron 1.7.4
	> linux x64 4.10.0-42-generic

**Comment by dNovel** [comment]
Same problem. Chaning the user agent via dev tools made it load just fine. Chat seems to be working, too after this.

**Comment by biffster** [comment]
+1

**Comment by almightyfoon** [comment]
Changing the user agent string to 
`Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.84 Safari/537.36`

or 

`Mozilla/5.0 (Windows NT 10.0; WOW64; rv:57.0) Gecko/20100101 Firefox/57.0`

does not resolve the issue.

**Comment by Najkon** [comment]
For me and more users in my company works option with another User Agent 
User Agent: Custom ->
Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.89 Safari/537.36

- then on app Rambox on Teams TAB - right click and " Reload "
but! that windows with Developer tools - MUST BE OPENED! Do not close it - that's only work "On Live"
 :)

**Comment by Whoops** [comment]
How are people changing the User Agent string? I can't seem to find that setting anywhere in RamBox or the dev tools.

**Comment by Najkon** [comment]
@Whoops - You must right click on TAB with Teams - then choise " Toggle Developer tools " on that new windows in left upster corver have tree small dots in line  (like firefox have settings menu) -> "More tools" -> " Network conditions" at the bottom of the window You will see " User agent" uncheck the checkbox - in menu choise ' Custom ... " and paste 

Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.89 Safari/537.36

- but! that windows with Developer tools - MUST BE OPENED! Do not close it - that's only work "On Live"
:)

**Comment by saenzramiro** [comment]
Hello guys,

I will be fixing this in the next release. Like @Najkon demostrate, Microsoft is blocking Electron browsers so we have to cheat it by using another User Agent.

**Comment by marcobaccaro** [comment]
The same issue.

RedHat 7
Electron: 1.6.2
Chrome: 56.0.2924.87
Node: 7.4.0
v8: 5.6.326.50

![screenshot from 2018-01-04 21-19-09](https://user-images.githubusercontent.com/8181653/34594172-420d38da-f195-11e7-8ec0-10ca48042911.png)

**Comment by valvin1** [comment]
Same here. I've tested with the different user-agent proposed using Developper Tools or Custom Code and I've not succeed in making it work :(

**Comment by valvin1** [comment]
I'm using [this app](https://github.com/karmainside/ms-teams-linux) for teams who succeeds in making teams working using Electron.

Here is the [commit ](https://github.com/karmainside/ms-teams-linux/commit/73a9f8739de64fc7a75e0eeccc103be6807ddb66) where User-Agent has been fixed but this user-agent is not working in Rambox using the 2 different method.

Hope it can help.

**Comment by saenzramiro** [comment]
I will try to release a new version with this fix next week.

**Comment by ujwalparker** [comment]
Following works for now

`navigator.__defineGetter__('userAgent', function(){
    return 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.2883.87 Safari/537.36';
});`

**Comment by marcobaccaro** [comment]
Great. Thanks man

Marco Baccaro
________________________________

**Comment by fingersonfire** [comment]
I had to change the user agent as the ones given above where blocked also.

I've added the below Advanced Code when editing the Teams tab.

`
navigator.__defineGetter__('userAgent', function(){
    return 'Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:57.0) Gecko/20100101 Firefox/57.0';
});
`

**Comment by saenzramiro** [comment]
Today I will release 0.5.14 with this fix.

**Comment by marcobaccaro** [comment]
Great!

Marco Baccaro
________________________________
