### ISSUE TITLE
Blank service screen (Slack, Telegram, Hangouts)

### ISSUE THREAD

**Issue by 5ulo** [saenzramiro/rambox#1359]
### Steps to reproduce

1. Add Hangouts service
2. click on the tab and is blank
3. Click reload service, still blank

### Expected behavior

There should be login page

### Actual behavior

Instead login is showing blank page which can be inspected with the inspect element. The page is okay after restarting whole Rambox. But sometimes it needs more restarts. The case of Hangouts is more problematic - it loads the first screen but after clicking on Login button the page is alsways white (blank). Attached videos tells you more.

![rambox1](https://user-images.githubusercontent.com/4980919/33996779-8c998b92-e0e2-11e7-9411-6092e9e4e5ea.gif)
![rambox2](https://user-images.githubusercontent.com/4980919/33996780-8cb563f8-e0e2-11e7-8c95-c60f1168c677.gif)

### ENVIRONMENT

> Rambox: v0.5.13

> OS: Linux Arch

> Arch: x64

**Comment by saenzramiro** [comment]
Did you tried by Disabling/Enabling Hardware Acceleration? It's in the Preferences.

**Comment by 5ulo** [comment]
lol.. it's working :D thanks for this trick
