### ISSUE TITLE
Microsoft Teams Browser Version Isn't Supported

### ISSUE THREAD

**Issue by vadriewyn** [saenzramiro/rambox#1364]
Opening up Microsoft Teams from Rambox now shows an error with the browser not being supported. I'm not sure what the built-in browser for Rambox is, but in the event it's using related to the system's default browser, I have ensured that all my installed browsers (Internet Explorer, Microsoft Edge, Chrome, Firefox) are at their latest versions as well.

	
	-
	> Rambox 0.5.13
	> Electron 1.7.8
	> win32 x64 10.0.16299

**Comment by luispintomartins** [comment]
+1 

	> Rambox 0.5.13
	> Electron 1.7.8
	> linux x64 4.10.0-42-generic

**Comment by 0xCCD** [comment]
+1

**Comment by pbek** [comment]
Thank you for this wonderful software!

Same on KDE Neon

	
	-
	> Rambox 0.5.13
	> Electron 1.7.8
	> linux x64 4.4.0-103-generic

**Comment by pbek** [comment]
Office365 still works

**Comment by kepalas** [comment]
+1

**Comment by chicojasl** [comment]
This worked for me: https://github.com/saenzramiro/rambox/issues/1354#issuecomment-350966660

**Comment by AKFourSeven** [comment]
@chicojasl I can confirm this fix works on macOS Sierra, albeit a bit slow, but better than nothing.

**Comment by saenzramiro** [comment]
Duplicate of #1354. Let's merge it.
