### ISSUE TITLE
no habre la ventana popup al intentar logearse en Feedly

### ISSUE THREAD

**Issue by MakuSensei** [saenzramiro/rambox#137]
hola, rambox no permite logearse en feedly ya que abre la ventana de logeo de manera externa en el navegador

**Comment by saenzramiro** [comment]
Así es, creo que en la versión que viene o la otra quizás pueda hacer que las ventanas de SSO que abren los diferentes servicios, puedan funcionar en Rambox.

Por ahora la marco duplicada, ya que existe otro ticket. #85

**Comment by MakuSensei** [comment]
Gracias, ojala se solucione bien el problema, :) es una excelente app
