### ISSUE TITLE
Right click doesn't work

### ISSUE THREAD

**Issue by ghost** [saenzramiro/rambox#1370]
I'm using Ubuntu Gnome 16.04.3 LTS and right-click drop-down menu doesn't show up within rambox

	
	-
	> Rambox 0.5.13
	> Electron 1.7.8
	> linux x64 4.4.0-104-generic

**Comment by NightFantomJ2** [comment]
For me it works in e.g. gmail but not in e.g. discord and slack, either gmail does something special or it's app-specific.

@AbsentAbyss could you specify which app(s) it doesn't work in?

**Comment by AbsentAbyss** [comment]
@NightFantomJ2 you're probably right, it seems to be app-specific. In my case it works for Outlook, Skype and WhatsApp Web, but not for Telegram, Facebook Messenger nor with Discord.

**Comment by Shmasya** [comment]
I think he wanted context menu from Electron. Example copy, past and etc .. It's already merged, but not deployed on last version. Whyyyyy?

**Comment by Grui** [comment]
I got the same bug sometimes with the windows version. A software restart is needed in that case

**Comment by Ash258** [comment]
Resolved in #1074
