### ISSUE TITLE
[Issue] Microsoft Teams - browser not supported

### ISSUE THREAD

**Issue by SimonLefort** [saenzramiro/rambox#1378]
Hello, 
I can't add a Microsoft Teams Service (don't blame me, I have no choice). The browser in apparently not supported.

### Steps to reproduce

1. Install Rambox on Debian (Buster)
2. Add a new Service and choose "Teams"
3. Enjoy. ;-) 

### ENVIRONMENT

> Rambox: v0.5.13-x64
> OS: Debian Buster
> Arch: x64

**Comment by Ash258** [comment]
Search before posting 😐
Duplicate of #1354

**Comment by SimonLefort** [comment]
Sorry, I was leaving work and I didn't want to forget. I'll search for the next time.
