### ISSUE TITLE
No  right-click menu?

### ISSUE THREAD

**Issue by dare023** [saenzramiro/rambox#138]
I am unable to get any menu on right-click.
Arch Linux, KDE.

Q:  can images be opened in popup box?

Version: 0.4.0
Platform: linux (x64)
Electron: 1.2.6
Chromium: 51.0.2704.106
Node: 6.1.0

Keep good work.

**Comment by sergiogj** [comment]
+1 i'm using linux mint  18cinnamont  edition


-
> Rambox 0.4.0
> Electron 1.2.6
> linux x64 4.4.0-28-generic

**Comment by saenzramiro** [comment]
No, right click is disabled. 

Images from where?

**Comment by dare023** [comment]
Ahh that makes sense :)
Why you disabled it?

For images, I meant in general, but mostly for skype. That would mean they would need to be downloaded?
I did not tried other services.

**Comment by saenzramiro** [comment]
I didn't disable it. By default, Electron disable right-click.

To do that, I have to find the way to enable it and display options in the context menu. Hopefully in a future release I will add this, but for now is not a priority. Sorry but you have to wait. :cry:

**Comment by dare023** [comment]
Nah, this is great software, I was more curious than in real need. 
Thank you.

**Comment by 3nids** [comment]
can this be reopened as a feature request?

**Comment by nmat** [comment]
@3nids https://github.com/saenzramiro/rambox/pull/1074
