### ISSUE TITLE
microsoft teams

### ISSUE THREAD

**Issue by av4937** [saenzramiro/rambox#1385]
![rambox teams](https://user-images.githubusercontent.com/35328370/34815698-5e4393d6-f6c3-11e7-8785-6c4737ad8ddf.PNG)
	
добрый день,  программа работает отлично,  все нормально, за исключением программы teams ,  после авторизации,  ваша программа предлагает скачать версию под какую либо операционную систему,   а хотелось бы видеть тот же teams,  только через web  интерфейс,  как например на сайте office.com 
спасибо 

	
	-
	> Rambox 0.5.13
	> Electron 1.7.8
	> win32 x64 10.0.15063

**Comment by Ash258** [comment]
.... #1354

**Comment by av4937** [comment]
THX U!)
