### ISSUE TITLE
A javaScript error occured in the main process: Uncaught Exception: TypeError: Error processing argument at index 0, conversion failure from...

### ISSUE THREAD

**Issue by KReguieg** [saenzramiro/rambox#1386]
On every interaction with Telegram this exception occurs.

![exception_rambox](https://user-images.githubusercontent.com/6112303/34841736-91338c60-f709-11e7-9ce7-3ea393f58d71.PNG)

	
	-
	> Rambox 0.5.13
	> Electron 1.7.8
	> win32 x64 10.0.16299

**Comment by marcedem** [comment]
I have also the same error with the latest version 0.5.14 on Ubuntu 17.10, x64.

**Comment by JapSeyz** [comment]
Same for me.

Every time I change tabs I get this error.

Running Elementary OS built on Ubuntu 16.04

**Comment by splatch** [comment]
Not sure if this is a work around for everyone - I cleared caches from rambox point of view after which application completely crashed. Even after restart it did not load tabs but was showing json contents. However after system restart it started to work without issues - meaning tab switching works without any errors any more.

**Comment by jsaalfeld** [comment]
This seems to be fixed with the latest version 0.5.15 - I have it only tested on one of my systems yet.

**Comment by jsaalfeld** [comment]
Upgraded my other machine as well and the error seems resolved:
 ```
Version: 0.5.15
Platform: linux (x64)
Electron: 1.8.2
Chromium: 59.0.3071.115
Node: 8.2.1
```

**Comment by kleusch** [comment]
I have the same error in 0.5.15 @ Windows 10 (x64)

**Comment by jsaalfeld** [comment]
[0.5.16 is out](https://github.com/saenzramiro/rambox/releases/tag/0.5.16) since a couple of hours. Did you try that version?

**Comment by pointhi** [comment]
@kleusch did you try to turn it off and on again? XD

From what I noticed, those errors happen after an update until the application is restarted.

**Comment by kleusch** [comment]
@pointhi 
Thanks, but it didn't help.

@jsaalfeld 
Nice, this fixed it, thanks.
I hope it doesn't occur again. If yes, then i will report it again.

**Comment by kleusch** [comment]
After 2 weeks without problems, the error is back!
Now on every tab click (switching services) the error occurs again.

I've received a whatsapp message and simultaneously the error occured. After this the error occurs every time clicking on tabs.

- restart doesn't help
- reinstall DOES help

But it would be nice if anyone can figure it out what's wrong. Every 2 weeks reinstalling the app isn't so nice. Let's see when it will happen the next time.

**Comment by KReguieg** [comment]
@kleusch on which version do you run rambox atm? :)

**Comment by kleusch** [comment]
@KReguieg

Latest - 0.5.16 (win 10 x64)

**Comment by KReguieg** [comment]
Okay, so this issue needs to stay open. ;)

**Comment by arqnogues** [comment]
![error rambox](https://user-images.githubusercontent.com/27439839/37988117-6b03e988-31d6-11e8-98a6-6e7be17ff0d0.jpg)
Me sale este error, ayuda!

**Comment by logi85** [comment]
can confirm - same here.

**Comment by dylanh724** [comment]
Yep, same. I tried to update >> tried to close related tasks, but there was something in the background that wouldn't close and the installer couldn't close it, despite permissions granted >> clicked abort >> it rolled back >> opened VSCode >> this err.

**Comment by CiderAndWhisky** [comment]
Same here, error every time I receive a Whatsapp message, even if Rambox window is closed

**Comment by Mi-Creativity** [comment]
I had the same scenario, I was getting this error only when upon successful login trying to store data in LocalStorage, but when I try to load a different website with server-side login it works just like it should. I've noticed that I get the error but it does store values into LocalStorage and if I re-launch the program the user is logged-in..

Since the error is not blocking the code from being executed all I needed to do is to find a way to "mute" it, and this is how it was achieved in the **main.js**

```
process.on('uncaughtException', function (error) {
    console.error('an error happened')
});
```
Hopefully this could help some people until this bug gets fixed
