### ISSUE TITLE
Slack turns Rambox tray icon to red with muted chats

### ISSUE THREAD

**Issue by n0v3xx** [saenzramiro/rambox#1388]
### Steps to reproduce

mute a chat (or group)
minimize Rambox
wait a new message in that group or chat

### Expected behavior

just turn red the tray icon with not muted chats

### Actual behavior

Allo turns Rambox tray icon to red with muted chats

### ENVIRONMENT

> Rambox: v0.X.X .. the latest version.

> OS: Windows 10

> Arch: x64

**Comment by Ash258** [comment]
@n0v3xx What version of Rambox did you use while experiencing this issue? If that was 0.5.13 and lower, that you should update to latest version and it should be fixed.

**Comment by n0v3xx** [comment]
Yes, thanks its fixed.
