### ISSUE TITLE
Aim Service is discontinued - removal of AIM icon is needed

### ISSUE THREAD

**Issue by ionutdurlea-okta** [saenzramiro/rambox#1391]
Steps to reproduce:

- Visit the services tab (add a new service)
- Click the AIM Icon
- Redirected to Support page confirming AIM Service is discontinued

Ask:

- Eliminate AIM Icon

	
	-
	> Rambox 0.5.14
	> Electron 1.7.8
	> win32 x64 10.0.16299

**Comment by saenzramiro** [comment]
Thank you. In next version, it will be removed.
