### ISSUE TITLE
No sound with WhatsApp voice messages

### ISSUE THREAD

**Issue by origal** [saenzramiro/rambox#1397]
### Steps to reproduce

1. Receive voice message recorded by WhatsApp 
2. Click play

### Expected behavior

You should hear the message playing

### Actual behavior

Message progress is moving, but there's no sound.

### ENVIRONMENT

> Rambox: v0.5.14

> OS: macOS high Sierra Version 10.13.2

> Arch: x64

**Comment by Edodums** [comment]
With Messenger it happens the same thing

**Comment by origal** [comment]
Actually videos have no sound in WhatsApp as well.

**Comment by joaotorres** [comment]
Isn't it the case that it happens when "Don't disturb" is turned on?

**Comment by origal** [comment]
@joaotorres Where do you turn "Don't disturb" on/off?

**Comment by joaotorres** [comment]
@origal Click on the Rambox logo on the top left and there click "Don't disturb", I think that shouldn't prevent intented sounds to be played so I just created another issue here: https://github.com/saenzramiro/rambox/issues/1475

**Comment by origal** [comment]
I wasn't aware such feature exists. You're right, this is indeed the problem.
'Don't disturb' feature mutes all sound, including voice messages.
Thanks @joaotorres

**Comment by joaotorres** [comment]
Feel free to +1 the issue I created if you think it should be changed.
