### ISSUE TITLE
on every restart: Please, check your internet connection and restart Rambox. 

### ISSUE THREAD

**Issue by muescha** [saenzramiro/rambox#1398]
### Steps to reproduce

1. Start Mac
2. Rambox is in autostart and starts
3. i get the message `Please, check your internet connection and restart Rambox. If you use a Proxy, please go to Preferences to configure it.`

### Expected behavior

- no error message while startup
- no modal message so it not is a "jumping icon" in dock
- just write it in the app and automatic detect if there is a connection (see how franz handle this)

### Actual behavior

- annoying "jumping icon" in dock bar
- an modal message which i need to click extra

### ENVIRONMENT

> Rambox: v0.5.13
> OS: 10.12.6
> Arch: x64 or ia32

> Version: 0.5.13
> Platform: darwin (x64)
> Electron: 1.7.8
> Chromium: 58.0.3029.110
> Node: 7.9.0

**Comment by Sarke** [comment]
#1255

**Comment by muescha** [comment]
closed as duplicate as #1255
