### ISSUE TITLE
Social Media?

### ISSUE THREAD

**Issue by eorroe** [saenzramiro/rambox#14]
Any plans on targeting social media? or just strictly straight messaging apps?

I have multiple twitters, instagrams, and a facebook.

It's fine if its not there, just wondering what other services are planned?

**Comment by saenzramiro** [comment]
In my opinion, I think we need to be focused on messaging and emails. If we start adding Social Media by default in the app, we will need to add a lot of other services.

Of course, you can add it manually if you want. See here: https://github.com/saenzramiro/rambox/wiki/Add-a-Custom-Service

**Comment by saenzramiro** [comment]
Maybe we can create a poll to know what people want! ;)

**Comment by eorroe** [comment]
Interesting, now since you can add your own service I'm pretty confused on what's this actually doing now? Isn't Electron making everything work offline? Since you can add any service what's it actually doing?

**Comment by eorroe** [comment]
I know it does the session thing which is why I'm using it, but is there an offline thing that its doing? I know the downloadable slack is built with electron

**Comment by saenzramiro** [comment]
Mmmmm, let me see if I can answer your questions.

Rambox is just using Webview component from HTML5 to load different web apps, all in one app. So you can have all you want in one place.

At the moment, I only added messaging and emailing common web apps, but the user can add whatever he wants to Rambox.

Yes, Slacks downloadable is built with Electron also. But I don't know if Slacks add more features to Electron to work better natively, or they are doing the same as Rambox (using Webview).
