### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by sergiogj** [saenzramiro/rambox#141]
1. Tweetdeck:
 - login fails, need to reload tab to see my account
 - No right click
2.  Is possible to change 2 clicks  on tab menu, to right click and add an option to close tab?

-
> Rambox 0.4.0
> Electron 1.2.6
> linux x64 4.4.0-28-generic

**Comment by saenzramiro** [comment]
1.1 - It will be fixed in next release.
1.2 - Why you need right click?
2 - I will try to change it, but I tried to enabled right click in Electron and is not simple. I have to investigate more.

**Comment by sergiogj** [comment]
1.2 i need right click on Tweetdeck to copy link to tweet.  If I want to share Tweet in other platforms I need link to tweet or just to cite a tweet. For me is important, the other features that I've  requested aren't very important. So if you don't want to waste your time investigating it, do not do it. 😉

**Comment by saenzramiro** [comment]
What about Ctrl + C?

**Comment by sergiogj** [comment]
Maybe I expressed bad, I just need the context menu (right click menu) , like in a web browser
Here you have an example:

_**Here in rambox**_
![image](https://cloud.githubusercontent.com/assets/11611091/17084153/22c94420-51b7-11e6-9ec2-2292ed5d56e2.png) 

_**Here in firefox**_
![image2](https://cloud.githubusercontent.com/assets/11611091/17084254/b39467b2-51b9-11e6-8a6c-e03460637b72.png)

**Comment by saenzramiro** [comment]
Got it! Ok, I will take a look if I can get a solution of this. But you have to wait for now.

**Comment by saenzramiro** [comment]
Enabling right click/context menu in Rambox is not easy. There are a few libraries to enable this, but are limited and have some bugs.

We will wait until Electron provide an easy API to enable.
