### ISSUE TITLE
Limit to only one instance

### ISSUE THREAD

**Issue by nstamm** [saenzramiro/rambox#143]
Hola! Aprovecho el español cuando puedo...

Sería una mejora sencilla e interesante que al ejecutar la aplicación no se abra otra instancia, es decir que se limite a una sola instancia de la aplicación. Es comodo para la gente que usa un launcher con shortcuts.

Saludos!

**Comment by saenzramiro** [comment]
Sí, es prioridad esa mejora.

La marco como duplicada y la seguimos en #87.
