### ISSUE TITLE
JS Error

### ISSUE THREAD

**Issue by Akimace** [saenzramiro/rambox#1436]
duplicate of #1386

**Comment by jacebenson** [comment]
Did this issue start when you first started using the app, or did it start happening after you made some configuration changes?

**Comment by sxmanton** [comment]
Hi, I also get this error. It seems to show up pretty consistently as long as I've left Rambox running for long enough (potentially computer locking/sleeping in between is also a factor). Once it crops up, it happens every time I get a notification, until I restart rambox and then everything is fine again, usually for a day or two.

**Comment by jsaalfeld** [comment]
Is this a duplicate of #1386
