### ISSUE TITLE
I have to enter username and password for every service every time

### ISSUE THREAD

**Issue by JEESxorcismo** [saenzramiro/rambox#144]
Hi, I shut down my laptop yesterday and when I started it today and opened Rambox, it asked me to log in to every service. Is that normal or is there something I need to configure?

-
> Rambox 0.4.0
> Electron 1.2.6
> win32 x64 10.0.10586

**Comment by saenzramiro** [comment]
No, it should save all your services in localStorage and open it again on launch Rambox.

Are you using a Rambox account to synchronize your services?

I have the same environment (Win 10) and works ok here. Try to remove all your services and add just one, enter your credentials and close Rambox ( File -> Quit ), open it again and see if works. If not, be sure if there isn't another software cleaning your localStorage and sessions from your PC.

[Check this comment](https://github.com/saenzramiro/rambox/issues/98#issuecomment-235317155)

Also, there is another thread talking about this. So I will close this one and we can continue [HERE](https://github.com/saenzramiro/rambox/issues/98).
