### ISSUE TITLE
I'll shown offline in slack

### ISSUE THREAD

**Issue by holzfelix** [saenzramiro/rambox#1447]
### Steps to reproduce

1. Add Slack to Rambox
2. Do some minutes nothing in slack
3. 

### Expected behavior

Shown as online in slack for others.

### Actual behavior

After some minutes I'll get offline in slack so each other user see me as offline in slack. 

### ENVIRONMENT

Version: 0.5.14

> OS: Windows 10

> Arch: x64

**Comment by Ash258** [comment]
https://twitter.com/slackhq/status/448966862521786368

> Disabling auto-away isn't on our immediate roadmap, but it's on our "someday" list. Stay tuned! ✨

Auto-away in slack is annoying. Not lurking around slack for 30 minutes does not mean not being available for anyone to ping and "someday" seems a bit vague for an essential feature like this. Fortunately using the slack API it's easy to circumvent this restriction.

**Comment by Ash258** [comment]
@holzfelix If you really want to be online you can use this custom js code:
```javascript
setInterval(function(){location.reload();}, 1700000);
```
Source: https://github.com/saenzramiro/rambox/wiki/Inject-JavaScript-Code

**Comment by holzfelix** [comment]
ok cool thanks! I will try it

**Comment by holzfelix** [comment]
works perfect Thanks!
