### ISSUE TITLE
Ads in Outlook

### ISSUE THREAD

**Issue by nachog4** [saenzramiro/rambox#145]
You should add an adblocker for sites like Outlook, if the project is based in chromium, the extension "Webmail Ad Blocker" is good, or any js/css to hide the ad boxes, as they take much space on screen and we can not always have the app in maximized mode.

Great app =) 
From another argentinian,

-
> Rambox 0.4.0
> Electron 1.2.6
> win32 x64 10.0.10586

**Comment by onedrawingperday** [comment]
+1 this it would be a killer feature.

Also uBlock Origin is an effective and light Chrome extension.

**Comment by saenzramiro** [comment]
I know it would be a killer feature, but I think is not a good idea of Rambox to enter in the world of "Ads Blockers"... or maybe for now.

**Comment by postadelmaga** [comment]
I think one approach would be add the possibility to install chrome extension ... I'm not sure if this is easy to implement in electron but at the end it a chromium box so I guess it is possible ...

**Comment by saenzramiro** [comment]
Electron for now only allow to add Extensions for Dev Tools. In a future, if they allow to add it for Electron itself, we can take a look to implement it.

**Comment by gnidorah** [comment]
+1
Vk has ugly ads
