### ISSUE TITLE
Incorrect link

### ISSUE THREAD

**Issue by 1beb** [saenzramiro/rambox#1456]
On the download page, the link to the 64 bit .deb actually links to an archive file.

**Comment by mmoscher** [comment]
Yep, can confirm :+1: 
Download leads to an tar.gz archiv

**Comment by AdrienHorgnies** [comment]
I was about the open an issue to address this.

Hyperref link value is : `https://getrambox.herokuapp.com/download/linux_64?filetype=deb` but the file actually downloaded is `Rambox-0.5.16-x64.tar.gz`.

**Comment by Ash258** [comment]
Duplicate of #1401
