### ISSUE TITLE
GNOME Shell tray icon integration?

### ISSUE THREAD

**Issue by orschiro** [saenzramiro/rambox#1458]
Hey guys, 

Currently tray icon only works with [TopIcons](https://extensions.gnome.org/extension/495/topicons/) and [TopIcons Plus](https://extensions.gnome.org/extension/1031/topicons/). 

Both are no longer maintained. 

Can we support [Appindicator](https://extensions.gnome.org/extension/615/appindicator-support/) too?

Thanks so much!

**Comment by valmar** [comment]
It works for me (after rebooting) by changing the Exec entry in the desktop file:

Exec=env XDG_CURRENT_DESKTOP=Unity "/opt/rambox/Rambox-0.5.14-x64.AppImage" %U

**Comment by orschiro** [comment]
Can confirm that it works. Thanks!

**Comment by orschiro** [comment]
@valmar just now I updated my Fedora 27 system and the hack no longer works.

Have you experienced something similar?

**Comment by valmar** [comment]
Uhm, sometimes when I update or restart the shell I have to reboot (restarting Rambox is not enough) to see the indicator again. This is not optimal, and maybe we should find a better solution.

**Comment by valmar** [comment]
I am also on Fedora 27. Just updated and rebooted, and the indicator
still works for me.

**Comment by orschiro** [comment]
> I am also on Fedora 27. Just updated and rebooted, and the indicator
still works for me.

Restarting helped. Thanks!
