### ISSUE TITLE
proxy

### ISSUE THREAD

**Issue by angimo9** [saenzramiro/rambox#146]
How do I configure proxy in Rambox to connect?

**Comment by saenzramiro** [comment]
Rambox don't have a Proxy configuration for now. Is a feature that we will add in a future release.

**Comment by angimo9** [comment]
Oh ok.
Thanks for the prompt response.

Angelo.

**Comment by postadelmaga** [comment]
I just found out about  [custom code](https://github.com/saenzramiro/rambox/wiki/Inject-JavaScript-Code) 
Having the possibility to change proxy using custom code would be already a nice feature

**Comment by henriquedesousa** [comment]
Any ideas when this is going to be implemented?

**Comment by saenzramiro** [comment]
This is old, Rambox now have Proxy in Settings.
