### ISSUE TITLE
"Enable HiDPI support" checkbox in preferences supposedly only relevant for Windows platform

### ISSUE THREAD

**Issue by M4urice** [saenzramiro/rambox#1464]
### Steps to reproduce

1. Go to the system-wide Preferences pane.
2. Check the "Enable HiDPI support" checkbox.
3. Relaunch.

### Expected behavior

HiDPI support changes something (e.g. UI scaling).

### Actual behavior

Nothing happens, because https://github.com/saenzramiro/rambox/blob/8094752efb55a003b516cbc2662cd7fa668bf7c4/electron/main.js#L50 only addresses a scaling Issue for Windows. Not really a problem, but a missleading UI element for non-Windows users.

### ENVIRONMENT

> Hardware: MacBook Pro (Retina, 13-inch, Early 2015)

> Rambox: v0.5.14

> OS: macOS High Sierra 10.13.3

**Comment by M4urice** [comment]
I added a pull request to hide the preference for non-Windows platforms with the `hidden` flag.

Also, shouldn't all occurrences of `,hidden: process.platform === 'darwin'` be `,hidden: process.platform !== 'win32'` instead (for example [here](https://github.com/saenzramiro/rambox/blob/master/app/view/preferences/Preferences.js#L205))?
`process.platform` would equal `linux` on Linux so irrelevant preferences would be visible (see https://nodejs.org/api/process.html#process_process_platform).

**Comment by riprop** [comment]
Hi,
I also have an issue with Rambox on HiDpi screen, on gmail I cant see nor access elements (buttons,...) on the far right and at the very button.
Zooming in/out change part of gmail application being seen, but no chance to show complete application.
Switching on/off hidpi support do not influence problem.

Version: 0.5.17
Platform: linux (x64)
Electron: 1.8.4
Chromium: 59.0.3071.115
HW: Macbook pro Retina 13"
OS: Linux Xubuntu 18.04
Node: 8.2.1

**Comment by saenzramiro** [comment]
@riprop Check if Rambox app itself have zoom. Go to Rambox tab and then, go to menu View -> Actual size.

**Comment by riprop** [comment]
Thank you for suggestion, I already tried that, but problem remains.
