### ISSUE TITLE
No recibo notificaciones en Inbox

### ISSUE THREAD

**Issue by MauricioAedo** [saenzramiro/rambox#148]
Hola Ramiro

Te escribo en español ya que se que eres Argentino, en primer lugar quiero felicitarte por esta excelente aplicación que estuve buscando hace mucho tiempo, en su tiempo usé Trillian y Digsby pero al día de hoy no satisface mis necesidades.

El problema que tengo es que en el servicio Inbox no recibo notificaciones cuando me llegan correos, he revisado todo tipo de configuración ya sea en Rambox como en Inbox y Gmail y no encuentro el problema. Actualmente tengo que revisar la pestaña cada cierto tiempo para encontrarme que tengo varios correos sin leer pero ninguna notificación.

Espero me puedas ayudar a encontrar la solución ya que me gusta mucho la aplicación y no me gustaría tener que dejar de utilizarla.

Saludos!

-
> Rambox 0.4.0
> Electron 1.2.6
> win32 x64 10.0.10586

**Comment by saenzramiro** [comment]
Hola Mauricio.

¡Muchas gracias! 

Lamentablemente Inbox nativamente no trae la opción de mostrar notificaciones de escritorio cuando te llega un mail (el cual casi todos los usuarios se quejan de esto). Es por eso que rondan muchos addons para Chrome, Firefox, etc. donde le agregan esta funcionalidad.

Yo también uso Inbox y generalmente me doy cuenta que me llegó un mail en el ícono del System Tray (que se pone rojo). Sino la otra que te queda, es volver a Gmail el cual sí tiene notificaciones (que justo yo estaba considerando hacer esto).

De todas formas, voy a ver si para la versión v0.4.2 puedo plantear una notificación propia de Rambox para Inbox.

Saludos.

**Comment by MauricioAedo** [comment]
Muchas gracias por tu respuesta Ramiro, pero mi problema parece ser distinto porque a mi no se me pone rojo ni la pestaña de Inbox ni el icono de Rambox, la única forma que tengo para ver los correos nuevos es revisar cada cierto tiempo.

Algo está mal en mi configuración? También lo probé con Gmail pero no veo diferencia, tengo ambos.

Saludos

**Comment by saenzramiro** [comment]
¿Te aparece el badge rojo en el tab del servicio con el número de correos sin leer?

**Comment by MauricioAedo** [comment]
No nada, en esta imagen http://es.tinypic.com/r/2drh1so/9 puedes ver que no aparece indicador rojo en las pestañas de Inbox y Gmail teniendo 4 correos sin leer, tampoco se pone rojo el icono de Rambox en la barra de tareas y system tray, lo cual funciona perfectamente con los otros servicios. 

Saludos

**Comment by saenzramiro** [comment]
Que raro... haceme el favor de ejecutar el siguiente código JS en la consola para ver si por lo menos encuentra los mails nuevos.

Hacé doble click en el tab de Inbox y seleccioná "Toggle Dev Tools", luego anda a Consola y ejecutá lo siguiente:

```javascript
document.getElementsByClassName("qG").length
```

Decime que número te devolvió. Asegurate de ejecutarlo estando en Recibidos y con mails sin leer.

**Comment by MauricioAedo** [comment]
Gracias por tu ayuda Ramiro.

Lo acabo de ejecutar y me devuelve 3 lo cual corresponde correctamente a los correos no leídos. 

Si puedo ayudarte en cualquier otra cosa para solucionarlo avisame, saludos.

**Comment by saenzramiro** [comment]
Ahora hacé lo mismo que antes pero con el siguiente código:

```javascript
function checkUnread(){updateBadge(document.getElementsByClassName("qG").length)}function updateBadge(e){e>=1?document.title="("+e+") "+originalTitle:document.title=originalTitle}var originalTitle=document.title;setInterval(checkUnread,3000);
```

Esto debería forzar a que mientras tengas un correo sin leer, te agregue el badge rojo en el tab y cambie el ícono del system tray.

Si no lo hace... hay algo muy raro...

**Comment by MauricioAedo** [comment]
Hola nuevamente Ramiro

En primer lugar debo ratificar que Gmail si me funciona bien, lo que pasaba era que tenía redirigido Gmail a Inbox por lo tanto ambas pestañas mostraban el mismo problema.

Ahora estoy usando ambos y solo Inbox me presenta el problema, he ejecutado el código que me indicas y no se ha solucionado como puedes ver en la siguiente imagen: http://i65.tinypic.com/35lccp5.png

Tengo entendido que hoy lanzarás una nueva versión, tal vez en ella se solucionen mis problemas.

Quedo atento a cualquier comentario, saludos.

**Comment by saenzramiro** [comment]
Hola Mauricio.

El código lo has ejecutado en Rambox, y no en la página de Inbox. Para abrir el Dev Tools de Inbox, debes hacer doble click en el tab de Inbox y seleccionar **Toggle Dev Tools**.

**Comment by MauricioAedo** [comment]
Hola Ramiro

Tienes razón, ahora lo hice como indicas y si funciona, se fuerza a que aparezca el ícono en Inbox en ese instante.

Esperemos sirva para encontrar una futura solución por el momento he vuelto a utilizar Gmail, saludos.

**Comment by saenzramiro** [comment]
Entonces al parecer nunca se terminaba de cargar el DOM de Inbox, ya que la ejecución de ese código automáticamente lo hace en el evento DOM-READY.

La verdad que no sabría porque razón te sucedía eso, ya que por lo menos sos el primero en reportar ese problema.

**Comment by saenzramiro** [comment]
Created new Issue for Desktop Notifications in #159 for v0.4.2.
