### ISSUE TITLE
Google Chrome unresponsive

### ISSUE THREAD

**Issue by dmagician038** [saenzramiro/rambox#1482]
### Steps to reproduce

1. Open **Any** Service (WahtsApp , Telegram... )
2. Open a chat with url's in the service
3. click a url

![chrome reastart](https://user-images.githubusercontent.com/1897534/36671856-f201e04e-1b05-11e8-926c-9e5fedf87987.png)

### Expected behavior

Should be opened -- I'm guessing in the default browser outside

### Actual behavior

Error message box: "Google Chrome is unresponsive. Relaunce now?"

### ENVIRONMENT

> Rambox: v0.5.14
> OS: Windows 10
> Arch: x64

**Comment by Ash258** [comment]
I don't think this is Rambox issue. I open links pretty often (from RSS service) and everything is great. 
Try to update your google chrome and then open link from any service.

**Comment by dmagician038** [comment]
Solved without any action on my side.
Thanks
