### ISSUE TITLE
Main process JS error

### ISSUE THREAD

**Issue by camrodam** [saenzramiro/rambox#1488]
repeating error popping up randomly, but also when switching/clicking between Rambox tabs:
![image](https://user-images.githubusercontent.com/4508900/36725181-c29377c2-1bb5-11e8-8676-4f057b6ef3df.png)

	
	-
	> Rambox 0.5.14
	> Electron 1.7.8
	> win32 x64 10.0.16299

**Comment by jsaalfeld** [comment]
Sounds like a duplicate of #1386

**Comment by camrodam** [comment]
indeed, apologies for duplication I'll close.
