### ISSUE TITLE
Overspending memory in OS X

### ISSUE THREAD

**Issue by flinbu** [saenzramiro/rambox#149]
Hi, in Mac OS X - El Capitan, the app generates to many "rambox helper", one per service in use plus one general process, and this can use a least 1GB of memory ram and make my iMac to slow when the app is in use. For this reason actually I'm not using the app.

**Comment by saenzramiro** [comment]
Thank you for sharing this.

I will investigate this, but I'm assuming this is an Electron thing.

**Comment by pedropapa** [comment]
Confirmed on macOS Sierra.

After updating to Rambox 0.5.9, OS X started running out of memory after **sleeping or idle**, after investigating more further I found out that it was because of Rambox, since if I don't start it I never get the memory problem again.

**Comment by saenzramiro** [comment]
@pedropapa Did you tried with version 0.5.10?

**Comment by pedropapa** [comment]
@saenzramiro on the 0.5.10 version I can confirm that the problem doesn't occurs anymore
