### ISSUE TITLE
Hipchat

### ISSUE THREAD

**Issue by KarloZKvasin** [saenzramiro/rambox#1493]
Hipchat doesnt work for this version of Rambox. I see data, but no design (structure of page).
	-
	> Rambox 0.5.15
	> Electron 1.8.2
	> win32 x64 10.0.16299

**Comment by vitorlans** [comment]
I'm struggling with the same issue, in my case just loading is showing.
that started to happen after update to last version.

> Rambox 0.5.15
> Windows 10

**Comment by Rabusek** [comment]
I have the same issue with other service (Glip), and noticed that going down to .14 version resolves the issue.

You can find it here:
https://github.com/saenzramiro/rambox/releases/tag/0.5.14
@KarloZKvasin @vitorlans

**Comment by ruvelro** [comment]
Same Here, can't connect Hipchat on 0.5.15 and Windows 10 v1709

**Comment by cpriest** [comment]
Just to chime in, I have 0.5.15 on two computers, both installed via chocolatey.  One works fine with hipchat, the other gives me the certificate warnings like ticket #573 

```
GET https://dmg75ly2d8uj2.cloudfront.net/vendor/aui/5.7.12/css/aui-all.css net::ERR_INSECURE_RESPONSE
```

**Comment by lsascha** [comment]
Same here with Version 0.5.15 on Windows 10 x64.
using the existing Tab of Hipchat did not show design.

Removing the Tab and readding it ended up forever in the Hipchat Loading screen with a couple net::ERR_INSECURE_RESPONSE errors in the console for a couple JavaScript and css files .

All files coming from cloudfront.net like `https://dmg75ly2d8uj2.cloudfront.net/preload-4.30.3.js` etc.
![rambox_2018-03-05_10-32-56](https://user-images.githubusercontent.com/4083570/36967656-9c3a87dc-2060-11e8-9628-c38c243e7bca.png)
