### ISSUE TITLE
Rambox Not Automatically Updating Gmail

### ISSUE THREAD

**Issue by BaronMind** [saenzramiro/rambox#1495]
In order to get new emails, I'm having to manually click my inbox on each Gmail tab to see what new emails are coming in. Is there any way to increase the frequency at which Rambox reloads/refreshes my Gmail tabs so I'm seeing new emails more quickly and easily?

	
	-
	> Rambox 0.5.15
	> Electron 1.8.2
	> darwin x64 17.4.0

**Comment by Rabusek** [comment]
I have the same issue with other service (Glip), and noticed that going down to .14 version resolves the issue.

You can find it here:
https://github.com/saenzramiro/rambox/releases/tag/0.5.14
@BaronMind

**Comment by wolv-dev** [comment]
Same with me in version 0.5.16

**Comment by wolv-dev** [comment]
It seems that https://mail.google.com/mail/?labs=0 is working much better!

I added Custom Service with
URL: https://mail.google.com/mail/?labs=0
Logo: https://www.google.com/a/1drop.de/images/favicon.ico

And with this, the sync is working without problems.
