### ISSUE TITLE
how to install in linux

### ISSUE THREAD

**Issue by rakshans1** [saenzramiro/rambox#15]

**Comment by biji** [comment]
just extract it, 
`chmod +x Rambox`
`./Rambox`

**Comment by draptik** [comment]
Maybe adding this information to a readme file (or somewhere else) would help. @biji Your solution was also my first guess, but I wasn't sure, so I looked in the issues and ended up here...

**Comment by saenzramiro** [comment]
Thank you guys!

I just created a Wiki for this: https://github.com/saenzramiro/rambox/wiki/Install-on-Linux
