### ISSUE TITLE
special characters not displayed

### ISSUE THREAD

**Issue by groZeuros** [saenzramiro/rambox#1507]
characters 🤦🏻‍♀️ are not displayed on FB messenger

	> Rambox 0.5.15
	> Electron 1.8.2
	> win32 x64 6.1.7601

**Comment by Ash258** [comment]
![Yes it is displayed](https://i.imgur.com/FPYd4ME.png "Yes it is")

**Comment by Corchoneitor** [comment]
Hi groZeuros.

I tested these and other emojis on Rambox and they seem to work.
Can you give us more information on how you are trying to do this?

Bye.

**Comment by groZeuros** [comment]
Sure, the emoji comes from a Thai iPhone,  but that's all I know
It's a bit complicated to guess where it comes from with only this 🤔
Will check on Ubuntu rambox.
