### ISSUE TITLE
Notifications don't show in Windows 10 action center

### ISSUE THREAD

**Issue by jim5359** [saenzramiro/rambox#151]
One of the problems I have with Rambox is knowing that someone sent me an IM.  Currently I get a Windows notification alert.  However, this alert goes away after a few seconds and if I don't notice it or I'm away from my desk there is no way to know I have an IM waiting for my response.

Windows 10 has an option for notifications to "Show in action center".  This is set per application.  I've turned it on for Rambox but it doesn't work.  For other apps what this does is show the alert in the Action center where I have to dismiss it for it to go away.  This would be a much better solution so I wouldn't miss IMs, but for some reason it's not working for Rambox.

Another related suggestion, change the Rambox icon in the taskbar/notification area (such as flashing) when an IM comes in.  The icon would stay that way until Rambox gains focus.

Thanks!

**Comment by jim5359** [comment]
I've updated to the latest 0.4.1 and see some different behavior.  When receiving a new message, in addition to seeing the Windows notification alert as before, when the alert goes away the Windows Action Center icon is now showing there is a new message.  This is an improvement since before it didn't do this.  However, when opening the Action Center no messages are displayed.  So the icon status is correct but the actual message has gotten lost.

Also, I'm now seeing the Rambox icon change when I receive new messages for HipChat.  Very nice!  However, this is not working for Yahoo! Messenger.

Thanks.

**Comment by saenzramiro** [comment]
Hey @jim5359 

Thank you for your feedback!

It will be a great feature to have notifications in Action Center, but it's an Electron bug (electron/electron#3916). Hopefully they fix it before next release of Rambox.

I will create a new issue for Yahoo! Messenger.

**Comment by jim5359** [comment]
Hi @saenzramiro,

The problem with the Action Center only happens for me with Yahoo! Messenger.  For HipChat the alerts do show properly in the Action Center.  So this would lead me to believe it's not an Electron issue causing this problem.

Thanks.

**Comment by saenzramiro** [comment]
That's weird. I tested with WhatsApp and Slack, and didn't work ok.

So I will take a look.

**Comment by jim5359** [comment]
It seems with HipChat if someone sends a message in a room that I'm in then I get a notification, but that notification doesn't show in the Action Center.  But if someone sends a message to me directly I get the alert AND it shows in the Action Center.

**Comment by saenzramiro** [comment]
Wow... weird. :confused:
