### ISSUE TITLE
Show version in UI

### ISSUE THREAD

**Issue by schmunk42** [saenzramiro/rambox#1512]
### Steps to reproduce

1. Try to look up the current version in UI (eg. settings)
2. or via `rambox --version`

### Expected behavior

See the version "somewhere" not only via package manager

### Actual behavior

Not visible

### ENVIRONMENT

> Rambox: v0.15.5

> OS: Arch Linux (Antergos)

> Arch: x64

**Comment by Corchoneitor** [comment]
Hi schmunk42.

You can see the version of Rambox going to Help -> About Rambox. There you'll find the installed version and others (Platform, Electron, Chromium, Node).

**Comment by schmunk42** [comment]
Thank you, I had **auto-hide** on :see_no_evil:
