### ISSUE TITLE
No notification sign (red number) appear for what's app tab

### ISSUE THREAD

**Issue by matanshel** [saenzramiro/rambox#1514]
### Steps to reproduce

1. 
2. 
3. 

### ENVIRONMENT

> Rambox: v0.X.X

> OS: XXXX

> Arch: x64 or ia32

**Comment by wolv-dev** [comment]
As workaround I added the following custom code to the whatsapp tab:

`function checkUnread() {
    const elements = document.querySelectorAll('.CxUIE, .unread');
    let count = 0;

    for (let i = 0; i < elements.length; i++) {
        if (elements[i].querySelectorAll('*[data-icon="muted"]').length === 0) {
            count += 1;
        }
    }
    
    updateBadge(count)
}
function updateBadge(count) {
    if (count && count >= 1) {
        rambox.setUnreadCount(count);
    } else {
        rambox.clearUnreadCount();
    }
}

setInterval(checkUnread, 1e3);`

**Comment by Ash258** [comment]
Not possible. https://github.com/saenzramiro/rambox/issues/1514#issuecomment-372957173 code is same as js_unread in 0.5.16.

@matanshel Do you have latest version of rambox installed?

**Comment by matanshel** [comment]
Seems like updating to newest version resolved the issue, thanks! @Ash258

**Comment by wolv-dev** [comment]
Update didn't fixed it for me

**Comment by Ash258** [comment]
@wolv-dev As you can see here: https://github.com/saenzramiro/rambox/blob/master/app/store/ServicesList.js#L31 that line is almost identical to code above. Try to look if you check **Display tab unread counter** in service configuration.

**Comment by wolv-dev** [comment]
@Ash258 I know. I checked it myself. But when I remove the custom code, the unread counter isn't working anymore. I have checked "Display tab unread counter" and "Include in global unread counter". I will remove the custom code again and hope, that it works now.

**Comment by wolv-dev** [comment]
Okay, it's working. Maybe the restart after changing the custom code helped and the reload didn't work.

**Comment by Ash258** [comment]
@wolv-dev Great. 
@matanshel You can close this issue.
