### ISSUE TITLE
Valid URL is not accepted as custom service

### ISSUE THREAD

**Issue by TheKarlo95** [saenzramiro/rambox#1515]
As title says I can't add custom service hosted on machine in local network.

### Steps to reproduce

1. Add new custom service
2. Enter: http://example:81
3. Input field becomes red and doesn't let me go further

### Expected behavior
Input form lets me add custom service since URL is valid.

### Actual behavior
Input field for URL becomes red and displays that URL is not valid.

### ENVIRONMENT
Electron: 1.8.2
Chromium: 59.0.3071.115
Node: 8.2.1

> Rambox:  0.5.15

> OS: Arch Linux

> Arch: x64

**Comment by Ash258** [comment]
Related to #1511

**Comment by saenzramiro** [comment]
Thanks @Ash258.

Let's continue in the related issue.
