### ISSUE TITLE
HELP ME.

### ISSUE THREAD

**Issue by petrolero11** [saenzramiro/rambox#152]
_Buenas noches amigos de Rambox,

     Escribo porque no puedo adicionar un nuevo servicio el cual es Line que por cierto no está en la lista de aplicaciones de mensajería.  Además aber como puedo actualizar la aplicación a la última versión cuando está esté disponible ya que no tengo en las opciones de los menús la opción de buscar actualizaciones o comprobar actualizaciones.  Deseo que puedan responder mis dudas.  Gracias.

Saludos,
Igor._

**Comment by saenzramiro** [comment]
Hola Igor.

Line no tiene una aplicación web accesible desde el navegador mediante una URL. Incluso ya lo hemos intentado en #36 #84 #139.

Con respecto a las actualizaciones, en la próxima versión vendrá la funcionalidad de autoupdate y con la posibilidad de buscar actualizaciones manualmente. De todas formas, cuando liberemos la nueva versión, te aparecerá una notificación en Rambox informándote que se encuentra una nueva versión.

Saludos.

**Comment by petrolero11** [comment]
Buenas noches Ramiro,


     Gracias por tu amable repuesta.


Saludos,


---
Igor A. Petrola P.
Email: petrola70@hotmail.com
Skype: petrolero70








________________________________
De: Ramiro Saenz <notifications@github.com>
Enviado: viernes, 29 de julio de 2016 09:53:57 a.m.
Para: saenzramiro/rambox
Cc: Igor; Author
Asunto: Re: [saenzramiro/rambox] HELP ME. (#152)


Closed #152<https://github.com/saenzramiro/rambox/issues/152>.

-
