### ISSUE TITLE
no sound in any apps

### ISSUE THREAD

**Issue by cycle337** [saenzramiro/rambox#1522]
### Steps to reproduce

1. Install new rambox rpm on Fedora
2. Open Whatsapp
3. Click play on any sound file.

### Expected behavior

Should play in my speakers.

### Actual behavior

The audio cursor moves, file seems to be playing but no sound comes out of speaker.

### ENVIRONMENT

> Rambox: v0.5.16

> OS: Fedora 27

> Arch: x64

**Comment by cycle337** [comment]
updated title to *any apps* as I can't get clips from youtube shared over twitter to play either.

**Comment by Fumesover** [comment]
Are you in do not disturb mode ? (F1) or on the main page top left

**Comment by cycle337** [comment]
I’ll check but afair I was normal mode

**Comment by cycle337** [comment]
yeah, that was it. it should've been more obvious like in the status bar or in the icon - maybe a visual enhancement of disturb mode on/off ?
