### ISSUE TITLE
Manually add custom webviews as services?

### ISSUE THREAD

**Issue by Secretss7** [saenzramiro/rambox#1526]
Hi,

Is there currently a way for users to add our own webviews as services? For example I would like to add Evernote as a webview. My iPhone is jailbroken and has a tweak installed that allows me to access iMessage via an IP address, so I would like to add that to Rambox too. This is possible to do in Franz since version 4 and I'm hoping it is possible in Rambox. 

I don't see custom adding of user services mentioned on Rambox.pro nor on your Github, although on the To Do list there is a mention of "deeplink to add new services". I'm not sure what that means specifically, do you mean for Rambox to add new services or for users to add their own services?

Please and thank you.

**Comment by AltS1** [comment]
It's possible.
On the main page at "Add new service" section scroll down and select "_Custom Service".
