### ISSUE TITLE
Simple question

### ISSUE THREAD

**Issue by thedonquixotic** [saenzramiro/rambox#1534]
How do you rename a tab? I created a tab and then accidently set it's name incorrectly and I would like to change it but I don't see how.

**Comment by 88scythe** [comment]
Go to the Rambox main screen (Rambox icon)
In the right column, hover over the service you want to edit and click the gear wheel.
Change the name and click Edit to confirm.

**Comment by thedonquixotic** [comment]
Okay I found it. I'm going to create a new issue offering help on UX stuff. I'm a professional UX designer and I'm very pro open source but not sure how to contribute to open source

**Comment by 88scythe** [comment]
Be aware that there's a big redesign incoming. Or at least they're talking about it since months ...
See https://github.com/saenzramiro/rambox/issues/244
