### ISSUE TITLE
deb 64 link redirects to .tar.gz file

### ISSUE THREAD

**Issue by Simon0Harms** [saenzramiro/rambox#1538]
This link:
https://getrambox.herokuapp.com/download/linux_64?filetype=deb
redirects to the tar.gz file instead of the -x64.deb file

Same problem on this link:
https://getrambox.herokuapp.com/download/linux_32?filetype=deb

The links are on this site:
http://rambox.pro/#download

**Comment by Ash258** [comment]
Duplicate of #1401

**Comment by Ash258** [comment]
@Simon0Harms If you need debian package you can download it [here](https://github.com/saenzramiro/rambox/releases/download/0.5.16/Rambox_0.5.16-x64.deb)
