### ISSUE TITLE
[new-feature-request] Skype for Business

### ISSUE THREAD

**Issue by abacao** [saenzramiro/rambox#154]
Please implement this.

There is a web client inside Office 365 that allow Skype For Business in browser.

Unfortunately it's a way of communication that I have to have!

**Comment by saenzramiro** [comment]
We had another ticket #52 talking about this.

The thing is we couldn't find a direct URL that points to Skype for Business to add it to Rambox.

Can you help me with this?

**Comment by abacao** [comment]
What can I do?
Lync or Skype for Business is currently working (in web-browser) here:
https://postimg.org/image/5hh7v14ef/

**Comment by saenzramiro** [comment]
In Rambox you have the service for Outlook 365, and you should see Skype at the right like in your screenshot.

But as you see, there isn't a direct URL for just Skype for Business/Lync, is always displays at the right in Outlook.

**Comment by abacao** [comment]
Not really...

The Office 365 opens a old layout in Rambox.
When that happens in browser, I delete the rest of the URL and leave only this:
https://outlook.office.com/owa/

Only this way (in browser) the now office 365 layout appears as the skype tab.

**Comment by acotillard** [comment]
hi,

any news about this isue ?

I dont know  if that can be helpfull but there is some informations about a plugin pidgin for skype business here : 

https://sourceforge.net/p/sipe/wiki/Frequently%20Asked%20Questions/

**Comment by gurunathsane** [comment]
As always Microsoft hiding things under the hood (even if things are not nice :/ ) May be for security.
