### ISSUE TITLE
[new-feature-request] Zoho

### ISSUE THREAD

**Issue by abacao** [saenzramiro/rambox#155]
https://www.zoho.com/

Also is used by a lot of people...

It's like a Google suite with email and chat

**Comment by saenzramiro** [comment]
Can you help me with finding a direct URL for the Email and Chat apps in Zoho?

**Comment by abacao** [comment]
email: https://mail.zoho.com/zm/#mail/inbox
chat: https://chat.zoho.com

**Comment by saenzramiro** [comment]
Great! I will take a look and see if I can add it for next release.
