### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by rodoviario** [saenzramiro/rambox#156]
Can you add the posibility for opening delegated accounts inside gmail.

The normal behaviour when you go to your icon dropdown menu and select a delegated account is a new window (new tab usually) and you are in the other account without the need of using credentials.

If you try to do so, it will open the default browser... and fail.

**Comment by saenzramiro** [comment]
I don't get it... Can you record a video of this problem?

**Comment by rodoviario** [comment]
Hola, disculpá el tamaño del attrachment, no se cómo hacer el video,
simplemente capturé 5 pantallas en png y creé un gif animado, la pantalla
es algo grande y así quedó el gif.

Te explico. Al comienzo se ve un escritorio y la ventana de Rambox con la
pestaña de Gmail activa, luego me voy, dentro de mi gmail a el ícono de
usuario (una cara de una pareja) y hago click.

Se despliega el menú donde sale mi usuario, y abajo, descolgadas, hay dos
cuentas más que me han otorgado "permiso" a mi cuenta principal para
accederlas. Esto se configura dentro del mismo gmail en acceso pop y
reenvío... o en consulta de otras cuentas. Una vez que tengo ese permiso
(de otra cuenta mía y la de mi pareja) puedo, simplemenete tocar alguna de
esas otras cuentas, y debería abrirse una nueva pestaña en el navegador y
llevarme directamente adentro de la cuenta (si, sin necesidad de poner la
clave de esa otra cuenta... porque tengo un permiso revocable para usarla
otorgado desde esas otras cuentas)

Pero lo que ocurre es que se abre un navegador (no me fijé si es el Firefox
o el PaleMoon), y me deja en la entrada para hacer login a la cuenta de
google.

Lo ideal sería una pestaña nueva dentro de Rambox... o al menos, si se abre
en un navegador externo, que pueda transportar la sesión iniciada hacia el
mismo. Tal vez todo esto resulta difícil o imposible de hacer, no lo se. No
lo reporté como un problema, sino como un feature request.

Gracias Ramiro, tu programa es el mejor :)
Rodolfo[image: Imágenes integradas 2]








2016-07-31 15:27 GMT-04:00 Ramiro Saenz <notifications@github.com>:

**Comment by saenzramiro** [comment]
To do that, just add many Gmail services for each account.

**Comment by rodoviario** [comment]
Thanks for the answer. That will work for accounts I personally own and
have password to login. For mi wife's account I will then have to ask her
for his actual password to do that, and it might be tricky to not raise
alarms in google servers if I log in from one location and she logs in from
another. Thanks god she is not using yet 2FA. I think I can live with that
:) Thanks Ramiro.

2016-08-01 15:35 GMT-04:00 Ramiro Saenz <notifications@github.com>:
