### ISSUE TITLE
[new-feature-request] Improve notification options

### ISSUE THREAD

**Issue by ruiumbelino** [saenzramiro/rambox#157]
Hi,

Thanks for making this useful program!

I would like to make a request, to improve the notification display, like Signal Desktop.

In each service options, and these options to improve privacy:
- Both sender name and message
- Only sender name
- Neither name and message

You can see the attached picture for better understanding:

![signal_desktop_settings](https://cloud.githubusercontent.com/assets/10651797/17252837/10ac22ce-55a6-11e6-98e4-4e3cfad25297.png)

Thanks for your support!

Regards

**Comment by saenzramiro** [comment]
Is a great idea, but Rambox don't handle notifications.

They come from the services, so if the service don't have any configuration, it's not possible for Rambox to modify the display.

Sorry! 😞
