### ISSUE TITLE
Integrate real VK Messenger (Vkontakte) Electron app in Rambox

### ISSUE THREAD

**Issue by MurzNN** [saenzramiro/rambox#1585]
At now Rambox integrate full vk.com website as messenger. But vk.com is not a messenger only, but full social network VKontakte like FaceBook. Facebook provide separate messenger app at https://messenger.com/

VK.com provide similar messenger app (separated from full social network interface) at https://vk.com/messenger - it built on Electron web technology, but not available at separate url at now. 

Is this possible to integrate VK Messenger Electron app into Rambox?

**Comment by saenzramiro** [comment]
No, we can't do that. Hopefully, they release a website only for messenger (like Facebook) so we can add it to Rambox.
