### ISSUE TITLE
[Inbox] Desktop Notifications

### ISSUE THREAD

**Issue by saenzramiro** [saenzramiro/rambox#159]
Add manually notifications to Inbox because don't have it.

**Comment by kissu** [comment]
Hi, I wanted to know if it was possible to get push notifications from Outlook for example with a little "1" near the name ? Or a desktop notification like in Thunderbird without having to go manually to the tab and check if an email has arrived, same like when using Messenger for example.
Thank you and keep up the awesome work ! :)

NB: sorry if it's not the correct place to ask that kind of question, but I don't find where else too...

**Comment by saenzramiro** [comment]
@kissu Outlook also don't have desktop notifications. I will take a look and see if I can add it in next release.

Refer #254

**Comment by saenzramiro** [comment]
Personal note: https://github.com/electron/electron/issues/262
