### ISSUE TITLE
Tweetdeck

### ISSUE THREAD

**Issue by knorrre** [saenzramiro/rambox#16]
For adding Tweetdeck you could use this url: [https://tweetdeck.twitter.com/?via_twitter_login=true](https://tweetdeck.twitter.com/?via_twitter_login=true).
After login you have to reload rambox with ctrl+r, then tweetdeck is working.

**Comment by saenzramiro** [comment]
Thank you! I will add it in the next release and see if I can prevent to reload Rambox.
