### ISSUE TITLE
Can't log in to Tweetdeck

### ISSUE THREAD

**Issue by forteller** [saenzramiro/rambox#160]
Hey. Love the app, thanks for making it Free software!

I'm having issues logging in to Tweetdeck. 

I fill in my username and password and click Log in. For a brief while there is a grey box in the bottom left corner with the word "Loading…" and then nothing more happens. I just stay on the login screen.

The first time I did this I got an e-mail from Twitter telling me about a new login, so it does seem to send my info to Twitter, though. I find this quite strange.

I'm using version 0.4.0 on Linux x64.

**Comment by saenzramiro** [comment]
Duplicate #16 #106 

It will be fixed in next release. Today we release it. :wink:

**Comment by forteller** [comment]
Oh, wow, that was fast! ;)

Thanks! I did search first, but only trough open issues, so that's why I didn't see that it's already been reported.
