### ISSUE TITLE
Support for keyboard shortcut Alt + 1/2/...

### ISSUE THREAD

**Issue by orschiro** [saenzramiro/rambox#1609]
Dear all, 

I am used to using Alt + 1 (or any other number) to switch to a specific tab in my Chrome browser. 

It's very hard to recondition myself and use Ctrl + 1 in Rambox to switch tabs. 

I know this is a very user-specific feature request but I would welcome a feature to additionally support Alt + number key. 

Looking forward whether or not this is requested by others as well!

**Comment by gameguy95** [comment]
Did you change some setting in Chrome to cause it to use Alt+number? Because I haven't changed any setting like that, and Alt+number did absolutely nothing in my Chrome setup. Ctrl+number worked for both without any setting changes.

**Comment by orschiro** [comment]
I did not. Thanks for mentioning that. Maybe that's Linux specific? Can anyone on Linux please confirm that Alt + 1 switches to first tab in Chrome?

**Comment by cmoro-deusto** [comment]
@orschiro I'm on arch linux using chrome "Version 65.0.3325.181 (Official Build) (64-bit)". Switching tabs works using Alt + number AND Ctrl + number for me here! :)

**Comment by cmoro-deusto** [comment]
Nevertheless, checking the official Chrome help for shorcuts, in Windows and Linux tab switching works using CTRL + number

https://support.google.com/chrome/answer/157179?hl=en&ref_topic=7437725

**Comment by orschiro** [comment]
@cmoro-deusto thanks! So probably it's consistent to only support Ctrl then. I will close this issue...

**Comment by Mumrau** [comment]
Maybe it would still be useful to give the user the possibility to activate this mode to function with Alt + Number?
(I would appreciate it given the fact that I'm super used to ALT+Number for chrome or my developer's IDEs.)
