### ISSUE TITLE
Disabling "Show in taskbar" has no effect

### ISSUE THREAD

**Issue by jbbr** [saenzramiro/rambox#162]
First of all: Thanks for the latest update, looks nice.

I was pleased to see the possibility to disable/configure "show in taskbar" in a new preferences menu (Maybe it wasn't new but I just haven't discovered it until now).

Anyway: Disabling "show in taskbar" has no effect on my system. Restarting the app doesn't help.

_Arch Linux x64, Rambox 0.4.1 from AUR
i3 desktop environment - but taskbar works the same as in Gnome 3._

**Comment by saenzramiro** [comment]
Ok, I will take a look.

**Comment by oahon** [comment]
I got it working on LXDE, but on i3 the basic Modifierkey+Shift+Q (which usually closes all app windows + processes) seems just to close the window (Ctrl+W behaviour).

[ Everything else is working great, big thumbs for you guys!]

**Comment by matiasgagliano** [comment]
Same issue here as commented on #163. Disabling *Start automatically on system startup* doesn't work either.

> Arch Linux x64, Rambox 0.4.1 from AUR, Gnome 3.20 under Wayland.

**Comment by weeman1337** [comment]
I added a PR that should fix this
