### ISSUE TITLE
Telegram load issues

### ISSUE THREAD

**Issue by nerotic** [saenzramiro/rambox#1623]
Method: channels.getFullChannel
Result: {"_":"rpc_error","error_code":500,"error_message":"RPC_MCGET_FAIL"}

When loading Telegram

	
	-
	> Rambox 0.5.17
	> Electron 1.8.4
	> win32 x64 10.0.16299

**Comment by Mikaela** [comment]
Telegram was down for ~11 hours which partially overlap when this issue was opened, so I guess it's working now and this is invalid?

**Comment by nerotic** [comment]
That's correct, I wasn't aware of the outage.  Sorry for the false alarm.

 Mark Oren                         <http://nerotic.net/>
 magento specialist


<mark@nerotic.net> [image: callto:neromadrid] <callto:nerotic.networks> [image:
tel:+1-347-875-0046] <+1-347-875-0046> [image:
http://www.linkedin.com/in/markoren] <http://www.linkedin.com/in/markoren>

**Comment by Ash258** [comment]
@nerotic Close this issue then.
