### ISSUE TITLE
Las nuevas preferencias no se graban

### ISSUE THREAD

**Issue by MauricioAedo** [saenzramiro/rambox#163]
Hola Ramiro

Estoy probando la última versión y veo que hay unas preferencias de las cuales he configurado que no se muestre en la barra de tareas y que no se inicie automáticamente pero cada vez que se reiniciar Rambox las preferencias vuelve por defecto.

Saludos

-
> Rambox 0.4.1
> Electron 1.3.1
> win32 ia32 10.0.10586

**Comment by saenzramiro** [comment]
Que raro... lo voy a mirar nuevamente.

**Comment by MauricioAedo** [comment]
Solucionado, era el mismo problema de usar cliente 32 en vez de 64 bits.

Gracias.

**Comment by matiasgagliano** [comment]
Mismo problema en ArchLinux. Ignora completamente las configuraciones de **no** mostrar en la barra de tareas y de **no** arrancar en el inicio.

> Version: 0.4.1
> Platform: linux (x64)
> Electron: 1.3.1
> Chromium: 52.0.2743.82
> Node: 6.3.0
