### ISSUE TITLE
Linux: Closing the window doesn't actually close, just minimize

### ISSUE THREAD

**Issue by forteller** [saenzramiro/rambox#166]
Thanks for making a install file for Linux!

But now when I try to close the window to just have it as a tray icon, it still shows up when I Alt+Tab. But if I right click on the tray icon and click on Show/Hide Window, then it does what I actually want it to do when I close the window: hide it.

Bonus issue, related to this: When the window is hidden I have to right click on the tray icon and click Show/Hide Window again to show it. It should be possible to just click on it.

Hope to see this fixed soon. Thanks for a great app! :)

**Comment by saenzramiro** [comment]
I will take a look on this.

**Comment by weeman1337** [comment]
I added a PR that should fix this

**Comment by forteller** [comment]
Sorry. I just updated to 0.4.2 and it's still just the same as before.

**Comment by weeman1337** [comment]
The window close handling didn't change in the 0.4.2 release. So this issue is still valid and should be reopened.

I'll update the pull request to the new code.

**Comment by saenzramiro** [comment]
@weeman1337 Yes please, because in v0.4.2 the code changed with a new config library. Waiting for PR...

**Comment by weeman1337** [comment]
@saenzramiro I submitted a new, updated PR.
