### ISSUE TITLE
Don't work Start minimized in Ubuntu 18.04

### ISSUE THREAD

**Issue by GuxMartin** [saenzramiro/rambox#1667]
### Steps to reproduce

1. File -> Preferences
2. Mark "Start automatically on system startup" and "Start-Minimized"
3. Save

### Expected behavior

Minimized on system startup

### Actual behavior

Don't work Start Minimized on system startup

### ENVIRONMENT

Ubuntu 18.04

> Rambox: v0.5.17

> OS: Ubuntu 18.04

> Arch: x64

**Comment by Faoc** [comment]
Duplicate of #1205 
I already proposed a PR which should fix this.
