### ISSUE TITLE
Add Actor

### ISSUE THREAD

**Issue by forteller** [saenzramiro/rambox#167]
I would love it if you would add Actor to the list of default supported messaging systems! 
https://actor.im/
https://github.com/actorapp/actor-platform/

**Comment by saenzramiro** [comment]
Did you add it as Custom Service?

If you did it, can you share the Unread Code you are using?

**Comment by forteller** [comment]
I have tried to add it as a custom service and it worked fine. But I don't know anything about any unread code. I'm not the developer of Actor, just a regular Joe, so I don't know much :)

**Comment by saenzramiro** [comment]
Ok, no problem. :wink: 

I will try to add it in next release.

**Comment by AnthonyEbert** [comment]
You can remove Actor now. It seems to not exist anymore.

**Comment by saenzramiro** [comment]
@AnthonyEbert Thank you, I will remove it in next release.
