### ISSUE TITLE
Would it be possible to choose fonts?

### ISSUE THREAD

**Issue by exec228** [saenzramiro/rambox#168]
Salut!
It is not a bug of your application. It is a bug in font-designers' heads.
I really hate broken fonts that are intended for anti-aliasing while I have it turned off.
So, I'd like to set Verdana everywhere, that is definitely optimised for raster screens
and does not have glitches in rendering.
Thank you!

-
> Rambox 0.4.1
> Electron 1.3.1
> win32 ia32 6.3.9600

**Comment by saenzramiro** [comment]
I will take a look if we can add this for next versions.

BTW, Are you using a ia32 arch system?

**Comment by exec228** [comment]
Salut, Ramiro Saenz!

Ramiro Saenz (2016/08/03, 01:01:06):

Ramiro> I will take a look if we can add this for next versions.
Thank you! Would be nice.

Ramiro> BTW, Are you using a ia32 arch system?

My system is Windows 8.1 x64.

____
luck
exec
>"Hello World!" 17 errors, 31 warnings.
P.S. <void>

**Comment by saenzramiro** [comment]
[Offtopic] So try to install the x64 version of Rambox, because ia32 don't have the autoupdate feature.

**Comment by saenzramiro** [comment]
I can try to add this in next version.

Electron give some options for this:

* `defaultFontFamily` Object - Sets the default font for the font-family.
  * `standard` String - Defaults to `Times New Roman`.
  * `serif` String - Defaults to `Times New Roman`.
  * `sansSerif` String - Defaults to `Arial`.
  * `monospace` String - Defaults to `Courier New`.
* `defaultFontSize` Integer - Defaults to `16`.
* `defaultMonospaceFontSize` Integer - Defaults to `13`.
* `defaultEncoding` String - Defaults to `ISO-8859-1`.

Do you think the options for `defaultFontFamily` are ok?

**Comment by exec228** [comment]
Salut!
I don't know what those options would affect.
For which parts of interface will it be in effect? Windows menu looks ok, since it is ruled by Windows. Inside windows there are many elements, though: accounts window, contacts list, chat messages, chat names, chat time, chat title, tabs title...

**Comment by saenzramiro** [comment]
I study the properties listed before and seems to not apply in Rambox, because is a web app. For services, you can't change the default font for each service.

Each one have their own font, and to change the font you will need to wait until we enable the injection of CSS for services.

I will close this issue and you will have to wait for a future version (hopefully in a month).

**Comment by exec228** [comment]
1) Firefox can override fonts
2) Stylish can override fonts
3) Sometimes even Chrome can (rarely, that is quite irritating) (--disable-remote-fonts kills even glyphs)
Anyways, hope font config will be available in observable future.
Thank you!

**Comment by igalic** [comment]
i hope it's not too bad to resurrect this thread, but i was wondering if it would be possible to adapt the default fonts used in Rambox?

Specifically, I'd like to set a dyslexic friendly font, like Opendyslexic or Dyslexie
