### ISSUE TITLE
Antivirus Kaspersky mark rambox setup - as trojan virus.

### ISSUE THREAD

**Issue by progserega** [saenzramiro/rambox#1685]
Antivirus said, that it is found trojan by behavioral analysis.
Windows: win 10 x64
Windows Version:	10.0.16299 Build 16299
Kaspersky version:  11.0.0.6499.AES56

![error](https://user-images.githubusercontent.com/1297163/40819002-673abc6e-659d-11e8-80dd-df7d425a624f.png)

![kasper](https://user-images.githubusercontent.com/1297163/40819398-38fc6036-659e-11e8-8819-bbea5c8d20b1.png)

**Comment by yafp** [comment]
and what should the developer do in your opinion?

**Comment by Ash258** [comment]
Cannot do anything about it.

Disable antivirus and install or use another way of installation (in best way use [scoop](https://www.scoop.sh), download unpacked version) or write to Kaspersky about bad recognition.
