### ISSUE TITLE
I'd like to help you with the translation.

### ISSUE THREAD

**Issue by wls0210** [saenzramiro/rambox#1695]
The translation is to use crowdin. However, it appears that there are not many entries registered that need to be translated. There are many parts that need translation, but crowdin says most of them are translated.  How can I help you with the translation?

> Rambox: v0.5.17

> OS: Windows 10

> Arch: x64

**Comment by Ash258** [comment]
/cc @saenzramiro 

Languages were updated about 5 months ago so it's possible that some newer translations are missing.

**Comment by wls0210** [comment]
Then, can I modify the code directly for translation if necessary?

**Comment by Ash258** [comment]
Don't know. Try it.

**Comment by saenzramiro** [comment]
Yes, we have to rebuild the translations for the next release of Rambox.

Please, all translations should do it in Crowdin. I will take a note to update all the languages for next release.

**Comment by Ash258** [comment]
@saenzramiro Could you add to package.json new task for translation downloading? 
only something like: `"translationDownload": "node languages.js download"` 

I am not sure how the workflow work.

**Comment by saenzramiro** [comment]
Sure, will do.
