### ISSUE TITLE
Scheduling of messages?

### ISSUE THREAD

**Issue by nrvale0** [saenzramiro/rambox#1708]
This is a feature request and/or request for information...

I'm interesting in having the ability to schedule messages. I don't see this feature in the Issues anywhere nor do I see a roadmap for the project on the website. Perhaps someone is already working on this?

If not, Rambox mentions the ability to inject custom code on the main website. I don't see any docs or additional mention of that feature when flipping through the UI. Perhaps someone could point me to some docs/codes? It seems like that ability might be key to adding the scheduled functionality I mentioned above.

Thx

**Comment by Ash258** [comment]
https://github.com/saenzramiro/rambox/wiki

**Comment by nrvale0** [comment]
:+1:
