### ISSUE TITLE
Minimizar al system tray

### ISSUE THREAD

**Issue by MauricioAedo** [saenzramiro/rambox#172]
En esta nueva versión cuando uno configura no mostrar en taskbar y se minimiza al system tray cuesta mucho volver a maximizarlo ya sea haciendo doble click en el icono o haciendo click derecho opción "Show/Hide Window".

Saludos

## 

> Rambox 0.4.1
> Electron 1.3.1
> win32 ia32 10.0.10586

**Comment by MauricioAedo** [comment]
Ramiro, no sugiero cambiar nada solo aviso de este bug. Tal vez no me expliqué bien, pero una vez minimizado Rambox al system tray es como que se pega y cuesta mucho para restaurarlo ya sea haciendo doble click en el icono o click derecho "Show/Hide Window".

Saludos

**Comment by saenzramiro** [comment]
Mauricio, me parece que te confundiste de thread.

**Comment by maikcrew** [comment]
Hello, If I understood you, talking about better hiding system tray. I use Thunderbird plug-in FireTray that allows hiding/opening to system tray by using the mouse wheel or by one clicking the left button. Likewise can click on the Close button to minimize the application to system tray also. This more quickly than click right button and choose hide/open app.
