### ISSUE TITLE
[new-feature-request] Master Password

### ISSUE THREAD

**Issue by abacao** [saenzramiro/rambox#174]
By now, I have almost all my life open in Rambox.

I think that Rambox should have a master password and a timeout after X seconds without use, it should lock Rambox.

**Comment by saenzramiro** [comment]
Well, we have an issue for this #27.

In version 0.4.1 you can lock Rambox, and if you close it locked, it will ask for password when open it again. For now, you can protect you like that.

I think we can to this for next version. :wink:
