### ISSUE TITLE
RAMBOX BUG AGAIN AND AGAIN

### ISSUE THREAD

**Issue by Iblort** [saenzramiro/rambox#1742]
![untitled-3](https://user-images.githubusercontent.com/40687567/42081154-0665deca-7b85-11e8-8b69-4f6023efd860.jpg)

	
	-
	> Rambox 0.5.17
	> Electron 1.8.4
	> win32 x64 10.0.17134

**Comment by Arebs** [comment]
As Iblort don't provide Information to reproduce it, I will do it instead: 
It usually happens if you have opened Rambox for a while (1 day or more usually). This Error message popped then up every time you switch to another chat.  If you restart Rambox, the Error is gone. 

	> Rambox 0.5.17
	> Electron 1.8.4
	> win32 x64 10.0.16299

**Comment by Iblort** [comment]
I cannot agree... this does not disappear when I restart Rambox. I NEED TO RESTART WHOLE COMPUTER. That is the reason why it is so bad and disappointing.

**Comment by Ash258** [comment]
Duplicate of #1656

**Comment by nniesen** [comment]
> I cannot agree... this does not disappear when I restart Rambox. I NEED TO RESTART WHOLE COMPUTER. That is the reason why it is so bad and disappointing.

You have to do "File >Quit Rambox", otherwise you're not restarting it because it's still running in the System Tray.
