### ISSUE TITLE
404 on donate link

### ISSUE THREAD

**Issue by peterchaula** [saenzramiro/rambox#1749]
https://fundraiseup.com/widget/FUNSGXPIJWQ/donate?key=KPCFEZKZ

	
	-
	> Rambox 0.5.17
	> Electron 1.8.4
	> linux x64 4.15.0-20-generic

**Comment by yafp** [comment]
the link above results in a "Not Found" here as well.

@peterchaula 
Might i ask where the link is coming from?
The donate menu in version 0.5.17 points tp paypal

**Comment by Ash258** [comment]
From heart icon inside app.
