### ISSUE TITLE
New GMail Layout - Unread badge script

### ISSUE THREAD

**Issue by 1dot44mb** [saenzramiro/rambox#1750]
Rambox GMail service's unread badge count does not work for new GMail layout. You can customize the service and inject the following JavaScript to make the badge reappear.

    function checkUnread() {
        var e = document.getElementsByClassName("bsU");
        var t = 0;
        if (e.length > 0) {
            t += parseInt(e[0].innerHTML.trim());
        }
        updateBadge(t);
    }

    function updateBadge(e) {
        if (e && e >= 1) {
            rambox.setUnreadCount(e);
        } else {
            rambox.clearUnreadCount();
        }
    }

    setInterval(checkUnread, 3000);

**Comment by Ash258** [comment]
Duplicate of #1649
