### ISSUE TITLE
No sound for Telegram voice messages

### ISSUE THREAD

**Issue by maurice-schleussinger** [saenzramiro/rambox#1751]
### Steps to reproduce

1. Use Telegram service in Rambox. 
2. Play voice message 

### Expected behavior

Hear the voice message when clicking "Play".

### Actual behavior

Message plays but no sound.

### ENVIRONMENT

> Rambox: v0.5.17

> OS: macOS 10.13.4 (High Sierra)

**Comment by Ash258** [comment]
Are you sure you have "Dont disturb" mode disabled?

![Mode](https://i.imgur.com/uEQhTjy.png)

**Comment by maurice-schleussinger** [comment]
@Ash258 You are correct. 
IMHO this is bad design. I commented on https://github.com/saenzramiro/rambox/issues/1475 and encourage others to do the same.
