### ISSUE TITLE
Restore configuration from backup creates duplicate tabs

### ISSUE THREAD

**Issue by MurzNN** [saenzramiro/rambox#1760]
When I use `Synchronize Configuration » Restore` action - Rambox creates duplicate of current tabs, with same name but empty user data (no cookies).

How can I prevent creating duplicates on restore configuration action and make Rambox reuse already exist tabs on current device?

**Comment by MurzNN** [comment]
In `~/.config/Rambox/Partitions` folder I see that duplicates have same oauth id (`servicename_N_google-oauth2%7C107098834222066052600`), but different number (`N`).

**Comment by MurzNN** [comment]
If I remove all Rambox configuration (whole folder in config) and try to restore from backup, it creates tabs normally, without duplicates.

**Comment by Ash258** [comment]
Duplicate of #1311
