### ISSUE TITLE
Telegram crash in desktop view

### ISSUE THREAD

**Issue by marin-h** [saenzramiro/rambox#177]
Works for a moment but then just shows plain blank window. I'm in ubuntu 16 with xfce and arc theme

**Comment by saenzramiro** [comment]
I tested in Windows 10 x64 and works ok.

Did you test it in Google Chrome? Did you reload the service?

**Comment by marin-h** [comment]
Tested in previous version of rambox and in franz, worked OK. Reloading the service isn't making any changes..

2 de agosto del 2016 16:22, "Ramiro Saenz"  escribió:
	I tested in Windows 10 x64 and works ok.

	Did you test it in Google Chrome? Did you reload the service?

**Comment by saenzramiro** [comment]
I think is an Electron bug.

Try to do this steps:

1. Once you have your Telegram blank screen, double click in Telegram tab and select Dev Tools.
2. Go to Network tab and then press F5 on your keyboard.

**Comment by saenzramiro** [comment]
Please read this comment: https://github.com/saenzramiro/rambox/issues/181#issuecomment-237327164

I will close this issue to merged with #181
