### ISSUE TITLE
Tabs don't playing sound

### ISSUE THREAD

**Issue by gabriellisboa20** [saenzramiro/rambox#1777]
none of the rambox tabs are playing sound. I've reinstalled, checked windows settings and nothing. What can be done?

	
	-
	> Rambox 0.5.17
	> Electron 1.8.4
	> win32 x64 10.0.17134

**Comment by heber-junior** [comment]
You tried press f1 key? This enable/disable sounds on Rambox.

**Comment by dln949** [comment]
I have the exact same issue, no sound coming out of audio/video playback anywhere in Rambox.  I do NOT have the "Don't Disturb" option enabled.  

Ubuntu 17.10
Rambox 0.5.17

**Comment by heber-junior** [comment]
I had this problem and I solved it by reinstalling the application.
I do not know what happened to be without sound.

**Comment by gabriellisboa20** [comment]
Tranks for try help me, Guys! But come back alone.
