### ISSUE TITLE
Modo don't disturb

### ISSUE THREAD

**Issue by MauricioAedo** [saenzramiro/rambox#178]
Hola nuevamente Ramiro.

He detectado un problema con el modo don't disturb, en Windows 10 a pesar de tenerlo activado me llegan notificaciones cada vez que recibo un correo en Gmail.

Saludos

-
> Rambox 0.4.1
> Electron 1.3.1
> win32 x64 10.0.10586

**Comment by saenzramiro** [comment]
¿Solamente en ese servicio?

**Comment by MauricioAedo** [comment]
Si

**Comment by saenzramiro** [comment]
Ok, voy a investigar al respecto.

¡Muchas gracias por tus aportes! :wink:
