### ISSUE TITLE
Rambox account - login issue

### ISSUE THREAD

**Issue by zetneteork** [saenzramiro/rambox#1784]
Unable to log in Rambox Account.

### Steps to reproduce

1.  Log In Rambox Account
2.  Username `email`
3.  Password

```
WE'RE SORRY, SOMETHING WENT WRONG WHEN ATTEMPTING TO LOG IN.
```

Rambox: v0.5.17

OS: Windows 10

Arch: x64

**Comment by Ash258** [comment]
Duplicate of #1698
