### ISSUE TITLE
Rambox "loading logo" stays showing forever

### ISSUE THREAD

**Issue by nstamm** [saenzramiro/rambox#179]
una imagen vale mas que mil palabras, así se queda.

![captura de pantalla de 2016-08-02 11-59-03](https://cloud.githubusercontent.com/assets/5531684/17348871/0baaae1a-58f0-11e6-823d-e72308dae481.png)

**Comment by saenzramiro** [comment]
¿Qué SO estás usando?

Que raro... voy a ver que puede estar pasando. Por ahora, ve a `View->Toogle Dev Tools` y en Console ejecuta lo siguiente:

```javascript
Ext.get('spinner').destroy();
```

**Comment by nstamm** [comment]
Estoy usando ubuntu gnome 16.04

Muchas gracias por dar una solución efectiva. Luego probaré de reinstalarlo a ver que ocurre.

3 de agosto del 2016 14:27, "Ramiro Saenz"  escribió:
	¿Qué SO estás usando?

	Que raro... voy a ver que puede estar pasando. Por ahora, ve a View->Toogle Dev Tools y en Console ejecuta lo siguiente:
	Ext.get('spinner').destroy();
