### ISSUE TITLE
A javaScript error ocurred in the main process

### ISSUE THREAD

**Issue by Leinad92** [saenzramiro/rambox#1790]
El detalle de mi problema es el siguiente, cuando me llega un mensaje a la aplicación que tengo vinculada en la app de rambox me llega el mensaje de un error de javascript he actualizado la plataforma y el error sigue apareciendo, espero me puedan ayudar muchas gracias.
![rambox_2018-07-23_12-22-26](https://user-images.githubusercontent.com/41589409/43092677-8c0f29d6-8e73-11e8-9a00-57186ddf9130.png)

	
	-
	> Rambox 0.5.17
	> Electron 1.8.4
	> win32 x64 10.0.17134

**Comment by Ash258** [comment]
Duplicate of #1656
