### ISSUE TITLE
Multiple tabs when I click on a link

### ISSUE THREAD

**Issue by arthurrschaefer** [saenzramiro/rambox#18]
Every time I click on a link inside my inbox account, at lesat 5 tabs with the same content are open on my browser.
It's boring close 4 tabs every time I open a link.

-
> Rambox 0.3.0
> Electron 1.2.5
> win32 x64 10.0.10586

**Comment by saenzramiro** [comment]
Yes, is boring. I will fix it in next release.

Related to #11, #6.
