### ISSUE TITLE
[UX] Changing tabs does not set document focus

### ISSUE THREAD

**Issue by Luzifer** [saenzramiro/rambox#180]
**setup**

- Use Rambox Version: 0.4.1 / Platform: darwin (x64) / Electron: 1.3.1 / Chromium: 52.0.2743.82 / Node: 6.3.0
- Add multiple tabs

**observed behavior**

- Change from one to another tab (for example Slack), start typing
- Document in the tab does not get the key events

**expected behavior**

- Change tab, the new tab document pane gets the focus
- Starting to type will let the document get the key events

**testcases**

- Slack: When the window has focus after changing tabs the typed characters will go into the input field
- TweetDeck: "N" opens the new-tweet pane while without focus nothing happens

**Comment by saenzramiro** [comment]
Great! I will improve this for next release.

**Comment by thomas-gaudin** [comment]
Should I add here that whenever I Alt+Tab to Rambox, the text input loses focus? But if I Ctrl+Tab between tabs, they keep focus and I can type and use keyboard shortcuts.

*Version:* 0.4.1 *Platform:* linux (x64) *Electron:* 1.3.1 *Chromium:* 52.0.2743.82 *Node:* 6.3.0

**Comment by saenzramiro** [comment]
@thomas-gaudin Yes, is good to know that also.
