### ISSUE TITLE
Disable Badge Option

### ISSUE THREAD

**Issue by Jeetah** [saenzramiro/rambox#182]
There should be an option for disabling the unread badge (OSX) on the taskbar icon (especially for eMail services like GMail, Inbox...). Reason: For focused work eMails should be pull = no notifications (already possible) and badges shown that could "steal" your focus.

**Comment by saenzramiro** [comment]
Ok, I will take a look.

**Comment by ric2b** [comment]
+1
An option to disable notification badges for a certain service would be great for things like e-mail!

**Comment by weeman1337** [comment]
Does #488 provide the desired feature?

#187 is related to this. Maybe one should be closed..

**Comment by Jeetah** [comment]
Yes, works for me now - the global option disables this on icon bar as wished.
