### ISSUE TITLE
Telegram: no unread count

### ISSUE THREAD

**Issue by andrey-yantsen** [saenzramiro/rambox#183]
![image](https://cloud.githubusercontent.com/assets/629281/17361539/bc3fad1e-5979-11e6-9235-35a58e77710b.png)

**Comment by vsxed** [comment]
Yes, was investigating in this too. The application reads the title of a webservice and uses the integer as the unread count. unfortunately telegram got a "blinking" title, which doesn't work that good.

**Comment by saenzramiro** [comment]
@vsxed Yes, also Messenger and others. I have to inject JS code to disable blinking title and detect new messages to modify it to "(x) Telegram".

If anyone can help with the code, is welcome. :smiley:
