### ISSUE TITLE
Feature-Request: Ignoring some services for global unread counter

### ISSUE THREAD

**Issue by MrChick** [saenzramiro/rambox#187]
It would be great if we could have an option to ignore a service for the global unread counter.

I want to have the unread count on my TinyTinyRSS-Tab, but having rambox report 2000+ unread messages all the time kinda stinks. So I'd love to have the global counter ignore that one tab.

Do you think this would be possible?

![rambox_unread_mock](https://cloud.githubusercontent.com/assets/706764/17405105/815af4fc-5a5e-11e6-87af-9f43ed61e424.png)

**Comment by saenzramiro** [comment]
Yes, I can add a new option in the window to ignore global counter.

**Comment by MrChick** [comment]
Any chance to get this in the next version? :)

**Comment by saenzramiro** [comment]
Sure. 😉

**Comment by weeman1337** [comment]
I'll take over this one and provide a PR soon.

**Comment by weeman1337** [comment]
I suggest adding two options to control the unread counter:

- one to control the tab unread counter
- one to exclude a service from the global counter

The idea behind is: maybe an user doesn't want global "spamming" but see if there are news on demand.

What do you think @saenzramiro?

![screenshot from 2016-11-23 10-55-41](https://cloud.githubusercontent.com/assets/6216686/20557427/ca2a75ea-b16b-11e6-9502-2ba363056bab.png)

**Comment by MrChick** [comment]
I like it!

**Comment by ZaLiTHkA** [comment]
That's an awesome idea @weeman1337, good thinking. :)

**Comment by saenzramiro** [comment]
@weeman1337 Great idea! I will add it in a future release.

**Comment by weeman1337** [comment]
@saenzramiro will help you out there. Just wanted to ask for your opinion. Will file a PR soon.
