### ISSUE TITLE
Hangout: click pop out open browser

### ISSUE THREAD

**Issue by biji** [saenzramiro/rambox#19]
Clicking **pop out** open browser, ~~clicking minimize do nothing~~

thanks

**Comment by saenzramiro** [comment]
I will take a look on this.

Thanks!

**Comment by saenzramiro** [comment]
This bug it cannot be fix it because when users click on **pop-up** option in a conversation, opens a URL in the default browser that doesn't have any session shared. Minimizing after pop-up is a Hangouts bug.
