### ISSUE TITLE
Windows taskbar icon does not display properly

### ISSUE THREAD

**Issue by Naoray** [saenzramiro/rambox#190]
When Rambox is launched the icon does not show up like it s supposed to do:
<img width="58" alt="unbenannt" src="https://cloud.githubusercontent.com/assets/10154100/17429902/91c20ef0-5af1-11e6-98a9-91588904ae37.PNG">

Temporary workaround:
1. Right click on the icon -> 'pin to taskbar'
2. Right click on the icon -> 'unpin from taskbar'

-
> Rambox 0.4.1
> Electron 1.3.1
> win32 ia32 10.0.10586

**Comment by saenzramiro** [comment]
Duplicate #170.

Thanks!
