### ISSUE TITLE
Don't see the window in the Alt-Tab Menu

### ISSUE THREAD

**Issue by Babwin** [saenzramiro/rambox#191]
Like you can see here : https://puu.sh/qqHRV/d679c30bb9.png (dual screen screenshoot).
I don't see Rambox in the alt+tab menu. 
- I don't know how to delete an Services we add.

+Is it possible to install Chromium Add-on ?
- It's not realy an issue but i'm one of those poeple who prefere use the twitter website than tweetDeck, may you plz add it.

Thx for the app !

## 

> Rambox 0.4.1
> Electron 1.3.1
> win32 x64 10.0.10586

**Comment by saenzramiro** [comment]
I have 3 monitors, same environment and works ok here. The only difference I noticed is that Alt + Tab window, [here is a screenshot](http://winaero.com/blog/wp-content/uploads/2016/06/Windows-10-alt-tab-hidden-background-windows.png) I found with the same design.

To remove a service, in the **Enabled Services** list, when you mouse over a service, you will see a bin a the end of the row.

Is not possible for now to add a Chromium Add-on. Electron don't have that feature yet.

You can add Twitter as a Custom Service ([read here](https://github.com/saenzramiro/rambox/wiki/Add-a-Custom-Service)).
