### ISSUE TITLE
Feedly.com does not works due to popup blocking

### ISSUE THREAD

**Issue by pasnox** [saenzramiro/rambox#193]
### Steps to reproduce

1.  Add feedly.com custom service
2. try to log in

### Expected behaviour

Allow log in

### Actual behaviour

Popup blocked and url is redirected to my default browser (Chromium)

### ENVIRONMENT

OSX El Capitan

Version: 0.4.1
Platform: darwin (x64)
Electron: 1.3.1
Chromium: 52.0.2743.82
Node: 6.3.0

**Comment by saenzramiro** [comment]
Ok, the thing here is to allow SSO from popups.

I will try to fix this in next release.

**Comment by mbarbey** [comment]
Is there some news about the integration of feedly ?
This issue was closed in september 2016 but it seem to not work (or not anymore, I don't know).

When I add feedly as custom service, I get the default page asking me to login, but when I try to login, it's my default navigator which show me the login page.

Thanks in advance for your feedback.

Version: 0.5.10
Platform: win32 (x64)
Electron: 1.7.4
Chromium: 58.0.3029.110
Node: 7.9.0

**Comment by saenzramiro** [comment]
We are keep working on this.
I closed this because there are other threads related with SSO popups.

**Comment by gt50** [comment]
I managed to get feedly working in rambox by using the SSO popup URL as the custom URL in rambox.

I opened an icognito window in chrome and tried to sign in. This is the current URL for the popup: https://feedly.com/v3/auth/auth?client_id=feedly&redirect_uri=https%3A%2F%2Ffeedly.com%2Ffeedly.html&scope=https%3A%2F%2Fcloud.feedly.com%2Fsubscriptions&response_type=code&ck=1512679618405&ct=feedly.desktop&landingPage=welcome&cv=30.0.1409&pageRef=welcome&mode=login. 

After pasting it as a custom URL I went through the google login procedure. After that was complete there is a link to go to feedly. It sent me back to the SSO page again, at which point I clicked the google button again and feedly worked normally.

**Comment by saenzramiro** [comment]
@gt50 Nice hack! Thank you.

**Comment by dixonge** [comment]
Using the SSO Popup URL does not work for me. Always end up back in main Chrome browser. If I click the feedly.com URL it just takes me to the main page with the Login link. Just a big never-ending loop.
