### ISSUE TITLE
Modo no molestar silencia y videos whatsapp

### ISSUE THREAD

**Issue by MauricioAedo** [saenzramiro/rambox#195]
Hola Ramiro

He detectado que mientras está activo el modo no molestar tampoco se escuchan los audios y videos de whatsapp y no queda otra opción que desactivar el modo.

Saludos

-
> Rambox 0.4.1
> Electron 1.3.1
> win32 x64 10.0.10586

**Comment by saenzramiro** [comment]
Hola Mauricio.

Cierro este ticket y hago un merge con el #79 y la seguimos ahí.
