### ISSUE TITLE
Error on install

### ISSUE THREAD

**Issue by petrolero11** [saenzramiro/rambox#197]
### Steps to reproduce

1. 
2. 
3. 

### Actual behavior

_Buenas noches, les escribo porue al bajar la última actualziación de su página web, la v.0.41 y instalarla en el PC, ésta no se instala como la anterior versión, queda como una aplicación web.  Me arroja el siguiente mensaje de error.  Deseo su amable respuesta.  Gracias._
![sin titulo1](https://cloud.githubusercontent.com/assets/20715199/17454553/61add31c-5b68-11e6-83cd-bbd3bb022fb0.jpg)

### ENVIRONMENT

> Rambox: v0.41

> OS: Windows 7 Ultimate

> Arch: x64

**Comment by saenzramiro** [comment]
¿Descargaste el archivo ZIP o el .exe?

**Comment by petrolero11** [comment]
Descargué el archivo.ZIP.


---
Igor A. Petrola P.
Email: petrola70@hotmail.com
Skype: petrolero70








________________________________
De: Ramiro Saenz <notifications@github.com>
Enviado: sábado, 06 de agosto de 2016 12:19:40 a.m.
Para: saenzramiro/rambox
Cc: Igor; Author
Asunto: Re: [saenzramiro/rambox] Error on install (#197)


¿Descargaste el archivo ZIP o el .exe?

-

**Comment by saenzramiro** [comment]
Por favor, descarga los archivos ejecutables de 64 o 32 bits. 

Los zip tienen un error que voy a estar corrigiendo en estos días.

**Comment by petrolero11** [comment]
Buenas noches Ramiro,


     Instalado el programa desde el ejecutable de 64 bits, operativo al 100%.  Gracias.


Saludos,

---
Igor A. Petrola P.
Email: petrola70@hotmail.com
Skype: petrolero70








________________________________
De: Ramiro Saenz <notifications@github.com>
Enviado: sábado, 06 de agosto de 2016 04:23:40 a.m.
Para: saenzramiro/rambox
Cc: Igor; Author
Asunto: Re: [saenzramiro/rambox] Error on install (#197)


Closed #197<https://github.com/saenzramiro/rambox/issues/197>.

-
