### ISSUE TITLE
enabling the "Trust invalid authority certificates"

### ISSUE THREAD

**Issue by spookssi** [saenzramiro/rambox#198]
Hi and thx for your work ! 

I have an error with my personal domain. 

`You have to remove the service and add it again, enabling the "Trust invalid authority certificates" in the Options.`

I have a simple question :). How can i enable Trust invalid authority certificates in the "option" on OSX ?

> OS: el capitan last version.

**Comment by gillesmagneville** [comment]
Hi,

Same problem with my personal domain and enabling Trust invalid authority certificates in the "option" but on Linux (Ubuntu 16.04)

**Comment by saenzramiro** [comment]
That option is in the configuration window when you add a Custom Service.
