### ISSUE TITLE
Hangout: flicker

### ISSUE THREAD

**Issue by biji** [saenzramiro/rambox#20]
flicker when choosing buddy to start chat (linux Fedora 24)

Thanks

**Comment by saenzramiro** [comment]
Can you explain me more in details? I don't use Flicker, so I don't know what are you talking about. 😄

**Comment by biji** [comment]
😂
It is flashing white, when choosing buddy/contact

**Comment by saenzramiro** [comment]
Oh sorry, I will take a look on this.

Thanks!
