### ISSUE TITLE
Slack Notification Settings

### ISSUE THREAD

**Issue by ThibaudDauce** [saenzramiro/rambox#200]
### Steps to reproduce

1. Set your Slack Notification Settings as "Only direct messages and highlight words"
2. Wait a message in a channel
3. See the red badge with "1" in the tab bar

### Expected behavior

I expect Rambox not record the notification in the tab bar.

### Actual behavior

Rambox seems to not be aware of the Slack Notification Settings.

### ENVIRONMENT

> Rambox: v0.4.1

> OS: Archlinux

> Arch: x64

**Comment by ThibaudDauce** [comment]
Seems to be the same problem than #184. Feel free to close this issue as duplicate.

**Comment by saenzramiro** [comment]
Thanks for report this. I will close it to merge it with #184.
