### ISSUE TITLE
Preferences not registered

### ISSUE THREAD

**Issue by Zeilloc** [saenzramiro/rambox#201]
Hello,
My issue is that at each time I restart my computer, Rambox launches but my preferences (File > Preferences) are reset to what they were at beginning instead of being saved.
This issue does not appear when I quit and launch Rambox myself in a Windows session: preferences are saved (till I restart the computer).
Thanks for help.

-
> Rambox 0.4.1
> Electron 1.3.1
> win32 x64 10.0.10586

**Comment by saenzramiro** [comment]
Ok, I will fix this for next release.

Thank you!

**Comment by Zeilloc** [comment]
You're welcome!
Thanks for the development.

Valentin

2016-08-08 14:29 GMT+02:00 Ramiro Saenz <notifications@github.com>:
