### ISSUE TITLE
Clicking on a desktop notification doesn't do anything

### ISSUE THREAD

**Issue by notnsane** [saenzramiro/rambox#207]
### Steps to reproduce

1. Enable Telegram desktop notifications (doesn't matter if preview or sound are active)
2. Minimize Rambox and get a message
3. A notification popup will appear in the lower right corner of the screen, click on it

Notes: No idea if this happens with other services also, so it might be a Global issue with notifications. Will report if I see something new.

Edit: I can confirm that **Discord** notifications also do nothing when clicked.

### Expected behavior

Rambox restores the window and opens the conversation, cursor ready to write a reply

### Actual behavior

Nothing happens

### ENVIRONMENT

> Rambox: v0.4.1

> OS: Windows 10 Anniversary Update

> Arch: x64

**Comment by saenzramiro** [comment]
Duplicate #34
