### ISSUE TITLE
IDIOMAS.

### ISSUE THREAD

**Issue by petrolero11** [saenzramiro/rambox#208]
Buenas noches amigos de Rambox,

     Les escribo porque deseo hacer una sugerencia.  Este plataforma es bien útil ya qe tenemos las aplicaciones que usamos con más frecuencia en un sólo sitio a manera de tablero de control pero sería más atractiva si se pudiera visualizar en el idioma nativo del usuario en este caso el español y cómo el creador de ésta novedosa plataforma es de Argentina no estaría de más que colocaran el idioma español y visualizar todo en éste idima.  Gracias.

Saludos,

Igor P.

-
> Rambox 0.4.1
> Electron 1.3.1
> win32 x64 6.1.7601

**Comment by saenzramiro** [comment]
Ya estoy trabajando en esto, por lo que en las próximas versiones ya contaremos con esta funcionalidad.

Duplicate #57
