### ISSUE TITLE
[Hootsuite] Add new service

### ISSUE THREAD

**Issue by notnsane** [saenzramiro/rambox#209]
(Sorry about the issues spam)

https://hootsuite.com/

I tried to add Hootsuite as a custom service, but it didn't work. It just reloaded the page after I used my login credentials. 

I didn't use either Facebook, Twitter or Google logins, just my Hootsuite account.

**Comment by saenzramiro** [comment]
(No problem @notnsane, for me is very important people participate with issues and new features)

Ok, I will take a look and add it for next release.
