### ISSUE TITLE
Application name too long in Windows 10

### ISSUE THREAD

**Issue by notnsane** [saenzramiro/rambox#210]
Just a very small cosmetic issue, it seems that the Windows 10's Task Manager pulls the Description as the App name. 

Screenshots:

![unvkml8](https://cloud.githubusercontent.com/assets/7162375/17504734/f3a25548-5dd1-11e6-91cb-1329138af34b.png)

![sr4abzr](https://cloud.githubusercontent.com/assets/7162375/17504748/0991b9de-5dd2-11e6-8d96-74c243bd4c55.png)

A correctly displayed app: 

![3lumlek](https://cloud.githubusercontent.com/assets/7162375/17504757/1da1691a-5dd2-11e6-8a22-7b6f9c1aeadf.png)

**Comment by saenzramiro** [comment]
Nice! Ok, I will fix this for next release.
