### ISSUE TITLE
[UX] Add badge counter on the tray icon

### ISSUE THREAD

**Issue by thomas-gaudin** [saenzramiro/rambox#211]
Right now, if I see a notification and I don't look at Rambox immediately, I often forget it and don't check it before long. The tray icon could show an indicator with the sum of all unread messages.

*Version:* 0.4.1
*Platform:* linux (x64) (Ubuntu Unity 16.04)
*Electron:* 1.3.1
*Chromium:* 52.0.2743.82
*Node:* 6.3.0

**Comment by saenzramiro** [comment]
Sure, I was thinking about doing this for next release. :wink:

**Comment by saenzramiro** [comment]
Merge with #229
