### ISSUE TITLE
La opcion de inciar automaticamente al arrancar esta bugeada

### ISSUE THREAD

**Issue by SBI-boy** [saenzramiro/rambox#212]
Dicha opcion simplemente a veces funciona a veces no, se resetea, de lo que la pongo para no iniciar la aplicacion, a veces si cumple, a veces no, y se inicia de cualquier forma con la opcion activada.

-
> Rambox 0.4.1
> Electron 1.3.1
> win32 x64 10.0.14393

**Comment by saenzramiro** [comment]
Duplicate #201 #163 

¡Gracias!
