### ISSUE TITLE
Allow zooming with [Ctrl +], [Ctrl -], [Ctrl Mousewheel] and the View menu

### ISSUE THREAD

**Issue by flying-sheep** [saenzramiro/rambox#217]
As stated in #114, currently only zooming via <kbd>Ctrl</kbd><kbd>Numpad&nbsp;+</kbd> and <kbd>Ctrl</kbd><kbd>Numpad&nbsp;-</kbd> works, but browsers also allow to use <kbd>Ctrl</kbd><kbd>+</kbd> and <kbd>Ctrl</kbd><kbd>-</kbd>, as well as <kbd>Ctrl</kbd><kbd>Mousewheel</kbd>

It would be also nice (if only for discoverability) to include Menu entries in the “View” menu

**Comment by franciscoluiz** [comment]
+1
