### ISSUE TITLE
[New service request] Add Zimbra

### ISSUE THREAD

**Issue by flying-sheep** [saenzramiro/rambox#218]
Hi, I figured out a hacky way to make Zimbra work: https://gist.github.com/flying-sheep/bfe349416496dd0cb876938b1e4f57ed

To eliminate the hacks, we need to get rid of the “2” (although it might always be the inbox folder), and maybe access the app instance differently from `_zimbraMail`

**Comment by saenzramiro** [comment]
Related to #175 

Thank you! I will take a look and add it for next release.

**Comment by flying-sheep** [comment]
oh damn, i should have searched. sorry!

**Comment by flying-sheep** [comment]
check out  saenzramiro/rambox-services-contrib#4

**Comment by saenzramiro** [comment]
Thank you!

**Comment by flying-sheep** [comment]
do you plan to add the services from there to rambox eventually?

if not, you’ll have to add an UI that can search and install them automatically. it’s too much of a hassle elsewise

**Comment by saenzramiro** [comment]
@flying-sheep I have an idea. :wink:
