### ISSUE TITLE
Impossible to delete one of my service

### ISSUE THREAD

**Issue by AlanChauchet** [saenzramiro/rambox#219]
Hi, I am desperately trying to remove Skype from my services but everytime I clik on the remove button and select 'Yes' some crazy things happens. For exemple, my services are reordered in a strange way or my gmail got his notifications turned off. But Skype is still here.

-
> Rambox 0.4.1
> Electron 1.3.1
> win32 x64 10.0.14393

**Comment by saenzramiro** [comment]
If you are logged in Rambox with a Rambox account, try to logout and relogin.

If not, you will need to clear your localStorage. To do this, you can go to "View -> Toggle Developer Tools" and in Console tab, execute this:

`localStorage.clear();`

Then, close Rambox and open it again.

**Comment by AlanChauchet** [comment]
Thanks, it worked

**Comment by marcobazzani** [comment]
what the actual fuck ?
