### ISSUE TITLE
VK.com

### ISSUE THREAD

**Issue by CB9TOIIIA** [saenzramiro/rambox#22]
Can you please add VK.com ?

**Comment by saenzramiro** [comment]
Sure! I will add it for the next release.

For now, you can add it manually. See here: https://github.com/saenzramiro/rambox/wiki/Add-a-Custom-Service

**Comment by CB9TOIIIA** [comment]
I will wait.  :+1:  and transfer from Franz

**Comment by CB9TOIIIA** [comment]
How i can subscribe on your newsletter? about update new service's and etc...

**Comment by saenzramiro** [comment]
I didn't add a newsletter option yet. I will think about it and let you know.

**Comment by saenzramiro** [comment]
I made a research and VK is a Social Network, not a messaging or emailing app. So I will not add it natively in the Service Lists, but you can still add it manually.

**Comment by justpusher** [comment]
VK is social network, but it indeed has an inbuilt messenger page. Franz allows adding VK, and that's very convenient to be notified for new messages. 
Please consider adding VK, too. 

P.S. is there a way to add a custom service to get notifiied about new messages?

**Comment by CB9TOIIIA** [comment]
@justpusher I supported the author of six months ago, and together we fixed a bugs and made the code to display messages:

``` 
function checkUnread(){updateBadge(parseInt(document.getElementById("l_msg").innerText.replace(/\D+/g,"")))}function updateBadge(e){e>=1?document.title="("+e+") "+originalTitle:document.title=originalTitle}var originalTitle=document.title;setInterval(checkUnread,3000);
```

![273020](https://cloud.githubusercontent.com/assets/1074710/22378659/676ec782-e4c7-11e6-8be5-701091b1c741.png)

**Comment by saenzramiro** [comment]
I will plan to add VK in next release.

**Comment by CB9TOIIIA** [comment]
![025618](https://cloud.githubusercontent.com/assets/1074710/22554402/f0ea76ac-e970-11e6-9fe9-88e48ee80693.png)

**Comment by 385olt** [comment]
made the messenger full screen, kinda like Facebook Messenger.

`function remove(id) { var elm = document.getElementById(id);elm.parentNode.removeChild(elm); }
remove("side_bar");remove("page_header_cont");remove("header_wrap2");remove("wrap_between");
var new_width = Number(document.getElementsByClassName("scroll_fix")[0].getAttribute("style").match(/\d+/)[0]) + 16;
document.getElementsByClassName("body_im")[0].setAttribute("style", "width: " + new_width + "px !important;");
document.getElementById("page_wrap").setAttribute("style", "width: " + new_width + "px !important;");
document.getElementsByClassName("scroll_fix")[0].setAttribute("style", "width: " + new_width + "px;");
document.getElementById("page_layout").setAttribute("style", "width: " + new_width + "px !important; padding: 0px !important; margin:0px !important");
document.getElementById("page_body").setAttribute("style", "width: " + new_width + "px !important; padding: 0px !important; margin:0px !important");
document.getElementsByClassName("im-page")[0].setAttribute("style", "height: calc(100vh - 1px); width: " + new_width + "px !important; padding: 0px !important;");
document.getElementsByClassName("im-page--chat-body-abs")[0].removeAttribute("style");
document.getElementsByClassName("im-chat-input--textarea")[0].setAttribute("style", "width: calc(100vw - 450px);");
document.getElementsByClassName("im-chat-input--txt-wrap")[0].setAttribute("style", "width: calc(100vw - 450px);");`

Tried to make it work for all screens, but not sure if I succeed.
