### ISSUE TITLE
Cookies problem when login with Facebook

### ISSUE THREAD

**Issue by CrazyGentleMan** [saenzramiro/rambox#224]
When I'm trying to login with Facebook, it request to enable Cookies to be able to do so.

Log in to use your Facebook account with Rambox.
Cookies Required
Cookies are not enabled on your browser. Please enable cookies in your browser preferences to continue.

-
> Rambox 0.4.1
> Electron 1.3.1
> win32 ia32 10.0.10586

**Comment by saenzramiro** [comment]
I tested in v0.4.1 and works OK for me. Also tested in the new version coming next and works.

I think is a problem with x32 version of Rambox. If you have a x64 architecture, please download Rambox for x64.

**Comment by AlexeyKot** [comment]
Have the same issue.
Downloaded latest x64 AppImage on my Ubuntu 16.10

**Comment by kwadwoadu** [comment]
Experiencing the same issue, macOS, rambox v 0.4.5
