### ISSUE TITLE
Blue Window

### ISSUE THREAD

**Issue by g0ttferd0m** [saenzramiro/rambox#225]
Hello,
All is on the [screenshot](http://imgur.com/aqo7cN2)
I've kind of blue screen and reload does nothing.
I've just followed the steps to install.
Thx for help :)

## 

> Electron 1.3.2
> Electron 1.3.2
> linux x64 4.6.0-kali1-amd64

**Comment by g0ttferd0m** [comment]
Yes, 
I've built it directly from the source. I've installed all dependencies needed, I'd no error while compiling.

**Comment by saenzramiro** [comment]
You have to the [env.js](https://github.com/saenzramiro/rambox/blob/master/env.js) file. Then check the console for errors to debug.

**Comment by g0ttferd0m** [comment]
Ok I'll do that. I'll post error log.
