### ISSUE TITLE
Adding a shortcut to switch between services

### ISSUE THREAD

**Issue by Mumrau** [saenzramiro/rambox#228]
Hello team, 
You made a great work that works well!
The only thing I'd like to have, is a shortcut to switch between tabs, I may have missed the feature but I looked into and I saw nothing like this.
That would be great!

**Comment by bascht** [comment]
@Mumrau Does switching with `<ctrl>+<tab>` or `<ctrl>+tab-number` work for you? Those shortcuts should be mapped by default.

**Comment by Mumrau** [comment]
Ho it works! Sorry about this, I didn't find anything...
Is there a way to change the shortcut?

**Comment by bascht** [comment]
I don't think you can change the shortcuts. They 're [bound by the app on startup](https://github.com/saenzramiro/rambox/blob/master/app/Application.js#L40-L65).

**Comment by Mumrau** [comment]
Thanks you for this!
