### ISSUE TITLE
Autostart broken on Mac

### ISSUE THREAD

**Issue by svoop** [saenzramiro/rambox#232]
The autostart feature is broken on Mac. Rambox re-installs a bash script as a login item when it is started manually, even if the "start automatically on system startup" preference has been unticked and the login script removed beforehand. In other words: It's currently impossible to disable autostart.

### Steps to reproduce

1. Launch Rambox 
2. Uncheck Rambox -> Preferences -> Start automatically on system startup
3. Optional: Delete Rambox login item
4. Quit Rambox
5. Launch Rambox
6. Quit Rambox
7. Reboot

### Expected behavior

Rambox shouldn't autostart.

### Actual behavior

Rambox does autostart.

### ENVIRONMENT

> Rambox: v0.4.1

> OS: 10.11.6

> Arch: x64

**Comment by dbpolito** [comment]
this is bugging me a lot too =( also the autostart on mac is kind of weird, it launches a terminal instead of just opening the app.

**Comment by saenzramiro** [comment]
@dbpolito Did you clone the repo and build Rambox in your Mac? Because maybe the Rambox dev app is trying to open at startup.

**Comment by dbpolito** [comment]
No downloaded from site

**Comment by onedrawingperday** [comment]
The same thing happens on Ubuntu Gnome 16.04. The startup script reinstalls itself in the Autostart folder every time I open Rambox.

I downloaded the rambox-0.4.1-x64.zip

**Comment by dmetzler1988** [comment]
have the same issue on mac (downloaded dmg from website).
i can reproduce it by:

> 1. Launch Rambox
> 2. Uncheck Rambox -> Preferences -> Start automatically on system startup
> 7. Reboot

**Comment by svoop** [comment]
@saenzramiro Very cool, thanks for this fix! Can't wait for a new release being cut!
