### ISSUE TITLE
Need to login for gitter everytime rambox starts

### ISSUE THREAD

**Issue by gossi** [saenzramiro/rambox#234]
### Steps to reproduce

1. Add Gitter support
2. Login with github
3. Quit Rambox
4. Start Rambox
5. Select Gitter tab
6. Login with github

### Expected behavior

Login with github once, keep it persistent across programm starts

### Actual behavior

Login with github everytime rambox starts.

### ENVIRONMENT

> Rambox: v0.4.1

> OS: macOS

> Arch: x64

**Comment by saenzramiro** [comment]
This is weird. I fixed this in 0.4.1.

Only with Gitter? Did you download the zip file or DMG file for Mac?

**Comment by billymcintosh** [comment]
Getting a similar issue, but with HipChat. 

> Version: 0.4.1
> Platform: linux (x64)
> Electron: 1.3.1
> Chromium: 52.0.2743.82
> Node: 6.3.0

**Comment by gossi** [comment]
I was on v 0.3.0 before. I installed 0.4.1 using the .dmg file. I overwrote my old version. Maybe there are still some old configs from v0.3.0 in action? I only use Gitter as that kind of OAuth service, so cannot confirm there are other services as well that happen to have the same problem.

**Comment by saenzramiro** [comment]
To be sure, it will be great if you can make a fresh install removing all files from Rambox and install it again.

**Comment by gossi** [comment]
Sure. Can you let me know, where config files are stored (on a Mac) so I delete them as well?

**Comment by saenzramiro** [comment]
In my case, I use an app for uninstalling apps. [Read more here](http://lifehacker.com/5828738/the-best-app-uninstaller-for-mac)...

**Comment by gossi** [comment]
I am using this one as well. So I did and freshly installed Rambox again. This time it worked. So persistent OAuth login across programm starts. Thanks a lot.
