### ISSUE TITLE
"Show in taskbar = off" equals problems

### ISSUE THREAD

**Issue by exec228** [saenzramiro/rambox#235]
0) Windows 8.1 x64, https://getrambox.herokuapp.com/download/win32_x64?filetype=zip
Version: 0.4.1
Platform: win32 (x64)
Electron: 1.3.1
Chromium: 52.0.2743.82
Node: 6.3.0

1) rambox_cfg.json:
{"always_on_top":0,"hide_menu_bar":0,"skip_taskbar":1,"auto_launch":1,"keep_in_taskbar_on_close":0,"start_minimized":1}

2) show window via tray icon. Then alt-tab to any other window.

PROBLEM:
• you cannot open rambox via double clicking tray icon
• you cannot find rambox via alt-tab.
The only way works is right-click on tray icon, press "Show/Hide", and then again right-click on tray icon and again press "Show/Hide".

EXPECTED:
• you can open rambox window via double clicking tray icon
• you can find rambox via alt-tab (may be optional, if it is really impossible)
• when the window is not focused, "Show/Hide" definitely shows the window. It should not require me to "hide" it first.

Thank you
exec228@gmail.com

## 

> Rambox 0.4.1
> Electron 1.3.1
> win32 ia32 6.3.9600

**Comment by sylvainar** [comment]
I agree with the fact that it should open with a double click.

But I'm not sure that Rambox should be accessible via alt-tab if it's hidden. That precisely why I hide Rambox, so it doesn't appear when I'm browsing alt-tab.

**Comment by exec228** [comment]
Optional? ;-)

I'd prefer single click over double click, actually.

**Comment by DellDor** [comment]
I have the same problem in **Debian**.
I have to minimize all others open windows to watch Rambox, and it never doesn't appear in Alt+Tab like a normal program.

Please, add GNU or Linux label too...

Tengo el mismo problema en Debian, y no como una posible mejora; simplemente es **desesperante** tener que minimizar o restaurar todas las demás ventanas para llegar a Rambox, sobre todo cuando estoy usando solo el teclado. deja de ser útil Alt+Tab.
¿Abrá algo que tengo mal configurado?

Gracias de antemano.
Thanks in advance...


Debian Testing (Sparky Linux)
Version: 0.4.4
Platform: linux (ia32)
Electron: 1.4.1
Chromium: 53.0.2785.113
Node: 6.5.0

**Comment by LTAcosta** [comment]
Can this be closed? Double clicking the tray icon appears to be working now.

Windows 10 (1607)
Version: 0.4.5
Platform: win32 (x64)
Electron: 1.4.7
Chromium: 53.0.2785.143
Node: 6.5.0

**Comment by exec228** [comment]
> Can this be closed? Double clicking the tray icon appears to be working now.
Cannot reproduce the fix.
I want no Rambox in task bar. I cannot get rid of it.

**Comment by saenzramiro** [comment]
Please update to latest version and confirm if this issue remains.

**Comment by sylvainar** [comment]
MAAAAN this update is awesome!

Well I don't remember, what's the expected behavior already ?

I'm on Ubuntu 16.04. A double click on Rambox icon doesn't open the window, neither it's open or closed. Whatever, it could wait the next update :wink: 
I truly love the way you managed certification issues !
