### ISSUE TITLE
Not Desktop-Notifications for Slack

### ISSUE THREAD

**Issue by JohaWeber** [saenzramiro/rambox#236]
No desktop-notifications or a switch to a red icon in the taskbar on new messages shown, although the "show notifications"-option is checked. Fresh or clean install does not help. Does not only apply to a special configurated channel in slack.

-
> Rambox 0.4.1
> Electron 1.3.1
> win32 ia32 10.0.14393

**Comment by saenzramiro** [comment]
Did you try with double-click in Slack tab and select Reload option?

Seems like is not injecting the JS code to detect new messages.

**Comment by saenzramiro** [comment]
BTW, desktop notifications needs to be enabled in Slack configuration. Go to Preferences -> Notifications and configure there. See that you have a "Send test notification" to check.

**Comment by JohaWeber** [comment]
All the stuff you mentioned were already activated and the manual test-notification was already tested and worked. But I found the fault: You have to uncheck "Mute all Sounds" in Slack - this also seem to affect the visual notification for messages. So no fault of Rambox (thanks for help!) but rather a very stupid hidden setting (in my opinion).

**Comment by MRayp** [comment]
if you are using windows 10, go to Settings > Notifications & actions, Get notifications from these senders and make sure Slack is turned on.
