### ISSUE TITLE
Optional BetterTweetDeck loading

### ISSUE THREAD

**Issue by Luzifer** [saenzramiro/rambox#237]
I'm not sure whether it's possible but what I'd like to see is an option to load [BetterTweetDeck](https://github.com/eramdam/BetterTweetDeck) into the TweetDeck tab in order to have for example the preview images for several services.

**Comment by saenzramiro** [comment]
For now, Electron don't allow to install chrome extensions.

I think they plan to allow it, if so there are a lot of things we can add to Rambox. :wink:
