### ISSUE TITLE
how delete a rambox gmail account

### ISSUE THREAD

**Issue by Djow89** [saenzramiro/rambox#239]
i want to syncronise 2 rambox together but i've associated the wrong gmail adress with one of them and when i want to relogin in gmail he keep the wrong address , my question is how to remove this .

-
> Rambox 0.4.1
> Electron 1.3.1
> win32 x64 10.0.14393

**Comment by saenzramiro** [comment]
You have an option to removed the remembered account and use another one. When you click in Login, it will show your gmail account, and at the bottom you have an option to delete that account.
