### ISSUE TITLE
Hipchat service should be started on the chat page

### ISSUE THREAD

**Issue by Tehem** [saenzramiro/rambox#241]
Hi,
Hipchat service is started on the hipchat home page : 
https://xxxxx.hipchat.com/home

Where it would be more convenient to directly start on the  chat 'web app' page :
https://xxxxx.hipchat.com/chat

Thanks!

-
> Rambox 0.4.1
> Electron 1.3.1
> linux x64 3.16.0-4-amd64

**Comment by saenzramiro** [comment]
Thank you!
