### ISSUE TITLE
Icon in Taskbar broken

### ISSUE THREAD

**Issue by Thalonius** [saenzramiro/rambox#245]
After a few days working perfectly the taskbar-icon vanished and left only a white icon (looking like this: http://www.fancyicons.com/free-icons/112/must-have/png/256/new_256.png ) .

The icon in the tray-area still works.
A restart of rambox or the computer doesn't help.

-
> Rambox 0.4.1
> Electron 1.3.1
> win32 ia32 6.3.9600

**Comment by saenzramiro** [comment]
Similar with #170 

I will fix this in next release. For now, you can check the desktop shortcut of Rambox to see if the icon is ok in the properties. If no, the path needs to be like this:

> %USERPROFILE%\AppData\Local\rambox\app-0.4.1\Rambox.exe

If not working, try to uninstall Rambox, clean the registry and install it again. I saw that you installed the 32bits arch, but please install the 64bits if you have a 64bits arch.

**Comment by Thalonius** [comment]
Hi,

thanks for the fast response.
I’ve checked the shortcuts and was able to solve the problem there.

I beleive the following happened:
My first Rambox-Version was 0.4.0 and I’ve updated to 0.4.1 some days ago.
Now there are 2 Links to Rambox:
%USERPROFILE%\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Rambox
%USERPROFILE%\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Ramiro Saenz

The working directory and picture-path of the first shortcut still pointed to this (non-existing) folder:
%USERPROFILE%\AppData\Local\Rambox\app-0.4.0

The second pointed correctly to
%USERPROFILE%\AppData\Local\Rambox\app-0.4.1

After I’ve updated the paths in the first shortcut I’ve got my icon again 😊

Thank you!
