### ISSUE TITLE
Howto add new service?

### ISSUE THREAD

**Issue by draptik** [saenzramiro/rambox#25]
What is the recommended way of adding a new service? Are there instructions somewhere I missed?

**Comment by saenzramiro** [comment]
I just created a new Wiki to help adding a Custom Service.

https://github.com/saenzramiro/rambox/wiki/Add-a-Custom-Service

To add a new service listed in the app for all users, you can suggest it here and I will add it later.

**Comment by draptik** [comment]
Thanks!
