### ISSUE TITLE
change icon size in volume mixed

### ISSUE THREAD

**Issue by Djow89** [saenzramiro/rambox#251]
![son](https://cloud.githubusercontent.com/assets/19527573/17833896/272f8220-672b-11e6-99e4-3faf7d4bf4d9.png) can you change the size because i can't change the volume

-
> Rambox 0.4.1
> Electron 1.3.1
> win32 x64 10.0.14393

**Comment by saenzramiro** [comment]
Duplicate #46 

I will see this bug in next release.
