### ISSUE TITLE
Wire - remember password?

### ISSUE THREAD

**Issue by ElvisPresly** [saenzramiro/rambox#253]
Hi. There is an opportunity to make that the password remained for "Wire"?

## 

> Rambox 0.4.1
> Electron 1.3.1
> linux x64 4.6.0-1-amd64

**Comment by notnsane** [comment]
I can confirm that latest Rambox + Wire can't remember my username and password, which is super annoying. 
Luckily I don't restart my PC often, so I don't have to start Rambox a lot.

**Comment by ElvisPresly** [comment]
The problem is still not solved, the tick has appeared to "remember password", but at restart all the same it is necessary to be authorized again

**Comment by saenzramiro** [comment]
Did you try removing the service and add it again? For me works ok on Windows 10 x64.

**Comment by ElvisPresly** [comment]
yes, so now works, thanks

**Comment by notnsane** [comment]
This issue is happening again @saenzramiro 

1. Login and tick "remember me"
2. Disable the service
3. Enable the service
4. You'll have to login again

**Comment by saenzramiro** [comment]
I will take a look again.

**Comment by makloda** [comment]
Doesn't work for me neither. Very annoying.

**Comment by saenzramiro** [comment]
Investigating this bug, for me works OK.

Are you still having this issue?

**Comment by notnsane** [comment]
Personally I'm not having this issue anymore, no. I'd been restarting my PC a million times these days and I was always logged in when I had to use Wire.

**Comment by saenzramiro** [comment]
Ok, so I will close it. Thanks.
