### ISSUE TITLE
issue with google 2 steps authentification

### ISSUE THREAD

**Issue by Nevax07** [saenzramiro/rambox#255]
when i try to sign in to my google account with the 2 step verification, for inbox and hangouts.
I got a white page, it was the same on "Franz" (another similar app to Rambox.

### Steps to reproduce

1. Go to Log in in Hangouts or Inbox
2. Type mail/password
3. White page

### Expected behavior

The page is displayed.

### Actual behavior

The page is loaded, when i move the cursor i can see it changes between the elements.

### ENVIRONMENT

Linux arch-obelix 4.7.2-1-ck #1 SMP PREEMPT Sat Aug 20 14:07:40 EDT 2016 x86_64 GNU/Linux

> Rambox: v0.4.1
Platform: linux (x64)
Electron: 1.3.1
Chromium: 52.0.2743.82
Node: 6.3.0

> OS: Arch Linux

> Arch: x64

**Comment by saenzramiro** [comment]
Seems to be an Electron bug. I will try to fix this for next release.
