### ISSUE TITLE
JavaScript-Error on numbers in window title

### ISSUE THREAD

**Issue by MrChick** [saenzramiro/rambox#257]
When opening an email containing an amazon order id in the title, rambox throws a javascript error.
Would probably happen on pretty much any email (or more exactly on any service) with some numbers in its title, I just happened to notice it on gmail with amazon.

seems like rambox is trying to parse the order id into the unread notifications count, which breaks for obvious reasons...

### Steps to reproduce

1. Open gmail
2. Open Mail with amazon order id (xxx-xxxxxx-xxxxxxx)
3. crash

### Expected behavior

no crash ;)

### Actual behavior

![unbenannt](https://cloud.githubusercontent.com/assets/706764/17888023/5e650f26-6929-11e6-82d6-cb0509275ae8.png)
![unbenannt](https://cloud.githubusercontent.com/assets/706764/17888250/645035c2-692a-11e6-88f5-2a4026782721.png)

### ENVIRONMENT

> Rambox: v0.4.1

> OS: Win10 Enterprise

> Arch: x64

**Comment by saenzramiro** [comment]
Related #51
