### ISSUE TITLE
To hide rambox_cfg.json (Linux)

### ISSUE THREAD

**Issue by ElvisPresly** [saenzramiro/rambox#259]
Hi
Debian testing Gnome 3.20
There can be a rambox_cfg.json file to hide or move to other place? Awfully irritates that it is in a root of the home folder. Thanks.

-
> Rambox 0.4.1
> Electron 1.3.1
> linux x64 4.6.0-1-amd64

![2016-08-23 21-49-45](https://cloud.githubusercontent.com/assets/18265958/17905404/8afb6d58-697b-11e6-8bac-e8c3480675e2.png)

**Comment by saenzramiro** [comment]
Duplicate #226
