### ISSUE TITLE
add yandex mail  [yandex.com/yandex.ru]  - mail.yandex.ru

### ISSUE THREAD

**Issue by CB9TOIIIA** [saenzramiro/rambox#260]
Please can you integrate mail - mail.yandex.ru  /  mail.yandex.com

**Comment by ElvisPresly** [comment]
You can be added Yandex mail manually

**Comment by CB9TOIIIA** [comment]
yep. I use this manually. But gmail - in stock / yahoo in stock. But popular Yandex - not.

**Comment by ElvisPresly** [comment]
@CB9TOIIIA may be done :) https://github.com/saenzramiro/rambox/pull/230

**Comment by saenzramiro** [comment]
It will be added in next release.
