### ISSUE TITLE
Support AOL/AIM

### ISSUE THREAD

**Issue by chuinker** [saenzramiro/rambox#261]
It's on the list of supported chat protocols, but I don't see how to add it.

**Comment by saenzramiro** [comment]
For now, you can add it as Custom Service. To know how to do it, [click here](https://github.com/saenzramiro/rambox/wiki/Add-a-Custom-Service).

I will add AIM in next release.

**Comment by chuinker** [comment]
Indeed, that works. Sorta. The ads the page displays are having certificate errors, but not sure that's something you can manage.

**Comment by saenzramiro** [comment]
Did you try to enable the option **Trust invalid authority certificates**?

**Comment by chuinker** [comment]
I did. Then I deleted and re-added it, and haven't used it enough since then to know if it's still occurring.

**Comment by saenzramiro** [comment]
Ok, so please report it here if still happens or not to see if I can add it in next release.

**Comment by chuinker** [comment]
Haven't seen it in a while, so I'm guessing it works.
