### ISSUE TITLE
Text area loses focus

### ISSUE THREAD

**Issue by forteller** [saenzramiro/rambox#262]
When you go back to Rambox the focus is lost from the text field you where using. This is very annoying.

### Steps to reproduce

1. Write in a text area
2. Alt-Tab out of Rambox then in again
3. Try to continue writing.

### Expected behavior

You should be able to just keep writing

### Actual behavior

Nothing happens because the focus has been lost. You have to move your hand to the mouse, click in the text field and then rewrite whatever you wrote while there was no focus on the text field.

### ENVIRONMENT

Ubuntu Gnome 16.04 x64 with the staging PPA.  Rambox 0.4.1

Thanks for a great application!

**Comment by saenzramiro** [comment]
Duplicate #180 

It will be fixed in next release. Thanks!
