### ISSUE TITLE
Preferences doens't save

### ISSUE THREAD

**Issue by Mumrau** [saenzramiro/rambox#267]
Hello,
The preferences of the application doens't save, I mean, when I restart the computer, they just didn't save.
When I'm talking about the preferences, I mean under Files > Preferences > Keep Rambox in Taskbar/Start minimized etc...
If someone has a fix, I'd take it gladly,
Thanks you already!
Regards

**Comment by saenzramiro** [comment]
Duplicate #201 

It will be fixed in next release.
