### ISSUE TITLE
Feature Request - Service: Signal

### ISSUE THREAD

**Issue by Stele77** [saenzramiro/rambox#268]
Hi!
Another highly popular service that is missing: Signal. Most likely still the best secured IM App today, much more to recommend then Telegram (Closed Source, no proven high Standart crypto but a closed source crypto). 

Problem is for adding it as custom service: It doesnt have a Web App, But chrome extension and desktop client. But it is open source, and APIs should be no problem to access AFAIK (I am no software dev!).
I hope this help!
Thanks
Steven

**Comment by saenzramiro** [comment]
Duplicate #26
