### ISSUE TITLE
[Idea] Lock on startup and time inactivity.

### ISSUE THREAD

**Issue by richardfrk** [saenzramiro/rambox#27]

**Comment by saenzramiro** [comment]
Yes, we can try to add this features but optionally. Because I think most users don't want that.

Thanks!

**Comment by richardfrk** [comment]
Nice!

**Comment by franciscoluiz** [comment]
of course that this feature must by optional!!! 

+1

**Comment by saenzramiro** [comment]
Lock on startup is done in v0.4.2. Let's separate and continue the inactivity feature in this issue #334 .
