### ISSUE TITLE
FR: Add Rainloop Webmail support

### ISSUE THREAD

**Issue by pztrn** [saenzramiro/rambox#270]
Please, add [Rainloop Webmail](http://www.rainloop.net/) support.

Working notifications checking code:

```
function checkUnread() {
    var e = document.getElementsByClassName("badge pull-right count");
    var t = 0;
    for(i = 0; i < e.length; i++) {
        if (parseInt(e[i].textContent.trim()) % 1 === 0 ) {
            t += parseInt(e[i].textContent.trim());
        }
    }
    updateBadge(t);
}

function updateBadge(e) {
    e >= 1 ? document.title = "(" + e + ") " + originalTitle : document.title = originalTitle
}
var originalTitle = document.title;
setInterval(checkUnread, 1000);
```

**Comment by saenzramiro** [comment]
Nice app!

I saw the demo app and I notice that they show the unread count in the titlebar so it should work without any code injection.

Why you suggest to add that code?

**Comment by pztrn** [comment]
In first place there was no counter, but yes, re-checked and it worked now, so code can be ignored. But anyway see this app as supported in already big list of apps will be great :)

**Comment by pztrn** [comment]
Correction: re-checked one more time on different mailbox (hosted on yandex.ru) - and there was no notifications and no counter in titlebar. After re-injecting code above counter appeared.

**Comment by pztrn** [comment]
Found bug in 0.4.1 - can't switch accounts, it constantly returns to first one. Example: I log in as mail1@example.com, add mail2@example.com, choosing mail2@example.com will redirect me back to mail1@example.com. Works flawlessly in browser (tested Firefox and Chromium).

**Comment by saenzramiro** [comment]
Ok, thank you.

So I will add the code injections because we cannot depend on the mail service used. And about switching accounts, I will test it and see if I can do something to fix it. One solution for now is to add two custom services for Rainloop for each account.
