### ISSUE TITLE
In Windows task manager the app description is shown rather than name

### ISSUE THREAD

**Issue by crash1989** [saenzramiro/rambox#271]
### Steps to reproduce

1.  Open Rambox
2.  Open Task Manager (Ctrl + Shift + Esc)
3. Find the processes related to Rambox

### Expected behavior
It should show up as Rambox . A plus could be to show the task for each process like 
Rambox- Inbox, Rambox - Outlook

### Actual behavior
The app is named as 'Free and Open Source messaging and emailing app that combines common web applications into one' which is the app's description not the name

### ENVIRONMENT

> Rambox: v0.4.1

> OS: Windows 10 64 bit Build 1607

![sketch](https://cloud.githubusercontent.com/assets/11497412/18031696/ece8f156-6cba-11e6-8faa-ac4ba306812b.png)

**Comment by saenzramiro** [comment]
Duplicate #210
