### ISSUE TITLE
Unable to switch team in slack

### ISSUE THREAD

**Issue by mathroule** [saenzramiro/rambox#273]
### Steps to reproduce

1. Open Slack tab
2. Open Slack menu on left
3. Click on "Sign in to another team..."

### Expected behavior

Open Slack log in form for a team, then log in.
After log in, should display "Switch to <team>" in Slack menu into Rambox.

### Actual behavior

Open Slack log in form for a team in default browser (which is Chrome). Then log in on webpage and I'm only able to switch team in my browser not in Rambox.

### ENVIRONMENT

> Rambox:
Version: 0.4.1
Platform: win32 (x64)
Electron: 1.3.1
Chromium: 52.0.2743.82
Node: 6.3.0

> OS:
Windows 10 Pro
Version: 1607
Build: 14393.82

> Arch: x64

**Comment by TriiNoxYs** [comment]
To have multiple slack teams in rambox I just create 2 slacks services and have teamA in a tab and teamB in an other tab.

**Comment by mathroule** [comment]
Thanks! I didn't thought about this possibility ;)
