### ISSUE TITLE
Open Hangouts attachments on the same window.

### ISSUE THREAD

**Issue by MartSerra** [saenzramiro/rambox#277]
### Steps to reproduce

1. On Hangouts on Rambox (https://hangouts.google.com/)
2. When you receive an image, gif, file or video the click on chat opens default web browser selected by the system. 
3. If you not logged in on this browser you need to copy the link and open on the browser that you are logged in to see the resource (image, file or video link)

### Expected behavior

The best way to handle this is open on the same window on Rambox

### Another Solution

The other way is to put a script to select the default fallback browser to open external links. Override on custom Script.

### ENVIRONMENT

> Rambox: v0.4.1

> OS: darwin(x64) on OSX

> Arch: x64

**Comment by saenzramiro** [comment]
I can try to do the same for Skype. Open it inside Rambox.

https://github.com/saenzramiro/rambox/blob/master/electron/main.js#L216-L255

**Comment by MartSerra** [comment]
I didn't try Skype yet but I think it could be awesome open it directly on __Rambox__.
