### ISSUE TITLE
[Discord] Drag and Drop from browser to Discord isn't working

### ISSUE THREAD

**Issue by notnsane** [saenzramiro/rambox#279]
### Steps to reproduce

1. Open a web browser (tested with Edge, Chrome and Vivaldi)
2. Open an image
3. Try and drag and drop the image to a Discord channel

### Expected behavior

The drag and drop "wizard" appears and image can be uploaded directly

### Actual behavior

The 🚫 sign appears and image can't be uploaded, user has to drag and drop it on desktop first, then drag it to Rambox window

### ENVIRONMENT

> Rambox: v0.4.1
> OS: Windows 10
> Arch: x64

**Comment by saenzramiro** [comment]
I tested this and in any case works. I tried that on Chrome 53 and shows me that "disable" sign. This is a Discord behavior.
