### ISSUE TITLE
XDG_DATA_DIRS is missing when starting AppImage on Fedora 24

### ISSUE THREAD

**Issue by abrianceau** [saenzramiro/rambox#280]
Seems to be a similar issue than this one : https://github.com/electron-userland/electron-builder/issues/682

### Steps to reproduce

1. Download Rambox-0.4.1-x64.AppImage
2. chmod +x Rambox-0.4.1-x64.AppImage
3. ./Rambox-0.4.1-x64.AppImage

### Expected behavior

Launch Rambox AppImage

### Actual behavior

No launch with this error :
```
/tmp/.mount_zq9Niy
$XDG_DATA_DIRS is missing. Please run /tmp/.mount_zq9Niy/AppRun from within an AppImage.

```
### ENVIRONMENT

> Rambox: v0.4.1-x64

> OS: Fedora 24 - 4.6.6-300.fc24.x86_64

> Arch: x64

**Comment by delphiki** [comment]
I can confirm, same issue with Fedora 24.

**Comment by saenzramiro** [comment]
Ok, I will take a look ASAP.

**Comment by probonopd** [comment]
Should be solved in the latest electron-builder.

**Comment by delphiki** [comment]
In the meantime, you can still launch it with one of these commands:
```shell
export XDG_DATA_DIRS="/usr/local/share"
./Rambox-0.4.1-x64.AppImage
```
or  
```shell
XDG_DATA_DIRS="/usr/local/share" ./Rambox-0.4.1-x64.AppImage
```

**Comment by Pablohn26** [comment]
[Here](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html) is the specification made by freedesktop.org. It says: 

> If $XDG_DATA_DIRS is either not set or empty, a value equal to /usr/local/share/:/usr/share/ should be used.

I am not sure if this is a rambox bug or an AppImage bug.

**Comment by probonopd** [comment]
It is a bug in older versions of electron-builder. Should be solved in the latest electron-builder.
electron-userland/electron-builder#682

**Comment by delphiki** [comment]
AppImage of version 0.4.2 works great, thanks!
