### ISSUE TITLE
[Facebook.com / Facebook Page] Service Request

### ISSUE THREAD

**Issue by notnsane** [saenzramiro/rambox#281]
Unusual request, but I'd like to have Facebook.com as a new service, or at least try and bugfix the Desktop Notifications - currently they do not work, you click on the "Turn On" button but nothing happens.

I need to use Facebook.com because AFAIK Messenger doesn't get the private messages of Pages / Business and it's very important for me.

**Comment by NathanRightnour** [comment]
+1 - I'm surprised this isn't available. Is this possible?

**Comment by saenzramiro** [comment]
I will add Facebook Messenger for Pages in a future release. For now, you can follow this configuration to add it as a [Custom Service](https://github.com/saenzramiro/rambox/wiki/Add-a-Custom-Service):

https://github.com/saenzramiro/rambox-services-contrib/issues/14

**Comment by Foggalong** [comment]
@saenzramiro I think you've set up the service using the legacy URL rather than the most recent version of pages:

* Old - https://www.facebook.com/caos.manchester/messages
* New - https://www.facebook.com/caos.manchester/inbox

**Comment by saenzramiro** [comment]
@Foggalong Yes, I will change it in next release.

**Comment by Foggalong** [comment]
@saenzramiro New release dropped but this wasn't fixed. Can this issue be reopened? :confused:

**Comment by Foggalong** [comment]
@saenzramiro Noticed there'd not been any progress on this so thought I'd make a quick PR (#1078) to fix it. Let me know if it's alright :smile:

**Comment by saenzramiro** [comment]
Let's continue this in your PR.
