### ISSUE TITLE
refresh only one tab. 

### ISSUE THREAD

**Issue by franciscoluiz** [saenzramiro/rambox#284]
### Steps to reproduce

1. Add your favs services.
2. Go on menu "View" and choose "Reload"
3. All tabs/services are reloaded

### Expected behavior

I think there should be an option to reload all the tabs/services, but also an option to reload ONLY AND ONLY the active tab.

### Actual behavior

the Reload option reloads the entire window with all tabs... I think it is unnecessary.

### ENVIRONMENT

Rambox: 0.4.1 win32 x64
Electron 1.3.1 
Chromium 52.0.2743.82
Node 6.3.0,
OS: Windows 8.1 x64

**Comment by saenzramiro** [comment]
You can do it by double click in the tab of the services and select Reload. :wink:

**Comment by franciscoluiz** [comment]
oW. thank you. sorry for the inconvenience!

**Comment by AmShaegar13** [comment]
Actually, I had to right click but this helped. Thanks! Could be different on a Linux system.

**Comment by saenzramiro** [comment]
Before was double click, now is right click. :wink:
