### ISSUE TITLE
Enable/disable specific services.

### ISSUE THREAD

**Issue by franciscoluiz** [saenzramiro/rambox#285]
I would also suggest an option to enable or disable specific service, without having to remove it and add it every time I want to turn it off.

### ENVIRONMENT

Rambox: 0.4.1 win32 x64
Electron 1.3.1 
Chromium 52.0.2743.82
Node 6.3.0,
OS: Windows 8.1 x64

**Comment by saenzramiro** [comment]
And why you want to turn it off? If is because you want to disconnect it for a while, there is an option to **Go Offline** by double click in the service tab.

**Comment by franciscoluiz** [comment]
cool. sorry again.

**Comment by saenzramiro** [comment]
I will replace Go Offline option to Enable/Disable services by removing the webview to release memory.

**Comment by saenzramiro** [comment]
I will replace Go Offline option to Enable/Disable services by removing the webview to release memory.
