### ISSUE TITLE
Troubles on adding new tab

### ISSUE THREAD

**Issue by flydze** [saenzramiro/rambox#286]
When I add a new tab, next tab gets the same name and on the main page changes its icon to the icon of the service I added.
Also, some icons change their position from one side to another and moreover sometimes get duplicated.
I managed to reproduce it many times on adding Slack, Telegram and Inbox.
See the [screenshot](http://flydze.tumblr.com/private/image/149793470643/tumblr_octw8alnJ21v07sbl)

-
> Rambox 0.4.1
> Electron 1.3.1
> win32 ia32 10.0.10586

**Comment by saenzramiro** [comment]
Are you logged in using a Rambox account to sync your services?

**Comment by flydze** [comment]
No, I use gmail account to sync the services.
I tried to logout and login again. This time, the added services appeared fine except one Inbox account that moved from the right side to the left side and lost its icon. Also it is not possible to access its configuration. See the [screenshot](http://flydze.tumblr.com/private/image/149795480098/tumblr_octzcp5Tpo1v07sbl)

Regarding the 32-bit version.
Actually, I use Win10x64. The latest Rambox version was installed through auto update, so I'm a bit surprised I have the 32-bit version of the application.
I will try to uninstall it and install the x64 version from the web site to see if it helps somehow.

**Comment by flydze** [comment]
Installed the x64 version.
The problem shown on the latest screenshot is still there.
Below is what About Rambox shows me.

Version: 0.4.1
Platform: win32 (x64)
Electron: 1.3.1
Chromium: 52.0.2743.82
Node: 6.3.0

BTW, I didn't have these problems when I installed and configured the application on Ubuntu 16.04 x64 couple of days ago.

**Comment by saenzramiro** [comment]
Yes, I know there are some bugs regarding with synchronization. Maybe try to remove that service and add it again.

The update had a problem with the service for autoUpdate and provide 32bits to 64bits users. That's why I asked you. It will be great to move to 64bits.

**Comment by flydze** [comment]
I removed the service in trouble and added it again. It appeared fine on the right side and seems to work correctly.
But then I tried to remove the Slack service I added before in order to try to reproduce the issue.
As the result, the Slack tab disappeared together with the Telegram tab that was next to it. At the same time, on the main tab both services are still present. See the [screenshot](http://flydze.tumblr.com/private/image/149795968083/tumblr_ocu03i6Rhm1v07sbl)

I tried to logout and the application got hanging out moving the progress bar. See another [screenshot](https://67.media.tumblr.com/332769cd5c525ddaa0a87d79833d6632/tumblr_ocu0epHZvQ1v07sblo1_540.png)

I closed the application through the tray icon menu without troubles.
On starting it again, I appeared logged out with the following set of services: [screenshot](https://66.media.tumblr.com/4ba38db53a5e4c6de309929686a7d5b2/tumblr_ocu0kkCVJy1v07sblo1_540.png)

On logging I was asked to confirm to apply configuration from the server and all services appeared fine.
On adding the Slack service again I have got the original problem.

**Comment by flydze** [comment]
Just noticed that during all these manipulations disappeared my Gitter account (it was the first on the left side)

**Comment by saenzramiro** [comment]
Yes, when start working bad with a synchronization, it will do bad things! I suggest to start over.

Remove all services from your account, logout, clear the localStorage, relaunch Rambox, login and start adding services.

Sorry for this inconvenience!

**Comment by flydze** [comment]
I should say the x64 version seems to be more stable.
Without cleaning everything it seemed to correct everything by itself after I added the Gitter account.

**Comment by saenzramiro** [comment]
I will close this issue then. I think I will do more stable the services settings local and cloud in a future version.
