### ISSUE TITLE
Waiting for font configuration

### ISSUE THREAD

**Issue by exec228** [saenzramiro/rambox#288]
![screenshot_1](https://cloud.githubusercontent.com/assets/275328/18179268/77cc174e-70a3-11e6-978f-98cbe5daee70.png)

Should I await for font configuration?
I'd prefer safe web-font from Microsoft font-pack, tuned for raster screens.
I hate ClearType and modern blurry fonts, so I have ClearType or whatever aliasing switched off. I suppose that there are some quantity of users that have it turned off as well.
Thank you!

-
> Rambox 0.4.1
> Electron 1.3.1
> win32 x64 6.3.9600

**Comment by exec228** [comment]
Btw, you use html renderer, some of existing ones. From Mozilla or Google. Their browsers can have fonts forcibly overridden.

**Comment by saenzramiro** [comment]
Related #168 

Let's continue this in #168.
