### ISSUE TITLE
Slect chat fragments for Ctrl-C (Ctrl-Insert)?

### ISSUE THREAD

**Issue by exec228** [saenzramiro/rambox#289]
### Steps to reproduce

1. Select text fragment of any message for Ctrl-C

### Expected behavior

Chat fragment is selected, Ctrl-Ins available.

### Actual behavior

Fragments cannot be selected.

### ENVIRONMENT

> Rambox: v0.4.1

> OS: Windows 8.1 x64

> Arch: x64 or ia32? Rambox-0.4.1-x64-win.zip
Version: 0.4.1
Platform: win32 (x64)
Electron: 1.3.1
Chromium: 52.0.2743.82
Node: 6.3.0

**Comment by saenzramiro** [comment]
Sorry but I don't understand the problem.

Maybe it will helps a lot if you can record a video for this.

**Comment by exec228** [comment]
Can I propose TeamViewer?
Skype: killer.crayon, GTalk: exec228@gmail.com, ICQ: 29023962

**Comment by pztrn** [comment]
Are you talking about copy-paste? If so - CTRL+V (shift+ins) is available and working.

**Comment by exec228** [comment]
Try to copy someone's phrase (to paste it to input box).

**Comment by pztrn** [comment]
...and everything worked!

What chat service do you use?

**Comment by exec228** [comment]
Hmm... You can close the issue as not reproducible.
Recently I got bad S.M.A.R.T. and reinstalled Windows.
I can select chat fragments now.
However, I got another error on application start.

**Comment by saenzramiro** [comment]
@exec228 That error is for Rambox from zip file. In next version will be fixed, but now you can install it using the executable (64bits).
