### ISSUE TITLE
Offline state is not remembered

### ISSUE THREAD

**Issue by Luzifer** [saenzramiro/rambox#294]
### Steps to reproduce

1. Set up an account in Rambox
1. Put that tab in offline mode
1. Reload that tab and notice it stays blank
1. Restart Rambox

### Expected behavior

Tab stays offline, loads a blank page

### Actual behavior

Tab loads the messenger and is online while showing the "Go online" button

### ENVIRONMENT

> Version: 0.4.1
> Platform: darwin (x64)
> Electron: 1.3.1
> Chromium: 52.0.2743.82
> Node: 6.3.0

**Comment by saenzramiro** [comment]
In next version this option will be removed and replaced with Enable/Disable service.
