### ISSUE TITLE
Feature-request: avoid slack-redir.net in slack-links

### ISSUE THREAD

**Issue by andrey-yantsen** [saenzramiro/rambox#295]
Slack modifies all posted links by prepending it with domain slack-redir.net. Sometimes it responses with 503 errors, it's quite annoying.

It would be great to have an option to prevent appending slack-redir.net.

**Comment by andrey-yantsen** [comment]
Ok, done this with custom code:
```
$(document).on('mouseover', 'span.message_body a[data-referer-original-href]', function(){$(this).removeAttr('onclick')});
```

**Comment by saenzramiro** [comment]
I tested for a few days and seems to work ok for me. I never saw a 503 error.

Good to you finding a custom code to prevent it! :wink:
