### ISSUE TITLE
No notifications icon in Telegram tab

### ISSUE THREAD

**Issue by orange-buffalo** [saenzramiro/rambox#296]
When there are unread messages in Telegram, the tab does not display notifications icon with number of unread messages / conversations. 

-
> Rambox 0.4.1
> Electron 1.3.1
> linux x64 4.7.2-040702-generic

**Comment by saenzramiro** [comment]
Duplicate #183 

Will be fixed in next release.

**Comment by orange-buffalo** [comment]
Cool! Can't wait getting new release, it looks very promising :)
