### ISSUE TITLE
[improvement] Shortcut for switching between tabs

### ISSUE THREAD

**Issue by arnogues** [saenzramiro/rambox#298]
Need shortcut to switch between services tabs.
You should use the same as chrome.
under mac it's CMD+ALT + LEFT ARROW (or RIGHT ARROW)

**Comment by saenzramiro** [comment]
Ok, I can try to add this also. Now you can do the same by Ctrl + Tab or Ctrl + Shift + Tab.

**Comment by arnogues** [comment]
Thx very much I was looking for the shortcut.

**Comment by gossi** [comment]
Can we still get cmd + alt since this is the standard way for browsers and was the one I tried. Ctrl + Tab is so windows 98.
