### ISSUE TITLE
java-fails at autoupdate on electron.asar

### ISSUE THREAD

**Issue by Vidarius** [saenzramiro/rambox#299]
always on start i get the information:
problems in electron.asar: 
![error](https://cloud.githubusercontent.com/assets/20396855/18331684/fb6adc92-759f-11e6-82fb-2792b5640659.jpg)

**Comment by saenzramiro** [comment]
Thank you for the report.

This will be fixed in next release. See commit 327485cc66efb37c7f88e3480683af97998008ab.

**Comment by Vidarius** [comment]
big thx :)
