### ISSUE TITLE
Google Calendar

### ISSUE THREAD

**Issue by alfechner** [saenzramiro/rambox#301]
I's love to see google calendar within Rambox. This is something I miss also in Franz.

Is a calendar something which fits into such a messenger app? If so, I'm happy to contribute code.

**Comment by MrChick** [comment]
I'm using google calendar as a custom service, works perfectly

**Comment by saenzramiro** [comment]
As @MrChick said, you can do it adding it as a [Custom Service](https://github.com/saenzramiro/rambox/wiki/Add-a-Custom-Service).

**Comment by adlibdalom** [comment]
Sorry to re-open a question like this, but since it's very related, I thought there might be a solution here:
Is there any way to make the icon in Rambox update like the favicon does for Google Calendar, i.e. show today's date?
