### ISSUE TITLE
empty tab in Ctrl + (tab number) switching

### ISSUE THREAD

**Issue by ab014** [saenzramiro/rambox#304]
### Steps to reproduce

1. Ctrl + (number of tabs on the left side + 1) 

### Expected behavior

Tab should switch to the first tab on the right side

### Actual behavior

A blank screen is shown.

### ENVIRONMENT

> Rambox: v0.4.2

> OS: elementary OS (based on Ubuntu 16.04)

> Arch: x64

**Comment by saenzramiro** [comment]
In Windows 10 works ok.

Is anyone having this bug?

**Comment by ab014** [comment]
fixed for me in v 0.4.4

**Comment by saenzramiro** [comment]
This is fixed in v0.4.4.
