### ISSUE TITLE
0.4.2 refuses to launch on OSX

### ISSUE THREAD

**Issue by mriehl** [saenzramiro/rambox#305]
### Steps to reproduce

1. Have 0.4.1 installed (works fine)
2. Upgrade to 0.4.2
3. Try to launch Rambox

### Expected behavior

App starts up

### Actual behavior

OS refuses to start the app based on my security policy (apparently the binary isn't signed).
0.4.1 launched fine.

### ENVIRONMENT

> Rambox: v0.4.2

> OS: OSX el capitan

> Arch: x64

**Comment by andrey-yantsen** [comment]
Just perform ctrl+click and then `open`.

**Comment by mriehl** [comment]
Yes that works, but I don't remember it being necessary with 0.4.1? It looks like it's not signed or something.

**Comment by andrey-yantsen** [comment]
Yep, it was the same with 0.4.1.

**Comment by saenzramiro** [comment]
As @andrey-yantsen said, for 0.4.1 was the same.

I have plans to sign the app in a future, but as you know costs $99/year and that's why I need the support for the users by making donations.
