### ISSUE TITLE
Keep Rambox in the taskbar when close it not sticking

### ISSUE THREAD

**Issue by NikolaZornic** [saenzramiro/rambox#306]
_Keep Rambox in the taskbar when close it_ reactivates after PC reboot, but works fine if I just close-open Rambox.

-
> Rambox 0.4.1
> Electron 1.3.1
> win32 x64 10.0.14393

**Comment by saenzramiro** [comment]
For the record, this was fixed in v0.4.2.

**Comment by NikolaZornic** [comment]
That's why I closed issue.
