### ISSUE TITLE
Icon not visible

### ISSUE THREAD

**Issue by bnn-y** [saenzramiro/rambox#307]
### Steps to reproduce

1. App started

![Screenshot](http://i.imgur.com/YJYEdaU.png)

### Expected behavior

Rambox Icon visible in Dock

### Actual behavior

Real Rambox Icon visible in Dock

### ENVIRONMENT

> Rambox:Version: 0.4.2

> OS: OSX 10.11.16

> Arch: x64

**Comment by necrodst** [comment]
Same problem with same config (Not only in dock also).

**Comment by saenzramiro** [comment]
I will fix this ASAP.

**Comment by saenzramiro** [comment]
Merge with #314
