### ISSUE TITLE
Links in Skype

### ISSUE THREAD

**Issue by njuart** [saenzramiro/rambox#308]
Hi, after update all links from Skype are opened in preview window but not in browser. It should be like this from now? Thx

-
> Rambox 0.4.2
> Electron 1.3.5
> win32 x64 6.3.9600

**Comment by jbbr** [comment]
Same issue here,

> Rambox 0.4.2
> Electron 1.3.5
> Arch linux x64, AUR

**Comment by Shmasya** [comment]
+

**Comment by Shmasya** [comment]
Please fixed this!
