### ISSUE TITLE
Building rambox

### ISSUE THREAD

**Issue by Pablohn26** [saenzramiro/rambox#311]
### Steps to reproduce

Trying to build rambox I have a lot of warnings about files (images) that do not exist and the build hangs on this step:
> [INF] Waiting for changes...

### Expected behavior

Built binary

### Actual behavior

Error (see below)

### ENVIRONMENT

> Rambox: v0.X.X

> OS: Fedora 24

> Arch: x64 

> Sencha Cmd v6.2.0.103 with Compass

### Trace

> Sencha Cmd v6.2.0.103
> [INF] Using GPL version of Ext JS version 5.1.1.451 from /home/pablo/dev/rambox/ext.
> [INF] The implications of using GPL version can be found here (http://www.sencha.com/products/extjs/licensing).
> [INF] Processing Build Descriptor : default
> [INF] Starting server on port : 1841
> [INF] Mapping http://localhost:1841/~cmd to /root/bin/Sencha/Cmd/6.2.0.103...
> [INF] Mapping http://localhost:1841/ to /home/pablo/dev/rambox...
> [INF] Server started at port : 1841
> [INF] Application available at http://localhost:1841
> [INF] Loading app json manifest...
> [INF] Appending content to /home/pablo/dev/rambox/bootstrap.js
> [INF] Writing content to /home/pablo/dev/rambox/bootstrap.json
> [INF] merging 346 input resources into /home/pablo/dev/rambox/build/development/Rambox/resources
> [INF] merged 346 resources into /home/pablo/dev/rambox/build/development/Rambox/resources
> [INF] merging 6 input resources into /home/pablo/dev/rambox/build/development/Rambox
> [INF] merged 6 resources into /home/pablo/dev/rambox/build/development/Rambox
> [INF] Writing content to /home/pablo/dev/rambox/sass/example/bootstrap.json
> [INF] Writing content to /home/pablo/dev/rambox/sass/example/bootstrap.js
> [INF] writing sass content to /home/pablo/dev/rambox/build/temp/development/Rambox/sass/Rambox-all.scss.tmp
> [INF] appending sass content to /home/pablo/dev/rambox/build/temp/development/Rambox/sass/Rambox-all.scss.tmp
> [INF] appending sass content to /home/pablo/dev/rambox/build/temp/development/Rambox/sass/Rambox-all.scss.tmp
> [INF] writing sass content to /home/pablo/dev/rambox/build/temp/development/Rambox/sass/config.rb
> [INF] executing compass using system installed ruby runtime
> WARNING: @theme-background-image: Theme image not found: images/toolbar/main-scroll-left.png
>          on line 18 of /home/pablo/dev/rambox/build/temp/development/Rambox/sass/../../../../../ext/packages/ext-theme-base/sass/etc/mixins/theme-background-image.scss
>          from line 328 of /home/pablo/dev/rambox/build/temp/development/Rambox/sass/../../../../../ext/packages/ext-theme-neutral/sass/src/toolbar/Toolbar.scss
>          from line 7 of /home/pablo/dev/rambox/build/temp/development/Rambox/sass/../../../../../packages/local/rambox-default-theme/sass/src/toolbar/Toolbar.scss
>          from line 1308 of /home/pablo/dev/rambox/build/temp/development/Rambox/sass/Rambox-all.scss
> WARNING: @theme-background-image: Theme image not found: images/toolbar/main-scroll-right.png
>          on line 18 of /home/pablo/dev/rambox/build/temp/development/Rambox/sass/../../../../../ext/packages/ext-theme-base/sass/etc/mixins/theme-background-image.scss
>          from line 328 of /home/pablo/dev/rambox/build/temp/development/Rambox/sass/../../../../../ext/packages/ext-theme-neutral/sass/src/toolbar/Toolbar.scss
>          from line 7 of /home/pablo/dev/rambox/build/temp/development/Rambox/sass/../../../../../packages/local/rambox-default-theme/sass/src/toolbar/Toolbar.scss
>          from line 1308 of /home/pablo/dev/rambox/build/temp/development/Rambox/sass/Rambox-all.scss
> WARNING: @theme-background-image: Theme image not found: images/toolbar/main-scroll-top.png
>          on line 18 of /home/pablo/dev/rambox/build/temp/development/Rambox/sass/../../../../../ext/packages/ext-theme-base/sass/etc/mixins/theme-background-image.scss
>          from line 328 of /home/pablo/dev/rambox/build/temp/development/Rambox/sass/../../../../../ext/packages/ext-theme-neutral/sass/src/toolbar/Toolbar.scss
>          from line 7 of /home/pablo/dev/rambox/build/temp/development/Rambox/sass/../../../../../packages/local/rambox-default-theme/sass/src/toolbar/Toolbar.scss
>          from line 1308 of /home/pablo/dev/rambox/build/temp/development/Rambox/sass/Rambox-all.scss
> WARNING: @theme-background-image: Theme image not found: images/toolbar/main-scroll-bottom.png
>          on line 18 of /home/pablo/dev/rambox/build/temp/development/Rambox/sass/../../../../../ext/packages/ext-theme-base/sass/etc/mixins/theme-background-image.scss
>          from line 328 of /home/pablo/dev/rambox/build/temp/development/Rambox/sass/../../../../../ext/packages/ext-theme-neutral/sass/src/toolbar/Toolbar.scss
>          from line 7 of /home/pablo/dev/rambox/build/temp/development/Rambox/sass/../../../../../packages/local/rambox-default-theme/sass/src/toolbar/Toolbar.scss
>          from line 1308 of /home/pablo/dev/rambox/build/temp/development/Rambox/sass/Rambox-all.scss
> WARNING: @theme-background-image: Theme image not found: images/toolbar/main-more-left.png
>          on line 18 of /home/pablo/dev/rambox/build/temp/development/Rambox/sass/../../../../../ext/packages/ext-theme-base/sass/etc/mixins/theme-background-image.scss
>          from line 7 of /home/pablo/dev/rambox/build/temp/development/Rambox/sass/../../../../../packages/local/rambox-default-theme/sass/src/toolbar/Toolbar.scss
>          from line 1308 of /home/pablo/dev/rambox/build/temp/development/Rambox/sass/Rambox-all.scss
> WARNING: @theme-background-image: Theme image not found: images/toolbar/newversion-scroll-left.png
>          on line 18 of /home/pablo/dev/rambox/build/temp/development/Rambox/sass/../../../../../ext/packages/ext-theme-base/sass/etc/mixins/theme-background-image.scss
>          from line 328 of /home/pablo/dev/rambox/build/temp/development/Rambox/sass/../../../../../ext/packages/ext-theme-neutral/sass/src/toolbar/Toolbar.scss
>          from line 12 of /home/pablo/dev/rambox/build/temp/development/Rambox/sass/../../../../../packages/local/rambox-default-theme/sass/src/toolbar/Toolbar.scss
>          from line 1308 of /home/pablo/dev/rambox/build/temp/development/Rambox/sass/Rambox-all.scss
> WARNING: @theme-background-image: Theme image not found: images/toolbar/newversion-scroll-right.png
>          on line 18 of /home/pablo/dev/rambox/build/temp/development/Rambox/sass/../../../../../ext/packages/ext-theme-base/sass/etc/mixins/theme-background-image.scss
>          from line 328 of /home/pablo/dev/rambox/build/temp/development/Rambox/sass/../../../../../ext/packages/ext-theme-neutral/sass/src/toolbar/Toolbar.scss
>          from line 12 of /home/pablo/dev/rambox/build/temp/development/Rambox/sass/../../../../../packages/local/rambox-default-theme/sass/src/toolbar/Toolbar.scss
>          from line 1308 of /home/pablo/dev/rambox/build/temp/development/Rambox/sass/Rambox-all.scss
> WARNING: @theme-background-image: Theme image not found: images/toolbar/newversion-scroll-top.png
>          on line 18 of /home/pablo/dev/rambox/build/temp/development/Rambox/sass/../../../../../ext/packages/ext-theme-base/sass/etc/mixins/theme-background-image.scss
>          from line 328 of /home/pablo/dev/rambox/build/temp/development/Rambox/sass/../../../../../ext/packages/ext-theme-neutral/sass/src/toolbar/Toolbar.scss
>          from line 12 of /home/pablo/dev/rambox/build/temp/development/Rambox/sass/../../../../../packages/local/rambox-default-theme/sass/src/toolbar/Toolbar.scss
>          from line 1308 of /home/pablo/dev/rambox/build/temp/development/Rambox/sass/Rambox-all.scss
> WARNING: @theme-background-image: Theme image not found: images/toolbar/newversion-scroll-bottom.png
>          on line 18 of /home/pablo/dev/rambox/build/temp/development/Rambox/sass/../../../../../ext/packages/ext-theme-base/sass/etc/mixins/theme-background-image.scss
>          from line 328 of /home/pablo/dev/rambox/build/temp/development/Rambox/sass/../../../../../ext/packages/ext-theme-neutral/sass/src/toolbar/Toolbar.scss
>          from line 12 of /home/pablo/dev/rambox/build/temp/development/Rambox/sass/../../../../../packages/local/rambox-default-theme/sass/src/toolbar/Toolbar.scss
>          from line 1308 of /home/pablo/dev/rambox/build/temp/development/Rambox/sass/Rambox-all.scss
> WARNING: @theme-background-image: Theme image not found: images/toolbar/newversion-more-left.png
>          on line 18 of /home/pablo/dev/rambox/build/temp/development/Rambox/sass/../../../../../ext/packages/ext-theme-base/sass/etc/mixins/theme-background-image.scss
>          from line 12 of /home/pablo/dev/rambox/build/temp/development/Rambox/sass/../../../../../packages/local/rambox-default-theme/sass/src/toolbar/Toolbar.scss
>          from line 1308 of /home/pablo/dev/rambox/build/temp/development/Rambox/sass/Rambox-all.scss
> WARNING: @theme-background-image: Theme image not found: images/button/decline-small-arrow.png
>          on line 18 of /home/pablo/dev/rambox/build/temp/development/Rambox/sass/../../../../../ext/packages/ext-theme-base/sass/etc/mixins/theme-background-image.scss
>          from line 907 of /home/pablo/dev/rambox/build/temp/development/Rambox/sass/../../../../../ext/packages/ext-theme-neutral/sass/src/button/Button_small.scss, in `extjs-button-small-ui'
>          from line 10 of /home/pablo/dev/rambox/build/temp/development/Rambox/sass/../../../../../packages/local/rambox-default-theme/sass/src/button/Button.scss
>          from line 1309 of /home/pablo/dev/rambox/build/temp/development/Rambox/sass/Rambox-all.scss
> WARNING: @theme-background-image: Theme image not found: images/button/decline-small-arrow-rtl.png
>          on line 18 of /home/pablo/dev/rambox/build/temp/development/Rambox/sass/../../../../../ext/packages/ext-theme-base/sass/etc/mixins/theme-background-image.scss
>          from line 907 of /home/pablo/dev/rambox/build/temp/development/Rambox/sass/../../../../../ext/packages/ext-theme-neutral/sass/src/button/Button_small.scss, in `extjs-button-small-ui'
>          from line 10 of /home/pablo/dev/rambox/build/temp/development/Rambox/sass/../../../../../packages/local/rambox-default-theme/sass/src/button/Button.scss
>          from line 1309 of /home/pablo/dev/rambox/build/temp/development/Rambox/sass/Rambox-all.scss
> WARNING: @theme-background-image: Theme image not found: images/button/decline-small-arrow.png
>          on line 18 of /home/pablo/dev/rambox/build/temp/development/Rambox/sass/../../../../../ext/packages/ext-theme-base/sass/etc/mixins/theme-background-image.scss
>          from line 907 of /home/pablo/dev/rambox/build/temp/development/Rambox/sass/../../../../../ext/packages/ext-theme-neutral/sass/src/button/Button_small.scss, in `extjs-button-small-ui'
>          from line 10 of /home/pablo/dev/rambox/build/temp/development/Rambox/sass/../../../../../packages/local/rambox-default-theme/sass/src/button/Button.scss
>          from line 1309 of /home/pablo/dev/rambox/build/temp/development/Rambox/sass/Rambox-all.scss
> WARNING: @theme-background-image: Theme image not found: images/button/decline-small-s-arrow.png
>          on line 18 of /home/pablo/dev/rambox/build/temp/development/Rambox/sass/../../../../../ext/packages/ext-theme-base/sass/etc/mixins/theme-background-image.scss
>          from line 907 of /home/pablo/dev/rambox/build/temp/development/Rambox/sass/../../../../../ext/packages/ext-theme-neutral/sass/src/button/Button_small.scss, in `extjs-button-small-ui'
>          from line 10 of /home/pablo/dev/rambox/build/temp/development/Rambox/sass/../../../../../packages/local/rambox-default-theme/sass/src/button/Button.scss
>          from line 1309 of /home/pablo/dev/rambox/build/temp/development/Rambox/sass/Rambox-all.scss
> WARNING: @theme-background-image: Theme image not found: images/button/decline-small-s-arrow-rtl.png
>          on line 18 of /home/pablo/dev/rambox/build/temp/development/Rambox/sass/../../../../../ext/packages/ext-theme-base/sass/etc/mixins/theme-background-image.scss
>          from line 907 of /home/pablo/dev/rambox/build/temp/development/Rambox/sass/../../../../../ext/packages/ext-theme-neutral/sass/src/button/Button_small.scss, in `extjs-button-small-ui'
>          from line 10 of /home/pablo/dev/rambox/build/temp/development/Rambox/sass/../../../../../packages/local/rambox-default-theme/sass/src/button/Button.scss
>          from line 1309 of /home/pablo/dev/rambox/build/temp/development/Rambox/sass/Rambox-all.scss
> WARNING: @theme-background-image: Theme image not found: images/button/decline-small-s-arrow-b.png
>          on line 18 of /home/pablo/dev/rambox/build/temp/development/Rambox/sass/../../../../../ext/packages/ext-theme-base/sass/etc/mixins/theme-background-image.scss
>          from line 907 of /home/pablo/dev/rambox/build/temp/development/Rambox/sass/../../../../../ext/packages/ext-theme-neutral/sass/src/button/Button_small.scss, in `extjs-button-small-ui'
>          from line 10 of /home/pablo/dev/rambox/build/temp/development/Rambox/sass/../../../../../packages/local/rambox-default-theme/sass/src/button/Button.scss
>          from line 1309 of /home/pablo/dev/rambox/build/temp/development/Rambox/sass/Rambox-all.scss
>    create Rambox-all.css 
> [INF] Preprocessing /home/pablo/dev/rambox/build/development/Rambox/resources/Rambox-all.css to /home/pablo/dev/rambox/build/development/Rambox/resources/Rambox-all.css
> [INF] Appending content to /home/pablo/dev/rambox/bootstrap.js
> [INF] Writing content to /home/pablo/dev/rambox/bootstrap.json
> [INF] Waiting for changes...
>

**Comment by saenzramiro** [comment]
Seems like you are using **sencha app watch**. That command is for develop mode.

To build you have to run:

1. npm run sencha:clean
2. npm run sencha:compile
3. npm run build:linux64

**Comment by Pablohn26** [comment]
Running 
> npm run sencha:compile 

drops me next error: 
> /home/pablo/dev/rambox/.sencha/app/init-impl.xml:382: com.sencha.exceptions.BasicException: Cannot find file: /home/pablo/dev/rambox/build/temp/production/Rambox/sencha-compiler/app/full-page-master-bundle.js

that path breaks on  _/home/pablo/dev/rambox/build/temp/_  where there is only a folder named _development_ (rather than production). 

To be honest, I do not know where to change that (it seems an environment variable).

**Comment by saenzramiro** [comment]
Are you sure you have the right permissions to create a folder? "production" folder will be created automatically by Sencha Cmd.

That problems are for Sencha Cmd, you can Google it and see what's happening.

**Comment by Pablohn26** [comment]
I finally get it.
> cat /etc/redhat-release: Fedora release 24 (Twenty Four)
> npm --version : 2.15.9
> sencha which: Sencha Cmd v6.2.0.103

Steps: 

1. git clone https://github.com/saenzramiro/rambox.git
2. cd rambox
3. npm install
3. cp env-sample.js env.js
4. npm run sencha:compile
5. npm start
