### ISSUE TITLE
Rambox Icon doesn't appear on application on OS X

### ISSUE THREAD

**Issue by MartSerra** [saenzramiro/rambox#314]
### Steps to reproduce

1. I try downloading the .zip and the DMG file
2. The icon of the application is missing and only show the Apple's default placeholder
3. I try to uninstall and reinstall again but the icon doesn't appear.

### Actual behavior

![untitled 1](https://cloud.githubusercontent.com/assets/7231751/18389520/ecb453dc-766b-11e6-9c60-cb00940a4090.png)
![untitled](https://cloud.githubusercontent.com/assets/7231751/18389521/ecbbe034-766b-11e6-8358-87e0083f0352.png)

### ENVIRONMENT

> Rambox: v0.4.2

> OS: OS X El Capitan Version 10.11.6

> Arch: x64

**Comment by just2jays** [comment]
+1,  upgraded this morning, lost the icon!

**Comment by sollymay** [comment]
+2 here

**Comment by fat0troll** [comment]
+3 here

**Comment by KonradHolubek** [comment]
+4

**Comment by TimoJohannes** [comment]
+5, same platform as op

**Comment by andrey-yantsen** [comment]
Duplicate #307

**Comment by saenzramiro** [comment]
I will fix this ASAP.

**Comment by Daminoweb** [comment]
+1 same problem.

**Comment by FreeNationalLottery** [comment]
+10 same problem.

**Comment by bpetrynski** [comment]
**Temporary solution**

Download the icon and follow instructions below:

> Step 1: Copy the icon to the clipboard
a) Click on this file from the Finder
b) Choose 'Get Info' from the 'File' menu.
c) In the info window that pops up, click on the icon
d) Choose 'Copy' from the 'Edit' menu.
e) Close the info window

> Step 2: Paste the icon to the desired item
a) Go to the item in the Finder that you want a custom icon
b) Click the item (file, folder, disk, etc) 
b) Choose 'Get Info' from the 'File' menu.
c) In the info window that pops up, click on the icon
d) Choose 'Paste' from the 'Edit' menu.
e) Close the info window

Instructions and icon from iconverticons.com

[icon.zip](https://github.com/saenzramiro/rambox/files/478490/icon.zip)

**Comment by isaacrojasgarcia** [comment]
The solution provided by @bpetrynski works fine. Thanks.

**Comment by raulmatei** [comment]
It looks like on my side it works on the MacBook display but not on the external monitor which is the default when attached.
