### ISSUE TITLE
Way to add Gistbox and Evernote?

### ISSUE THREAD

**Issue by dare023** [saenzramiro/rambox#317]
Hi, I know this is not directly  related to a  purpose of this app, but is there a way to add Gistbox and Evernote?
I think it would be useful to have all web services in one place.

**Comment by notnsane** [comment]
Have you tried with Custom Services?

**Comment by dare023** [comment]
I did now after yo pointed me, thank you.
Think it works, after several application restarts.
Basically, problem is that clicking on login link gets to empty screen.
I solved by placing login url of Evernote and somehow managed to login to Gistox. (login url did not help)
Would be nice if this issues can be fixed, just to have it run more smooth.  
Thanks for pointing me to solution
