### ISSUE TITLE
Services are defined, but they dont show up

### ISSUE THREAD

**Issue by artukrap** [saenzramiro/rambox#320]
After version update from 0.4.1 to 0.4.2 my services are gone
[http://prntscr.com/cga5p6](http://prntscr.com/cga5p6)

-
> Rambox 0.4.2
> Electron 1.3.5
> win32 x64 10.0.14393

**Comment by brwolfgang** [comment]
This is a duplicate of #313

**Comment by saenzramiro** [comment]
@artukrap All your bugs are related. Please follow the steps I mentioned in the other issue.
