### ISSUE TITLE
No Icon in update 0.4.2

### ISSUE THREAD

**Issue by klowdo** [saenzramiro/rambox#322]
![icon in doc](https://cloud.githubusercontent.com/assets/6265447/18426909/2996c1a8-78c5-11e6-8520-4ba7cda6fa30.png)

No icon in latest update

-
> Rambox 0.4.2
> Electron 1.3.4
> darwin x64 15.4.0

**Comment by andrey-yantsen** [comment]
Duplicate #314

**Comment by saenzramiro** [comment]
Thank you @andrey-yantsen . Let's merge with #314.
