### ISSUE TITLE
No se puede imprimir desde Inbox

### ISSUE THREAD

**Issue by MauricioAedo** [saenzramiro/rambox#326]
En primer lugar muchas gracias Ramiro por está nueva versión con muchas correcciones y mejoras.

He detectado que no es posible imprimir desde Imbox, por ejemplo un adjunto en el correo electrónico en formato PDF.

Saludos

-
> Rambox 0.4.2
> Electron 1.3.5
> win32 x64 10.0.14393

**Comment by saenzramiro** [comment]
Después de investigar un rato, me encuentro con que no se puede detectar si el usuario desea imprimir o navegar simplemente en una página, ya que los dos eventos utilizados para esto no lo detectan.

Me es imposible detectar cuando un usuario quiere abrir un link común y corriente en su navegador default o si quiere imprimir, o navegar simplemente.

Daré por cerrada la tarea, hasta que Electron brinde la posibilidad de hacerlo para luego abrirla nuevamente.
