### ISSUE TITLE
Notification in mightytext and hangout

### ISSUE THREAD

**Issue by etemam** [saenzramiro/rambox#328]
Hi,

First, i would like to thank, Rambox is a great job!

I have a problem with mightytext notification and hangouts notification. They does not appear on mac os x. 

### Steps to reproduce

1. Receive a SMS or a message via hangout
2. On chrome notification show
3. Rambox does not show any notification.

### ENVIRONMENT

Rambox: v0.4.2
OS: Mac OS X 10.11.5

Sincerly

**Comment by saenzramiro** [comment]
Hangouts don't have native Desktop Notifications, and MightyText seems not working because I tested in Google Chrome and no notifications showed up.

Can you check this?

**Comment by etemam** [comment]
Sorry for delay,

Notification for mightytext are available on chrome but maybe with a plugin.

**Comment by saenzramiro** [comment]
Desktop Notifications for Hangouts will be added in next release.

**Comment by saenzramiro** [comment]
MightyText don't have any option to show desktop notifications on this web app or something to know the unread count of messages to do it manually in Rambox. There is a thread about this ([see here](http://help.mightytext.net/forums/123495-general/suggestions/2388569-unread-count)) and we have to wait for that.
