### ISSUE TITLE
Add an EditorConfig file

### ISSUE THREAD

**Issue by weeman1337** [saenzramiro/rambox#331]
This may help rambox in the future when more people contribute to the project. An EditorConfig file can be used to define some basic code styles like type of line breaks or encoding. Many editors and IDEs support EditorConfig files. You find an overview here: http://editorconfig.org/#overview

@saenzramiro if you're fine with it I can add one based on the current code and send you a PR.

**Comment by saenzramiro** [comment]
Sweet! Yes, please. I will wait your PR. :)
