### ISSUE TITLE
Outlook account does not want to delete from the 'enabled services list' on the main tab

### ISSUE THREAD

**Issue by theunsfvo** [saenzramiro/rambox#332]
### Steps to reproduce

1. Add Outlook service
2. Delete Outlook service with dustbin icon
3. Outlook service remains in list

### Expected behavior

Outlook service should be removed from the enable service list
### Actual behavior

Outlook service remains on the enable service list
### ENVIRONMENT

> Rambox: v0.4.2

> OS: Win 10 Pro ver 1511

> Arch: x64

**Comment by saenzramiro** [comment]
Can you open the DevTools and paste here the error is throwing when you try to remove it?

**Comment by theunsfvo** [comment]
Hi Ramiro,
​​
There was not error. It just returns to the list view and leaves the
service there.

Regards,
Theuns

**Comment by saenzramiro** [comment]
So I will suggest to remove all your localStorage data running in the console:

`localStorage.clear()`

Close Rambox and open it again, and start over.

**Comment by theunsfvo** [comment]
​localStorage.clear() returns an 'undefined' message...

Got this from the dev tools console when I tried removing the Outlook
service:

app.js:1 Uncaught TypeError: Cannot read property 'dom' of
undefinedremoveServiceFn @ app.js:1(anonymous function) @ app.js:1callback
@ app.js:1(anonymous function) @ app.js:1btnCallback @ app.js:1callback @
app.js:1fireHandler @ app.js:1onClick @ app.js:1fire @ app.js:1fire @
app.js:1publish @ app.js:1doDelegatedEvent @ app.js:1onDelegatedEvent @
app.js:1(anonymous function) @ app.js:1​


On 14 September 2016 at 18:58, Ramiro Saenz <notifications@github.com>
wrote:

> localStorage.clear()




Regards,
Theuns  - "I love deadlines. I like the whooshing sound they make as they
fly by." Douglas Adams
  IQ Business <http://www.iqbusiness.net>: *Solution Architect *| *TOGAF 9
Certified Enterprise Architect *
   My 3D Images <http://bluestarcreations.wordpress.com/> || Some of my
writings <http://www.writingroom.com/writingresults.aspx?m=Zandria> || My
Awesome Stuff Blog <http://awesomestufftheunslikes.wordpress.com/about/>

**Comment by saenzramiro** [comment]
Very weird. Just clear your localStorage manually going to DevTools, then Application tab and then Local Storage. Remove all the values and reboot Rambox.

**Comment by theunsfvo** [comment]
Had a quick look but couldn't spot where to clear the local storage. Only
just started looking at Dev Tools.

Ps. Restarted RamBox today and all the services I had were gone, except
Outlook :(, had to add them all again.

Regards,
Theuns  - "I love deadlines. I like the whooshing sound they make as they
fly by." Douglas Adams
  IQ Business <http://www.iqbusiness.net>: *Solution Architect *| *TOGAF 9
Certified Enterprise Architect *
   My 3D Images <http://bluestarcreations.wordpress.com/> || Some of my
writings <http://www.writingroom.com/writingresults.aspx?m=Zandria> || My
Awesome Stuff Blog <http://awesomestufftheunslikes.wordpress.com/about/>

**Comment by saenzramiro** [comment]
Yes, clearing your localStorage will reset Rambox, so you will need to add all again.

If you don't fix the Outlook problem, it will keep having problems.

**Comment by theunsfvo** [comment]
Okay, tried it again and the Outlook one is gone now...

but found another bug when trying to open a URL in Gmail it asks to
relaunch Chrome... will log it seperately with the console history..


Regards,
Theuns  - "I love deadlines. I like the whooshing sound they make as they
fly by." Douglas Adams
  IQ Business <http://www.iqbusiness.net>: *Solution Architect *| *TOGAF 9
Certified Enterprise Architect *
   My 3D Images <http://bluestarcreations.wordpress.com/> || Some of my
writings <http://www.writingroom.com/writingresults.aspx?m=Zandria> || My
Awesome Stuff Blog <http://awesomestufftheunslikes.wordpress.com/about/>
