### ISSUE TITLE
No notification with Ryver

### ISSUE THREAD

**Issue by y-sampol** [saenzramiro/rambox#333]
Hi,

I've got 3 diffrent tabs: one for my Slack account, one for my Hangout account, one for my Ryver account.

I'm getting notifications only for the first two and never for my Ryver account (no message count on the tab or on the Rambox icon in the Windows Task Bar, even if it's a direct message). The other two accounts are working fine.

I've checked the account configuration and it's the same on all three: "Show notification" is checked.

Thanks!
Yoann
![image](https://cloud.githubusercontent.com/assets/22168408/18467480/74139b3a-79a0-11e6-90d0-bcccb932df36.png)
![image](https://cloud.githubusercontent.com/assets/22168408/18467540/a1309d66-79a0-11e6-8d39-d139b59d1869.png)

## 

> Rambox 0.4.2
> Electron 1.3.5
> win32 x64 10.0.14393

**Comment by AlainRUSSIER** [comment]
+1

**Comment by relgames** [comment]
Hi, having the same issue. Is there a workaround? Ryver was the reason I switched to Rambox.

**Comment by saenzramiro** [comment]
Ok, I will take a look on this for next version.
