### ISSUE TITLE
Custom service (vk.com) crashes Rambox

### ISSUE THREAD

**Issue by gnidorah** [saenzramiro/rambox#337]
### Steps to reproduce

1. Add vk.com as custom service
2. Login on vk service tab

### Expected behavior

It should login and work

### Actual behavior

It logins but Rambox crashes after that

### ENVIRONMENT

> Rambox: v0.4.2

> OS: OS X 10.11.6

> Arch: x64

**Comment by gnidorah** [comment]
@saenzramiro 
Additionally I have a question: for custom services do unread message counters work? Thanks.

**Comment by gnidorah** [comment]
My fault, I've used http://vk.com as URL. Now I've switched to http**s**://vk.com and crash disappeared.

**Comment by saenzramiro** [comment]
It will only works automatically if the service you are adding change the title if there is any new message (ex: **(2) WhatsApp**). If not, you have to write JavaScript code to detect new messages. Read more [here](https://github.com/saenzramiro/rambox/wiki/Add-a-Custom-Service)...

**Comment by gnidorah** [comment]
Thanks for the answer!

BTW can't reproduce this bug anymore. Perhaps was due some particular advertising banner on vk. Sorry.
