### ISSUE TITLE
No notifications for Mattermost

### ISSUE THREAD

**Issue by lnalex** [saenzramiro/rambox#338]
### Steps to reproduce

1. Enable desktop notifications on the channel (Global default (For all activity))
2. Send Rambox to the background
3. Receive new message in the channel

### Expected behavior

Receive notifications about new messages in a Mattermost channel

### Actual behavior

Does not receive notifications

### ENVIRONMENT

> Rambox: v0.4.2

> OS: win32

> Arch: x64

**Comment by saenzramiro** [comment]
Did you check if **Don't Disturb** is disabled? Can you try to do the same steps but in Google Chrome and see if works?

**Comment by lnalex** [comment]
**Don't Disturb** is disabled of course. 
I tried in my browsers (Firefox, Chromium) and it is working.

**Comment by saenzramiro** [comment]
I don't have any Mattermost host to test it. If you can provide to me just for test this issue, it will be great. You can send the data via a PM on Gitter if you want.

**Comment by jbbr** [comment]
@saenzramiro I've sent you an email with a mattermost account for testing.

**Comment by saenzramiro** [comment]
@jbbr Thank you so much. I received the email, so ASAP I will test this issue.

**Comment by saenzramiro** [comment]
Tested and works ok for me in Windows 10 x64.

**Comment by lnalex** [comment]
I'm on Windows 7 Pro x64, it is strange...

**Comment by jbbr** [comment]
I didn't had any problems too. @Inalex: I assume notifications in Rambox work fine with other services? I've had problems with notifications on Linux because I needed to install some kind of notification daemon. But I assume this shouldn't be required on Windows.

> Rambox 0.4.2
> Mattermost 3.3.0 and 3.4.0

**Comment by lnalex** [comment]
It works perfectly on Linux but in Windows I don't know the reason why it is not working

**Comment by saenzramiro** [comment]
@lnalex Windows 7 don't have Desktop Notifications API. So that's why you don't see it.

Sadly you will need to move to Windows 10 to have all features working.

**Comment by lnalex** [comment]
I hope I'll see some other people concerned by this problem here.
