### ISSUE TITLE
Kiwirc shows a "The service with the following URL has an invalid authority certification."

### ISSUE THREAD

**Issue by pulpo** [saenzramiro/rambox#339]
### Steps to reproduce

1. Add a new service
2. Choose Kiwi IRC

### Expected behavior

Display the Kiwi IRC page 

### Actual behavior

Displays error message: 

```
The service with the following URL has an invalid authority certification.

https://owa.clients.kiwiirc.com/piwik.js

If is a Custom Service, you have to remove it and add it again, enabling the "Trust invalid authority certificates" in the Options
```
### ENVIRONMENT

> Rambox: v0.4.2

> OS: ElementaryOS Loki

> Arch: x64

**Comment by svoop** [comment]
Same on macOS with Rambo 0.4.4.

**Comment by saenzramiro** [comment]
That message is a warning to let the user know that there are certifications not valid in the service that is loading.

If Kiwi IRC sign `https://owa.clients.kiwiirc.com/piwik.js` with a valid certificate, the message will be dissapear.

**Comment by svoop** [comment]
https://groups.google.com/forum/#!topic/kiwiirc/Ej1zRU6Vm-E

**Comment by saenzramiro** [comment]
@svoop Sweet! They fixed it. :)

**Comment by svoop** [comment]
Cool, however, even though the message is gone, all I get is a blank page (on Mac).

**Comment by MrChick** [comment]
@svoop that is probably #363

**Comment by Hasimir0** [comment]
@svoop  Hi, I am experiencing the same problem with Skype for Web

As soon as I try to login with my username this messahe appears:

```
**The service with the following URL has an invalid authority certification.
https://auth.gfx.ms/16.000.26709.00/Default1033.css**
```

**Comment by saenzramiro** [comment]
@Hasimir0 See #460
