### ISSUE TITLE
Open Rambox on Notification click

### ISSUE THREAD

**Issue by saenzramiro** [saenzramiro/rambox#34]
Every time the app shows a Notification, when you click it needs to open the app and if will be great to switch to that service/tab.

## 

> Rambox 0.3.0
> Electron 1.2.5
> win32 x64 10.0.10586

**Comment by benavern** [comment]
+1

**Comment by saenzramiro** [comment]
Personal note: https://github.com/electron/electron/issues/262#issuecomment-116466249

**Comment by ElvisPresly** [comment]
@saenzramiro In Linux will work?

**Comment by saenzramiro** [comment]
@ElvisPresly I think it can work, I hope so.

**Comment by saenzramiro** [comment]
Seems to be not simple. I will move this for a future.

**Comment by saenzramiro** [comment]
Any PR for this will be great!

**Comment by franciscoluiz** [comment]
+1

**Comment by Slomo17** [comment]
It works in [Franz](http://meetfranz.com/) on linux, so it should be possible.

**Comment by ElvisPresly** [comment]
@Slomo17  Franz non open source

**Comment by vitorcrovador** [comment]
+1

**Comment by franciscoluiz** [comment]
but use the same basis, for example, electron...  so it is possible!!! 💃 

i do not see the need, by clicking on the notification to open exactly the conversation in question. but if open the related tab/service already will help a lot.

**Comment by Slomo17** [comment]
@ElvisPresly I Kown, thats why i want to switch. I just said, that it should be possible, because Franz uses electron too, like franciscoluiz already said.

**Comment by benavern** [comment]
I agree!
