### ISSUE TITLE
Slack notification no longer counts

### ISSUE THREAD

**Issue by forteller** [saenzramiro/rambox#340]
In previous version everything worked fine with the Slack notification. But now there is no number in it, only a dot. Ubuntu Gnome, 16.04.

**Comment by lnalex** [comment]
**Use the issue template**

**Comment by forteller** [comment]
Gladly when there are steps needed to reproduce an issue and/or it's needed to explain what should happen and what actually happens.

Here there are no steps to reproduce except for "run the application", which I would think goes without saying, and "use the Slack function in the application", which I mentioned in the title, and nothing more to explain. That's why I chose to not use it this time, to save me time writing and everyone else time reading more than necessary. I'll use it next time I report something :)

**Comment by saenzramiro** [comment]
@forteller In version 0.4.2 we changed channel unread counters to a dot in the tab. If you have unread messages in Direct Messages, will show the number.

**Comment by forteller** [comment]
Ah, I see. That makes sense. Thank you for the reply and your great work!
