### ISSUE TITLE
only active at Taskbar showing

### ISSUE THREAD

**Issue by Vidarius** [saenzramiro/rambox#343]
Version: 0.4.2
Platform: win32 (x64)
Electron: 1.3.5
Chromium: 52.0.2743.82
Node: 6.3.0
Rambox-0.4.2-x64-win.zip

Program-Symbol now all the Time in the Taskbar - i would have it back only to the "Notify"Bar

is it possible to make a option to take it would everyone like more? (show in or not @taskbar)

i wish If i get a new Message - so its open a window in the taskbar > thats nice - but again with a free option > only notify bar (popup the windows info window)/ taskbar minimized / open program window

sry 4 my bad english

**Comment by saenzramiro** [comment]
You have an option in **Preferences** do disable taskbar and only have it in system tray when close it.

**Comment by Vidarius** [comment]
why you make it not @ the primäry option bar?
