### ISSUE TITLE
Request: support for Kakao messaging

### ISSUE THREAD

**Issue by Vidarius** [saenzramiro/rambox#344]
Is it possible to support kakao? (https://de.wikipedia.org/wiki/KakaoTalk)

Thanks for the great project!

**Comment by saenzramiro** [comment]
AFAIK, they don't have any web app to use Kakao from the web.

**Comment by Vidarius** [comment]
http://app.pc.kakao.com/talk/win32/KakaoTalk_Setup.exe

here you can download it - at gives als as portable app

**Comment by saenzramiro** [comment]
That's for download a desktop app. You need to find a URL to access Kakao and using via a web browser.

I will close this issue for now and then, we can reopen it when information is provided.
