### ISSUE TITLE
[Feature request] Reload only active pane

### ISSUE THREAD

**Issue by etemam** [saenzramiro/rambox#349]
I do not know if this is a wanted feature but when we reload with shortcut command it reloads all the panes. I personally think that it will be better to reload the active pane.

Sincerly, 
### Steps to reproduce
1.  Press CMD+R on mac 
2.  It reloads all panes
### Wanted behavior

When reload shortcut is press reload only the current pane

Rambox: v0.4.2
OS: Mac OS X 10.11.5

**Comment by saenzramiro** [comment]
We can think about creating a shortcut for reloading. Now, you can reload active service by right click in the tab service and selecting "Reload".

**Comment by etemam** [comment]
Yes i have seen this, but if a shortcut can be done it will be appreciated.

Thanks a lot,

**Comment by Ash258** [comment]
It's old issues, so it is well known, but there is already shortcut.

Active service could be reloaded with `CTRL+SHIFT+R` or `⌘⇧R`
