### ISSUE TITLE
Rambox freezes when displaying notification in windows 10

### ISSUE THREAD

**Issue by L3nn0x** [saenzramiro/rambox#350]
When rambox displays a notification using windows 10 action center, Rambox's UI freezes completely. The program is still running in the background because a sound is played when a notification is received.

Setps to reproduce : Connect to any service that uses windows 10 notification tray, receive a notification displayed on screen. Rambox then freezes completely.

Preventing the service to show notifications seems to prevent the problem.

-
> Rambox 0.4.2
> Electron 1.3.5
> win32 x64 10.0.14393

**Comment by saenzramiro** [comment]
In my case, I use the same environment and works ok for me.

Can anyone confirm this please?

**Comment by arthureggert** [comment]
I can make some tests, but who service is using windows 10 action center?

**Comment by L3nn0x** [comment]
I mainly have this problem with Slack.

**Comment by L3nn0x** [comment]
I've been looking into it, Whatsapp has the same problem. When a notification appears, one of Rambox's processes goes crazy and eat all of my CPU. I have to kill Rambox completely and relaunch it.

Hope it helps, I'll try monitoring more.

**Comment by saenzramiro** [comment]
@L3nn0x Because of your problems, it should be an Electron bug.

**Comment by L3nn0x** [comment]
Reinstallation didn't help. Should I contact Electron instead then?

**Comment by saenzramiro** [comment]
Before contacting Electron, please check if Rambox is consuming a lot of CPU and RAM, if so please read #366 and follow the lasts instructions in last comments.

**Comment by L3nn0x** [comment]
Seems like spoofing the tooltip.io domain name does the trick.

Thanks a lot.

**Comment by gak** [comment]
I have this issue too with WhatsApp. The Rambox window apparently locks up and finally continues after several minutes. However, during the frozen state, it still receives messages and shows them in a notification.

Version: 0.5.3
Platform: win32 (x64)
Electron: 1.4.15
Chromium: 53.0.2785.143
Node: 6.5.0
Also running 3 Slacks.

@L3nn0x What does spoofing the domain mean? Just set the hosts file to 127.0.0.1 for that domain? Does that just disable the notifications?
