### ISSUE TITLE
Auth0 Login Error

### ISSUE THREAD

**Issue by konfuzius** [saenzramiro/rambox#353]
> Rambox
> Oops!, something went wrong
> 
> Callback URL mismatch.
> The url "file:///Applications/Rambox.app/Contents/Resources/app.asar/index.html" is not in the list of allowed callback URLs: file:///E:/wamp/www/rambox/index.html, https://rambox.auth0.com/mobile, file:///, file:///*, file:///opt/Rambox/resources/app.asar/index.html.
> Please go to the Application Settings page and make sure you are sending a valid callback url from your application.

- Login credentials are correct. I can login into https://manage.auth0.com.
- Login via Google freezes Rambox

![](https://picload.org/image/rdracgig/bildschirmfoto2016-09-20um15.4.png)

### ENVIRONMENT

> Rambox: v0.4.2
> OS: OS X 10.9.5
> Arch: x64 or ia32
> Platform: darwin (x64)
> Electron: 1.3.4
> Chromium: 52.0.2743.82
> Node: 6.3.0

**Comment by saenzramiro** [comment]
Thank you for your report. This was fixed in commit 79dc0b8a4eb22b672835e764ca55eafd5f216f54, so next release will be ok.

**Comment by aj-ptw** [comment]
@saenzramiro what was the fix for this? Working in an electron app and having the SAME PROBLEM!!! I looked at the code but am not too sure... ps: awesome looking electron app!!

**Comment by saenzramiro** [comment]
@aj-ptw I don't remember, but I think it was related with the version of Auth0 libraries.
