### ISSUE TITLE
Hipchat- Credential are not saved & wrong page shown

### ISSUE THREAD

**Issue by postadelmaga** [saenzramiro/rambox#354]
When I login on hipchat I have 2 issues:
1. I'm not redirected to the webapp chat page but the homepage of hipchat is shown
2. whenever I refresh the page I have to re-enter the credential ( no matter if I have checked the 'remember me' checkbox)
### ENVIRONMENT

> Rambox: v0.4.2

**Comment by postadelmaga** [comment]
The problem is still present on Rambox 0.4.4

How to reproduce:
- Login in Hipchat (check 'Keep me signed in' checkbox)
- Press Control + R ( reload page/service)
The login box is again shown.

Same procedure on Chrome keep the session

**Comment by saenzramiro** [comment]
I just investigated this issue, and for me works OK now.

Can you confirm if this still valid?
