### ISSUE TITLE
Impossible to remove a service

### ISSUE THREAD

**Issue by AkSponkynot** [saenzramiro/rambox#356]
### Steps to reproduce

1. Add a new service
2. Try to remove this service
3. Log in and use the service

### Actual behavior

The service is not removed 
The service can be enabled or disabled it's change nothing.

### ENVIRONMENT

> Rambox: v0.4.2

> OS: Windows 10

> Arch: x64

**Comment by saenzramiro** [comment]
Is there a use case that Rambox had problems but I couldn't find it. However, in next release I improved this so hopefully it will fix this.

For now, please follow this steps: https://github.com/saenzramiro/rambox/issues/219
