### ISSUE TITLE
No more win32 setup or archive ?

### ISSUE THREAD

**Issue by fredleger** [saenzramiro/rambox#358]
### Steps to reproduce

1. Go to the site
2. Look for IA32 setup (none)
3. Go to github 0.4.2 (neither, ia32.zip contains linux binaries)

![image](https://cloud.githubusercontent.com/assets/2778741/18785638/9d433c08-8199-11e6-8d9f-b7b287caebe7.png)

### Expected behavior

I know Win32 is going to die one day, but for now it's still a common OS (i have to use it for work)

### ENVIRONMENT

> Rambox: v0.4.2

> OS: Win7

> Arch: ia32

**Comment by saenzramiro** [comment]
I will add ia32 again in next release. 👍
