### ISSUE TITLE
Scrolling on the pages opened from a link is glitching 

### ISSUE THREAD

**Issue by guillefar** [saenzramiro/rambox#359]
### Steps to reproduce

1. Click on a link in a message
2. Go to the new opened page
3. Scroll

### Expected behavior

To scroll normally

### Actual behavior

Text becomes unreadable. all the surface is a mess. Attached it is an image (th
![captura de pantalla de 2016-09-23 16-26-07](https://cloud.githubusercontent.com/assets/1972792/18790669/f99288ea-81af-11e6-9c7b-bc538e2885ba.png)
e link I opened is http://sailsjs.org/documentation/concepts/deployment)

### ENVIRONMENT

Ubuntu 16.04 

> Rambox: v0.4.2

> OS: Linux

> Arch: x64

**Comment by saenzramiro** [comment]
Thank you for your report.

Seems to be an Electron bug, so please report this in the official [repo](https://github.com/electron/electron).

**Comment by zeke** [comment]
Could this be related to https://github.com/saenzramiro/rambox/issues/7 ?

**Comment by saenzramiro** [comment]
@zeke No, #7 is related to a Ext JS bug in a scrolling TabBar.
