### ISSUE TITLE
Line (messenger app)

### ISSUE THREAD

**Issue by ist109** [saenzramiro/rambox#36]
Quite widely used, I think right behind Whatsapp and WeChat. It is why I am considering ditching Franz.

**Comment by saenzramiro** [comment]
Can you share a link to Line to use it in Web browsers?

**Comment by ist109** [comment]
Actually I just realised that Line has since disconnected their web version.

  

I guess that's why Franz didn't implement it as well.

  

http://thenextweb.com/insider/2015/07/30/line-just-got-a-chrome-extension-so-
you-can-chat-right-in-your-browser/#gref  

  

Here's the closest thing I can see that might work, would this suffice for
Rambox's integration?

  

(sorry non-coder here so I didn't understand the underlying technicalities
better)

  

Sent from [Nylas N1](https://link.nylas.com/link/4d9t7uc7ao3nqqztvf01y37e1
/local-
3f020f1d-9002/0?redirect=https%3A%2F%2Fnylas.com%2Fn1%3Fref%3Dn1&r=cmVwbHkrMDEzNTA0ZDA2NzFjM2IyYzI2OGE0OWU5NWVkYTVhNGU4YjdiMWU2MDI4MTIyMmVkOTJjZjAwMDAwMDAxMTM4ZjJmZTQ5MmExNjljZTA5YmVkNDU0QHJlcGx5LmdpdGh1Yi5jb20=),
the extensible, open source mail client. Not free, but works well.  

![](https://link.nylas.com/open/4d9t7uc7ao3nqqztvf01y37e1/local-
3f020f1d-9002?r=cmVwbHkrMDEzNTA0ZDA2NzFjM2IyYzI2OGE0OWU5NWVkYTVhNGU4YjdiMWU2MDI4MTIyMmVkOTJjZjAwMDAwMDAxMTM4ZjJmZTQ5MmExNjljZTA5YmVkNDU0QHJlcGx5LmdpdGh1Yi5jb20=)

On Jul 2 2016, at 3:31 pm, saenzramiro &lt;notifications@github.com&gt; wrote:  

> Can you share a link to Line to use it in Web browsers?

>

> —  
> You are receiving this because you authored the thread.  
> Reply to this email directly, [view it on
GitHub](https://github.com/saenzramiro/rambox/issues/36#issuecomment-230088943&r=cmVwbHkrMDEzNTA0ZDA2NzFjM2IyYzI2OGE0OWU5NWVkYTVhNGU4YjdiMWU2MDI4MTIyMmVkOTJjZjAwMDAwMDAxMTM4ZjJmZTQ5MmExNjljZTA5YmVkNDU0QHJlcGx5LmdpdGh1Yi5jb20=),
or [mute the thread](https://github.com/notifications/unsubscribe
/ATUE0OOqgTnX-
5wf16vgnorKBXCNP7h0ks5qRhPkgaJpZM4JDmNv&r=cmVwbHkrMDEzNTA0ZDA2NzFjM2IyYzI2OGE0OWU5NWVkYTVhNGU4YjdiMWU2MDI4MTIyMmVkOTJjZjAwMDAwMDAxMTM4ZjJmZTQ5MmExNjljZTA5YmVkNDU0QHJlcGx5LmdpdGh1Yi5jb20=).![](https://github.com/notifications/beacon/ATUE0Px65Y3XvRCF6E5gA9bn9cT3mu6Oks5qRhPkgaJpZM4JDmNv.gif)

**Comment by kevin940726** [comment]
+1 for adding LINE into the service.

Here is a good open source command line [project](https://github.com/carpedm20/LINE) written in python that I can find.

**Comment by tobiasmuehl** [comment]
+1 for Line. Unfortunately there's no official way to include it, but the project @kevin940726 linked looks promising.

**Comment by saenzramiro** [comment]
I will close this issue until Line release a web app.
