### ISSUE TITLE
jQuery-Problems with KiwiIRC and custom server

### ISSUE THREAD

**Issue by MrChick** [saenzramiro/rambox#363]
### Steps to reproduce
1. Add KiwiIRC-Service with custom server
2. Try to open the Kiwi tab
### Expected behavior

Get the login mask displayed
### Actual behavior

Blank page with jQuery-Errors:

> Uncaught (in promise) Error: Syntax error, unrecognized expression: .panel[style_=display: block] .msg(…)
> jquery-1.11.1.min.js:2 Uncaught Error: Syntax error, unrecognized expression: .panel[style_=display: block] .msg
> jquery-1.11.1.min.js:2 Uncaught Error: Syntax error, unrecognized expression: .panel[style*=display: block] .msg

Strange thing is: adding the exact same Kiwi installation as custom service works as intended without a problem.
### ENVIRONMENT

> Rambox: v0.4.4
> 
> OS: Win10 Enterprise 1607
> 
> Arch: x64

**Comment by svoop** [comment]
I get a different message on the console (that's for Mac): "Failed to clear temp storage: It was determined that certain files are unsafe for access within a Web application, or that too many calls are being made on file resources. SecurityError"

**Comment by wolv-dev** [comment]
I'm getting the same error when adding the official server.

**Comment by rokups** [comment]
And i am getting no errors at all but still seeing blank page. Both when adding official and unofficial servers. Like already said adding kiwiirc as custom service works ok. This is with v0.4.5.
