### ISSUE TITLE
Rambox Account/Login not working

### ISSUE THREAD

**Issue by saenzramiro** [saenzramiro/rambox#364]
### Steps to reproduce
1. Try to login.
2. Keep spinning.
### Expected behavior

Open popup to login via SSO.
### Actual behavior

Is not opening nothing.

In macOS works but is duplicating the services.
### ENVIRONMENT

> Rambox: v0.4.4
> 
> OS: Win 10
> 
> Arch: x64

**Comment by saenzramiro** [comment]
Seems to be only in my environment.

**Comment by babastienne** [comment]
Same bug when trying to connect with google.

Same environment (win 10, but now with rambox 0.4.5, arch x64). The connection with google works on my xubuntu OS. Seems to be specific to windows.

**Comment by saenzramiro** [comment]
Try to uninstall Rambox, then go to C:/Users/your_user/AppData/Roaming and remove the folder "Rambox". Install latest version and try again.

**Comment by babastienne** [comment]
Ok it's works, thank you for your help.

**Comment by JeppeLeth** [comment]
I had the same issue. The issue only appears when I had disabled hardware acceleration.
I fixed it by unchecking the Disable Hardware Acceleration (needs to relaunch).
