### ISSUE TITLE
Problem with upper indicator in Ubuntu 16.04

### ISSUE THREAD

**Issue by ismasaga** [saenzramiro/rambox#365]
After upgrading RamBox I can not close without closing the upper indicator (the 'Always on top' option is enabled)

> Rambox 0.4.4
> Electron 1.4.1
> linux x64 4.4.0-38-generic

**Comment by saenzramiro** [comment]
What is "the upper indicator"? Can you provide steps to reproduce please?

**Comment by ismasaga** [comment]
No steps are needed. How can I leave Rambox in the background?

**Comment by saenzramiro** [comment]
I think this is related with #369.

Can you confirm?

**Comment by ismasaga** [comment]
Yes, it is equal. Sorry but he put it after me.
