### ISSUE TITLE
Keyboard Shortcut to hide Rambox

### ISSUE THREAD

**Issue by sylvainar** [saenzramiro/rambox#368]
Hey !

Nice work first.

I'd like to know if there is a possibility to "hide" Rambox in the notification bar only using a keyboard shortcut, instead of clicking on the icon and chose Show/Hide. 

Thanks !

**Comment by saenzramiro** [comment]
I can take a look on this. 😉

**Comment by suamikim** [comment]
`Alt+F4` works for me just fine in Windows.

**Comment by sylvainar** [comment]
Doesn't work on Ubuntu :cry:

**Comment by ponyesteves** [comment]
Should start working with  #379. But nevertheless a global shortcut for show-hide would be very helpfull.  ALT-F4 only will function for hide. 

Great App by the way!!! (Ahora en castellano!! Muy bueno lo de ustedes Ramiro,  orgullo nacional!!  :argentina: Espero poder contribuir pronto con Rambox) Felicitaciones

**Comment by saenzramiro** [comment]
@ponyesteves Gracias. 😉 

I will take a look for a global shortcut.

**Comment by saenzramiro** [comment]
Let's merge this issue with #379.
