### ISSUE TITLE
Don't minimize anymore

### ISSUE THREAD

**Issue by rominail** [saenzramiro/rambox#371]
On Linux, since the new version, on click on the close button it doesn't minimize anymore in launch tray but close Rambox completly

-
> Rambox 0.4.4
> Electron 1.4.1
> linux x64 4.4.0-38-generic

**Comment by ab014** [comment]
I'm having a similar issue. If you close app the window gets closed and wouldn't open at all. I have to kill the Rambox process to restart the application.

**Comment by saenzramiro** [comment]
Let's merge this thread to #369
