### ISSUE TITLE
High CPU usage in newer version (0.4.4)

### ISSUE THREAD

**Issue by mrazola** [saenzramiro/rambox#373]
Hi!

CPU usage is increasing a lot for after last update. One of the Rambox processes keeps using high CPU %, but after a while, and the UI starts feeling unresponsive. The issue is not detected on a fresh restart, neither on the older version.

### ENVIRONMENT
Platform: linux
Rambox: v0.4.4
OS: linux
Arch: x64
Electron: 1.4.1
Chromium: 53.0.2785.113
Node: 6.5.0

**Comment by phryneas** [comment]
Same here. Also happens with all services disabled, so no browser windows besides the "add a service" tab running (and this chrome subprocess seems to be the one with high CPU usage).

Platform: linux
Rambox: v0.4.4
OS: ubuntu

**Comment by saenzramiro** [comment]
Let's merge this thread with #366
