### ISSUE TITLE
Sending mail multiple times at once from Inbox by Gmail

### ISSUE THREAD

**Issue by NikolaZornic** [saenzramiro/rambox#375]
Sometimes sending mail using Inbox by Gmail, my collegues receive mail multiple times (2-4 times the same mail).

Sending mail from the Chrome browser doesn't produce this problem.

## 

> Rambox 0.4.4
> Electron 1.4.1
> win32 x64 10.0.14393

**Comment by saenzramiro** [comment]
Did you have this problem in previous version?

**Comment by NikolaZornic** [comment]
Not sure about 0.4.2, but yes I had this problem in the beginning of September.

**Comment by saenzramiro** [comment]
Ok, I will take a look.

**Comment by saenzramiro** [comment]
Do you keep having this issue?

**Comment by NikolaZornic** [comment]
No, looks like that this issue is gone.
