### ISSUE TITLE
Click on icon must open service tab

### ISSUE THREAD

**Issue by abhimanyu003** [saenzramiro/rambox#377]
### Steps to reproduce

![test](https://cloud.githubusercontent.com/assets/265913/18935519/2b429d4c-85fe-11e6-98cf-454a3bb5ba72.jpg)
### Expected behavior
1. If you click on icon it must open it's tab.
2. For example if you click on Twitter icon it must open Twitter tab.
### Actual behavior

Nothing Happens
### ENVIRONMENT

> Version: 0.4.4
> Platform: linux (x64)
> Electron: 1.4.1
> Chromium: 53.0.2785.113
> Node: 6.5.0

**Comment by saenzramiro** [comment]
This is not a bug. What you are reporting is a feature request.
