### ISSUE TITLE
Include jabber 

### ISSUE THREAD

**Issue by Skybeat** [saenzramiro/rambox#38]
It will be nice if you can include jabber (XMPP protokol).

**Comment by jbbr** [comment]
As rambox uses web versions of messengers for now, it might be an idea to add support for custom websites/services just by adding a URL.
Or specific support for web based jabber clients like https://github.com/jcbrand/converse.js

**Comment by saenzramiro** [comment]
:wink: 
https://github.com/saenzramiro/rambox/wiki/Add-a-Custom-Service

**Comment by saenzramiro** [comment]
As @jbbr said, for now we can include a web app that have a Jabber service.

What service do you propose?

**Comment by collectorgeneral** [comment]
@saenzramiro Hello, I came across this wonderful app, and I would love if you can integrate xmpp support!

Their official [website](https://conversejs.org/) has a demo on the side. I am thinking if you can package the js file along with the release, you can probably open an empty webpage with that frame integrated and allow users to connect to their xmpp server. There is no need to rely on a service to deliver essentially the same js file. Would this be feasible?

**Comment by saenzramiro** [comment]
That's not the idea of Rambox right now, sorry. :'(

We have to find a website providing Jabber and we can add it then.

**Comment by Shadyjames** [comment]
Not to beat a dead horse but no xmpp is the only thing stopping me from making the switch to rambox, so I'd be very happy to see this happen

**Comment by SimJoSt** [comment]
@Shadyjames you can either add the mentioned https://conversejs.org/ as a custom service or propose another website, which can act as a xmpp client.

**Comment by Akronix** [comment]
why was this closed? :(

**Comment by MrChick** [comment]
@Akronix because there is no "official" XMPP webclient and nobody proposed a usable one?

**Comment by Akronix** [comment]
I wouldn't expect an "official" xmpp webclient because the philosophy of jabber isn't to favor specific clients or implementations of the xmpp protocol.
However, even if there isn't a currently usable one, I would expect to eventually add one in the future.

**Comment by MrChick** [comment]
of course there won't be an official client. Still, who is keeping you from reopening this issue once you've found a usable webclient?
Would be pretty senseless to keep this issue open for all eternity

**Comment by joe776** [comment]
https://inverse.chat/
Seems to work pretty nicely as custom service and is fullscreen (based on converseJS). I just gave it a quick try, haven't figured out the unread counter, yet.

**Comment by gnidorah** [comment]
> Final version of my custom JS

Counter works, thanks!

> Beware that this might share your password if you're using Auth0!

I have slightly crappy version https://gnidorah.github.io/converse.js/inverse.html that stores credentials only on your computer.
I don't believe we will get good security with pure JS client that both works for any Jabber server and also doesn't need authorization gates.
