### ISSUE TITLE
Global hotkeys

### ISSUE THREAD

**Issue by suamikim** [saenzramiro/rambox#382]
Are there any global hotkeys (system wide & within the application) available?

What I'm specifically looking for including priority from 1 (must have) to 5 (nice to have):
- (1) **System wide hotkey to open the app**
  - Alternative which would also work for me: Opening the app a second time when it's already running (minimized to system tray) currently does nothing, whilst it should bring up the app from system tray. This way I could use my quick launcher or the windows start menu to open it with the keyboard only.
- **Quick launcher** inside the app which could be used for the following (besides others):
  - (1) **Switch between services**
    - I'm aware of `Ctrl+X` which feels a little cumbersome to me since it's hard to type and "only" works for the services, whilst a launcher could be used for all kind of navigation.
  - (3) **Directly go to conversation with a user**
    - I guess that would be hard to implement since you'd have to implement & maintain it for each service separately but it would be an incredible feature...

If you don't know, what I actually mean by "quick launcher", have a look at what `Ctrl+K` does in Slack.

Also is there any documentation about existing shortcuts & global hotkeys? I just stumbled about `Ctrl+X` "by luck"...

**Comment by mbesch0711** [comment]
very important stuff to enhance speed at work with a lot of services

**Comment by saenzramiro** [comment]
I don't like the idea of using a wide hotkey to open the app, but we can improve it to open it when is already opened.

Quick Launcher it's a great idea, we will add it in version 1.0. But going directly to a conversation it's a very hard task... also to maintain.

I will create another issue for the Quick Launcher to add it to the roadmap. So I will close this one.
