### ISSUE TITLE
Notification icon indicator

### ISSUE THREAD

**Issue by suamikim** [saenzramiro/rambox#383]
I'd really appreciate if you could change the global tray & individual service icon if there is at least one unread message inside one of the services. I don't need any "counting badges" but only an indicator which says "There is a new message" or "There's nothing".

Right now, if I get a message while I'm not at the computer I won't get any hint about it in the system tray when I get back.
Even worse, I'd have to click through every service to check if there are any unread messages since there's no hint on the service icons neither.

Are there any plans to implement such a feature? The absence of it makes the app pretty much useless to me whilst I do really enjoy it's other features on first glance.

Thanks

**Comment by suamikim** [comment]
I just realized that there actually are icon notifications but they don't seem to work consistently. E.g. Slack didn't show me those notifications when I started using the app but they do now.

I'm going to observe the behavior and report back as soon as I can tell you more.

Also I'm using a custom page (Outlook OWA) where this feature is (understandably) not available. I know how to check via custom JS, if there are any unread messages within this service. Can I somehow notify `rambox` about those unread messages myself?

**Comment by saenzramiro** [comment]
Sure, if you add it as a Custom Service, you can write JS code to do whatever you want, in this case check unread messages.

Please read [THIS](https://github.com/saenzramiro/rambox/wiki/Add-a-Custom-Service) and [THIS](https://github.com/saenzramiro/rambox/wiki/Inject-JavaScript-Code).

If you use Outlook 365 service in Rambox, you can add also JS code in the Advance option inside the Edit window.

**Comment by nancytch** [comment]
@saenzramiro Still seeing an issue with the notifications in the system tray -- they are not working consistently. Using 0.5.3 on mac. 

Just not seeing this at all in the preferences: 
https://github.com/saenzramiro/rambox/blob/master/app/view/preferences/Preferences.js#L98

**Comment by zetxek** [comment]
Same here.

![rambox 2017-03-21 09-26-17](https://cloud.githubusercontent.com/assets/240085/24138438/7b92ef0c-0e18-11e7-9ddb-0337d8393934.png)
![rambox 2017-03-21 09-26-02](https://cloud.githubusercontent.com/assets/240085/24138437/7b92dbfc-0e18-11e7-96d9-c3a12e46c12e.png)

And the dock icon never has any badge indicator, alert, of anything notifying of new messages.

**Comment by thelmstedt** [comment]
Same on linux:
Version: 0.5.3
Platform: linux (x64)
Electron: 1.4.15
Chromium: 53.0.2785.143
Node: 6.5.0

**Comment by saenzramiro** [comment]
I will take a look.
