### ISSUE TITLE
Jump to service with unread messages when opening from system tray

### ISSUE THREAD

**Issue by suamikim** [saenzramiro/rambox#384]
I'd really appreciate if you could automatically jump to a service with unread messages, when opening rambox from the system tray.

If there are more than one services with unread messages I'd prever if you'd jump to the one which received the latest message. Alternatively simply jumping to the first service in the list would also be fine for me...

**Comment by saenzramiro** [comment]
I understand that for some users will be a great feature, but for others not. Sometimes, you want to open Rambox and check other services that they don't have any unread message, and leave the unread messages for later.

I think, to satisfy all the users, it will be great to open Rambox on notification click and if is possible, go directly to the service that shows that notification. We have an issue for that (#34) but I couldn't do it yet.
