### ISSUE TITLE
Open rambox when clicking on Win 10 notification message

### ISSUE THREAD

**Issue by suamikim** [saenzramiro/rambox#385]
New messages are shown as Win 10 notifications which is just fine:

![win-10-notification](https://cloud.githubusercontent.com/assets/2870365/18987223/f320d394-8700-11e6-9c23-4fdb4e7efeff.png)

It would be very convenient if you could open Rambox from the system tray and automatically switch to the source-service of the message when clicking on the icon.

**Comment by saenzramiro** [comment]
Duplicate #34
