### ISSUE TITLE
How to sync services

### ISSUE THREAD

**Issue by suamikim** [saenzramiro/rambox#386]
The notes say that rambox can `Sync your configuration between multiple computers`. How can I use this feature? Is there any documentation I can't find?

**Comment by saenzramiro** [comment]
You have to use a Rambox Account. For that, just go to the top-right corner of the Rambox tab, in the Login button, create an account and sign in in all your computers with the same account.

**Comment by suamikim** [comment]
Ok, I'd prefer to share the settings using my private file sharing service (Nextcloud) if possible.
Is there a way to achieve this by e.g. using symlinks to the directory in which the settings are saved?

Is there one fixed directory in which those are saved or are they somehow "spread" over the system (like registry etc.)?

**Comment by saenzramiro** [comment]
Not right now, sorry. Services are stored in the Local Storage.
