### ISSUE TITLE
Discord notification icon shows a dot all the time

### ISSUE THREAD

**Issue by tehoko** [saenzramiro/rambox#388]
![image](https://cloud.githubusercontent.com/assets/2924029/19015502/01fefaf2-8806-11e6-88e5-7df97c4d8b06.png)

No matter what I do, I can't get rid of this dot permanently. I noticed I can hide it by closing any existing Direct Message chat with a friend, but the dot comes back after 2 or 3 seconds.

I clicked through every open chat and verifed that none of them show an unread badge.

This dot **does not** show in Rambox's title in the taskbar nor make the tray icon red.

-
> Rambox 0.4.4
> Electron 1.4.1
> win32 x64 10.0.10586

**Comment by saenzramiro** [comment]
The dot budge is for unread messages in groups.

Please check if your groups have unread messages.

**Comment by tehoko** [comment]
Looks like the culprit was not an unread message in a chat room (I scrolled through them all), but an old pinned message from one of the groups, posted a few months ago.

Sorry for taking your time.

**Comment by tristanlee85** [comment]
In efforts to help anyone else that comes across this issue, I have had the same for months with what appeared to be no unread messages in my groups. And no unread pinned messages either.

What it ended up being was a group that I had been recently added to and there was no on-going conversation. However, my permissions did not let me read the history. There was no unread notification on the group/channel itself, but after right-clicking on the channel and clicking **Mark Read**, suddenly it went away.

**Comment by rnyberg** [comment]
This can also happen if someone does an @here or @everyone notification and then deletes the message before you read it. You'll be stuck with an unread badge on the web client and on (not related to Rambox) mobile client. Desktop client resolves the thing.

**Comment by Mathitos** [comment]
@rnyberg Know anyway to fix this?

**Comment by rnyberg** [comment]
I don't know any way to fix an @everyone / @here notification that was deleted before you read it. It usually goes away on it's own pretty soon.

**Comment by hughes** [comment]
@tristanlee85's answer was helpful, but to save time if you have lots of channels you can right-click on the whole server icon in the far-left column and click "mark as read".

**Comment by dino572** [comment]
@hughes This solved it for me.

**Comment by masatti** [comment]
I've had this issue for months, maybe half a year. Never bothered to fix it because I barely used Discord. Anyway, I cleared all messages from all servers. Didn't help. Anyone got ideas?

I'm guessing the notifications are from unread messages or @ from a server I left or was removed from, hence no way to clear the messages.
