### ISSUE TITLE
No menu of apps

### ISSUE THREAD

**Issue by Bjr49000** [saenzramiro/rambox#389]
Win10, i just download, install and connect with google account, i have skype, messenger and inbox and one other without logo and name and i can't delete. I can't access to skype messenger and inbox
![capture](https://cloud.githubusercontent.com/assets/21093159/19022558/25e0d9ba-88db-11e6-9f30-d409fe361b78.PNG)

## 

> Rambox 0.4.4
> Electron 1.4.1
> win32 x64 10.0.14393

**Comment by saenzramiro** [comment]
Seems like you had a bug and now services are not displayed properly.

Please, go to **Help -> Tools -> Clear cache and LocalStorage** and start over.

**Comment by Bjr49000** [comment]
Same problem when i connect at my account

**Comment by Bjr49000** [comment]
I uninstall and install same problem and logo is bug

**Comment by saenzramiro** [comment]
I think your account have data stored incorrectly, so that's why you have that error. We can try to reset your account to start over, but you need to send me your account details (service used and email).

**Comment by Bjr49000** [comment]
Ok i sent that to you

**Comment by saenzramiro** [comment]
Send an email to rambox@protonmail.com.
