### ISSUE TITLE
Autostart with windows

### ISSUE THREAD

**Issue by Skybeat** [saenzramiro/rambox#39]
I haven't found any setting to start rambox with Widnows (Autostart)
It will be nice if you can a settings section where i can setup a autostart enabled or disabled.

thanks

**Comment by saenzramiro** [comment]
Yes, It will be nice. For now, you can do as I did. Copy the Rambox shortcut icon to the **C:\Users\Administrador\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Startup** folder.
