### ISSUE TITLE
Number in badge in tab is not updated [Zimbra mail]

### ISSUE THREAD

**Issue by markoshorro** [saenzramiro/rambox#390]
### Steps to reproduce
1. When an email is received
2. Clik on email received but badge in the tab is not updated (neither in the Rambox icon)
### Expected behavior

It should update the number of notifications on that tab
### Actual behavior

It updates the number if the tab is refreshed ("Reload" button)
### ENVIRONMENT

> Rambox: v0.4.4
> OS: Linux (Ubuntu)
> Arch: x64

**Comment by saenzramiro** [comment]
Can you provide a test email so we can test it and fix it?
