### ISSUE TITLE
Synced services needs login after restart

### ISSUE THREAD

**Issue by dmetzler1988** [saenzramiro/rambox#391]
### Steps to reproduce

1. Login via GitHub as example
2. sync the services with github accounts
3. close rambox
4. restart rambox
5. need to login to all services again (not so if the services are not synced with an account)

### Expected behavior

Can you maybe fix this, that the services stayed logged in after restart? 
so than if you don't login with an account?

### Actual behavior

After every restart you need to login to every synced service.

### ENVIRONMENT

Mac OS Sierra 10.12

> Rambox: v0.4.4

> OS: Mac OS Sierra 10.12

**Comment by saenzramiro** [comment]
And what about if you don't sync your services?

If you stay logged out and restart Rambox. Are the services asking to login every time?

**Comment by dmetzler1988** [comment]
no, if i stay logged out and restart Rambox, the services don't asking to login every time - only at first time.
I tried it out today again - now it works. maybe a os-restart was needed to solve this problem.
