### ISSUE TITLE
Horde shows wrong unread message number

### ISSUE THREAD

**Issue by Kinokudeiro** [saenzramiro/rambox#394]
### Steps to reproduce

1. Double click in any message on "Entrada" (inbox folder)

### Expected behavior

Not show unread message number.

### Actual behavior
It shows a huge number as unread messages in the upper tab (when i have read them all). When  I click in any other clickable place it disappears.

**Note**: It doesn't reproduce in any other folder. It's no a big issue but you may want to fix it at some point

![horde_unread](https://cloud.githubusercontent.com/assets/22609873/19072924/5272ade2-8a38-11e6-9254-57fedc16aa19.png)
-
> Rambox 0.4.4
> Electron 1.4.1
> win32 x64 10.0.14393

**Comment by saenzramiro** [comment]
Can you check if the email you opened had in the subject the same number that was displayed in the badge?

**Comment by Kinokudeiro** [comment]
Exactly! Well, I guess so, it's a number with a lot of digits so it doesn't
fit in the tab, but the last 7 digits do match. That's why i didn't
realized.

Hope it helps.

2016-10-05 14:46 GMT+02:00 Ramiro Saenz <notifications@github.com>:

**Comment by saenzramiro** [comment]
Some services have that behavior. I will try to prevent this bug in a future release.
