### ISSUE TITLE
Ctrl+Tab switching is partly broken

### ISSUE THREAD

**Issue by andrey-yantsen** [saenzramiro/rambox#395]
Meantime Ctrl+Shift+Tab works fine.
### Steps to reproduce
1. Add 5 services, 3 of them aligned to the left and 2 others — to the right
2. Open first tab (with supported services list)
3. Press Ctrl+Tab 5 times
### Expected behavior

Last tab is opened
### Actual behavior

First tab opened
### ENVIRONMENT

> Rambox: v0.4.4
> OS: macOS 10.12
> Arch: x64

**Comment by andrey-yantsen** [comment]
Explanation in GIFs:
1. Ctrl+Tab: http://take.ms/r2b6X
2. Ctrl+Shift+Tab: http://take.ms/l4m37

**Comment by saenzramiro** [comment]
Ups! 🙃
