### ISSUE TITLE
Remove side padding from Telegram chat?

### ISSUE THREAD

**Issue by edgard** [saenzramiro/rambox#396]
Is it possible to remove the padding on the sides of Telegram chat? It seems out of place.

**Comment by saenzramiro** [comment]
Telegram web app is like that. Have padding on the sides.

In a future release, we will add to Rambox the possibility to inject CSS so you can remove sides and also apply colors, etc.

**Comment by Silent-Hunter** [comment]
Franz somehow removed the padding and made the web Telegram fill the whole screen. I wonder if that same thing could be applied here.

**Comment by saenzramiro** [comment]
Sure, we will add CSS injection in a future release. Also you will be able to inject your own CSS to change styles!

**Comment by Silent-Hunter** [comment]
Hey thanks!

**Comment by rodneyrod** [comment]
So how would one inject this CSS into a Rambox service?

https://www.nickmcummins.com/stylish/stylish-telegram-full-screen.css

**Comment by danielnieto** [comment]
This would be awesome!
