### ISSUE TITLE
notifications does not work with zimbra

### ISSUE THREAD

**Issue by thoru** [saenzramiro/rambox#398]
zimbra has the ability to show a popup to notify a new mail. it uses the notification api of browsers.
in rambox it does not show at all.

I talked to another user on mac, and he says it shows the popup. So perhaps the notification permission is missing in windows version?

## 

> Rambox 0.4.4
> Electron 1.4.1
> win32 ia32 6.1.7601

**Comment by saenzramiro** [comment]
Did you check if you have to enable it manually in Zimbra settings?

Some services have the option to enable desktop notifications (for example Facebook Messenger). Maybe I forgot to add a note in Zimbra Add Window to let the user know to enable desktop notification option.

**Comment by thoru** [comment]
Just tested the same in newest rambox and I confirm it works now :D
