### ISSUE TITLE
[Win8-10] Uninstall

### ISSUE THREAD

**Issue by Bjr49000** [saenzramiro/rambox#401]
On win10 or 8 you can uninstall apps just with right click in menu apps (in windows) but when i click on uninstall i have programs and functionnality is open can you add uninstall via right click :
![image](https://cloud.githubusercontent.com/assets/21093159/19212431/560e52be-8d51-11e6-87c4-b94a72be6ff5.png)
And can you just show app, no folder with your name please.

(Sorry i'm FR so no good english ^^)

**Comment by saenzramiro** [comment]
Uninstall app by right click is a behavior of Electron Build, and there's nothing I can do.

About my name in the folder, I will try to remove it for next releases.
