### ISSUE TITLE
Hangouts doesn't load Google Voice contact info

### ISSUE THREAD

**Issue by szhu** [saenzramiro/rambox#406]
### Steps to reproduce
1. Add a Hangouts tab
2. Sign ~it~in to a Google account using Google Voice texting via Hangouts
3. Look at the sidebar
### Expected behavior

Google Voice text conversations should initially display the phone number. After a fraction of a second (probably after contact info loads), the conversations change to displaying the contact names.
### Actual behavior

Google Voice text conversations ~should~ display the phone number and never display the contact name.
### ENVIRONMENT

> Rambox: v0.4.4
> 
> OS: Mac OS X 10.11.6
> 
> Arch: x64
### Debug info

Console shows:

```
https://clients6.google.com/voice/v1/users/@me/account?checkHangoutsCallingPermission=false&key=xxxxxxxxxxxxxx-xxxxxxxxxxxxxxxx-xxxxxxx&locale=en&alt=protojson
Failed to load resource: the server responded with a status of 401 ()
```

Chrome, which loads Hangouts properly, doesn't have this error.

**Comment by saenzramiro** [comment]
Do you still have this issue?

**Comment by szhu** [comment]
I tested it again just now. Yes I do.

Rambox 0.4.5.89

**Comment by saenzramiro** [comment]
Can you make a video showing this issue? I cannot reproduced it.

**Comment by rummik** [comment]
This is specifically an issue with Google Voice or Project Fi SMS chats that have names attached to them.  Rambox only shows the number, not the name and then the number

In FireFox and Chrome:
![image](https://cloud.githubusercontent.com/assets/630909/22305194/9966d4b6-e308-11e6-9bdc-3c9e285360d6.png)

In Rambox:
![image](https://cloud.githubusercontent.com/assets/630909/22304859/449e00ae-e307-11e6-9762-bb271f354187.png)

Console output on Rambox:
```
(program):1 Uncaught TypeError: Cannot read property 'contentWindow' of null
https://clients6.google.com/voice/v1/users/@me/account?checkHangoutsCalling… Failed to load resource: the server responded with a status of 401 ()
clients4.google.com/invalidation/lcs/client?xpc=%7B… Uncaught ReferenceError: invalidation is not defined
(program):1 Uncaught TypeError: Cannot read property 'contentWindow' of null
https://clients6.google.com/voice/v1/users/@me/account?checkHangoutsCalling… Failed to load resource: the server responded with a status of 401 ()
```

**Comment by rummik** [comment]
My best guess is that Hangouts loads up an `<iframe>` for some of the requests, and then fails when it tries to access the frame's `contentWindow`

**Comment by rummik** [comment]
This appears to be fixed in 0.5.3

**Comment by saenzramiro** [comment]
Yes @rummik, Hangouts use iframes.
Please @szhu, confirm if this is fixed.

**Comment by szhu** [comment]
It works! Thanks for following up on this.
