### ISSUE TITLE
AdBlocking

### ISSUE THREAD

**Issue by krambock** [saenzramiro/rambox#407]
if you are using chrome (or chromium) as base, it could be nice to let install plugins to avoid the ads on those services that are web-based.. Mighty Text for instance. 

### ENVIRONMENT

Version: 0.4.4
Platform: win32 (x64)
Electron: 1.4.1
Chromium: 53.0.2785.113
Node: 6.5.0

**Comment by saenzramiro** [comment]
Related #145

**Comment by gnidorah** [comment]
+1
Vk has ugly ads

**Comment by Kristinita** [comment]
+1. It would be nice, if will be added any ad-blocking extension, [**uBlock Origin**](https://chrome.google.com/webstore/detail/ublock-origin/cjpalhdlnbpafiamejdnhcphjbkeiagm?hl=en) for example.

Thanks.
