### ISSUE TITLE
Window Opening Position

### ISSUE THREAD

**Issue by solariz** [saenzramiro/rambox#409]
I use a laptop connected to a docking station with two additional Monitors. Problem: When I shutdown my computer and next time I boot without connected to this monitors rambox still opens up on a disconnected monitor, unreachable for me. Also known WIN arrow move tricks wont work.

Would be nice to have a check if this position is actually valid before setting the window back to it, alternatively startup at screen 0 always.

thanks !!!

-
> Rambox 0.4.4
> Electron 1.4.1
> win32 x64 10.0.14393

**Comment by saenzramiro** [comment]
Related #323

**Comment by johnnyasantoss** [comment]
Is this fixed? I'm having this problem too on Windows 10, and the `WIN + Directional arrows` is not working ☹️

**Comment by saenzramiro** [comment]
This is a common problem of Electron apps. We have to find a way to solve this.
For now, you can do the following to move the windows:
1. `Alt+Space`
2. Press `m`
3. Then `Up Arrow`
4. Finally, move your mouse to see Rambox windows.

If this doesn't work, try the same but before do this:
1. `Alt+Space`
2. Press `r`
