### ISSUE TITLE
Add microphone support (Skype)

### ISSUE THREAD

**Issue by jbbr** [saenzramiro/rambox#41]
It would be great to have Skype call support.
"Franz" already has some rudiment support for skype calls - so this is possible using Electron.

I assume HTML5 Web Audio API and maybe something like WebRTC must be supported. But I'm not sure about the requirements of skype web calls.

**Comment by saenzramiro** [comment]
Yes, I will add it for the next release.

You are right, surelly it can be done. I will take a look. Thanks bro!
