### ISSUE TITLE
[OSX] Prevent Terminal opening on System Startup

### ISSUE THREAD

**Issue by saenzramiro** [saenzramiro/rambox#411]
### Steps to reproduce
1. Restart computer.
2. On startup, two terminals will be opened.
### Expected behavior

No terminals opened.
### Actual behavior

Two terminals opened.
### ENVIRONMENT

> Rambox: v0.4.4
> 
> OS: OSX 10.11.6
> 
> Arch: x64

<img width="636" alt="captura de pantalla 2016-10-14 a las 3 40 18 p m" src="https://cloud.githubusercontent.com/assets/2694669/19398814/d01fe522-9224-11e6-8e36-8c89633504a6.png">

**Comment by saenzramiro** [comment]
One terminal is for the development environment, the other one is for the production app.

**Comment by YesThatAllen** [comment]
I have idea changing the Electron Autolaunch in  [main.js](https://github.com/saenzramiro/rambox/blob/master/electron/main.js#L45-L48) from `Rambox` to `Rambox.app` will fix this.

```js
// Configure AutoLaunch
const appLauncher = new AutoLaunch({
	 name: 'Rambox'
	,isHiddenOnLaunch: config.get('start_minimized')
```

![login-items](https://cloud.githubusercontent.com/assets/2879972/20143865/444dc97e-a660-11e6-8e41-210d6f58ab5a.png)


That said, I'd rather not have Rambox force itself in to my login items. Removing this or making it optional would be more friendly, IMO.

**Comment by saenzramiro** [comment]
@YesThatAllen Thank you, I will try this for next release.

You can disabled Rambox autostart by going to Preferences.

**Comment by YesThatAllen** [comment]
Ah, now I see it. I'd been expecting to see Preferences in the Mac native "Rambox" menu.

I found `Start automatically on system startup` 

I'll suggest a rename to `Start Automatically on Login`

Thank for the pointer.

**Comment by YesThatAllen** [comment]
I don't know how [this commit](https://github.com/YesThatAllen/rambox/commit/4ad0d80b740da421aec14f367c9b3abe31c85089) would work for Windows/Linux, but happy to submit the PR.

**Comment by saenzramiro** [comment]
I think `Start automatically on system startup` it's more understandable and common.

Feel free to submit a PR for `Rambox.app`. 😉

**Comment by Bheemaanil** [comment]
It is still happening for me on Version 0.5.3. Is any fix done??

**Comment by saenzramiro** [comment]
@Bheemaanil I will try to fix it for next release.

**Comment by saenzramiro** [comment]
This is a bug for AutoLaunch library.

https://github.com/Teamwork/node-auto-launch/issues/28

I will try to apply a temp fix.

**Comment by timothe** [comment]
Still happening on 0.5.9 for me...

**Comment by saenzramiro** [comment]
@timothe You will have to remove a configuration in your Mac.

Please go to your System Preferences, then Users and Groups and in the startup section, remove the "Rambox - Unix executable".
