### ISSUE TITLE
Proxy

### ISSUE THREAD

**Issue by mortezaPRK** [saenzramiro/rambox#412]
It would be nice if we could use proxy for each service. Right now we can use global proxy

**Comment by saenzramiro** [comment]
Can you give me a reason to have a proxy for each service? 🤔

**Comment by mortezaPRK** [comment]
Some users may not be able to access some services directly.
For example, I can't access Facebook service directly due to censorship in my country (Iran).

**Comment by saenzramiro** [comment]
Ok, so you are meaning that you want to use a proxy only on Facebook and not in the other services because only Facebook is restricted. Right?

**Comment by mortezaPRK** [comment]
yes

**Comment by saenzramiro** [comment]
Merged with #420
