### ISSUE TITLE
Constant notifications

### ISSUE THREAD

**Issue by evancaldwell** [saenzramiro/rambox#415]
I'm on Elementary OS Freya (Ubuntu 14.04)
Since I updated to 0.4.4 if Rambox does not have focus, anytime I get a new message Rambox will constantly notify my of various new messages until I refocus on Rambox. If Rambox does have focus it will constantly notify until I unfocus and refocus.

## 

> Rambox 0.4.4
> Electron 1.4.1
> linux x64 4.4.0-42-generic

**Comment by saenzramiro** [comment]
In what service is notifying you?

**Comment by evancaldwell** [comment]
Google Inbox and Google Hangouts.

**Comment by isaacvandor** [comment]
Can confirm this is also happening to me on Windows 10 using Google Inbox and Google Hangouts.

**Comment by saenzramiro** [comment]
Ok, I will take a look.

**Comment by YesThatAllen** [comment]
I'm seeing this with Google Hangouts on my Mac. (I'm not seeing it with Slack or Trello)

-
> Rambox 0.4.4
> Electron 1.4.1
> darwin x64 16.0.0

**Comment by saenzramiro** [comment]
Yes, the other day I was seeing this bug in Hangouts. To stop notifications, just marking as read the conversation and it will stop notifying when all notifications queued are shown.

**Comment by zagapyan** [comment]
Confirmed that this issue is occurring on Mac OS Sierra in Google Hangouts.

**Comment by grberk** [comment]
Also seeing a constant Hangouts alert when I have a new message. I have to mark it as read in Hangouts for it to stop.
![chrome_2016-11-09_09-12-22](https://cloud.githubusercontent.com/assets/16178470/20143160/84e14694-a65d-11e6-9b37-233cc2636679.png)

**Comment by redbaron-gt** [comment]
Confirm that this issue is occurring on Arch in Google Hangouts.
Notification is constantly reappearing. Only way to stop is to make conversation read. 
It's very annoying!!!

**Comment by ekerazha** [comment]
I can confirm this issue with Hangouts on Windows 10.

**Comment by matejuh** [comment]
Same problem OS X El Captain.

Version: 0.4.5
Platform: darwin (x64)
Electron: 1.4.7
Chromium: 53.0.2785.143
Node: 6.5.0
