### ISSUE TITLE
You can't add a Messenger tab for FB@Work

### ISSUE THREAD

**Issue by Izin** [saenzramiro/rambox#417]
### Steps to reproduce

1. Add the service "Facebook Messenger"
2. Try to edit the URL to connect
3. Find that you can't and be stuck

### Why FB@Work?

I'm using both personal Fb account, and pro Fb account (my company use it too for intern communication and announces).

The URL to connect to our Facebook at Work is like this: https://companyName.facebook.com.

Could you provide us a way to setup an URL like this?

Thank you!

**Comment by saenzramiro** [comment]
Sure, I didn't have time to see Facebook at Work, but I will take a look ASAP.

In the meantime, did you try to add it as a [Custom Service](https://github.com/saenzramiro/rambox/wiki/Add-a-Custom-Service)?

**Comment by Izin** [comment]
@saenzramiro it works, but not the way I'd like. It's not a FB Messenger app, but the classic FB web page with everything. I dunno if it's possible to have just the conversations...

Thank's btw I wasn't aware of the Custom Service.

**Comment by saenzramiro** [comment]
Seems like Facebook have a mobile app called "Work Chat" that is only for messages, but it doesn't have any web app yet. You will have to wait until they release it and then, add it as a Custom Service.

Of course, we will add it too. 😉
