### ISSUE TITLE
Preferences save bug

### ISSUE THREAD

**Issue by saenzramiro** [saenzramiro/rambox#418]
### Steps to reproduce
1. Be sure to have Master Password activated.
2. Open Preferences.
3. Change one setting.
4. Save.
### Expected behavior

Save changes and close window.
### Actual behavior

It not saving and windows persist opened.
### ENVIRONMENT

> Rambox: v0.4.4
> 
> OS: Win 10
> 
> Arch: x64

**Comment by weeman1337** [comment]
It was a problem in the master password handling logic when saving the preferences.
I provided a PR with a fix.

**I suggest to test the preferences/master password behavior carefully before the next release.**
Because if it's not working the users are locked out!
