### ISSUE TITLE
Duplicate service tab

### ISSUE THREAD

**Issue by andsvb2** [saenzramiro/rambox#419]
Hi, first of all, sorry for my bad English.
The issue is that every time I close the Rambox, when I restart it, there is a duplicate tab for WhatsApp and TweetDeck.
One tab is the same that already existed, because my account is still logged in, but the other tab is just the same when you start a new service and will log in to start to use.

I'm using Mate 1.16.0, on updated Arch Linux.

## 

> Rambox 0.4.4
> Electron 1.4.1
> linux x64 4.8.2-1-ARCH

**Comment by saenzramiro** [comment]
Try to start over, remove all your services by going to Help menu, then Tools and Clear cache and Local Storage.

**Comment by isma94** [comment]
I have the same problem in Ubuntu 16.04 LTS 64-bit, but for me EVERY service gets duplicated after restart.

**Comment by saenzramiro** [comment]
@isma94 Did you try to do what I commented before?

**Comment by isma94** [comment]
Sorry for not responding in the time. Yes, and I haven't had this problem anymore.
