### ISSUE TITLE
RamBox consuming 50% less ram

### ISSUE THREAD

**Issue by franciscoluiz** [saenzramiro/rambox#423]
V8 JavaScript Engine: Fall cleaning: Optimizing V8 memory consumption
http://v8project.blogspot.com.br/2016/10/fall-cleaning-optimizing-v8-memory.html

this news will affect the chromium... which subsequently affect the electron, which then affect the RamBox?

**Comment by bendikl** [comment]
Nice, I think already the implementation of Rambox in electron is quite effective at handling RAM. Strangely if feels better than Chrome directly when using 10+ services.

**Comment by saenzramiro** [comment]
@franciscoluiz Right, we only have to wait. 😉
