### ISSUE TITLE
Top tabs. Too slow scrolling (frustrating UX)

### ISSUE THREAD

**Issue by bendikl** [saenzramiro/rambox#424]
Today when having more tabs than your window width you can click the arrows or scroll with mouse over the area to see more of them. Todays implementation is slow and very frustrating for the user. I`m suggesting that on click of arrow it should scroll to end (or to next width limit), same goes for mouse scroll, it should then do the same.

![5lcb4aaxal](https://cloud.githubusercontent.com/assets/9542610/19561363/b4a6f930-96d8-11e6-9a23-d4562ffc3e5e.gif)
### Steps to reproduce
1. Add tabs until at least 1,5X full width of window is covered. Or resize window so many tabs are out of range.
2. Click the arrow icon towards the hidden tabs or scroll with mouse over area.
### Expected behavior

Should scroll to next "section" or "paging" or until the end. Depends on difficulty of implementation, all should be acceptable and better than todays implementation.
### Actual behavior

Scrolls slowly when click arrows or scroll with mouse...very slow...very frustrating for the user.
### ENVIRONMENT

> Rambox: v0.4.4
> 
> OS: win32 (x64)
> 
> Arch: x64

**Comment by weeman1337** [comment]
I'll have a look and provide a PR soon.
