### ISSUE TITLE
Not getting any notifications

### ISSUE THREAD

**Issue by krambock** [saenzramiro/rambox#425]
### Steps to reproduce
1. On any service (whatsapp, Telegram, slack, Hangouts) set the notifications to on.  Also on Rambox I've the Show notifications marked. 
2. Get a new message
3. No desktop notification, only red icon
### Expected behavior

When you get a new message it should  show a notifications playing the sound, marks the icon as red, the tab with a red indicator. a window with the notification.. ie. Mightytext window showing the SMS text.
### Actual behavior

When you get a new message it doesn't show any notifications plays the sound, marks the icon as red, and the tab with a red indicator. but not getting any desktop notifications
### ENVIRONMENT

Version: 0.4.4
Platform: win32 (x64)
Electron: 1.4.1
Chromium: 53.0.2785.113
Node: 6.5.0

**Comment by saenzramiro** [comment]
What version of Windows are you running? Did you check if Don't Disturb mode is disabled?

**Comment by krambock** [comment]
I'm using Windows 7 Professional Edition.  Yes the first option I reviewed.. and it's not enabled.  Even it plays sounds when getting messages. but no other notification. 

Maybe I could check any other option? (ini, or config files?) I've also used a custom JS to review that the notifications are enabled and they are..

**Comment by saenzramiro** [comment]
AFAIK, Electron/Chromium don't support HTML5 notifications in Windows 7.
