### ISSUE TITLE
/lib/x86_64-linux-gnu/libidn.so.11: invalid ELF header

### ISSUE THREAD

**Issue by Pablohn26** [saenzramiro/rambox#429]
### Steps to reproduce

1. Upgrade all debian packages
2. Run Rambox

### Expected behavior

Start Rambox

### Actual behavior

Error: `error while loading shared libraries: /lib/x86_64-linux-gnu/libidn.so.11: invalid ELF header`

### ENVIRONMENT

> Rambox: v0.4.4

> OS: Debian 9. libidn.so.11.6.16

> Arch: x64 

Tried with deb, zip and appimage binaries

**Comment by saenzramiro** [comment]
Pablo, are you trying to run native Rambox or your own version?

**Comment by Pablohn26** [comment]
native Rambox.
I finally find out the problem and it is not related with Rambox. So I close this issue. Sorry about that.
