### ISSUE TITLE
Stays in ram

### ISSUE THREAD

**Issue by Hauwertlhaufn** [saenzramiro/rambox#43]
After ending rambox by clicking on the x of the window it remains in ram and contiues to use 655,9 MB.
The only way to end it is to restart the pc.

-
> Rambox 0.3.0
> Electron 1.2.5
> win32 x64 10.0.10586

**Comment by saenzramiro** [comment]
Rambox is not closing when you click the X. Instead it's minimizing to the system tray. The RAM used also depends of the services you add it.

You can quit by going to "File -> Quit" or right-click in the system tray icon.

**Comment by Hauwertlhaufn** [comment]
Thank you for your answer. But wouldn't it be more user-friendly to say that, before it minimizes or still have a open window which remains in the task bar, just like skype does?

**Comment by saenzramiro** [comment]
I couldn't understand your prev message, sorry.

Skype give you the option to have it allways opened in taskbar or in the system tray. If you click the X, it close the window but not quitting the app.

**Comment by Hauwertlhaufn** [comment]
But you can see, that skype still is open. Pressing x is the same as the minimizing it with left button. Rambox is then just visibe in the notification-area.

Another thing that I just found:
When you "quit" Rambox by pressing x and then open it again via the desktop icon, it opens a rambox completly new, instead of opening the old window that already runs.

**Comment by Jimi-James** [comment]
I'm wondering if you have a system tray at all? Skype, by default, "minimizes to tray", which is very much not the same thing as minimizing it with the left button. It closes the window completely, but keeps running, and the way to access it again after that is through its tray icon. That's the same functionality that Rambox has. Maybe what's going on here is Skype knows how to change its functionality when it detects that the desktop environment has no tray, and Rambox doesn't.

**Comment by Hauwertlhaufn** [comment]
[Youtube: How to Minimize Skype to System Tray](https://www.youtube.com/watch?v=omvK8ADIgu8)
Seems like that was on by default, after installation, for me. Maybe that's a possible opt-in function for rambox too?

And in my humble opinion the point of rambox is to run just one instance. Otherwise I just could run the official desktop versions of skype, wire, whatsapp and so on. Or what do you think?

**Comment by ekerazha** [comment]
@saenzramiro 
This behavior is unintuitive and problematic on Windows. I pinned Rambox to the taskbar and sometimes I "close" the window instead of minimizing it. Then I click the icon on the taskbar to re-open the window and it loads a new instance instead of re-opening the current instance. This is the reason why I'm switching back to Franz.

**Comment by saenzramiro** [comment]
I will fix this for the next release. It's a priority!
