### ISSUE TITLE
Suggestion: RSS/Atom Feed Reader

### ISSUE THREAD

**Issue by chmercesmoreira** [saenzramiro/rambox#430]
We already have email and messaging features integrated with the system, what about a feed reader?

Version: 0.4.4
Platform: linux (x64)
Electron: 1.4.1
Chromium: 53.0.2785.113
Node: 6.5.0

**Comment by MrChick** [comment]
Which one? 
I'm using my own tiny tiny rss as custom service

**Comment by chmercesmoreira** [comment]
I didn't know that it is possible to add custom services, I'm going to took a look at this.
