### ISSUE TITLE
Opening Rambox on login opens Terminal App

### ISSUE THREAD

**Issue by alextrastero** [saenzramiro/rambox#431]
### Steps to reproduce

1. Open Rambox on login
2. Terminal window opens
<img width="697" alt="screen shot 2016-10-25 at 10 07 41" src="https://cloud.githubusercontent.com/assets/4152819/19677756/0b53cbc6-9a9b-11e6-8c27-c785187009a8.png">

### Expected behavior

Don't open Terminal

### Actual behavior

Opens Terminal

### ENVIRONMENT

> Rambox: v0.4.4

El Capitan: 10.11.6 (15G1004)

> Arch: x64

**Comment by saenzramiro** [comment]
Duplicate #411
