### ISSUE TITLE
Add Shout IRC 

### ISSUE THREAD

**Issue by wolv-dev** [saenzramiro/rambox#434]
Due to kiwi irc not working (https://github.com/saenzramiro/rambox/issues/363), another IRC client should be added.

Maybe it's possible to add http://shout-irc.com/ even when it's not web based. But the client looks very good to me (see for yourself at http://demo.shout-irc.com/).

(Can't label it as new service)

**Comment by pztrn** [comment]
Shout is dead, it's better to add fork - https://github.com/thelounge

**Comment by pztrn** [comment]
My code for The Lounge, should work for Shout also:

```javascript
function checkUnread() {
    var e = document.getElementsByClassName("badge highlight");
    var t = 0;
    for(i = 0; i < e.length; i++) {
        if (parseInt(e[i].textContent.trim()) % 1 === 0 ) {
            t += parseInt(e[i].textContent.trim());
        }
    }
    updateBadge(t);
}

function updateBadge(e) {
    e >= 1 ? document.title = "(" + e + ") " + originalTitle : document.title = originalTitle
}
var originalTitle = document.title;
setInterval(checkUnread, 1000);
```
