### ISSUE TITLE
Add LinkedIn

### ISSUE THREAD

**Issue by quentinus95** [saenzramiro/rambox#439]
Hi!

It would be great to be able to have LinkedIn private messages inside the app.

Url: https://www.linkedin.com/messaging
Type: messaging

Thanks!

**Comment by pheijmans** [comment]
I have version 0.4.5 but i don't see the linkedin private messages service ?

**Comment by quentinus95** [comment]
The original version has been deleted and replaced by 0.5.0 because an urgent fix has been released weeks ago (check the right panel of this issue).
