### ISSUE TITLE
Rambox does not send passwords for some services

### ISSUE THREAD

**Issue by alien2003** [saenzramiro/rambox#442]
Rambox does not save login information for some services, at least for Protonmail, Openmailbox and Steam while Gmail and other popular services like Discord work fine.

-
> Rambox 0.4.4
> Electron 1.4.1
> win32 x64 6.3.9600

**Comment by saenzramiro** [comment]
Protonmail don't use sessions for now. (see [here](https://protonmail.uservoice.com/forums/284483-feedback/suggestions/9594603--keep-me-logged-in-option))

But other services, should save sessions.

Did you tried removing the service and add it again?

**Comment by alien2003** [comment]
Yes. Steam and Openmailbox don't work. Tutanota does. I think that's because of the same reason as Protonmail because I have the same problem with Steam and Openmailbox in my web browsers.
Any possible workarounds?

**Comment by gnidorah** [comment]
Same for me with Steam. It asks for password after resuming computer from sleep or restarting Rambox. But I had the same problem when was a Franz user. This seems to be the service policy itself.
@saenzramiro perhaps we could somehow modify cookies to last Steam session longer?

**Comment by saenzramiro** [comment]
@gnidorah I don't think so, we have to wait until Steam add this feature. For now, you can add custom JS code to inject your username and password into the fields automatically if you want.

About Openmailbox, I don't have an account to test it. @alien2003 Please test it in your default browser and see if keep your session opened.

**Comment by gnidorah** [comment]
@saenzramiro Thanks. No other possible options? Testing in a browser: I wonder why tab closing of Steam and then opening it again doesn't lead to logout, while browser restart leads.

**Comment by alien2003** [comment]
@gnidorah Openmailbox logs out when you close the web browser too. It's not a Rambox bug.

**Comment by gnidorah** [comment]
@alien2003 I understand. I'm asking what would be the possible out-of-box solution for people. Because it's really annoying to login so often.

**Comment by gnidorah** [comment]
@saenzramiro 
> For now, you can add custom JS code to inject your username and password into the fields automatically if you want

If I use synchronization, I guess my Steam password will then fly into the cloud? :-)
