### ISSUE TITLE
Discord chat text flickers on mouse hover

### ISSUE THREAD

**Issue by notnsane** [saenzramiro/rambox#443]
### Steps to reproduce

1. Open Discord
2. Open any server
3. Hover the mouse over some text in the main chat field

### Expected behavior

Nothing happens, text is displayed correctly.

### Actual behavior

Text flickers for half a second.

### ENVIRONMENT

> Rambox: v0.4.4
> OS: Windows 10
> Arch: x64

---

Notes: This doesn't happen with latest Chromium (Vivaldi snapshot release which is update to latest Chromium). Might have to do with GDI / DirectWrite font rendering: https://groups.google.com/a/chromium.org/forum/#!msg/chromium-dev/WzivQg8_drw/C8ZrRMLcAAAJ 

GIF of the issue: 

![rxccxgv](https://cloud.githubusercontent.com/assets/7162375/21988975/f98bdd96-dbe7-11e6-9fbc-cf906b8222a5.gif)

**Comment by averrin** [comment]
Maybe same bug, but i have worst

![image](https://cloud.githubusercontent.com/assets/426007/25747959/0b0af3d4-31b2-11e7-9ab1-82f34a972827.png)

**Comment by saenzramiro** [comment]
Wow! Is this happening in latest version 0.5.9?

**Comment by notnsane** [comment]
@saenzramiro yes, it's still happening. I have an AMD card (drivers fully updated), no idea if it changes anything

**Comment by khenderick** [comment]
It (behavior stated by @averrin) also happens on other chat services like Skype, WhatsApp and Slack.

**Comment by saenzramiro** [comment]
Did you tried by disabling Hardware acceleration in the Preferences?

**Comment by notnsane** [comment]
it still happens without Hardware Acceleration and it only happens in Discord in my case. I use Telegram, Whatsapp and Discord.

**Comment by khenderick** [comment]
It was disabled. I now enabled it, and everything seems OK now :+1:
