### ISSUE TITLE
Save Preferences doesn't work

### ISSUE THREAD

**Issue by antzpantz** [saenzramiro/rambox#444]
### Steps to reproduce

1. Log into Rambox
2. Go to Preferences
3. Change any setting
4. Press Save
5. Nothing happens

### Expected behavior

Settings are saved

### Actual behavior

Settings aren't saved. Not sure what else to say really.

### ENVIRONMENT

> Rambox: v0.4.4

> OS: Windows 10

> Arch: x64

Version: 0.4.4
Platform: win32 (x64)
Electron: 1.4.1
Chromium: 53.0.2785.113
Node: 6.5.0

**Comment by saenzramiro** [comment]
Duplicate #418
