### ISSUE TITLE
Global key shortcuts that start with ALT don't work in KDE Plasma

### ISSUE THREAD

**Issue by sebbuku** [saenzramiro/rambox#445]
### Steps to reproduce

1. Start typing.
2. Try to trigger global key shortcut that starts with the ALT key.
3. Menu opens and input field loses focus.

### Expected behavior

Menu should open only if you press another key for the menu (e.g. ALT + F for File Menu) and the input / textarea should keep the focus when using other ALT triggered shortcuts.

### Actual behavior

If I try to trigger ALT + SHIFT (my global shortcut for changing the keyboard layout) the File Menu opens. 

### ENVIRONMENT

> Rambox: v0.4.4

> OS: Kubuntu 16.10

> Arch: x64

**Comment by sebbuku** [comment]
Just saw this commit: https://github.com/saenzramiro/rambox/commit/7c1c03c95ccb7a4aefa3fe3ec16ed3ff719707d7.

I think that should solve the problem.

**Comment by saenzramiro** [comment]
@sebbuku Yes. 😉
