### ISSUE TITLE
Amium shows browser unsupported message

### ISSUE THREAD

**Issue by c-shankar** [saenzramiro/rambox#447]
### Steps to reproduce

1. Login to Amium

### Expected behavior
Should detect the user agent as Chrome or Firefox instead of electron.

### Actual behavior
Shows this message "Oops, this browser isn't supported yet!"

### ENVIRONMENT

> Rambox: v0.4.4
> OS: Ubuntu 16.04
> Arch: x64

**Comment by saenzramiro** [comment]
Do you still have this issue?

**Comment by saenzramiro** [comment]
I contacted Amium team and they said:

> Hi there - this is a browser compatibility error. It will be fixed in the future but at the moment we can't fix it. Hopefully you'll be able to add Amium back to your services list in the next version.
