### ISSUE TITLE
No tab/task bar notifications/badge update from GroupMe

### ISSUE THREAD

**Issue by grberk** [saenzramiro/rambox#448]
When I have GroupMe messages come in, there are no system tray/task bar notifications/badge updates. I haven't had any issues with Hangouts or FB Messenger.

### ENVIRONMENT

> Rambox: v0.4,4

> OS: Win10

> Arch: x64

**Comment by swrobel** [comment]
This doesn't seem to be working for me in 0.5.3 on Mac. I get Notifications with the Desktop Notifications setting enabled in GroupMe, but it doesn't badge the Rambox icon or the GroupMe tab...

**Comment by saenzramiro** [comment]
@swrobel We are currently have a bug related with that. We will try to fix it in next release.

**Comment by grberk** [comment]
So I'm now running on v 0.5.10, and this is still not working properly. Is there a fix for this coming?

**Comment by saenzramiro** [comment]
We will take a look on next release.

**Comment by saenzramiro** [comment]
GroupMe uses Angular and seems like they don't store in any variable or HTML element the unread count. Only when you are in the "Chats" section, the unread counter works. But if you change the section to another, it will remove the Chats section to replace it with the new one.

I couldn't find a way to get it, so I will keep this issue opened until someone can help us with this.
