### ISSUE TITLE
Icon incorrect size macOS

### ISSUE THREAD

**Issue by goodbytes-gb** [saenzramiro/rambox#45]
Not a massive issue but the app icon is too big and out of sync with the rest of the of the dock, it's kinda annoying.

<img width="225" alt="rambox" src="https://cloud.githubusercontent.com/assets/850149/16547204/3ccd65b4-415d-11e6-89d0-3853c33ca0fa.png">

As you can see it bleeds at the top and bottom... almost touching the 'open indicator'

Would be nice to see it the correct size.

**Comment by saenzramiro** [comment]
For a few pixels! Hehehehe!

I will take a look, but as you said, this is not critical.

Thanks!

**Comment by MartSerra** [comment]
I will submit the same request for running applications on OS X but I prefer update this in comment. Thanks for make this great application. 
![rambox_big_icon](https://cloud.githubusercontent.com/assets/7231751/17860500/2284e7e6-6853-11e6-9dd3-64ec8e5adb22.png)
