### ISSUE TITLE
Service tabs don't show their contents until I refresh the Rambox UI

### ISSUE THREAD

**Issue by ZaLiTHkA** [saenzramiro/rambox#453]
I've got Rambox set to "Start automatically...", with "Start minimized" disabled. When I log in and it launches, both my "Inbox" and "Skype" tabs show nothing but a white page. The services page on the app icon tab as well as adding a new service shows their respective content correctly.

If I reload the app with `ctrl+r`, then both my two usual registered services load without any problems, so this only seems to affect the initial app auto-load.

Just for reference, my desktop runs Mate on Linux Mint 18 and it gets internet through my WiFi. Normally this takes about 5 or 6 seconds from the time my wallpaper shows up, which makes me suspect Rambox is trying to load the pages before the online connection is actually there. I could temporarily run a physical LAN cable to my router to check this theory if need be, just let me know.

Thanks for sharing this app by the way; as just one of it's many perks, I'm so very glad to not have to deal with M$ Skype's horrid desktop UI anymore, yet I still get a desktop app.. (: Simply awesome.

-
> Rambox 0.4.4
> Electron 1.4.1
> linux x64 4.4.0-45-generic

**Comment by saenzramiro** [comment]
Thank you, I appreciate your words.

I think the same as you. Rambox is loading before you have internet connection. You can test it with a LAN cable and also just close it and open it again to check if the load process is working ok.

**Comment by ZaLiTHkA** [comment]
Apologies for the delayed response, I've had a pretty busy weekend and I only got to check up this now..

I confirmed the issue by checking the console output; I've got a bunch of `Failed to load resource: net::ERR_INTERNET_DISCONNECTED` errors when trying to load the resources.

Not sure if you can think of a more graceful way to handle this, but for now I've disabled the built-in auto start option, created a script containing the command `sleep 5 & /opt/Rambox/Rambox` and created a new startup entry pointing to that. This seems to be a long enough delay for my specific setup.

**Comment by saenzramiro** [comment]
Sure, I will try to handle that in a future relase.
