### ISSUE TITLE
It keeps starting on booting

### ISSUE THREAD

**Issue by felipeblan** [saenzramiro/rambox#455]
It keeps starting on booting even when i disabled it.

### Steps to reproduce

1. It starts when my OS boots.
2.  I disabled it from my startup apps.
3.  I keeps booting with OS.

### Expected behavior

Rambox used to not start when my machine boots.

### Actual behavior

It is booting at start even though i have disabled it several times.

### ENVIRONMENT

> Rambox: v0.4.4

> OS: Linux Mint 17.3

> Arch: x64

**Comment by saenzramiro** [comment]
Did you try by disabling from Rambox Preferences?

**Comment by felipeblan** [comment]
Now it is working. Thanks!
