### ISSUE TITLE
Riot, cert warning

### ISSUE THREAD

**Issue by pztrn** [saenzramiro/rambox#456]
Just added a Riot service to Rambox, and here we go:

![20161113_130006-window](https://cloud.githubusercontent.com/assets/869402/20244385/8d540fe2-a9a9-11e6-8111-e893601171f3.png)

When clicking OK page didn't continue to load. Checked certificate thru firefox - it is valid till September 2017. Checked date&time on my PC - all fine, NTP works.

I'm on rambox 0.4.4, gentoo current, with blocked tooltip.io CDNs thru hosts.

**Comment by saenzramiro** [comment]
Try to open Developer Console from Riot service and check all files to see which file have an invalid certificate.

**Comment by RobWJacob** [comment]
i have also some cert warnings
fresh installed rambox on windows 10 64bit
added gitter
got this error:

https://cdn.mxpnl.com/libs/mixpanel-2-latest.min.js

when i put this link into chrome, no cert error.

<img width="418" alt="gittercerterror" src="https://cloud.githubusercontent.com/assets/6211267/20381434/bada5ef2-aca7-11e6-8211-09ba82ddf993.PNG">

also my movim server, i use letsencrypt, works fine in chrome

or a blogpost in my movim session loads a img from https://cdn.serif.com
they use thawte

same behaviour on another windows 10 machine, they all worked before...

**Comment by saenzramiro** [comment]
Let's merge this with #460
