### ISSUE TITLE
Yahoo Mail Service

### ISSUE THREAD

**Issue by david-camden** [saenzramiro/rambox#458]
had Yahoo Mail Service integrated for longer
today at PC start rambox told me theres an "invalid authority certification". if it is custom service, i shall check the accept invalids button.

added yahoo mail as custom service and checked this button.
then theres an exception error message in javascript with many error lines.
i click ok, service is added with a blank screen and the error "invalid authority certification".
nothing more

[http://i.imgur.com/tun2p7i.jpg](http://i.imgur.com/tun2p7i.jpg)

[http://i.imgur.com/LTmfQnG.jpg](http://i.imgur.com/LTmfQnG.jpg)

what happend to yahoo mail service since yesterday?
-
> Rambox 0.4.4
> Electron 1.4.1
> win32 x64 6.1.7601

**Comment by 5moufl** [comment]
same as https://github.com/saenzramiro/rambox/issues/457 ?

**Comment by saenzramiro** [comment]
Let's merge with #460
