### ISSUE TITLE
Icon in Win10 Volume Mixer is too big

### ISSUE THREAD

**Issue by r15ch13** [saenzramiro/rambox#46]
The Icon in the Win10 Volume Mixer is too big.

![rambox-big-icon](https://cloud.githubusercontent.com/assets/432127/16556470/90d10f9e-41da-11e6-9e94-ba9f71397bd6.png)

That are a few more pixels than in #45 :smile:

**Comment by saenzramiro** [comment]
Hahaha! Just a few more pixels!

Ok, I will take a look. Thanks!
