### ISSUE TITLE
General certificate issue

### ISSUE THREAD

**Issue by gnidorah** [saenzramiro/rambox#460]
There are now certificate warnings with many services. This needs hotfix asap. With ICQ it even locks the entire Linux interface (KDE). There are now a lot of bug issues about concrete service.

**Comment by gnidorah** [comment]
https://github.com/saenzramiro/rambox/issues/459
https://github.com/saenzramiro/rambox/issues/458
https://github.com/saenzramiro/rambox/issues/457
https://github.com/saenzramiro/rambox/issues/456

**Comment by rokups** [comment]
Skype affected as well.

**Comment by bundyo** [comment]
I can confirm - Skype's MS login is blocked, Facebook one works.

**Comment by Pegasuz** [comment]
I have the same problems with Outlook 365 and skype

**Comment by saenzramiro** [comment]
Because we didn't release any update for Rambox since 26 September, I think the massive invalid certification is related with services that all those services use. I know is weird, because they are all "serious" companies, but it happens. A few months ago, we have something similar with Kiwi IRC and the problem was related with Kiwi team ( #339 ). 

Let's wait a few days and see if the problem is solved, and if is not, I will release a minor release removing that message or something similar.

**Comment by rokups** [comment]
Uhm but these services work just fine in the browser, just not in rambox.

**Comment by Hasimir0** [comment]
I can confirm what rokups said.
Skype works normally from the web browser, while Rambox suddenly stopped working properly.

**Comment by saenzramiro** [comment]
Ok, so I will investigate what's happening.

**Comment by ekerazha** [comment]
Franz seems to work fine, too.

**Comment by pztrn** [comment]
Looks like issue caused by https://bugs.chromium.org/p/chromium/issues/detail?id=664177

**Comment by 88scythe** [comment]
Linkedin (via Custom Service https://www.linkedin.com/messaging) is also affected.

**Comment by saenzramiro** [comment]
@ekerazha AFAIK, Franz don't let the user know there are certificates invalid.

**Comment by CrashyBang** [comment]
Same issue with gitter.

**Comment by antzpantz** [comment]
Same issue with Yahoo! Mail and Yahoo! Messenger.

**Comment by rokups** [comment]
If it is what @pztrn said wouldnt releasing update with updated electron solve the issue? Would try myself but with given instructions it does not build..

**Comment by ZEROF** [comment]
Hi,

Just for up to date info, on my side yahoo, office365 have this issue and kwirc show only blank page.

**Comment by alien2003** [comment]
The same problem with Spype

**Comment by rrhutch** [comment]
I am having the Certificate warning issues on Voxer, MightyText, HootSuite, and Slack. I wasn't clear from this issue post whether a solution had been arrived at or not.

**Comment by saenzramiro** [comment]
I will release a minor release tomorrow fixing the Certificate warning.

**Comment by pztrn** [comment]
Great, looking forward for new release ^_^.

**Comment by ZaLiTHkA** [comment]
I was getting this with Gitter the last time I tried, just activated the service again after the 0.4.5 update and it's working perfectly now. :) Thanks @saenzramiro.

**Comment by bundyo** [comment]
Electron 1.4.12's fix seems interesting ;)

http://electron.atom.io/blog/2016/12/09/certificate-transparency-fix

**Comment by ZaLiTHkA** [comment]
@bundyo, excuse my ignorance here, but I'm not sure what you find interesting about it.. They just [updated](https://github.com/electron/electron/pull/8176) the `libcc` library to a version that doesn't have that problem.

**Comment by Ara4Sh** [comment]
Hello 
Same problem on Skype 
```
Version: 0.4.5
Platform: linux (x64)
Electron: 1.4.7
Chromium: 53.0.2785.143
Node: 6.5.0
```

**Comment by rokups** [comment]
Yup problem is back. We need electron update.

**Comment by bundyo** [comment]
@ZaLiTHkA, did you check the issue it fixes and why iy warranted separate update? Also that's why 0.4.5 failed again. :)

**Comment by cyboman32** [comment]
+1 problem is back

**Comment by nstrelow** [comment]
Same here for all services

**Comment by rokups** [comment]
@saenzramiro you had a chance to do bunch of merges but not a new build? Please do not neglect this. People are depending on rambox for their communications and periodically we are cut out for multiple days. This is not cool at all. There should be some kind of time-based release schedule updating electron at least so we do not get hit with certificate timebomb.

**Comment by gnidorah** [comment]
@saenzramiro For whatever reason Franz never had this issue (and I have an old version)

**Comment by henry49100** [comment]
Hello team, I can't even access to the mySms logon page et get same error popup. Doesn't work even when I enable the option "trust invalid certificate".

**Comment by antzpantz** [comment]
Might be a good idea to mention that if you are incredibly reliant on this 'free' software, the best way to support the project is to donate some money!

**Comment by gnidorah** [comment]
Continuing in https://github.com/saenzramiro/rambox/issues/573

**Comment by sverhagen** [comment]
Although the economic value of open source software does not just come from financial donations, I certainly _do_ donate money to open source projects. But I generally do it after using a particular tool for a long time. I've only recently started using Rambox, and while I appreciated it, when it worked, that's a sentiment quickly nullified when critical defects aren't addressed. While donating is voluntary, _so, too, is contributing_, so I think we all hugely appreciate your effort to this cause. But it _is_ strange and disappointing to see that the maintainers aren't jumping on this issue, to make a new version available users. (Is this just not an issue for everyone? I really don't understand why this would not be your first priority, even when donations aren't pouring in.) And doing regular merges of other things just _does_ feel strange, while some of us are clicking our way through never ending certification warnings. So, with the utmost respect for all you've done for this open source project, I ask you: _would you please make a new version available?_

**Comment by Izin** [comment]
For 25 people complaining, you have perhaps 100 users uninstalling it just because of this problem with certificates. And the more we wait for a solution, the more you lose users.

I love Rambox and use it every single day. Please, just do something to prevent the problem in the future, thanks @saenzramiro :S

**Comment by thepaandu** [comment]
+1 skype zoho

**Comment by ColinLeverger** [comment]
+1 skype, also have problems with some certs on messenger!

**Comment by bblaha** [comment]
+1

**Comment by vengomatto** [comment]
+1 skype
slack and whatsapp are working

**Comment by Fil** [comment]
Same problème on several services.
I'd take a version that doesn't beep and block, but just silently refuses to load those resources.

**Comment by Xqua** [comment]
The certificate for the service are fine for me, 
BUT it looks like the error comes from displaying a Tumblr or cloudfront or other service in a service 
Example: I'm on Slack and there is a tumblr GIF posted, the https of Tumblr pops up a certif warning because it is not the Slack one ? 
If not then it's that the CA root validation system is getting corrupt somehow ? What are you using ?

**Comment by twinklebob** [comment]
I know the main developers are probably busy working on Rambox 1.0, which by the sneak previews they gave us is looking like it'll be great. But can we not look at switching Electron in the current version. It's not something I've played with before, otherwise I'd probably have a go at it myself. According to http://electron.atom.io/blog/2016/12/09/certificate-transparency-fix version 1.4.12 doesn't have this recurring issue. Hopefully they're not just ignoring the warnings.

**Comment by rokups** [comment]
Electron was updated [two days ago](https://github.com/saenzramiro/rambox/commit/2030ad025e528a44a89d94da4bc46d60a0690163). All we need is a freakin new build/version bump.

**Comment by balasankarc** [comment]
I am still getting Certificate error for Riot.

**Comment by sbuysse** [comment]
Hum, not the first to complain, no much news. I guess I will take a look at Franz again. Too bad :/

**Comment by Xqua** [comment]
@rokups @twinklebob if you know how to build a node app like this and update electron could you take a look here ?
https://github.com/saenzramiro/rambox/wiki/DEPLOYMENT

**Comment by erzzo** [comment]
+1

**Comment by ZEROF** [comment]
Yep this issue as back on my side as well, one week without update.

**Comment by saenzramiro** [comment]
Please update to version 0.5.3!

**Comment by Xqua** [comment]
Solved with latest Update ! Thanks ! <3 <3 <3
