### ISSUE TITLE
Issue with font-awesome

### ISSUE THREAD

**Issue by KonradHolubek** [saenzramiro/rambox#461]
### Steps to reproduce

1. I use Rambox with a CRM called Insightly
2. Since today, when I log into  Insightly for the first time or when I make a change in a record I get an alert about Font Awesome

### Expected behavior

No alert

### Actual behavior

The alert is : 

"The service with the following URL has an invalid authority certification.

https://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css

If is a Custom Service, you have to remove it and add it again, enabling the "Trust invalid authority certificates" in the Options."

### ENVIRONMENT

> Rambox: 0.4.4

> OS: Mac OS Sierra 10.12

> Arch: x64 

Thank you, 

Konrad

**Comment by saenzramiro** [comment]
Let's merge with #460
