### ISSUE TITLE
Having issues with MightyText certficates

### ISSUE THREAD

**Issue by samuraicer** [saenzramiro/rambox#463]
Upon start up of Rambox, there are a bunch of certificate errors that pop up relating to the MightyText certifcates for it's web app.
![screenshot from 2016-11-14 17-08-32](https://cloud.githubusercontent.com/assets/8301499/20284872/03f090e2-aa8d-11e6-8b51-ba29f95e930f.png)

-
> Rambox 0.4.4
> Electron 1.4.1
> linux x64 4.4.0-47-generic

**Comment by saenzramiro** [comment]
Duplicate #460
