### ISSUE TITLE
Cannot login to Office 365

### ISSUE THREAD

**Issue by grzegor** [saenzramiro/rambox#465]
Cannot login to Office 365:

"The service with the following URL has an invalid authority certification.
https://secure.aadcdn.microsoftonline-p.com/ests/2.1.5104.7/content/cdnbundles/login.min.css
If is a Custom Service, you have to remove it and add it again, enabling the "Trust invalid authority certificates" in the Options."

Rambox: v0.4.4
OS: macOS 10.12.1

**Comment by saenzramiro** [comment]
Duplicate #460
