### ISSUE TITLE
Popup about https pictures with Zoho email connector

### ISSUE THREAD

**Issue by tbondois** [saenzramiro/rambox#466]
With Zoho email connector, in lot of html emails i have theses popup (sometimes 50 for a same email, and i need to close every of them because it block all others interactions with Rambox) : 

Certification Warning

see picture :  
![rambox_zoho_popup](https://cloud.githubusercontent.com/assets/11269723/20312066/6a679d1e-ab52-11e6-94b1-b1cfdce3171b.png)

I don't find options to enable that https certificates (which should be valid i think)

-
> Rambox 0.4.4
> Electron 1.4.1
> win32 x64 10.0.14393

**Comment by tbondois** [comment]
and i don't have problems when I open theses email with the Zoho web client, pictures are displayed correctly. If at least you could prevent theses popups to open (even if pictures are not displayed), or give the proper option about certificates in Rambox.
Because in state, Zoho email in barely usable.

**Comment by Rictus** [comment]
I'm having the same problem with Outlook.

**Comment by saenzramiro** [comment]
Related with #460
