### ISSUE TITLE
Ext.cq1 is not a function

### ISSUE THREAD

**Issue by rokups** [saenzramiro/rambox#467]
### Steps to reproduce

1. git clone https://github.com/saenzramiro/rambox.git
2. npm install
3. Configure env-sample.js and rename it to env.js.
4. npm run sencha:compile
5. npm start

### Expected behavior

Application should start, added services should appear as tabs and work.

### Actual behavior

Application starts, services can be added but they do not appear as tabs. Console displays `Ext.cq1 is not a function` error.

### ENVIRONMENT

Rambox: v0.4.4 and HEAD

OS: Archlinux

Arch: x64

NodeJS: v7.1.0

npm: v3.10.9

**Comment by saenzramiro** [comment]
Try before step 5, to run:
`cd build/production/Rambox`

**Comment by rokups** [comment]
If i do that i get following error:

> npm ERR! missing script: start

**Comment by saenzramiro** [comment]
Oh, my bad.

So instead of step 4, do:

`sencha app watch`

**Comment by rokups** [comment]
That worked. After i ran this command it stopped showing:

> [INF] Waiting for changes...

Closed it with `Ctrl-C` and then `npm start` launched correctly working application. Maybe it should be reflected in quick start section of readme.

P.S. I tried updating electron to 1.4.6 and it solved certificate errors.

**Comment by saenzramiro** [comment]
@rokups Yes, I will update the quick start section.
Thanks for the feedback, I will consider upgrade to 1.4.6.

**Comment by alexdevero** [comment]
I just run into this issue as well after trying to run rambox following the instructions in quickstart. Running `sencha app watch` helped. This command should be mentioned in quickstart.
