### ISSUE TITLE
Issue with skype

### ISSUE THREAD

**Issue by ZeekHuge** [saenzramiro/rambox#469]
I added the Skype into the services and then tried to login into it, but a white-blank screen appears with following 5 dialogue boxes :

> The service with the following URL has an invalid authority certification.
> 
> --Link--
> 
> If is a Custom Service, you have to remove it and add it again, enabling the "Trust invalid authority certificates" in the Options.

There were 5 different --links-- in those 5 different dialogue boxes-
1. https://auth.gfx.ms/16.000.26754.00/DefaultLogin_PCore.js
2. https://auth.gfx.ms/16.000.26754.00/DefaultLoginPaginatedStrings.EN.js
3. https://auth.gfx.ms/16.000.26754.00/DefaultLogin_PCore.js
4. https://auth.gfx.ms/16.000.26754.00/DefaultLoginPaginatedStrings.EN.js
5. https://auth.gfx.ms/16.000.26754.00/Default1033.css 

Skype is working fine on my browser, so I even tried to add it as a Custom_service to Rambox, but the result was same.

> Rambox 0.4.4
> Electron 1.4.1
> linux x64 4.4.0-45-generic

**Comment by c-shankar** [comment]
you can refer to the previous conversation https://github.com/saenzramiro/rambox/issues/460

**Comment by saenzramiro** [comment]
Like @c-shankar said, it's related with #460 .
