### ISSUE TITLE
Protocol: ICQ

### ISSUE THREAD

**Issue by lancetekk** [saenzramiro/rambox#47]
I am not sure how difficult that might be - and if its even worth the effort, since icq isn't that popular anymore. Since the protocol is rather closed source, i can imagine this being a bigger issue.
It might be possible to look at other GPL-licensed software (looking at you, Miranda-IM) for some help with the icq service.

I think it would be a nice addition, if the effort is worth the increased usability.

**Comment by saenzramiro** [comment]
I think that Rambox needs to be outside of having an internal messaging app. But searching I found that ICQ have a web app. (https://web.icq.com/)

So I will add it for the next release.
