### ISSUE TITLE
Non-existing notifications shown in slack

### ISSUE THREAD

**Issue by IvanBashkirov** [saenzramiro/rambox#471]
One of my slack teams constantly displays 16 notifications. Can't clear it. Moreover, notifications work totally fine on another slack team. What I did:

- Checked the desktop app version and the web app version. No notifications there. 
- Closed all channels (except the main one) and DMs.
- created unreads channel and made sure it's empty
- Set notifications settings to none (both general and channel specific). 
- Reloaded the service.
- Reloaded Rambox.
- Closed/launched rambox.
- Deleted/recreated slack service. Shows same 16 notifications even when created with 'don't show notifications' option.

Any ideas?

P.S. Rambox is awesome otherwise, thanks for doing such a great job.

Using with MacOS Sierra 10.12.1

-
> Rambox 0.4.5
> Electron 1.4.7
> darwin x64 16.1.0

![screen shot 2016-11-18 at 22 21 00](https://cloud.githubusercontent.com/assets/20935063/20443840/aca06f1e-addf-11e6-915b-b0db6d6cb106.png)

**Comment by IvanBashkirov** [comment]
UPDATE: when an actual notification is reveived the number changes to the correct one. So if I get a direct message or a mention it will display '1' or '2', etc. But as soon as I read the messages it changes to '16'.

**Comment by saenzramiro** [comment]
I think is related with your configuration with Slack. I always tested with the default view, so please be sure to have **All my channels and DMs** only selected in **Preferences -> Advanced -> Channel List**.

**Comment by IvanBashkirov** [comment]
Have that selected, still that 16 notifications, really odd. Can't reproduce the error either, only shows up in this channel.

**Comment by saenzramiro** [comment]
😕

**Comment by nmat** [comment]
I have seen lots of fixes regarding reading of messages for slack. Do you still get this behaviour? In release notes for slack at least there is a few fixes for it.

**Comment by IvanBashkirov** [comment]
I have many slack group in rambox, and it only happens with this one. All others work fine. Using the group in the standalone application also works fine. Even if I choose to mute all notifications in Slack preferences it still shows that 16, very odd 😆

**Comment by saenzramiro** [comment]
Can you execute the following code in Slack's developer console? (right click in the Slack tab and Dev. Console).

`var a = 0,
    b = 0;
$(".unread_msgs").each(function() {
    a += isNaN(parseInt($(this).html())) ? 0 : parseInt($(this).html())
}), $(".unread_highlights").each(function() {
    b += isNaN(parseInt($(this).html())) ? 0 : parseInt($(this).html())
}); console.log(a, b);`

Then tell me the values of a and b.

**Comment by IvanBashkirov** [comment]
@saenzramiro 0 0

**Comment by IvanBashkirov** [comment]
The only way to get read of it is to untick 'Display tab unread counter'. That of course means that I don't get any notifications at all for unread messages.

**Comment by saenzramiro** [comment]
Please execute `document.title` and tell me the value.

**Comment by IvanBashkirov** [comment]
Ah, I think you got it pinned down. `document.title` reveals "Coursera Machine Learning (June '16) Slack". Thought there must be something funny going on with how it sees that number in the title and indeed when I executed `document.title = "Coursera Machine Learning (June '14) Slack", the unread messages badge showed '14' for couple of seconds (then it went to 16 again, I guess by resyncing).

**Comment by saenzramiro** [comment]
Gotcha! Consider to inject custom JavaScript code to change document title to another text without number.
