### ISSUE TITLE
Unable to add services when login (with user and google) Bug.

### ISSUE THREAD

**Issue by alecuba16** [saenzramiro/rambox#472]
#Login with user pass or google and I'm unable to add services. there is one service that is empty and not editable/removable.

With thw developer tools opened I can see the following error:
 USER NOT LOGGED IN
app.js:1 Uncaught TypeError: Cannot read property 'get' of null
file:///C:/Users/pc/AppData/Local/Rambox/app-0.4.5/resources/app.asar/resources/icons/ Failed to load resource: net::ERR_FILE_NOT_FOUND

I tried:
-reinstall, clear cache with F5 and developer console with disable cache
-remove the rambox folder and reinstall again.

The file app.asar exists.

Without login I'm able to add services.

Im able to replicate it in 3 windows 10 and one gentoo linux, maybe is account related problem?

> Rambox 0.4.5
> Electron 1.4.7
> win32 x64 10.0.14393

**Comment by saenzramiro** [comment]
I think your account have wrong saved data and that caused the problem. Please send me your accounts details and I will reset it. You can log in in Gitter and send me a PM.

**Comment by alecuba16** [comment]
The account was fixed.  Ramiro found that the data might be causing the problem.

Thanks ramiro.
