### ISSUE TITLE
popup with annoying text without information about chat service

### ISSUE THREAD

**Issue by andrius** [saenzramiro/rambox#476]
I am constantly receiving following message:

https://dl.dropbox.com/s/r5esxrxdxz1zr5a/Screenshot%202016-11-22%2011.41.20.png

That happens for more than one week already and if it would be some chat message or gif, it would disappear by now.

Also it's not informative at all, I do use 9 chat services and do not understand which one sending this text

**Comment by saenzramiro** [comment]
Did you updated to the latest version of Rambox (v0.4.5)?

**Comment by andrius** [comment]
yes, at day of release

**Comment by saenzramiro** [comment]
Well... so you are using a custom service with an invalid certificate.

If you load the following URL in Google Chrome:

> http://fastly.cedexis-test.com/img/20367/r20.gif

You will see that have an invalid certificate.

**Comment by andrius** [comment]
Please explain what is 'custom service'? I use skype, facebook messenger, whatsapp, slack. They have valid certificate and this message is returning all the time

**Comment by saenzramiro** [comment]
Try to disable one service at a time to see who is causing this warning.
Disable a service by clicking the checkbox in the "Enabled Services" list, then Ctrl + R to reload Rambox. Continue with other services until you find it.
