### ISSUE TITLE
Repeated Hangouts notifications in macOS sierra

### ISSUE THREAD

**Issue by aljimmix** [saenzramiro/rambox#478]
### Steps to reproduce

1. Open Rambox, add the Hangouts and start a conversation
2. Change focus
3. Receive a message in such conversation

### Expected behavior

Get a system notification and sound (if configured) with the text "Hangouts - you have 1 new message"

### Actual behavior

The notifications appears, sounds 4 times, closes itself and reappears. This keeps happening until you make the Hangouts conversation be 'marked as read' (meaning: you interact with the conversation)

### ENVIRONMENT

MacOS sierra on MacBook Pro Late 2015.

> Rambox: v0.4.5 (this didn't happen before, only started to happen when I updated yesterday to the latest version)

> OS: macOS sierra fully updated (v10.12.1)

**Comment by saenzramiro** [comment]
Duplicate #415.
