### ISSUE TITLE
Whatsapp doesn't work

### ISSUE THREAD

**Issue by tlesch** [saenzramiro/rambox#48]
Whatsapp doesn't work. When I create a new whatsapp tab it remains blank.

**Comment by lancetekk** [comment]
Did you try to close/restart the application or use the reload feature? Worked for me after a refresh.

**Comment by tlesch** [comment]
try it several time to reload, reinstall, reopen, still the same problem. I’m on Mac Yosemite.
> On 4 Jul 2016, at 13:50, Lorentz Roßbacher <notifications@github.com> wrote:
> 
> Did you try to close/restart the application or use the reload feature? Worked for me after a refresh.
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub <https://github.com/saenzramiro/rambox/issues/48#issuecomment-230273019>, or mute the thread <https://github.com/notifications/unsubscribe/AEEbIJFyOrm-TT6w3o5FKjNUJ0rGFlW8ks5qSPN0gaJpZM4JESMk>.
> 

Tilman Lesch
tilmanlesch@gmail.com <mailto:tilmanlesch@gmail.com>
tilmanlesch.com <http://tilmanlesch.com/>

**Comment by saenzramiro** [comment]
Did you check if you have the Internet connection working? If you try to open WhatsApp in your default web browser, works?

Works fine for me also. :confused:
