### ISSUE TITLE
Unable to login in TweetDeck

### ISSUE THREAD

**Issue by eudennis** [saenzramiro/rambox#481]
### Steps to reproduce

1. Add a new TweetDeck account
2. Try to login

### Expected behavior

It should login, but it doesn't do nothing.

### ENVIRONMENT

> Rambox: v0.4.5

> OS: Ubuntu

> Arch: x64

**Comment by saenzramiro** [comment]
Please, try to clear your cache and localStorage by going to **Help** -> **Tools**.

**Comment by eudennis** [comment]
Didn't work :/

**Comment by saenzramiro** [comment]
Can you record a video please?

**Comment by eudennis** [comment]
https://www.dropbox.com/s/9o7sj7y6axzjx3z/example_rambox.mkv?dl=0

**Comment by saenzramiro** [comment]
Got it, the problem seems to be with a 2FA.

Let's merge this with #403.
