### ISSUE TITLE
No tray or launcher notifications from certain services

### ISSUE THREAD

**Issue by msbentley** [saenzramiro/rambox#482]
Certain services are not updating the unread count in the Unity launcher or changing the tray icon colour, but do show unread notifications in the app and/or play sounds/pop up desktop notifications.

Apps that work OK: Skype, FB Messenger, Hangouts, Wire
Apps that don't work: Rocket Chat, Slack

### ENVIRONMENT

> Rambox: v0.4.5 (Electron: 1.4.7, Chromium: 53.0.2785.143, Node: 6.5.0)
> OS: Ubuntu 16.10
> Arch: x64

**Comment by saenzramiro** [comment]
Can you share screenshots or a video?

**Comment by msbentley** [comment]
Sure! Here are two examples for services from each of the lists above, first Skype (working) and then Rocket (not working):

![rambox_skype](https://cloud.githubusercontent.com/assets/1671065/20626717/c9b8fcec-b31b-11e6-8b8e-c034400830ac.png)

![rambox_rocket](https://cloud.githubusercontent.com/assets/1671065/20626730/dc7317aa-b31b-11e6-8851-97d76980c854.png)

**Comment by saenzramiro** [comment]
That's ok. We only notify in tray icon when you have private messages. That's why the first screenshot is red (because of Skype) and the second is white.

So group notifications is notified by a badge with a dot but not in the tray.

**Comment by msbentley** [comment]
Thanks for the answer! Would it be possible to make it optional to get notifications (in Slack, Rocket) for messages in any channel? For me this is critical since these are the primary services I use, and without notifications of activity I can't keep track of conversations...
