### ISSUE TITLE
Services do not get focus when Rambox is focused by mouse click.

### ISSUE THREAD

**Issue by justfortherec** [saenzramiro/rambox#483]
This is related to issues #180  and #262 which were said to be fixed already.

Services do not get focus when switching from other applications to Rambox. That means that I always have to click twice to focus text fields. When switching with Alt+Tab, focus is correctly left in previously selected text fields, but not when clicking (anywhere) in the Rambox window.

Another observation: When clicking on the service icon in the tab bar, instead of in a text field, focus is not correctly set to the text field if it was focused before focusing another application.

### Steps to reproduce

1. Focus any other window than Rambox.
2. Focus Rambox again by clicking on text input field.

### Expected behavior

- Text input field has input.
- I can start typing immediately.

### Actual behavior

Text field has focus for a split second (cursor is visible) but focus is lost immediately.
A second click in text field is necessary to focus the service and be able to start typing.

### ENVIRONMENT

- Version: 0.4.5
- Platform: linux (x64)
- Electron: 1.4.7
- Chromium: 53.0.2785.143
- Node: 6.5.0

**Comment by TMartinPPC** [comment]
I have this exact same issue on Ubuntu 16.04 x64 but can confirm that it doesn't happen to me on MacOS Sierra.

**Comment by saenzramiro** [comment]
This is an Electron bug, see here: https://github.com/electron/electron/issues/5900

We will use @paulcbetts code in https://github.com/electron/electron/issues/5900#issuecomment-224174095.
