### ISSUE TITLE
Zoom not working

### ISSUE THREAD

**Issue by alfonsoabadc** [saenzramiro/rambox#484]
Hi there. I'm new at Rambox. I have three accounts (Whatsapp, Hangouts and FB Messenger). I see it very small, so I left click the tab and select Zoom in, but whenever I choose a diferent conversation the zoom goes back to normal so I have to Zoom in again and so on. 

-
> Rambox 0.4.5
> Electron 1.4.7
> win32 x64 10.0.14393

**Comment by Novack-** [comment]
Same here.

**Comment by guedressel** [comment]
See #426
