### ISSUE TITLE
Telegram unread-count flapping

### ISSUE THREAD

**Issue by Luzifer** [saenzramiro/rambox#485]
### Steps to reproduce

1. Add a Telegram tab
2. Switch to another tab
3. Receive a "secret chat" message (direct message)
4. Don't touch that message on any device
4. Watch the unread-count

### Expected behavior

Unread-count increases to one, stays at having one unread message

### Actual behavior

See this `gif`: (In case it does not move see it [here](http://knut.cc/1W0K0O051o0z))
![](https://d3vv6lp55qjaqc.cloudfront.net/items/310K3e2B3T3L0Q2Z0G44/Screen%20Recording%202016-11-24%20at%2007.24%20PM.gif)

### ENVIRONMENT

> Version: 0.4.5
> Platform: darwin (x64) (macOS Sierra 10.12.1 (16B2555))
> Electron: 1.4.7
> Chromium: 53.0.2785.143
> Node: 6.5.0

**Comment by justfortherec** [comment]
I can confirm this. It happens both for Telegram and Hangouts in my case.

**Comment by GoodSoulGermany** [comment]
Confirm (Hangouts)

**Comment by pedropapa** [comment]
Confirmed only in Telegram, the unread count is indeed blinking and sometimes I don't receive sound alerts or anything when a new message arrives.

OS: macOS Sierra

**Comment by DBX12** [comment]
Confirm with Telegram (not a Hangouts user) on `Linux 4.4.0-51-generic #72-Ubuntu SMP  x86_64 GNU/Linux`
Is there a JavaScript snippet to stop the flickering temporarily until a permanent solution is found by the developer?

**Comment by weeman1337** [comment]
#523 suggests a "web view API" for setting the unread count explicitly via messages from the service code. Maybe it can help preventing flickering.
