### ISSUE TITLE
Cannot login to Slack using SSO

### ISSUE THREAD

**Issue by iliyang** [saenzramiro/rambox#486]
My organization uses single sign-on for Slack exclusively, i.e. I must use SSO to use Slack, and when I open http://myorganization.slack.com there's an SSO button for login, which when I click I get a blank page and cannot login. I'm attaching screenshots below.

### Steps to reproduce

1. Add a Slack account for organization
2. Click "Sign in with Organization SSO" button

### Expected behavior

In a regular browser, when I click the "Sign in with Organization SSO" button, I'm being redirected to a blank company web page which pops up a standard browser user/password dialog box for me to enter my credentials, and then I'm redirected back to Slack. I've put a screenshot at the very bottom of this post.

### Actual behavior

In Rambox, when I click the "Sign in with Organization SSO" button, I'm probably still redirected to that blank company web page, but the login dialog box doesn't pop up, so I can't login.

### Suggestion for a fix

I see two options:
1. If I could somehow copy the Slack authentication cookie from my Chrome browser to Rambox, this could solve the issue, as it would bypass the login process inside Rambox. I tried messing with the "Cookies" file in the slack settings in AppData, but without success.
2. But ideally, Rambox shouldn't block the login dialog box in the first place and let me log in directly.

### ENVIRONMENT

> Rambox: v0.4.5

> OS: Windows 10

> Arch: x64

<br/>

#### This is how the Slack login page looks for me.

![image](https://cloud.githubusercontent.com/assets/802594/20623846/80457366-b301-11e6-95fc-8998a2ca072c.png)

<br/><br/>
#### But then I press the SSO button, this is what I get - a blank page with no login popup.

![image](https://cloud.githubusercontent.com/assets/802594/20623851/83ad9ede-b301-11e6-9b96-fd67730fe2c9.png)

<br/><br/>
#### And this is how the login web page appears in Chrome:

![image](https://cloud.githubusercontent.com/assets/802594/20624116/ee821770-b302-11e6-8b08-51e7054d88e3.png)

**Comment by saenzramiro** [comment]
Yes, SSO in services don't work in Rambox when the service opens a URL in the default browser. If the service is configured to open a popup, works.

I have to find a way to solve this, but for now, I couldn't. Sorry.

There is another issue talking about this, so I will close it.

**Comment by eryshev** [comment]
Hi @saenzramiro,

We still have this issue.
Could you elaborate more this point ?

> If the service is configured to open a popup, works.

Could Slack service be configured in a good way or you talking about authentication service???

Or if there is an open issue about it could you point me out to it because I like you application but can't use it with my company authentication :(

**Comment by iliyang** [comment]
@eryshev What I did was to bypass the authentication in Rambox by simply importing the cookies that Slack sets in my browser. That is, I opened Slack in my Chrome browser, then I opened the developer tools window, got all the cookies and pasted them in Rambox's "Custom Code" section in the Slack service settings. The code I currently have there is (with some identifiers stripped out for security):

```javascript
document.cookie = 'b;expires=Thu, 01 Jan 1970 00:00:00 GMT';
document.cookie = 'b=SOME_RANDOM_GIBBERISH; domain=.slack.com';
document.cookie = 'a-20975202787=MORE_RANDOM_GIBBERISH; domain=.slack.com';
document.cookie = 'a=20975202787; domain=.slack.com';
```

Now every time I (re)load Rambox, Slack logs in automatically using these cookies and I can use it.

**Comment by eryshev** [comment]
Thank you @iliyang, it works!:)
Do you know how long the slack session lasts? 
Cookies are valid for a long period of time...

**Comment by iliyang** [comment]
I've been using the same config for months. In fact, maybe even close to a year now!

**Comment by eryshev** [comment]
@iliyang it seems like a long living solution, thank you again :1st_place_medal: I will try to use it with some outlook services now!

**Comment by iliyang** [comment]
Cheers and good luck! Let us know if you find anything interesting along the way :)
