### ISSUE TITLE
Rambox does notify for messages in services with disabled notifications

### ISSUE THREAD

**Issue by justfortherec** [saenzramiro/rambox#487]
I have muted all notifications for Telegram (and have also muted the specific group inside Telegram) but Rambox still shows red unread counts in the service tab and the Rambox icon in the notifications area turns red when new messages arrive (I don't know whether any sounds are played because sound is turned off on my system).

Rambox should not notify me of new messages for services that I have muted. Even better, it should not notify me of messages inside a muted conversation/group of a service even if the entire service is not muted.

### Steps to reproduce

1. Disable notifications for service (for instance for Telegram)
2. Receive message in service (for instance in a group conversation in Telegram)

### Expected behavior

Rambox ignores new messages.

### Actual behavior

Rambox shows a red unread count in service tab and the Rambox icon in the notification center of the operating system turns red.

### ENVIRONMENT

- Version: 0.4.5
- Platform: linux (x64)
- Electron: 1.4.7
- Chromium: 53.0.2785.143
- Node: 6.5.0

**Comment by justfortherec** [comment]
Clarification: I just found out that Rambox allows disabling of notifications and muting of all sounds. I was talking about the former.

**Comment by saenzramiro** [comment]
**Show notifications** option is for preventing toast notifications. There isn't an option to disable badges in tags and tray icon. There's another ticket for that ( #187 ), and hopefully in next version we will add this feature.
