### ISSUE TITLE
No notifications in gnome 3.20 Wayland

### ISSUE THREAD

**Issue by Murmele** [saenzramiro/rambox#49]
If I get a new email, I don't get a notification, I just see, that the icon in the left edge is red. (Gmail, Gnome 3.20, Wayland). It's also with whats app and hangouts messages.

Is there also a possibility to move the menubar into the first row and delete the 2 row of this gray bar (see attached foto)?
![bildschirmfoto von 2016-07-04 13-47-36](https://cloud.githubusercontent.com/assets/10099533/16559640/8e9a7b70-41ee-11e6-835c-02ac1d66d089.png)

## 

> Rambox 0.3.0
> Electron 1.2.5
> linux x64 4.5.2-1-ARCH

**Comment by saenzramiro** [comment]
When you said **Notification** you are meaning like a toast notification? Because if the service you are using don't provide a toast notification, you will not see any of it.

Badges in tabs works ok?

About the menu bar, that's how Electron handle it. Maybe we can add a setting to autohide the menubar.

**Comment by Murmele** [comment]
In gnome 3.20 I can get a notification, see screenshot below. It seems to be a problem with electron: [https://github.com/electron/electron/issues/465#issuecomment-214392962](url)
![bildschirmfoto von 2016-07-04 17-42-11](https://cloud.githubusercontent.com/assets/10099533/16565658/1f4f15b6-420f-11e6-8cf9-d2beb8b0ca8e.png)

**Comment by flying-sheep** [comment]
your link is somehow broken: https://github.com/electron/electron/issues/465#issuecomment-214392962

**Comment by saenzramiro** [comment]
Like @flying-sheep said, notifications are working. Maybe you have to install **libnotify** library to make it work. Also, some services you have to manually enable notifications.

**Comment by flying-sheep** [comment]
i think you missed a part:

> and i **don’t** think i get notifications… when are they supposed to show up? when any counter goes up?

**Comment by benavern** [comment]
Hi, Now the setting for menubar to hide exists, 
Could you implement it, I can tell you that it could improve a lot the design on windows
```
autoHideMenuBar: false,
```
[Doc](https://github.com/electron/electron/blob/master/docs/api/browser-window.md#new-browserwindowoptions)

Thank you in advance!

**Comment by saenzramiro** [comment]
That's already implemented. Go to Preferences and enable the option to autoHide.
