### ISSUE TITLE
iCloud Mail

### ISSUE THREAD

**Issue by gabryesse** [saenzramiro/rambox#494]
Hi, when I try to log in into iCloud, it try to go into mailbox but return to the login form.

Thanks.

-
> Rambox 0.4.5
> Electron 1.4.7
> win32 x64 10.0.14393

**Comment by twinklebob** [comment]
Duplicate of #405, which is still occurring for me on:

> Rambox 0.4.5
> Electron 1.4.7
> linux x64 3.19.0-32-generic

**Comment by saenzramiro** [comment]
Ok, so let's close this issue.
