### ISSUE TITLE
Error with proxy with authentication

### ISSUE THREAD

**Issue by jorgeleon79** [saenzramiro/rambox#496]
On the network where I am trying to use rambox I get the following error when I open the application and I can not use it

**2016-11-30 17:08:20> Program: Starting Squirrel Updater: --processStart Rambox.exe
2016-11-30 17:08:20> Program: Want to launch 'C:\Users\X70987LE\AppData\Local\Rambox\app-0.4.5\Rambox.exe'
2016-11-30 17:08:20> Program: About to launch: 'C:\Users\X70987LE\AppData\Local\Rambox\app-0.4.5\Rambox.exe': 
2016-11-30 17:08:24> Program: Starting Squirrel Updater: --download https://getrambox.herokuapp.com/update/win32/0.4.5
2016-11-30 17:08:24> Program: Fetching update information, downloading from https://getrambox.herokuapp.com/update/win32/0.4.5
2016-11-30 17:08:24> CheckForUpdateImpl: Using existing staging user ID: 09828a08-d296-5d28-81b9-9797ffbb3a06
2016-11-30 17:08:24> CheckForUpdateImpl: Downloading RELEASES file from https://getrambox.herokuapp.com/update/win32/0.4.5
2016-11-30 17:08:24> FileDownloader: Downloading url: https://getrambox.herokuapp.com/update/win32/0.4.5/RELEASES?id=Rambox&localVersion=0.4.5&arch=amd64
2016-11-30 17:08:24> IEnableLogger: Failed to download url: https://getrambox.herokuapp.com/update/win32/0.4.5/RELEASES?id=Rambox&localVersion=0.4.5&arch=amd64: System.Net.WebException: Error en el servidor remoto: (407) Se requiere autenticación del proxy.
   en System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   en System.Net.WebClient.GetWebResponse(WebRequest request, IAsyncResult result)
   en System.Net.WebClient.DownloadBitsResponseCallback(IAsyncResult result)
--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---
   en System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   en Squirrel.Utility.<LogIfThrows>d__35`1.MoveNext()
2016-11-30 17:08:24> FileDownloader: Downloading url: https://getrambox.herokuapp.com/update/win32/0.4.5/releases?id=rambox&localversion=0.4.5&arch=amd64
2016-11-30 17:08:24> IEnableLogger: Failed to download url: https://getrambox.herokuapp.com/update/win32/0.4.5/releases?id=rambox&localversion=0.4.5&arch=amd64: System.Net.WebException: Error en el servidor remoto: (407) Se requiere autenticación del proxy.
   en System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   en System.Net.WebClient.GetWebResponse(WebRequest request, IAsyncResult result)
   en System.Net.WebClient.DownloadBitsResponseCallback(IAsyncResult result)
--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---
   en System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   en Squirrel.Utility.<LogIfThrows>d__35`1.MoveNext()
2016-11-30 17:08:24> CheckForUpdateImpl: Download resulted in WebException (returning blank release list): System.Net.WebException: Error en el servidor remoto: (407) Se requiere autenticación del proxy.
   en System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   en System.Net.WebClient.GetWebResponse(WebRequest request, IAsyncResult result)
   en System.Net.WebClient.DownloadBitsResponseCallback(IAsyncResult result)
--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---
   en System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   en Squirrel.Utility.<LogIfThrows>d__35`1.MoveNext()
--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---
   en System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   en Squirrel.FileDownloader.<DownloadUrl>d__3.MoveNext()
--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---
   en System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   en Squirrel.UpdateManager.CheckForUpdateImpl.<CheckForUpdate>d__2.MoveNext()
2016-11-30 17:08:24> FileDownloader: Downloading url: https://getrambox.herokuapp.com/update/win32/0.4.5/RELEASES?id=Rambox&localVersion=0.4.5&arch=amd64
2016-11-30 17:08:24> IEnableLogger: Failed to download url: https://getrambox.herokuapp.com/update/win32/0.4.5/RELEASES?id=Rambox&localVersion=0.4.5&arch=amd64: System.Net.WebException: Error en el servidor remoto: (407) Se requiere autenticación del proxy.
   en System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   en System.Net.WebClient.GetWebResponse(WebRequest request, IAsyncResult result)
   en System.Net.WebClient.DownloadBitsResponseCallback(IAsyncResult result)
--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---
   en System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   en Squirrel.Utility.<LogIfThrows>d__35`1.MoveNext()
2016-11-30 17:08:24> FileDownloader: Downloading url: https://getrambox.herokuapp.com/update/win32/0.4.5/releases?id=rambox&localversion=0.4.5&arch=amd64
2016-11-30 17:08:24> IEnableLogger: Failed to download url: https://getrambox.herokuapp.com/update/win32/0.4.5/releases?id=rambox&localversion=0.4.5&arch=amd64: System.Net.WebException: Error en el servidor remoto: (407) Se requiere autenticación del proxy.
   en System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   en System.Net.WebClient.GetWebResponse(WebRequest request, IAsyncResult result)
   en System.Net.WebClient.DownloadBitsResponseCallback(IAsyncResult result)
--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---
   en System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   en Squirrel.Utility.<LogIfThrows>d__35`1.MoveNext()
2016-11-30 17:08:24> CheckForUpdateImpl: Download resulted in WebException (returning blank release list): System.Net.WebException: Error en el servidor remoto: (407) Se requiere autenticación del proxy.
   en System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   en System.Net.WebClient.GetWebResponse(WebRequest request, IAsyncResult result)
   en System.Net.WebClient.DownloadBitsResponseCallback(IAsyncResult result)
--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---
   en System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   en Squirrel.Utility.<LogIfThrows>d__35`1.MoveNext()
--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---
   en System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   en Squirrel.FileDownloader.<DownloadUrl>d__3.MoveNext()
--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---
   en System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   en Squirrel.UpdateManager.CheckForUpdateImpl.<CheckForUpdate>d__2.MoveNext()
2016-11-30 17:08:24> FileDownloader: Downloading url: https://getrambox.herokuapp.com/update/win32/0.4.5/RELEASES?id=Rambox&localVersion=0.4.5&arch=amd64
2016-11-30 17:08:24> IEnableLogger: Failed to download url: https://getrambox.herokuapp.com/update/win32/0.4.5/RELEASES?id=Rambox&localVersion=0.4.5&arch=amd64: System.Net.WebException: Error en el servidor remoto: (407) Se requiere autenticación del proxy.
   en System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   en System.Net.WebClient.GetWebResponse(WebRequest request, IAsyncResult result)
   en System.Net.WebClient.DownloadBitsResponseCallback(IAsyncResult result)
--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---
   en System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   en Squirrel.Utility.<LogIfThrows>d__35`1.MoveNext()
2016-11-30 17:08:24> FileDownloader: Downloading url: https://getrambox.herokuapp.com/update/win32/0.4.5/releases?id=rambox&localversion=0.4.5&arch=amd64
2016-11-30 17:08:24> IEnableLogger: Failed to download url: https://getrambox.herokuapp.com/update/win32/0.4.5/releases?id=rambox&localversion=0.4.5&arch=amd64: System.Net.WebException: Error en el servidor remoto: (407) Se requiere autenticación del proxy.
   en System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   en System.Net.WebClient.GetWebResponse(WebRequest request, IAsyncResult result)
   en System.Net.WebClient.DownloadBitsResponseCallback(IAsyncResult result)
--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---
   en System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   en Squirrel.Utility.<LogIfThrows>d__35`1.MoveNext()
2016-11-30 17:08:24> CheckForUpdateImpl: Download resulted in WebException (returning blank release list): System.Net.WebException: Error en el servidor remoto: (407) Se requiere autenticación del proxy.
   en System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   en System.Net.WebClient.GetWebResponse(WebRequest request, IAsyncResult result)
   en System.Net.WebClient.DownloadBitsResponseCallback(IAsyncResult result)
--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---
   en System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   en Squirrel.Utility.<LogIfThrows>d__35`1.MoveNext()
--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---
   en System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   en Squirrel.FileDownloader.<DownloadUrl>d__3.MoveNext()
--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---
   en System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   en Squirrel.UpdateManager.CheckForUpdateImpl.<CheckForUpdate>d__2.MoveNext()
2016-11-30 17:08:24> FileDownloader: Downloading url: https://getrambox.herokuapp.com/update/win32/0.4.5/RELEASES?id=Rambox&localVersion=0.4.5&arch=amd64
2016-11-30 17:08:24> IEnableLogger: Failed to download url: https://getrambox.herokuapp.com/update/win32/0.4.5/RELEASES?id=Rambox&localVersion=0.4.5&arch=amd64: System.Net.WebException: Error en el servidor remoto: (407) Se requiere autenticación del proxy.
   en System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   en System.Net.WebClient.GetWebResponse(WebRequest request, IAsyncResult result)
   en System.Net.WebClient.DownloadBitsResponseCallback(IAsyncResult result)
--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---
   en System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   en Squirrel.Utility.<LogIfThrows>d__35`1.MoveNext()
2016-11-30 17:08:24> FileDownloader: Downloading url: https://getrambox.herokuapp.com/update/win32/0.4.5/releases?id=rambox&localversion=0.4.5&arch=amd64
2016-11-30 17:08:24> IEnableLogger: Failed to download url: https://getrambox.herokuapp.com/update/win32/0.4.5/releases?id=rambox&localversion=0.4.5&arch=amd64: System.Net.WebException: Error en el servidor remoto: (407) Se requiere autenticación del proxy.
   en System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   en System.Net.WebClient.GetWebResponse(WebRequest request, IAsyncResult result)
   en System.Net.WebClient.DownloadBitsResponseCallback(IAsyncResult result)
--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---
   en System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   en Squirrel.Utility.<LogIfThrows>d__35`1.MoveNext()
2016-11-30 17:08:24> CheckForUpdateImpl: Download resulted in WebException (returning blank release list): System.Net.WebException: Error en el servidor remoto: (407) Se requiere autenticación del proxy.
   en System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   en System.Net.WebClient.GetWebResponse(WebRequest request, IAsyncResult result)
   en System.Net.WebClient.DownloadBitsResponseCallback(IAsyncResult result)
--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---
   en System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   en Squirrel.Utility.<LogIfThrows>d__35`1.MoveNext()
--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---
   en System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   en Squirrel.FileDownloader.<DownloadUrl>d__3.MoveNext()
--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---
   en System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   en Squirrel.UpdateManager.CheckForUpdateImpl.<CheckForUpdate>d__2.MoveNext()
2016-11-30 17:08:24> Unhandled exception: System.AggregateException: Se han producido uno o varios errores. ---> System.Net.WebException: Error en el servidor remoto: (407) Se requiere autenticación del proxy.
   en System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   en System.Net.WebClient.GetWebResponse(WebRequest request, IAsyncResult result)
   en System.Net.WebClient.DownloadBitsResponseCallback(IAsyncResult result)
--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---
   en System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   en Squirrel.Utility.<LogIfThrows>d__35`1.MoveNext()
--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---
   en System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   en Squirrel.FileDownloader.<DownloadUrl>d__3.MoveNext()
--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---
   en System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   en Squirrel.UpdateManager.CheckForUpdateImpl.<CheckForUpdate>d__2.MoveNext()
--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---
   en System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   en Squirrel.UpdateManager.<CheckForUpdate>d__7.MoveNext()
--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---
   en System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   en Squirrel.Update.Program.<Download>d__7.MoveNext()
   --- Fin del seguimiento de la pila de la excepción interna ---
   en System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   en System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   en System.Threading.Tasks.Task`1.get_Result()
   en Squirrel.Update.Program.executeCommandLine(String[] args)
   en Squirrel.Update.Program.main(String[] args)
---> (Nº de excepción interna 0) System.Net.WebException: Error en el servidor remoto: (407) Se requiere autenticación del proxy.
   en System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   en System.Net.WebClient.GetWebResponse(WebRequest request, IAsyncResult result)
   en System.Net.WebClient.DownloadBitsResponseCallback(IAsyncResult result)
--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---
   en System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   en Squirrel.Utility.<LogIfThrows>d__35`1.MoveNext()
--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---
   en System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   en Squirrel.FileDownloader.<DownloadUrl>d__3.MoveNext()
--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---
   en System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   en Squirrel.UpdateManager.CheckForUpdateImpl.<CheckForUpdate>d__2.MoveNext()
--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---
   en System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   en Squirrel.UpdateManager.<CheckForUpdate>d__7.MoveNext()
--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---
   en System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   en Squirrel.Update.Program.<Download>d__7.MoveNext()<---**

My network is a proxy that requires authentication.

-
> Rambox 0.4.5
> Electron 1.4.7
> win32 ia32 6.3.9600

**Comment by saenzramiro** [comment]
Right, like the error message said, you need to authenticate in your proxy to download files from our Heroku server. I don't know how to do that, by that's the problem.

If you find the solution, please share it here.

**Comment by jorgeleon79** [comment]
I think the problem is that in the application you can indicate the proxy but not the user and the password.

**Comment by nephilim1973** [comment]
Trying:    http://user:pass@x.x.x.x     [port]
Did not work   :-(

**Comment by Wonskcalb** [comment]
How come this is closed. No solution have been provided. And in fact, same here, I'm behind a proxy w/ authentication, and there is no way for me to connect. Even by giving the details within the proxy URL.

**Comment by zicklag** [comment]
I have the same issue because my proxy requires authentication.
