### ISSUE TITLE
Can't right click inside a tab

### ISSUE THREAD

**Issue by ric2b** [saenzramiro/rambox#498]
### Steps to reproduce

1. Open Rambox
2. Open a service tab, like slack, messenger, etc.
3. Try to right click inside that service to get options like copy.

### Expected behavior

Right click should open the normal OS options like copy, select all, etc.

### Actual behavior

Nothing happens when I right click. (If the mouse pointer is over text is flashes to a mouse pointer icon and then back to a text cursor icon).

Right clicking on other parts of Rambox does work though, I can right click on a tab title to get the forward/back, zoom, reload and developer options.

### ENVIRONMENT

> Rambox: v0.4.5

> OS: Windows 10 Pro 64bit

> Arch: x64

**Comment by YesThatAllen** [comment]
likely to be addressed here:

https://github.com/saenzramiro/rambox/pull/491

**Comment by saenzramiro** [comment]
Duplicate #138 

Hopefully in a future we can add it.
