### ISSUE TITLE
Rambox has to be licensed under the GPLv3

### ISSUE THREAD

**Issue by Lazza** [saenzramiro/rambox#499]
A software which includes GPLed code has to be released in its entirety under the GNU GPL license of the same version (or higher, if that is allowed by the original developer). This is specified in the text of the GPL license.

Rambox uses the Sencha Ext JS library which is available under the GNU GPLv3 license. As [specified on their website](https://www.sencha.com/legal/GPL/):

> You can elect to use the GPL v3 license without paying a fee, provided you must comply with GPLv3 license terms.
> 
> -   If you create software that uses GPL, you must license that software under GPL v3 (see [GPL FAQ]), and
> -   [...]

  [GPL FAQ]: http://www.gnu.org/licenses/gpl-faq.html#IfLibraryIsGPL

### Expected behavior

Rambox is released as GPLv3 software.

### Actual behavior

Rambox is MIT licensed, violating the GPL license of Sencha Ext JS.

**Comment by saenzramiro** [comment]
You are right. My bad...
