### ISSUE TITLE
Windows notifications now showing for any service

### ISSUE THREAD

**Issue by Pranav14** [saenzramiro/rambox#5]
Notifications option turned on for each, not muted. I can hear the ping sounds though, like on Facebook Messenger. Just no Windows banners.

-
> Rambox 0.3.0
> Electron 1.2.5
> win32 x64 10.0.14371

**Comment by saenzramiro** [comment]
On Facebook Messenger, you need to enable Notifications manually. Go to the gear at the top left in Facebook Messenger, and then, Configuration. Click on "Enable Notifications".

I will add this steps in next release.

**Comment by Pranav14** [comment]
I tried that also. Turns out that the issue was the banner did not preview, only remained in the action center. Clicking on the notification does not open the application either, btw.

**Comment by saenzramiro** [comment]
So I think you had enabled the option for "Quiet hours" in the Action Center. If you disabled, I will work.

I will create an issue for open the app on notification click. Thanks!
