### ISSUE TITLE
Flicker while opening email in gmail

### ISSUE THREAD

**Issue by Murmele** [saenzramiro/rambox#50]
When I would open a email in gmail, there is a short flicker while opening the mail. (Gnome 3.20, Wayland). The flicker isn't in the chromium browser.

-
> Rambox 0.3.0
> Electron 1.2.5
> linux x64 4.5.2-1-ARCH

**Comment by saenzramiro** [comment]
I will try to take a look, thanks!

**Comment by saenzramiro** [comment]
Can you see if that flickering is the **Loading...** mask that shows every time the page is loading?
