### ISSUE TITLE
Tumblr

### ISSUE THREAD

**Issue by tiukov** [saenzramiro/rambox#501]
Bug with Tumblr service. Many certificate errors ("Trust invalid authority certificates" - enabled).

-
> Rambox 0.4.5
> Electron 1.4.7
> darwin x64 16.1.0

**Comment by saenzramiro** [comment]
Tumblr is not a native service. If a warning about certificates is showing, is because there is a file loading from a server that it's have an invalid certificate.

**Comment by evancaldwell** [comment]
I'm having this issue as well but do not have any custom services and have not added anything from Tumblr. Is there somewhere I could look to see why these keep popping up?

**Comment by evancaldwell** [comment]
I'm getting 20-30 of these every morning when I get into the office now. Where can I look to see where they are originating and stop them?

**Comment by saenzramiro** [comment]
Try updating to version 0.5.3.

**Comment by evancaldwell** [comment]
I updated and It's been most of the day without that popping up so I thinks this one is fixed.
