### ISSUE TITLE
clicking a web link does not do anything

### ISSUE THREAD

**Issue by crackjack** [saenzramiro/rambox#503]
### Steps to reproduce

1. Add any service with links in its content (eg: tweetdeck)
2. Click on any link that appears in the content
3. Neither the link opens in its tab or new tab nor in the default system browser

### Expected behavior

Links are expected to open either inline, or in the default system browser.

### Actual behavior

Nothing happens when you click the link.

### ENVIRONMENT

> Rambox: v0.4.5

> OS: CentOS 7

> Arch: x64

**Comment by saenzramiro** [comment]
It should work. Did you try with other services?

**Comment by crackjack** [comment]
Does not work with Slack, GMail and Skype too. Cannot copy the link either, right-click also does not work. There's another ticket for that.

**Comment by pcuinty** [comment]
Does not work on Gitter either. However, Discord and Tweetdeck is fine.

OS: xubuntu 16.04
Rambox v0.4.5

**Comment by saenzramiro** [comment]
I think it depends of the OS, because on Windows 10 and mac OS works ok.

**Comment by rokups** [comment]
Workaround is to add this to custom code:

    setInterval(function(){document.querySelectorAll('.urlPreviewText a').forEach(function(a){a.onclick=function(){window.open(this.href);return false;};});}, 3000);

**Comment by abers** [comment]
I am experiencing the same issue on i3wm. Links work fine when using KDE or Gnome. However, when clicking links in i3wm nothing happens. Adding the custom code to each of the enabled services does not resolve the issue.
