### ISSUE TITLE
Feature request: More options to organise services

### ISSUE THREAD

**Issue by 88scythe** [saenzramiro/rambox#504]
**Problem:**
Right now, you can set the icons for services in Rambox, change their label/text and align them left or right. I feel this is rather limited.

**Usecase:**
I was using the align left/right possibility to distinguish between work vs. private communication & planning/task tools in Rambox. But when adding many services, this ends up in one big list of icons where you can't distinguish left from right anymore. Especially on smaller screens. I've now removed the service names as to only keep their icons so I still have some whitespace in between the left and right aligned parts.

**Feature request:**
More options to organise the list of services in Rambox better.

**Suggestions:**
- Option to add whitespace "   "or dividers " | "to put in between the services.
- Option to add multiple rows (instead of one scrolling row), where the user can assign which services to see in which row.
- Option to switch to vertical services bar instead of the current horizontal approach.
- Option to align services to center (adding to the "align left" / "align right" options currently available.)
- Option to hide a service's icon (This would also cover issue #256)
- Option to put service name below icon instead of next to it.

**Attempted workaround:**
In order to achieve the "whitespace" effect, I tried adding a custom service without name, with a transparent pixel as icon, and whatever as URL. While this indeed creates whitespace that I can drag between my services, for one reason or another it also assigns an "11 unread" badge, no matter what URL I change it to (even when changing URL to a space, I still got the "11 unread" label above it). Rambox doesn't allow leaving the URL empty.

**Comment by 88scythe** [comment]
After fiddling around some more with these empty dummy "whitespace" services, it doesn't seem to be without issues either:

- When dragging one of them somewhere in between other services and/or changing its name from nothing to "Work:" it suddenly created a duplicate dummy service.
- I have problems removing the duplicate dummy service. After confirming I want to delete, it's removed from the horizontal services list, but stays in my "Enabled services" overview. When restarting Rambox, the deleted service returns in between my other services.
- Tried a bunch of things, but couldn't delete the pesky dummy service clone.
- Went to Menu - Help - Tools and did "clear cache" & "local storage" & logged in to my Rambox account again via Google login.
- See my Enabled Services overview, (including the pesky dummy clone) but don't have my service icons in the horizontal bar anymore.
- Can't edit any service in the overview either. Hovering does show the gear wheel (edit) and recycle bin (remove) icons, but when clicking either of those icons, I'm getting a translucent overlay but nothing else changes.
- Uninstalled & reinstalled Rambox. No effect. Also weird is that in the top right corner, I see the "Login" button, but am clearly still logged in as I can still see my enabled services overview. When clicking the Login button and logging in using my Google account, my name and Google profile picture are shown but the rest stays the same.

Help? :)

**Comment by saenzramiro** [comment]
Wow! I think you will have to wait until we release v1.0.0. 😉 

Please check #244. More news coming in next days...

**Comment by 88scythe** [comment]
Great news, hadn't found that, thanks for linking.

**Comment by gimntut** [comment]
From these lists can create a repository of services:
https://zapier.com/api/v3/services/for-picker
http://alternativeto.net/platform/online/?sort=likes
