### ISSUE TITLE
Certification Warning blocking application

### ISSUE THREAD

**Issue by ghost58400** [saenzramiro/rambox#506]
### Steps to reproduce

1. connect your PC to your phone's wifi AP (i'm french and I have a Sosh mobile plan), it also appears with my university's network
2. just wait 1 sec and the message appears

### Expected behavior

No message.

### Actual behavior

Error message, in loop, blocking the application, because when you close it, another appears instantly.
This appears even if you haven't got any service tab so I think it is related to the app's google analytics.
It doesn't appear with my personal network.

![capture d ecran 19](https://cloud.githubusercontent.com/assets/24221261/20937666/3536a2ec-bbe8-11e6-9353-50ede29647f9.png)

### ENVIRONMENT

> Rambox: v0.4.5

> OS: Win 10 pro

> Arch: x64

**Comment by saenzramiro** [comment]
It's an Electron bug. Fixed in 1.4.12.

http://electron.atom.io/blog/2016/12/09/certificate-transparency-fix

**Comment by LuckyLuky** [comment]
+1

**Comment by alzearafat** [comment]
Cannot use Rambox today, because this nasty bug +1

**Comment by Poil** [comment]
+1

**Comment by juuuuuu** [comment]
+1

**Comment by nunopicado** [comment]
+1

**Comment by XavierTolza** [comment]
+1

**Comment by angelopolotto** [comment]
I have the same problem here. I tried clean my cache and my local storage in help/tools, but that didn't solve the problem. I attach a print of the warning message
![rambox_warning](https://cloud.githubusercontent.com/assets/3145741/22175955/1b0842fe-dfe7-11e6-84e7-a19d1c604035.PNG)
.

**Comment by icecaster** [comment]
+1
