### ISSUE TITLE
La interfaz grafica no se muestra

### ISSUE THREAD

**Issue by SBI-boy** [saenzramiro/rambox#507]
Hola, tal como esl titulo dice, desde hace 2 dias que no puedo usar correctamente rambox ya que que la UI no se muestra, quise reinstalar per me da un error, no se que ha podido salir mal y no se que hacer para soluicionarlo sin perder todos los servicios y configuraciones
Imagen: http://i.imgur.com/Ds1dYGQ.jpg
Error al reinstalar: http://pastebin.com/tWfWfCqw

### ENVIRONMENT

> Rambox: v0.4.5

> OS: Win 10

> Arch: x64

**Comment by weeman1337** [comment]
Hi, I really want to help here but I can't uderstand you ;)

Can you please send your request in English?

**Comment by saenzramiro** [comment]
@weeman1337 Thank you man, I take this.

¿Instalaste Rambox desde el .exe de 64 bits?

Si es así, quizás deberías desinstalarlo, usar algún limpiador de registros como CCleaner y luego, volver a instalarlo.
