### ISSUE TITLE
Wrong status of unread emails with gmail

### ISSUE THREAD

**Issue by Murmele** [saenzramiro/rambox#51]
I saw, when I opened the last email with a bug report, that it changes the status of rambox. It shows me that I got a new email and in the gmail logo it shows me 49 unread emails. If I open the other report with the number of #50 it shows me that I have 50 unread emails. For better description you can find here a screenshot:

![bildschirmfoto von 2016-07-04 18-10-31](https://cloud.githubusercontent.com/assets/10099533/16566310/88588020-4213-11e6-9d6a-9b67c4f9ef9d.png)

-
> Rambox 0.3.0
> Electron 1.2.5
> linux x64 4.5.2-1-ARCH

**Comment by saenzramiro** [comment]
That's weird. I will take a look.

**Comment by Murmele** [comment]
Thank you. A great compliment to your really cool messenger app!

**Comment by TMartinPPC** [comment]
Hi @saenzramiro,

I'm experiencing the exact same problem. Only difference is I'm on Mac and version 0.5.10. I wasn't sure if I should create another issue since this one was already closed.

Thanks for any insight.
