### ISSUE TITLE
Rambox eating RAM!!! 5GB!

### ISSUE THREAD

**Issue by cjdg** [saenzramiro/rambox#512]
### Steps to reproduce

1. Run rambox in Ubuntu 16.04
2. Run along firefox.
3. Check memory

### Expected behavior

Not taking all ram!

### Actual behavior

System going slow and rambox helper using up to 5.4 GB

### ENVIRONMENT

> Rambox: v0.4.5

> OS: Ubuntu 16.04

> Arch: x64

**Comment by cjdg** [comment]
![seleccion_021](https://cloud.githubusercontent.com/assets/5726836/21061164/ccd4ad36-be10-11e6-931e-9e5de9b67921.png)

**Comment by cjdg** [comment]
![seleccion_021](https://cloud.githubusercontent.com/assets/5726836/21061195/e7ffb326-be10-11e6-87d3-8cfd5e19cb41.png)

**Comment by weeman1337** [comment]
How many services did you add? Can you please list them?

**Comment by saenzramiro** [comment]
You have to separate each service, because Rambox itself consume just a few MB, but each services runs in a separate process.

**Comment by lanwin** [comment]
@cjdg It looks a lot like one of the services that you use has a memory leek. You should see the same memory usage if you open that services in Chrome and use it in the same way and same time as in Rambox.

**Comment by arnauldb** [comment]
"rambox helper using up to 5.4 GB"

what I did is to manually delete the files in the "cache", as below in the screenshot. I'd like to have a way to clean the "cache" folders, as it builds up day after day...it seems to keep the old images and other files...

![selection_004](https://cloud.githubusercontent.com/assets/13196747/21430688/74a01642-c864-11e6-9cca-ddb6d33f951f.png)

**Comment by EvgenyTerebenin** [comment]
Rambox eats 1Gb, i have 5 active and 2 disabled services.
![image](https://cloud.githubusercontent.com/assets/17678440/24551859/ee4bbd8c-162c-11e7-84b4-19b1ce98fb32.png)
Ubuntu 16.04, 12 Gb RAM 
![image](https://cloud.githubusercontent.com/assets/17678440/24551883/059b1cbc-162d-11e7-87a0-ce2979de00ad.png)
Sometimes it eats about 2-2,3 Gb. It's terrible:(

**Comment by MurzNN** [comment]
Confirm the issue, Rambox eats more than 3Gb, even after disabling all services (uncheck checkboxes).
So the problem is in Rambox core, not in services. Also here https://github.com/saenzramiro/rambox/issues/1588 is feature request about memory usage.
