### ISSUE TITLE
Unable to compile local copy of project

### ISSUE THREAD

**Issue by ZaLiTHkA** [saenzramiro/rambox#513]
Greetings.. I've forked the repo in order to try out a few things, but I'm unable to run it on my local machine, which has:

* Linux Mint 18 x64 (with `4.4.0-51-generic` headers)
* Sencha Cmd 6.2.1.29
* Node 4.5.0 (installed via NVM 0.31.6)
* npm 3.10.6
* ruby 2.3.1p112
* compass 1.0.3

Because of the "Sencha Cmd" version difference, I was prompted to run `sencha app upgrade`, which I did (returned no errors). But now when I try run `npm run sencha:compile`, I get the following error:

```
[ERR] The following error occurred while executing this line:
/home/dre/workspace/rambox/.sencha/app/build-impl.xml:285: The following error occurred while executing this line:
/home/dre/workspace/rambox/.sencha/app/sass-impl.xml:189: The following error occurred while executing this line:
/home/dre/workspace/rambox/.sencha/app/sass-impl.xml:292: Problem: failed to create task or type x-compass-compile
Cause: The name is undefined.
Action: Check the spelling.
Action: Check that any custom tasks/types have been declared.
Action: Check that any <presetdef>/<macrodef> declarations have taken place.
```

Am I doing something wrong here? I have no experience with Sencha, nor much with Ruby, its pretty much just for the cli dependencies used by many of the NodeJS packages and build tools out there.

**Comment by weeman1337** [comment]
Make sure you installed the compass extension, see https://docs.sencha.com/cmd/guides/intro_to_cmd.html#intro_to_cmd_-_using_older_frameworks

If it still doesn't work, please run the npm command by hand with the debug flag.

**Comment by ZaLiTHkA** [comment]
Ah, I saw that option in the setup, but I thought it wasn't required because both this project and my system were both on Sencha Cmd major version 6.

I'm at work at the moment, so I'll try update my setup this evening when I get home (GMT+2) and let you know what happens.

**Comment by ZaLiTHkA** [comment]
Apologies for the delayed response @weeman1337, I got swamped with a bunch of work stuff shortly after my previous message. Now that I'm finally on leave, I had a chance to look at this again.

Anyways, re-installing SenchaCmd with the "Compass extension" has resolved my environment issue; thanks for the help. :+1:
