### ISSUE TITLE
Cannot reset user preferences

### ISSUE THREAD

**Issue by avallete** [saenzramiro/rambox#514]
### Steps to reproduce

1. Set Master Password
2. Forget Master Password
3. Try to launch the App

### Expected behavior
A "Forget Password ?" option to reset user prefs.

### Actual behavior
I'm stuck at the launchstart of the app. I've tried to locate the "config" folder to reset my app but I can't find it.

### ENVIRONMENT
> Rambox: v0.4.5

> OS: MacOS

> Arch: x64

**Comment by weeman1337** [comment]
Don't know where to locate it on macOS, but on Linux you find a `config.json` in `~/.Rambox/`. It's a hidden directory. You can do a `grep -Hrni master_password` in your home directory in a terminal to find the file.

When you found the file, set `master_password` to `false`.

Hope that helps...

**Comment by saenzramiro** [comment]
Yes, you will have to find the `config.json` file and edit it manually.
