### ISSUE TITLE
Feature Request: Plugin support?

### ISSUE THREAD

**Issue by jantman** [saenzramiro/rambox#516]
I can't find any information on whether such a thing exists, but it would be great if there was support for plugins to add new services (i.e. something like [Franz's plugins](https://github.com/meetfranz/plugins) but with a clear way to trigger popup notifications).

**Comment by saenzramiro** [comment]
You can add [Custom Services](https://github.com/saenzramiro/rambox/wiki/Add-a-Custom-Service).
