### ISSUE TITLE
Any plans to add Skype for Business

### ISSUE THREAD

**Issue by dnichk** [saenzramiro/rambox#52]
This would be huge for those of us who use Linux in the enterprise and our company uses Lync for IM.

**Comment by saenzramiro** [comment]
I made a research to find a way to add it, but I couldn't find a solution. What I saw is that there isn't a web app for Lync, is only a software that you have to download it.

Am I wrong? Can you help me with this?

**Comment by dnichk** [comment]
I don't know a ton about it yet, But I know a web app exists.

https://support.office.com/en-us/article/What-is-Skype-for-Business-Web-App-1ff3d412-718a-4982-8ff2-a4992608cdb5

http://thenextweb.com/microsoft/2015/06/09/office-365-integrates-skype-for-business-chat-and-calls-on-the-web/

**Comment by saenzramiro** [comment]
Well... seems that Skype for Business is inside Office 365. We already have an Office 365 option for Outlook. In next release I renamed to "Outlook 365".

We need to find a way to have a URL that goes directly to Skype for Business inside Office 365.

**Comment by dnichk** [comment]
We are moving up there in the next few weeks. One of my counterparts is testing up there - I will see if I can get the URL. Do you need it to where the login page is?

**Comment by saenzramiro** [comment]
Yes, a URL that when you aren't logged shows a login form or if you are logged, shows the app.

If you can find that URL, please share!

**Comment by dnichk** [comment]
Ok, I just finished moving my account in. SO it appears as though there is no login URL. It is just part of webmail. It is just a sidebar off to the right. Can't seem to pop out the skype for business portion. But it does show up when using the office 365 integration. No idea if notifications and such work yet though.

**Comment by saenzramiro** [comment]
For now, I will close this until we get a direct URL for Skype for Business.
