### ISSUE TITLE
Services being replaced and duplicating

### ISSUE THREAD

**Issue by ylluminate** [saenzramiro/rambox#520]
I initially set up HipChat in Rambox and it logged right in just fine.  I then proceeded to set up Skype, and then discovered that the text for HipChat (I had set it to blank) was replaced with Skype. I thought that that was odd, so I proceeded to hit cmd-r and then found that I had two Skype services and even the icon was replaced upon refresh.  Having a bugger of a time setting up multiple services...

**Comment by jbbr** [comment]
I used to have similar problems related to the Firebase synchronization of Rambox.
It's a nice feature when it works - but sometimes services end up with a wrong name or problems occur as the one you described.

Maybe it helps to Log out from the Rambox account (In Services configuration/Rambox tab) in case you don't need the sync functionality.

**Comment by ylluminate** [comment]
You were correct @jbbr, it was indeed the sync service that was the culprit.

**Comment by saenzramiro** [comment]
As you know, it's a common bug and related with synchronization. I will close this issue, hopefully in a future version we fix this.
