### ISSUE TITLE
Golden Kitty Award?

### ISSUE THREAD

**Issue by ylluminate** [saenzramiro/rambox#521]
I noticed that Franz has a message popping up for everyone asking folks to vote for it for the GoldenKitty award and thought the Rambox community might also want to do something similar:
https://www.producthunt.com/@goldenkittymeow/collections/2016-desktop-product-of-the-year

**Comment by saenzramiro** [comment]
I think to participate to that award, you have to be a trending app for a day or something similar.

It will be great if we can participate.

**Comment by ylluminate** [comment]
https://www.producthunt.com/posts/rambox

**Comment by saenzramiro** [comment]
Yes, we can try that.
