### ISSUE TITLE
Missing services buttons / dislocated dialogs

### ISSUE THREAD

**Issue by nunopicado** [saenzramiro/rambox#524]
Problem occured after signing in with Rambox Account (via Google profile) in an installation where several services had already been Setup.
Rambox asked if it could delete the services already Setup to use the ones configured in the Rambox account, to which I said "yes".
It logged in, but after that, the only 'service' in the toolbar is the Rambox Setup tab, even though several services are configured.
When trying to edit a service, or add a new one, the dialog appears in the bottom left corner of the window, mostly out of sight.
Reinstalling Rambox didn't solve.
Uninstalling Rambox, deleting all Rambox folders and then reinstalling also didn't solve.
![rambox](https://cloud.githubusercontent.com/assets/13234399/21191412/ec9ba0b0-c21c-11e6-80f4-0bb4e19d0324.PNG)

-
> Rambox 0.4.5
> Electron 1.4.7
> win32 x64 10.0.14393

**Comment by saenzramiro** [comment]
This is a common bug. It related with Firebase. You can remove all data going to Help -> Tools and select both options. Then, try to use Rambox without an account until we fix it.
