### ISSUE TITLE
Feature request: Disable system tray

### ISSUE THREAD

**Issue by lanwin** [saenzramiro/rambox#526]
### Expected behavior

There are two things. 

First starting with Win7 the System tray is mostly for services that dont require any or less attention like Dropbox. But Rambox ist mostly an App which I would expect the most uses use and open it often. Since Win7 the more natural behavior for such an App is to pin it to the taskbar and keep it open or minimize it. 

Second I am often have Rambox only open for some time and then need to close completely. Often cause I switch the machine. The current behavior which moves rambox to tray when closing the Window requires me to expand the tray, right click it and quit it. 

So I would suggest to add at least an option to disable system tray or better, an option which users need to enable system tray explicitly (cause First).

### ENVIRONMENT

Rambox: v0.4.5

OS: Win 10 Pro

Arch: x64

**Comment by saenzramiro** [comment]
Yes, we will add it in next version.
