### ISSUE TITLE
Tweetdeck won't connect

### ISSUE THREAD

**Issue by pheijmans** [saenzramiro/rambox#529]
When i want to login to tweetdeck there is no follow-up screen. I do get an email that there is a login, but i don't see tweetdeck running. When i login with the same credentials on tweetdeck there is no problem.

-
> Rambox 0.4.5
> Electron 1.4.7
> win32 x64 10.0.14393

**Comment by MrChick** [comment]
Try to reload the tab after the login, usually works for me but yeah this needs to be fixed

**Comment by pheijmans** [comment]
this did the trick, thanks!

**Comment by dogancelik** [comment]
I still can't log in, I use 2-factor-auth (phone activation) and it cancels the requests without me doing anything.

![rambox_2017-01-23_01-30-19](https://cloud.githubusercontent.com/assets/486818/22187263/aed8e504-e10b-11e6-8b73-1515c82876bd.png)

**Comment by saenzramiro** [comment]
Try updating to version 0.5.3!

**Comment by dogancelik** [comment]
Updated and it works, thanks 😃
