### ISSUE TITLE
Link between two services

### ISSUE THREAD

**Issue by achilleasM16** [saenzramiro/rambox#531]
I do not know if this is exactly an issue or not, because i am not using the services provided.

As a team, we use Trello a lot and i have added it as a custom service. We also use WhatsApp to communicate and we tend a lot to send card links. My question is, is there a way to open the card in my existing Trello tab on Rambox and not in the browser? The same applies to links for Evernote Notes (again a custom service)

**Comment by saenzramiro** [comment]
I think there is a way to do it (not easy) but is not the intention of Rambox. Sorry!
