### ISSUE TITLE
problem with Tweetdeck double authentification 

### ISSUE THREAD

**Issue by DavidOgereau** [saenzramiro/rambox#533]
I'm unable to log into tweetdeck with double authentification on rambox: I receive the SMS on my phone, but I have nowhere to enter it.
Eveything is fine when I log on tweetdeck without rambox.

-
> Rambox 0.4.5
> Electron 1.4.7
> win32 x64 10.0.14393

**Comment by saenzramiro** [comment]
Duplicate #403
