### ISSUE TITLE
clear cache

### ISSUE THREAD

**Issue by arnauldb** [saenzramiro/rambox#535]
Hello,

how can I clear the cache in rambox ? Rambox is using 3 GB on my system...

thank you,

![selection_003](https://cloud.githubusercontent.com/assets/13196747/21426674/78e90808-c850-11e6-9209-6eff33e6294a.png)

**Comment by saenzramiro** [comment]
Go to **Help -> Tools** menu.

**Comment by theotheo** [comment]
It seems doesn't work.
