### ISSUE TITLE
Right-click of links not giving options for HipChat

### ISSUE THREAD

**Issue by ylluminate** [saenzramiro/rambox#540]
When I right click a link in HipChat on Rambox, it does not give a menu like it would normally on macOS.  

The following is an example of what should show up:
![example](https://cl.ly/1O1g061R261n/Image%202016-12-25%20at%206.25.33%20PM.png)

It seems that right-click is generally b0rked in HipChat on Rambox.

**Comment by saenzramiro** [comment]
Native context menu is disabled. Some services added a personalized context menu manually (like Skype) and those works ok.

**Comment by ylluminate** [comment]
The problem is that I'm not able to right click links to get the actual link.  HipChat truncates links with an ellipses when they are long and one cannot simply copy those, thus Rambox's current functionality simply will not allow many links to be copied properly out of the app.  One cannot use Rambox for HipChat with this being the case if you ever want to interact with URLs differently than just clicking...

**Comment by saenzramiro** [comment]
Ok, and what about clicking the link? It opens in the browser?

**Comment by ylluminate** [comment]
Yes, correct.
