### ISSUE TITLE
Cookie problems with Facebook login

### ISSUE THREAD

**Issue by kwadwoadu** [saenzramiro/rambox#542]
### Steps to reproduce
1. Login through Facebook 

### Expected behavior
To get logged in :-)

### Actual behavior
Cookies Required
Cookies are not enabled on your browser. Please enable cookies in your browser preferences to continue.

### ENVIRONMENT
Version: 0.4.5
Platform: darwin (x64)
Electron: 1.4.7
Chromium: 53.0.2785.143
Node: 6.5.0

**Comment by brossow** [comment]
FWIW, I know this was closed almost exactly a year ago, but I got this same error when I tried to log in to Facebook to register a new Rambox account. When I tried again, it was successful. Thought I should mention it.

`Version: 0.5.14
Platform: win32 (x64)
Electron: 1.7.8
Chromium: 58.0.3029.110
Node: 7.9.0`
