### ISSUE TITLE
Push bullet shows blank screen after trying to log in

### ISSUE THREAD

**Issue by cjdg** [saenzramiro/rambox#547]
### Steps to reproduce

1. Go to pushbullet
2. try to log in with gmail
3. Blank screen

### ENVIRONMENT

> Rambox: v0.X.X

> OS: XXXX

> Arch: x64 or ia32

**Comment by nmat** [comment]
Tested this now and it seems that pushbullet requires cookies to work properly with local storage.

One idea would maybe be to use electron-cookies in requirement for pushbullet service in rendering.

**Comment by saenzramiro** [comment]
Duplicate #185.
