### ISSUE TITLE
It is impossible to open a picture received in Skype

### ISSUE THREAD

**Issue by flydze** [saenzramiro/rambox#55]
When I receive a picture in Skype I can see the preview, but on clicking it to see the full picture I get 6 tabs opened in Chrome and each of them has just one word "Unauthenticated".

![image](https://cloud.githubusercontent.com/assets/8363828/16576698/861194d8-4299-11e6-894c-70e1578c9475.png)

> Rambox 0.3.0
> Electron 1.2.5
> win32 x64 10.0.10586
> Chrome 51.0.2704.106

**Comment by saenzramiro** [comment]
Sure, I can find a way to do it.

Thanks!

**Comment by saenzramiro** [comment]
I try it and for me works ok, shows me the picture instead of the "Unauthenticated" message.

6 opened tabs was fixed in #11.

Let's see if in the next release you still have this error. For now, I close it.
