### ISSUE TITLE
Random freezes

### ISSUE THREAD

**Issue by cjdg** [saenzramiro/rambox#550]
sometimes it freezes to respond

### Steps to reproduce

Send to tray
then click to show the window
freeze.

### Expected behavior

minimizze to tray and restore windows

### Actual behavior
minimize to tray, stop responding

### ENVIRONMENT

> Rambox: v0.4.5

> OS: Ubuntu 16.10

> Arch: x64

**Comment by saenzramiro** [comment]
How many services you have in Rambox and how much RAM you have?

**Comment by cjdg** [comment]
I have about 200 services and 8 gb of ram

**Comment by saenzramiro** [comment]
200 services? 😕 

You have to use less services or increase your RAM.
