### ISSUE TITLE
Clicking on messages opens mega options

### ISSUE THREAD

**Issue by cjdg** [saenzramiro/rambox#551]
### Steps to reproduce

1. Click on view on any message
2. It shows control panel of mega
3. 

### Expected behavior

Show messages on rambox

### Actual behavior

NOT OPENING OTHER SOFTWARE!

### ENVIRONMENT

> Rambox: v0.4.5

> OS: Ubuntu 16.10

> Arch: x64

**Comment by saenzramiro** [comment]
That's weird. I think you have something wrong in your computer. Maybe this is related with #550.
