### ISSUE TITLE
implement drag and drop to attach file

### ISSUE THREAD

**Issue by andrewsu** [saenzramiro/rambox#552]
### Steps to reproduce

1. Drag file from windows explorer, drop in Rambox hipchat tab

### Expected behavior

File would be prepared for attachment, exactly as if the file had been selected using the paperclip icon

### Actual behavior

Rambox opens dialog to save file

### ENVIRONMENT

> Rambox: v0.4.5

> OS: Windows 10

> Arch: x64

**Comment by saenzramiro** [comment]
Can you confirm if this keep happening?

Works for me. 😕
