### ISSUE TITLE
Windows popping complaining about certificates after installing ad-blocking solution

### ISSUE THREAD

**Issue by rodoviario** [saenzramiro/rambox#555]
i have installed an adblocking solution into my wireless router called ab-solution.
This script manages a huge combined host list and redirects ads to a pixelsrv inside the router. Since this change into my home network, Rambox started to show windows complaining about different ad providers, related with the accounts I have configures (I think).
I only use it for gmail and whatsapp.

The problem is that it generate hundreds of windows one upon the other, and its impossible to close them all.

A workaround I am using is to add those hosts to a whitelist in the ad-blocking solution inside the router, and that have reduced the window notification bombing. Mainly google analytics, and others have been putted in the white list.

The windows suggest all the time to recreate the "custom service" and enable the "trust invalid authority certificate", but the services I am using are not customs to recreate... they are gmail and whatsap legacy servces.

I have attached a screenshot with the windows that pops.

I think that the certificate error is because it is detecting that the certificate (of the router) is not a certified one... or is not the one that really belongs to the host issuing the ad

![example of behaviour](https://cloud.githubusercontent.com/assets/4974682/21678429/0c0ec8ba-d315-11e6-9d66-5f502b7abde5.png)

-
> Rambox 0.4.5
> Electron 1.4.7
> linux x64 4.8.0-32-generic

**Comment by saenzramiro** [comment]
> I think that the certificate error is because it is detecting that the certificate (of the router) is not a certified one... or is not the one that really belongs to the host issuing the ad

I think so, we show that warning when a certification validation is invalid. Commonly, are when a Custom Services is added, that's why we talk in the message about Custom Services.

Nothing to do... if you have an invalid certificate, it will show that warning. You can keep adding to the white list or close it. In a future version, we will improve this warnings.
