### ISSUE TITLE
Hipchat no longer loads at start or reload

### ISSUE THREAD

**Issue by snds** [saenzramiro/rambox#557]
Attempts have been made to correct this such as disabling the service, removing the service and re-adding the service, reloading the service, restart of machine, removal, and reinstallation of Rambox. All to no avail. Regular Hipchat web service and native app operate normally.

### Steps to reproduce

1. Load Rambox
2. Expect Hipchat to load
3. Hipchat does not load

### Expected behavior
Hipchat has worked in the past few months.

### Actual behavior
Hipchat no longer loads and only provides a blank screen.

### ENVIRONMENT

> Rambox: v0.4.5

> OS: Mac OSX 10.11.6 (El Capitan)

> Arch: x64

**Comment by saenzramiro** [comment]
Works for me with no problems. Can you check now?

**Comment by snds** [comment]
After clearing the local storage for my other issue (#558) it started
working again. Perhaps the issue was tied to the cloud sync system?

Thanks for responding to these, BTW.

Cheers,
Sean


On January 9, 2017 at 4:36:01 AM, Ramiro Saenz (notifications@github.com)
wrote:

Works for me with no problems. Can you check now?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/saenzramiro/rambox/issues/557#issuecomment-271274109>,
or mute the thread
