### ISSUE TITLE
Services do not permanently delete

### ISSUE THREAD

**Issue by snds** [saenzramiro/rambox#558]
### Steps to reproduce

1. Attempt to delete service
2. Restart Rambox

### Expected behavior
Services are expected to be deleted from both local and cloud instances

### Actual behavior
After deletion, the service seems to disappear from the tab bar but not from the services list. If you restart Rambox the service reappears inexplicably as active and available.

### ENVIRONMENT

> Rambox: v0.4.5

> OS: Mac OSX 10.11.6 (El Capitan)

> Arch: x64

**Comment by saenzramiro** [comment]
Yes, this is a bug we have to fix ASAP. Please use Rambox without cloud sync for now.

You can clear your localStorage by going to Help -> Tools.
