### ISSUE TITLE
Rambox logs me out of all services when I quit it. 

### ISSUE THREAD

**Issue by ArtursO** [saenzramiro/rambox#559]
### Steps to reproduce

1. Add multiple accounts to Rambox
2. Quit Rambox (cmd + Q)
3. Re-open Rambox

### Expected behavior

Logged in as user registered with Rambox, I have a password enable on Rambox. When I log back in Rambox asks me to log into all of nine my services again. The services are 4 slack channels, discord, gitter, inbox by gmail, linkedin, and a custom website. I wish I could log into Ramobox and already be logged in to all my services since I already authenticated once. 

### Actual behavior

I'm asked to re-login back into every service.

### ENVIRONMENT

> Rambox: v 0.4.5

> OS: macOS Sierra V 10.12.2

> Arch: darwin (x64)

**Comment by saenzramiro** [comment]
It's suppose to save your sessions. Can you remove all your services, clear your localStorage and cache (Help menu -> Tools), quit Rambox and then, add one service to check if works.

**Comment by SimJoSt** [comment]
Sometimes happens to me too. Are there any logs I can send when it happens again?

**Comment by WolfangAukang** [comment]
This only happened to me the following way:

- Installed app and executed it (additional detail, I logged myself through Github)
- Services aren't configured (first time), so I configure them.
- Restart Rambox
- Services aren't configured, so I had to reconfigure them back
- Restart Rambox
- Services are working normally.

**Comment by saenzramiro** [comment]
Please update to latest version, and confirm if this issue it's remains.

**Comment by ArtursO** [comment]
This is no longer an issue it seems. Thanks Ramiro!!

**Comment by jamy015** [comment]
For the record, this happened to me this morning. However, I can't seem to reproduce it after that event.

> Rambox 0.5.3
> Electron 1.4.15
> win32 x64 10.0.14393

**Comment by pluckrose** [comment]
I get this with Slack everytime I quit and go back in. It always shows the slack  'you've found a glitch' page and then I sign back into my team and it works.

All other services are ok.

Am using Slack, Hipchat, inbox x3 & whatsapp.

**Environment**
Version: 0.5.9
Platform: darwin (x64)
Electron: 1.7.1
Chromium: 58.0.3029.110
Node: 7.9.0

**Comment by saenzramiro** [comment]
@pluckrose Is this happening in version 0.5.10 also?

**Comment by pluckrose** [comment]
Yeah and still happens without fail.

If I close rambox it will always do that with slack. Inbox does it occasionally, I'll wonder why I'm not getting emails and it's because it's signed out but doesn't happen everyday.

*Environment*
Version: 0.5.10
Platform: darwin (x64)
Electron: 1.7.4
Chromium: 58.0.3029.110
Node: 7.9.0

**Comment by saenzramiro** [comment]
Did you check the "Remember me" checkbox in the login form?

**Comment by blade2005** [comment]
Having this issue with Hipchat and Teams on version:
Rambox: v0.5.13
linux (x64)
Electron: 1.7.8
Chromium: 58.0.3029.110
Node: 7.9.0

**Comment by pluckrose** [comment]
Morning All

Just to give a bit more info on this, it still happens every time I quit Rambox but I don't have to enter my username and password every time, just my workspace url for slack.

So 
- Quit Rambox
- Open it and click on the slack tab, it will always show this https://i.imgur.com/OJXj33P.jpg
- Click Sign In and will take me here > https://i.imgur.com/IB9w0q7.png
- Enter my workspace URL then I'm back in again

**Environment**
Version: 0.5.13
Platform: darwin (x64)
Electron: 1.7.8
Chromium: 58.0.3029.110
Node: 7.9.0

and just in case it's any help, my mac specs > https://i.imgur.com/zei9IH8.png
