### ISSUE TITLE
Disabling Notifications Doesn't work

### ISSUE THREAD

**Issue by ddiinn** [saenzramiro/rambox#56]
Created a slack enabled service. After a few days disabled it's notifications. It showed notifications as disabled, yet still showed them.

I tried closing and opening the program but this didn't affect anything.

-
> Rambox 0.3.0
> Electron 1.2.5
> win32 x64 10.0.10586

**Comment by saenzramiro** [comment]
Ok, I will take a look on this.

Thanks!
