### ISSUE TITLE
Rambox login issue

### ISSUE THREAD

**Issue by luigisalas** [saenzramiro/rambox#566]
I install RamBox and I make login for recover my accounts... the accounts are listed (recovered) BUT I cannot use then... 

At the dashboard the account are listed... BUT the horizontal tabs are not showing... I can not clic on the action buton (delete, config, etc.)

If I delete the cache and Clear Loral Storage I can start config again my accounts... but I cannot recovered its using rambox account option..  👎  

-
> Rambox 0.4.5
> Electron 1.4.7
> win32 x64 10.0.14393

**Comment by saenzramiro** [comment]
Probably your account have an invalid format and that's why you cannot use it. We have to reset your account.

Using Rambox account is unstable.
