### ISSUE TITLE
Icon in system tray flickers in unity

### ISSUE THREAD

**Issue by Akronix** [saenzramiro/rambox#568]
I wonder if it's just me or if it happens to anyone else.
I just installed rambox with a few services in my ubuntu 16.04 machine. In my normal computer use, the indicator icon in the system tray flickers changing very quickly from the "no icon defined" to the rambox one. I mean, it does not dissapear form the system tray, it's always there, but the icon sometimes blinks which is very annoying and distracting.

I have experienced something similar with Franz, but It only happened when Franz was changing its icon to change the unread notifications displayed. It's like Rambox indicator is continuing refreshing itself.

It happens with either hardware accelaration disabled or enabled. I couldn't say this makes any difference.

### Steps to reproduce

1. Wait for little of computer activity, try changing of workspace or clicking Rambox icon. It happens randomly.

### Expected behavior

No flickering of the icon

### Actual behavior

Flickering of the icon

### ENVIRONMENT

> Rambox: latest stable? don't know where to find it.

> OS: Ubuntu 16.04

> Arch: x64

**Comment by Akronix** [comment]
is anyone else experiencing this issue?

**Comment by saenzramiro** [comment]
Can you confirm this in latest version 0.5..3?

**Comment by agharbeia** [comment]
I don't have this in Ubuntu 14.04, not in 0.5.3 nor the previous two releases.

**Comment by Akronix** [comment]
I think it's fixed in 0.5.3. I can say for sure because I have been only using it for one day, but .
