### ISSUE TITLE
Malware detected in windows binary

### ISSUE THREAD

**Issue by arthrp** [saenzramiro/rambox#569]
Malware is detected in windows binary downloaded from the official page (http://rambox.pro/). Currently it seems to be only Badoo, but previously [several more antiviruses](https://alternativeto.net/software/rambox/) were marking the binary as malware. Would you explain why is this happening?

![virustotal](https://i.imgur.com/n99qQ6U.png)

**Comment by DBX12** [comment]
I'm not sure I would trust an alert from Baidu. (This may be a prejudice, but if this Baidu is connected to the search engine with the same name, then I have some problems with it. Baidu does not give a single f*** about robots.txt. So maybe its something personal between me and Baidu but I don't trust it)

**Comment by saenzramiro** [comment]
Sure, quoting from @MarshallOfSound:

> It is detected as a Trojan because they way we install (no admin permissions required) is considered suspicious by really strict AV and Firewall tools.

Read [here](https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/issues/1232#issuecomment-227963465).

**Comment by arthrp** [comment]
Thanks. Can you link the issue you mentioned to this one?

**Comment by saenzramiro** [comment]
https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/issues/1232#issuecomment-227963465
