### ISSUE TITLE
Languages

### ISSUE THREAD

**Issue by knorrre** [saenzramiro/rambox#57]
How to translate?

**Comment by saenzramiro** [comment]
For now, Rambox doesn't have multi-language support. I will try to do it in next releases.

**Comment by Airon90** [comment]
From [Facebook](https://www.facebook.com/ramboxapp/photos/a.1182221115184805.1073741828.1151398944933689/1182221028518147/?type=3):

> We are preparing #Rambox to support multi-language. If you have time to help, please go to https://crowdin.com/project/rambox/invite

**Comment by Pablohn26** [comment]
is this planned for any milestone?

**Comment by saenzramiro** [comment]
@Pablohn26 Yes, hopefully in next minor release,
