### ISSUE TITLE
OS X status menu icon is missing

### ISSUE THREAD

**Issue by Tuchkata** [saenzramiro/rambox#571]
### Steps to reproduce

1. Start Rambox
2. Open Rambox settings
3. No option available to show it in status menu/tray

### Expected behavior

Icon should be shown in the upper right corner same as in Linux for instance

### Actual behavior

No icon available there and the option is missing in the settings

### ENVIRONMENT

> Rambox: v0.4.5

> OS: Mac OS X Sierra 10.12.2

**Comment by saenzramiro** [comment]
We are not planning for now display a tray icon in MacOS. Only in the dock bar.

**Comment by jonathanwiesel** [comment]
Any chance for this to be implemented? since a year has passed and maybe things have changed
