### ISSUE TITLE
Error message when using HipChat

### ISSUE THREAD

**Issue by ivanha** [saenzramiro/rambox#574]
### Steps to reproduce
An error message shown up when opening HipChat, and the normal chat window is not showing.

### Actual behavior

![screen shot 2017-01-15 at 16 36 12](https://cloud.githubusercontent.com/assets/6939920/21961317/9e2dc776-db41-11e6-9b13-f2f914ef50e5.jpg)

### ENVIRONMENT

> Rambox: v0.4.5

> OS: macOS Sierra 10.12.2

> Arch: x64

**Comment by ekerazha** [comment]
#573
