### ISSUE TITLE
Better certification warning

### ISSUE THREAD

**Issue by Yamakaky** [saenzramiro/rambox#575]
The current certification warning only shows the URL, which is not very helpful when there are a lot of services used. An improvement would be to show in the notification the name of the service from which the alert comes from.

**Comment by SimJoSt** [comment]
Also, most of the URLs are not shown in their entirety, as they are too long, which also hinders debugging.

**Comment by justfortherec** [comment]
I agree with both @Yamakaky  and @SimJoSt. Additionally, I suggest only showing the certificate warning  inside the tab of the service it applies to. That could be combined with my proposal of [displaying certificate warnings in modeless windows](589).

**Comment by SimJoSt** [comment]
The actual proposal can be found here: #589

**Comment by saenzramiro** [comment]
Please refer #589
