### ISSUE TITLE
using the @ when writing emails changes pages

### ISSUE THREAD

**Issue by ivosousamartins** [saenzramiro/rambox#58]
-
> Rambox 0.3.0
> Electron 1.2.5
> win32 x64 6.3.9600

**Comment by saenzramiro** [comment]
I'm working in this right now. Related to #31 .

**Comment by ivosousamartins** [comment]
Great! And great app also!

Ivo Sousa Martins

+351 962 918 268

Find me on Linkedin
<http://www.linkedin.com/pub/ivo-sousa-martins/b/7ba/826>
