### ISSUE TITLE
Enable copying of URLs from links

### ISSUE THREAD

**Issue by agharbeia** [saenzramiro/rambox#584]
Right clicking on a link should bring a context menu to copy the link's target URL.

This need first arose for me when dragging a tweet in a Tweetdeck instance failed as described in #583.
An alternative method is to insert the URL of the tweet to be added to the collection.

There was no way to copy the URL of a tweet.

**Comment by flying-sheep** [comment]
also “save target as” would be cool.

**Comment by saenzramiro** [comment]
Duplicate #297
