### ISSUE TITLE
Pop up on skype messages

### ISSUE THREAD

**Issue by nicolangr** [saenzramiro/rambox#585]
Every skype message received pops a error messages

"The service with the following URL has an invalid authority certification.

https://c.microsoft.com/trans_pixel.aspx?wcs.tz=1&wcs.cot=5&wcs.route=60001&wcs.ctrl=&wcs.ts=1484572452064&wcs.cd=0&wcs.eid=a494f23b-eb9d-89f1-1469-ca65ef9b6309&wcs.sr=1366x768&wcs.bs=1364x633&wcs.r=https%3A%2F%2Fweb.skype.com%2F&wcs.ti=(2)%20Skype&wcs.rsd=web.skype.com&wcs.rsus=%2Fen%2F&wcs.rsqs=&wcs.rihs=1&wcs.v=3.5&wcs.vct=1&wcs.vs=0&wcs.vclt=0&wcs.vfpv=0&wcs.et=1&ms.prod=Skype&ms.env=production&ms.rwd=desktop&ms.skype_userhash=3829327521003700227&ms.interactiontype=1&ms.pageType=webclient&ms.lang=en&ms.skypepn=webclient%2Fmain&ms.ea_offer=Client%20Notification&ms.ea_action=Browser%20Notification%20for%20IM%20displayed&ms.cid=7001&wcs.tr=0

If is a Custom Service, you have to remove it and add it again, enabling the "Trust invalid authority certificates" in the Options."
-
> Rambox 0.4.5
> Electron 1.4.7
> linux x64 3.19.0-32-generic

**Comment by uoowuo** [comment]
Skype, Slack and Zoho Mail all suddenly started popping up certificate errors.
They seem to be related to URLs that are either third-party or hosted on another server.
Skype login is broken. Same versions, Linux.

**Comment by gossi** [comment]
Skype has a hidden pixel on each message sent, which will trigger a popup. So, it is actually impossible to chat there.

**Comment by martin-g** [comment]
I believe Microsoft Outlook 365 stopped working for the same reason.
Since yesterday it stopped loading here.

Version: 0.4.5
Platform: linux (x64)
Electron: 1.4.7
Chromium: 53.0.2785.143
Node: 6.5.0

**Comment by jorgespiessens** [comment]
#573

**Comment by anastrophe** [comment]
Any reason for lack of .dmg for MacOS?
