### ISSUE TITLE
Service request: Mastodon

### ISSUE THREAD

**Issue by ineffyble** [saenzramiro/rambox#586]
Mastodon is  is a free, open-source social microblogging network/twitter alternative, based on GNU Social.

**Comment by 0x11de784a** [comment]
For me adding it as custom service worked fine. Notifications don't get piped though.

**Comment by jordanjay29** [comment]
Maybe a service such as [Mstdn](https://github.com/rhysd/Mstdn) would be useful for Rambox?

**Comment by saenzramiro** [comment]
Implemented in v0.5.9.
