### ISSUE TITLE
Issue on Skype

### ISSUE THREAD

**Issue by Thorketil** [saenzramiro/rambox#587]
Hi,
Since a few days my Skype session on Rambox can't be used anymore. Each time I try to login, I get many certification warnings, and before being able to enter my password it ends up to a white page.

![image](https://cloud.githubusercontent.com/assets/18676213/22015127/068d7d06-dca1-11e6-9cbf-05b8e9721137.png)

![image](https://cloud.githubusercontent.com/assets/18676213/22015186/4b932a36-dca1-11e6-9bda-f114fdb9bae0.png)

-
> Rambox 0.4.5
> Electron 1.4.7
> win32 x64 10.0.14393

**Comment by jorgespiessens** [comment]
#573

**Comment by JinxPC** [comment]
similar problem with security certs, but i'm connected. every time i log in or get a message, the error pops up

**Comment by Thorketil** [comment]
Thanks!
