### ISSUE TITLE
Pushbullet - invalid authority certification

### ISSUE THREAD

**Issue by DocSmirc** [saenzramiro/rambox#588]
after starting RAMBOX I get multible time the warning:
The service with the following URL has an invalid authority certification......"
wss://websocket.pushbullet.com/subscriber/...

very annoying message. 

-
> Rambox 0.4.5
> Electron 1.4.7
> win32 x64 10.0.14393

**Comment by jas99** [comment]
+1
Getting on all my services

**Comment by ChromoX** [comment]
+1
Can't even login to GroupMe because every time I try and click the username box I get a popup which removes focus. This is a serious problem to the usability of this client.

**Comment by procdaddy11** [comment]
Happening here as well :/

**Comment by trojkat** [comment]
Already reported in #573

**Comment by Daminoweb** [comment]
Same same ...
