### ISSUE TITLE
Re-add "preferences" to menu

### ISSUE THREAD

**Issue by ruihildt** [saenzramiro/rambox#590]
I now know that preferences can be found with the cog icon in the main page, but I would like to to suggest adding preferences as an item under "file" or "edit" or as a new item.

I think it would really make sense, specifically for GNU+Linux distros, as the menu is not hidden by default. So you kinda expect to have it there.

For a few months I was thinking it wasn't there until now.

**Comment by saenzramiro** [comment]
Make sense, I will consider to add it again.

**Comment by ruihildt** [comment]
Thanks !
