### ISSUE TITLE
Minimize by click Rambox icon

### ISSUE THREAD

**Issue by moceap** [saenzramiro/rambox#592]
Rambox doesn't minimize by clicking on its icon!

**Comment by SimJoSt** [comment]
It also would be interesting to make it a single-click feature. Not double click.

**Comment by chmercesmoreira** [comment]
Actually there are cases where the users can't even open/close Rambox by clicking or double clicking the Rambox icon on the system tray.
https://github.com/saenzramiro/rambox/issues/608

**Comment by notnsane** [comment]
There should be several options.

If Rambox is shown:
* Click on tray to hide, OR
* Double click on tray to hide

If Rambox is hidden:
* Click on tray to show, OR
* Double click on tray to show

Many softwares handle this situation differently. I asked for the single click before and it was denied.

Personally I don't even use the Tray anymore for Rambox, so I could ask for an option to remove the Tray icon... in fact, I think I will right now =P

**Comment by saenzramiro** [comment]
Double-click on the tray icon will show window and focus it always.

To hide the window, you will need to right click and select *Show/Hide Window*.

To fixing some issues with tray, let's merge with #786.
