### ISSUE TITLE
Back Arrow

### ISSUE THREAD

**Issue by BarryHavenga** [saenzramiro/rambox#593]
Hi. Suggestion: A back arrow would be nice. I have used Rambox for accessing Linkedin and I can't see a way to get back to a referring page.

-
> Rambox 0.4.5
> Electron 1.4.7
> linux x64 4.8.0-36-generic

**Comment by saenzramiro** [comment]
If you have a mouse with backward and forward buttons, works ok. Also, there is a **Back** and **Forward** by making right click in the tab of the service.

**Comment by BarryHavenga** [comment]
Ok thanks

⁣

**Comment by fretelweb** [comment]
How about Alt + Left or Alt + Right ?
