### ISSUE TITLE
Gmail links open 3 times/tabs in Chrome

### ISSUE THREAD

**Issue by mmsullivan** [saenzramiro/rambox#6]
Clicking on a link in gmail (in my case, an html email from Pocket) opens the link 3 times (3 separate tabs) in Chrome.

-
> Rambox 0.3.0
> Electron 1.2.5
> darwin x64 15.5.0

**Comment by saenzramiro** [comment]
Thank you for reporting this. I will take a look ASAP.

**Comment by mmsullivan** [comment]
Absolutely, let me know if I can assist. Loving the app so far. Thank you!

**Comment by xorti** [comment]
Well, I was experiencing the same issue with gmail and 6 tabs (6 configured services). I restarted rambox, and opening the same link now only opened 1 tab.

**Comment by twinklebob** [comment]
I've had the same thing with Rambox on Windows 10 and Chrome. Restarting it also fixed it for me. I was getting 4 tabs.

**Comment by hombrepac** [comment]
Seems to be happening again. Anyone else having this issue? 
Using 0.5.10, Arch Linux and Firefox.

**Comment by saenzramiro** [comment]
In Windows 10 works ok. :S
