### ISSUE TITLE
Invalid authority certification warning

### ISSUE THREAD

**Issue by Franziskus1988** [saenzramiro/rambox#600]
### Steps to reproduce

Warning message appears without special interaction.

### Expected behavior

No certification warning.

### Actual behavior

This messages appear:
![image](https://cloud.githubusercontent.com/assets/5774027/22237088/d9c08692-e209-11e6-86b8-72245f60e4fc.png)

### ENVIRONMENT

> Rambox: v0.4.5

> OS: WIN10

> Arch: win32 (x64)

**Comment by bendikl** [comment]
Been getting the same lately, really annoying since they stack up when away from computer so you have to force-close Rambox, I tried disabling all services except whatsapp and slack...still getting it!

**Comment by nightkall** [comment]
![rambox](https://cloud.githubusercontent.com/assets/20248397/22244652/abd14d5c-e22c-11e6-83c3-d9042b9bcbb9.jpg)


Same here.

**Comment by gangstara2** [comment]
Same here, I'm really confused. ![Rambox Error](https://monosnap.com/file/OqCUQaejusSBFxeMzJrPxB4AK9tn5q.png)

**Comment by Zottelchen** [comment]
Already known, see #573. Dev also knows about this but is waiting for God-knows-what.

**Comment by clementlamoureux** [comment]
Fixed in 0.5.2 :)

**Comment by saenzramiro** [comment]
Download 0.5.2 or so.
