### ISSUE TITLE
Riot app Cert Issue

### ISSUE THREAD

**Issue by Akinevz** [saenzramiro/rambox#601]
Opening the Riot tab shows the following window (with typos in it) and then an empty window. No settings can be found anywhere.
![img-2017-01-24-195629](https://cloud.githubusercontent.com/assets/1402632/22264394/adcf5cfa-e26f-11e6-877a-bb986ff3728b.png)

-
> Rambox 0.4.5
> Electron 1.4.7
> linux x64 4.8.13-1-ARCH

**Comment by tiny6996** [comment]
This issue also exists on windows 10.

**Comment by Zottelchen** [comment]
Already known, see #573. Dev also knows about this but is waiting for God-knows-what.

**Comment by saenzramiro** [comment]
Please update to latest version.
