### ISSUE TITLE
Can't add a Custom Service

### ISSUE THREAD

**Issue by Akinevz** [saenzramiro/rambox#602]
Attempting to add a custom service results in the following message
![img-2017-01-24-200647](https://cloud.githubusercontent.com/assets/1402632/22264759/0d0aec42-e271-11e6-94f1-97639cc65ec6.png)

In addition, the icon field goes red when enclosed in `"`s, yet the URL field isn't affected.

Also, it seems to not honour the "Trust invalid authority certificates":

![img-2017-01-24-201257](https://cloud.githubusercontent.com/assets/1402632/22264868/8e5a3eec-e271-11e6-942d-415cd8f1409b.png)

-
> Rambox 0.4.5
> Electron 1.4.7
> linux x64 4.8.13-1-ARCH

**Comment by raverrebel** [comment]
Can confirm this.
> Rambox 0.4.5
> Electron 1.4.7
> linux x64 4.4.0-45-generic

**Comment by saenzramiro** [comment]
Please update to latest version and confirm if this continue.

**Comment by raverrebel** [comment]
Updated to version 0.5.2. I had no problems adding a custom service.

**Comment by saenzramiro** [comment]
Latest version is 0.5.3. Please, be sure to have the latest.

**Comment by Akinevz** [comment]
Downloaded 0.5.3 from AUR 7 minutes ago. Can confirm fixed.
