### ISSUE TITLE
yahoo mail security issue

### ISSUE THREAD

**Issue by kevshocker** [saenzramiro/rambox#604]
I get a trust invalid authority certificate error when trying to add yahoo mail to rambox. When I try to remove and add it again, there is no option for enabling "Trust invalid authority certificates". See below

Here is the error:

"Certification Warning
The service with the following URL has an invalid authority certification.
https://comet.yahoo.com/comet
If this is a Custom Service, you have to remove it and add it again, enabling the "Trust invalid authority certificates" in the Options.""

-
> Rambox 0.4.5
> Electron 1.4.7
> win32 x64 10.0.14393

**Comment by Zottelchen** [comment]
Already known, see #573. Dev also knows about this but is waiting for God-knows-what.

**Comment by saenzramiro** [comment]
Please update to latest version.
