### ISSUE TITLE
dialog keep on popping up

### ISSUE THREAD

**Issue by bbetter** [saenzramiro/rambox#605]
mac os x sierra

<img width="502" alt="screen shot 2017-01-25 at 6 43 34 pm" src="https://cloud.githubusercontent.com/assets/6604503/22299868/5e6dfd5a-e32e-11e6-9730-3ec8ce30375e.png">

**Comment by breescorner** [comment]
I'm getting the same message with SLACK. I have to deactivate SLACK to stop the pop-up. It doesn't seem to have a checkbox to trust invalid certificates.

**Comment by thirdangle** [comment]
I am also getting this message with Slack. I am running Windows 10.

**Comment by Zottelchen** [comment]
Already known, see #573. Dev also knows about this but is waiting for God-knows-what.

**Comment by saenzramiro** [comment]
Please update to latest version.
