### ISSUE TITLE
Rambox does not start after upgrade to 0.5.1 (endless loading animation)

### ISSUE THREAD

**Issue by jbbr** [saenzramiro/rambox#606]
After upgrading from Rambox 0.4.5 to 0.5.1 rambox does still start but it is stuck at the loading animation. There is an error in the dev console (See screenshot)

The (now broken) profile had been configured with several services (Whatsapp, Slack, Skype) and was synchronized with a Rambox account.

This might have something to do with connectivity to the Rambox Account/Syncing service. After deleting the profile in `~/.config/Rambox` rambox loaded fine but clicking on "Login" resulted in a endless loading of the Rambox Account modal.
Next start it did load - so not sure if this is connected to the described issue after upgrading.

I kept a copy of the working profile before the upgrade and the broken profile after the upgrade to be able to reproduce the issue.

Thanks for continuing development/fixing the annoying certificate bug :)

### ENVIRONMENT
> Rambox: v0.5.1
> OS: Arch Linux
> Arch: x64

![image](https://cloud.githubusercontent.com/assets/682607/22315983/56c9c57a-e36a-11e6-8ba1-49e5086e617f.png)

**Comment by KANekT** [comment]
After upgrading from Rambox 0.4.5 to 0.5.2 - i have this issue

**Comment by KANekT** [comment]
https://github.com/saenzramiro/rambox/issues/609 - you heed clear cache

**Comment by bjab** [comment]
I have made fix to application and repacked [app.asar](https://drive.google.com/a/eauio.pl/file/d/0B1VV12x28m-dTWR2T0xWUHRXelE/view?usp=sharing).
You have to put it into rambox install directory, in my case it is:
c:\Users\<user>\AppData\Local\Rambox\app-0.5.2\resources\app.asar
I don't know where rambox install on other OSes.

**Comment by martinnj** [comment]
@bjab could you make a pull request for the fix so it can go into the code proper? :)

**Comment by bjab** [comment]
Done :)

**Comment by KANekT** [comment]
in macOS /Applications/Rambox.app/Contents/Resources

**Comment by KANekT** [comment]
But connect to Auth0 not working? 
I see only
"Please wait until we get your configuration."

**Comment by bjab** [comment]
My solution is only for incompatibility of profile data between versions in localStorage. 
I think, that problem of translating old user profile to new between Auth0 and local Rambox must be resolved by developers.

**Comment by dmetzler1988** [comment]
same error here - also with macOS 10.12.2
thx to @bjab for this solution - it helped me to start the app :)

**Comment by saenzramiro** [comment]
Please update to latest version 0.5.3.
