### ISSUE TITLE
Nothing happens when clicking above the Rambox icon on the system tray.

### ISSUE THREAD

**Issue by chmercesmoreira** [saenzramiro/rambox#608]
### Steps to reproduce

1. Click above the system tray icon of Rambox.

### Expected behavior

After clicking above the Rambox icon on the system tray the application window should be opened if closed or closed if opened.

### Actual behavior

Nothing happens when clicking above the Rambox icon on the system tray.

### ENVIRONMENT

System: `Host: carlos-pc Kernel: 4.10.0-1-MANJARO x86_64 (64 bit) Desktop: KDE Plasma 5.8.5 Distro: Manjaro Linux`

Rambox: `Version: 0.5.1
Platform: linux (x64)
Electron: 1.4.15
Chromium: 53.0.2785.143
Node: 6.5.0`

Arch: x64

I did a video sample showing what I mean when I say that the window should be opened after clicking above the system tray icon of Rambox, I'm going to show how the Thuderbird icon on the system tray behaves on my system.
![output](https://cloud.githubusercontent.com/assets/20016536/22317599/f77838c6-e35b-11e6-99a1-e5f646636516.gif)

@edit
There are already some issues closed talking about the same subject:

https://github.com/saenzramiro/rambox/issues/206
This one says that it is possible to open Rambox by double clicking the icon on the system tray, but actually even double clicking the icon doesn't work.

https://github.com/saenzramiro/rambox/issues/384
This second one says that in the past the icon on the system tray worked properly, so I guess that it was working only on Windows or after some new release of Rambox this feature stopped working.

**Comment by DerEnderKeks** [comment]
I've got the same problem.
System: `Linux Mint 18.1 Cinnamon` (Kernel `4.8.0-32-generic`)
Rambox: `0.5.2`

**Comment by alextakitani** [comment]
Nothing works on the tray for me, not even notifications.

System: Linux Mint 18.1 Cinnamon
Rambox: 0.5.2

**Comment by saenzramiro** [comment]
I will fix this in next version.

**Comment by alambike** [comment]
Same problem here, ubuntu16.04 with Unity. I have to click 2 times in "show/hide Window" to open Rambox window.

**Comment by tareko** [comment]
Also adding a reference to #700 and #592 , which are the same issue.

**Comment by tareko** [comment]
I assume that 0.5.8 was supposed to resolve this? It does not on GNOME. left-click or double-click does not produce the window.

**Comment by DerEnderKeks** [comment]
Can confirm that. Same on Cinnamon with Rambox `0.5.8`. No action on left or double left click.

**Comment by toXel** [comment]
Confirmed on GNOME and Arch Linux. The thing is: there are other electron apps where this is working! Try Slack for example. In GNOME I just have to single-click on the Slack icon in the tray and it will open.

**Comment by toXel** [comment]
So I just cloned the repo and changed [this line](https://github.com/saenzramiro/rambox/blob/master/electron/tray.js#L37) from `double-click` to `click` and it just works now in GNOME! So simple but so handy! @saenzramiro Could I open a PR with a little change to that code so it will register a single click event on Linux?

**Comment by zierler-f** [comment]
Any update on this?

**Comment by chmercesmoreira** [comment]
After today's update for version 0.5.9 the problem was still not solved. Was it supposed to be solved after this update?

**Comment by tareko** [comment]
Also not resolved for me.

**Comment by dankawka** [comment]
Same here:

> Distributor ID: Ubuntu
> Description:    Ubuntu 17.04
> Release:        17.04
> Codename:       zesty

> Version: 0.5.9
> Platform: linux (x64)
> Electron: 1.7.1
> Chromium: 58.0.3029.110
> Node: 7.9.0

**Comment by chmercesmoreira** [comment]
@saenzramiro Hello, could you please take a look at this problem again? It seems that it was not solved on milestone 0.5.4. I'm using currently version 0.5.10 and it is still not working.

**Comment by GlebWork** [comment]
Not resolved for me. Checked on 16.04 and 17.04.

**Comment by alxxlc** [comment]
This is a problem for me as well. I think this issue should be reopened.

Using:
Rambox 0.5.12
Manjaro-i3 17.0.4
i3WM 4.13

**Comment by phatina** [comment]
Doesn't work for me; running Fedora 25.

**Comment by 100GPing100** [comment]
```
Version: 0.5.13
Platform linux (x64)
Electron: 1.7.8
Chromium: 58.0.3029.110
Node: 7.9.0
```

`uname -a`
```
Linux where 4.10.0-37-generic #41~16.04.1-Ubuntu SMP Fri Oct 6 22:42:59 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
```

This is KDE Neon running latest version. Happens on two completely different machines.

**Comment by MurzNN** [comment]
The ugly workaround for Debian/Ubuntu and some other Linux distributions is remove libappindicator library file from filesystem (or rename):
```
mv /usr/lib/x86_64-linux-gnu/libappindicator.so.1.0.0 /usr/lib/x86_64-linux-gnu/libappindicator.so.1.0.0_off
```
