### ISSUE TITLE
Rambox won't retrieve my services on connection

### ISSUE THREAD

**Issue by dhouard** [saenzramiro/rambox#613]
When I log in I can only see a dialog titled "Connecting" and "Please wait until we get your configuration" in it.

Connection never ends.

I cleared cache and local storage but neither of them worked.

-
> Rambox 0.5.2
> Electron 1.4.15
> linux x64 4.9.4-1-default

**Comment by 4sStylZ** [comment]
I have deleted the `~/.config/Rambox/` and this action doesn’t fix the bug.

**Comment by YesThatAllen** [comment]
I had this problem on my mac, and updating to 0.5.3 fixed the issue.

**Comment by saenzramiro** [comment]
Like @YesThatAllen said, please update to latest version.
