### ISSUE TITLE
Pushbullet : Local Storage seems to be unaccessible to us

### ISSUE THREAD

**Issue by walout** [saenzramiro/rambox#614]
### Steps to reproduce

1. Add pushbullet service
2. Sign in with Google 
3. Error

### I Have 
Sorry, something went wrong.

Local Storage seems to be unaccessible to us.

Do you have cookies disabled?

Some browser extensions can conflict with our site. Temporarily disable them to test this.

If you still can't log in, send us an email at hey@pushbullet.com.

### ENVIRONMENT

> Rambox: v0.5.2

> OS: Windows 7

> Arch: x64

**Comment by twinklebob** [comment]
Yeah, I'm getting that since the upgrade to 5.2 on Linux. Every other service I've tried is working fine.

> Rambox 0.5.2
> Electron 1.4.15
> linux x64 4.4.0-59-generic

**Comment by ArcturusB** [comment]
I can reproduce this too with the following versions:

~~~
Version: 0.5.3
Platform: linux (x64)
Electron: 1.4.15
Chromium: 53.0.2785.143
Node: 6.5.0
~~~

Cheers, and a huge thanks to the team for your hard work! ;)

**Comment by squirrelboot** [comment]
Just throwing in that I am having this same exact error with 0.5.3 on Windows 10.

Sorry, something went wrong.
Local Storage seems to be unaccessible to us.
Do you have cookies disabled?
Some browser extensions can conflict with our site. Temporarily disable them to test this.
If you still can't log in, send us an email at hey@pushbullet.com.

**Comment by saenzramiro** [comment]
Let's merge with #185.

**Comment by shoshijak** [comment]
Hi! 
I'm having exactly this issue as well. 

Rambox version: 0.5.3
OS: Ubuntu 16.04 (x64)

I've just discovered Rambox and I absolutely love it! Thanks a lot for your work!
