### ISSUE TITLE
Rambox get stuck at the Loading-Screen.

### ISSUE THREAD

**Issue by ruben2000de** [saenzramiro/rambox#615]
![bildschirmfoto_2017-01-26_12-13-49](https://cloud.githubusercontent.com/assets/6840582/22329300/f5888b6e-e3c0-11e6-816a-cd5efd2768a2.png)

Rambox get stuck at the Loading-Screen.

-
> Rambox 0.5.2
> Electron 1.4.15
> linux x64 4.4.41-1-MANJARO

**Comment by philipp-r** [comment]
This fixed it for me: <https://github.com/saenzramiro/rambox/issues/609#issuecomment-275312983>
