### ISSUE TITLE
Upgrading from 0.4.5-x64 to 0.5.2-x64

### ISSUE THREAD

**Issue by agharbeia** [saenzramiro/rambox#617]
I've upgraded from 0.4.5-x64 to 0.5.2-x64.
I had been using Auth0 from the beginning.
Upon launching, Rambox stayed at the flying icons initial screen.
I shut it down deleted ~/.config/Rambox and relaunched.
It started well, but after I logged in to retrieve my configuration it never finishes the retrieval progress phase.
I purged rambox package, reinstalled it, then repeated as above, but I'm still unable to get it to restore my configuration.

**Comment by twinklebob** [comment]
See #609. It's getting confused because it's never done a sync before https://github.com/saenzramiro/rambox/issues/609#issuecomment-275347732. The old data isn't available so you need to rebuild your connections and log in again, but once you're in it seems to be a bit of an improvement on 4.5

**Comment by saenzramiro** [comment]
Refer to #609 please.
