### ISSUE TITLE
No puedo entrar

### ISSUE THREAD

**Issue by MauricioAedo** [saenzramiro/rambox#618]
Luego de la actualización de hoy no puedo ingresar a Rambox, se queda pegado en la imagen de inicio y no carga nunca. He probado borrar la cache y almacenamiento local pero aún así me es imposible ingresar a mi cuenta.

-
> Rambox 0.5.2
> Electron 1.4.15
> win32 x64 10.0.14393

**Comment by alex0520** [comment]
Duplicado https://github.com/saenzramiro/rambox/issues/609 recuerde que debería comentar y reportar en ingles

**Comment by saenzramiro** [comment]
Refer to #609
