### ISSUE TITLE
can't import my configuration.

### ISSUE THREAD

**Issue by arnauldb** [saenzramiro/rambox#619]
Hello,

I installed the last update but I can't import my configuration after logging, I keep having the following message for hours, see screenshot. I cleared the cache, uninstalled, deleted files and folders, reinstalled, nothing. I run ubuntu and rambox was fine before the last update.

![selection_007](https://cloud.githubusercontent.com/assets/13196747/22334937/e2e4b912-e3dc-11e6-861e-323f364d5c82.png)

Thanks,

-
> Rambox 0.5.2
> Electron 1.4.15
> linux x64 4.8.0-27-generic

**Comment by phendryx** [comment]
Same on MacOS Sierra 10.12.1

**Comment by keplerk** [comment]
I have the same problema on Windows 10 Version 0.5.2

**Comment by saenzramiro** [comment]
I think you should start from 0, sorry. We remove Firebase to synchronize services and now we use Auth0 Metadata. You should add your services and then, click in Backup. Then you can start using Restore.
