### ISSUE TITLE
keyboard shortcuts for Slack

### ISSUE THREAD

**Issue by jonpday** [saenzramiro/rambox#62]
https://get.slack.help/hc/en-us/articles/201374536-Slack-keyboard-shortcuts

these would be great, thanks.

**Comment by saenzramiro** [comment]
I tested and seems to works some shortcuts. I think is a Slack bug.

**Comment by jonpday** [comment]
some of the shortcuts work (e.g. Ctrl-K) but the standard browser navigation shortcuts e.g. Alt-Left don't.

**Comment by saenzramiro** [comment]
Correct, so I think is a Slack bug on his web app. If you open Slack in your favorite browser and try the shortcuts, some are not working.

**Comment by andrey-yantsen** [comment]
Actually there is an issue with shortcuts: when you just changed focus to Rambox from another app you should click somewhere inside slack's window, otherwise hotkeys will not work.

**Comment by saenzramiro** [comment]
@andrey-yantsen Yes, that will be fixed in next release ( #180 ).

**Comment by shanness** [comment]
The Alt-Left and Alt-Right navigations work in chrome for me using the slack web interface, but not in Rambox (or Franz).  This is a pretty critical navigation shortcut (the only way to get back to the last channel you were on).  So it doesn't seem to be a bug in the slack web app, but rather in rambox or electron?
