### ISSUE TITLE
Microsoft Teams Doesn't works

### ISSUE THREAD

**Issue by reysillo** [saenzramiro/rambox#620]
Microsoft Teams Doesn't works:
I selected Microsoft Teams service, log in on that and after login dialog the windows shows a purple window and no more, I reload the tab, remove service and create it again but the problem continues.

thank you and best.

RC

-
> Rambox 0.5.2
> Electron 1.4.15
> darwin x64 16.3.0

**Comment by saenzramiro** [comment]
Sorry but I couldn't test it Microsoft Teams (paid service).

Is there a possibility to share to me via PM a test account to use it and fix the problem?

**Comment by lroetzer** [comment]
I've got the same problem, it's just showing a purple screen You could test it using a free Office 365 trial: https://products.office.com/en-us/microsoft-teams/group-chat-software

**Comment by meyju** [comment]
Hi, I have the same issue. We use ADFS in our company to authenticate Users in Office365. The auth redirect to the ADFS Service and back to MS Teams is done correctly. After that I get der purple screen.

In the developer Console of electron, I can see Java Script errors:
`angular.min.js:117 Error: Script error.
    at a.onerror (https://statics.teams.microsoft.com/hashedjs/3-app.min-e0c0fa93.js:1113:24607) undefined(anonymous function) @ angular.min.js:117(anonymous function) @ angular.min.js:89(anonymous function) @ loggingService.min.js:1a.onerror @ loggingService.min.js:1
`
`angular.min.js:40 Uncaught TypeError: Cannot read property 'on' of undefinede @ notificationsService.desktop.min.js:1instantiate @ angular.min.js:41(anonymous function) @ angular.min.js:42invoke @ angular.min.js:41(anonymous function) @ angular.min.js:39invoke @ angular.min.js:41(anonymous function) @ angular.min.js:43d @ angular.min.js:40e @ angular.min.js:41instantiate @ angular.min.js:41(anonymous function) @ angular.min.js:42invoke @ angular.min.js:41(anonymous function) @ angular.min.js:39invoke @ angular.min.js:41(anonymous function) @ angular.min.js:43d @ angular.min.js:40e @ angular.min.js:41instantiate @ angular.min.js:41(anonymous function) @ angular.min.js:42invoke @ angular.min.js:41(anonymous function) @ angular.min.js:39invoke @ angular.min.js:41(anonymous function) @ angular.min.js:43d @ angular.min.js:40e @ angular.min.js:41instantiate @ angular.min.js:41(anonymous function) @ angular.min.js:42invoke @ angular.min.js:41(anonymous function) @ angular.min.js:39invoke @ angular.min.js:41(anonymous function) @ angular.min.js:43d @ angular.min.js:40e @ angular.min.js:41instantiate @ angular.min.js:41(anonymous function) @ angular.min.js:42invoke @ angular.min.js:41(anonymous function) @ angular.min.js:39invoke @ angular.min.js:41(anonymous function) @ angular.min.js:43d @ angular.min.js:40e @ angular.min.js:41invoke @ angular.min.js:41(anonymous function) @ angular.min.js:43p @ angular.min.js:7bb @ angular.min.js:43c @ angular.min.js:21yc @ angular.min.js:21(anonymous function) @ _:221i @ jquery.min.js:2fireWith @ jquery.min.js:2ready @ jquery.min.js:2J @ jquery.min.js:2`

> Version: 0.5.3
Platform: linux (x64)
Electron: 1.4.15
Chromium: 53.0.2785.143
Node: 6.5.0

**Comment by saenzramiro** [comment]
Ok, I will take a look for next release.

**Comment by jhult** [comment]
I also get just a purple screen.

**Comment by rob-heine** [comment]
Same behaviour in 

* Rambox 0.5.3
* Electron 1.4.15
* win32 (x64)

**Comment by ced64k** [comment]
Same purple screen here

**Comment by angladajosep** [comment]
Same problem:

Rambox 0.5.3
Electron 1.4.15
ubuntu 16.04 (x64)

**Comment by DennisVonDerBey** [comment]
I get the same problem. When I tried to add it to Franz as an plugin it threw the same error. Propably using the same Electron version?

**Comment by KITSJamesWalker** [comment]
I also get this problem

**Comment by meyju** [comment]
Hi found another bugreport with the same issue by another tool: [webcatalog: Issues 28](https://github.com/webcatalog/webcatalog/issues/28)

They fixed the issue by changing the user-agent of electron because Microsoft itself uses it for there offical client.

**Comment by saenzramiro** [comment]
Thanks @meyju !

**Comment by ced64k** [comment]
Hi, sometimes I still get the "ready purple screen" with 0.5.9. If I reload the tas it works.

**Comment by saenzramiro** [comment]
@ced64k What about in version 0.5.10?

**Comment by ced64k** [comment]
@saenzramiro I didn't get the purple screen since a few weeks, so I'll say it's fixed
