### ISSUE TITLE
Rambox does not start - Uncaught TypeError: Cannot read property 'services_lastupdate' 

### ISSUE THREAD

**Issue by HoracePGreeley** [saenzramiro/rambox#622]
### Steps to reproduce

1. Upgraded to Rambox 0.5.2
2. Rambox restarted
3. Rambox shows "splash screen", with with background color.
4. Notification "THE FUTURE IS COMING!" pops up
5. Notification "WE NEED YOUR HELP!" pops up
6. The splash screen animation never stops
7. Getting a error on developer console:
app.js:1 Uncaught TypeError: Cannot read property 'services_lastupdate' of undefined
![image](https://cloud.githubusercontent.com/assets/11772186/22340460/d98ff212-e3ed-11e6-95a1-5493a6e7bd8b.png)

![image](https://cloud.githubusercontent.com/assets/11772186/22340613/52320a2a-e3ee-11e6-93f8-1a90123c0ccc.png)

### Expected behavior

Rambox starts up as normal

### Actual behavior

Rambox always shows the splash screen

### ENVIRONMENT

> Rambox: v0.5.2

> OS: Windows 10.0.14393

> Arch: x64

**Comment by SecurityAntics** [comment]
Also getting the same. Tried clearing cache/local storage. Also running 0.5.2 updated today.

![image](https://cloud.githubusercontent.com/assets/24718370/22341039/60aa3aac-e3e7-11e6-8c40-6866496740a1.png)

**Comment by mattwatkins93** [comment]
Getting the same as above ^

**Comment by ZeekHuge** [comment]
Thats true. Confirming this on my system too.

Version: 0.5.2
Platform: Ubuntu 14.04 (x64)

**Comment by mattwatkins93** [comment]
0.5.3 looks to already be out. This is fixed for me in this version.

**Comment by ZeekHuge** [comment]
Yes, 0.5.3 fixes this.
Issue should be closed now I guess.

**Comment by HoracePGreeley** [comment]
Confirm, this issue is fixed in 0.5.3. Unfortunately, I had to reinstall Rambox. 
Thanks for fixing this issue! I close the issue.
