### ISSUE TITLE
Error occured when trying to backup your configuration

### ISSUE THREAD

**Issue by yannbertrand** [saenzramiro/rambox#623]
### Steps to reproduce

1. Synchronize configuration
2. Backup

### Expected behavior

Generate a backup file

### Actual behavior

![screen shot 2017-01-26 at 19 48 23](https://cloud.githubusercontent.com/assets/5855339/22345514/a6dbb3ac-e400-11e6-90e3-0e9e6b27dfe6.png)

### ENVIRONMENT

macOS Sierra 

> Rambox: v0.5.3

> OS: 10.12.2

> Arch: x64

**Comment by saenzramiro** [comment]
Try to logout and login again, then backup.

**Comment by yannbertrand** [comment]
Thank you!
