### ISSUE TITLE
Hootsuite Issue After Update

### ISSUE THREAD

**Issue by rrhutch** [saenzramiro/rambox#626]
Thanks for the recent update to fix the certificate issues. After the update, I cannot get the authentication to seemingly pass through on Hootsuite. I have a login with an email address and password and I also have it setup for Facebook authentication. After trying either of those, it simply returns right back to the login screen.

I have removed the service and added it back, and am still able to reproduce the problem. I have verified that there is not a current issue with Hootsuite, since I was able to login with both methods through a browser.

-
> Rambox 0.5.3
> Electron 1.4.15
> win32 x64 10.0.14393

**Comment by saenzramiro** [comment]
Did you tried by adding Hootsuite as Custom Service?

**Comment by rrhutch** [comment]
I had replied via email and not sure if that add it to the thread, so I am adding directly.

I had not tried it as a custom service. However, I just did and was able to reproduce the same problem.

**Comment by quentinus95** [comment]
@saenzramiro this issue seems generalized to multiple services and situations. Do you have any tip to apply a temporary fix before next release ?

**Comment by saenzramiro** [comment]
@quentinus95 I have to investigate where is the problem and then, if I find it, I will try to share a temporary fix.
