### ISSUE TITLE
'services_lastupdate' of undefined

### ISSUE THREAD

**Issue by ravecat** [saenzramiro/rambox#628]
After update on 0.5.2 version I start rambox and get infinite loading. In devtools I see error "Uncaught TypeError: Cannot read property 'services_lastupdate' of undefined"

Rambox: v0.5.2
OS: Debian8
Arch: x64

**Comment by jbbr** [comment]
This should be fixed with v0.5.3.

Although I get some other errors related to `services_lastupdate` in dev console, it doesn't seem to affect usage anymore.
