### ISSUE TITLE
Whatsapp: Wrong number of unread conversations

### ISSUE THREAD

**Issue by pedropapa** [saenzramiro/rambox#630]
### Steps to reproduce

1. Have a lot of unread conversations
2. The number of unread conversations on the tab icon will differ from the actual unread conversations.

### Expected behavior

The unread conversation count should be equal to the whatsapp's unread conversation number.

### ENVIRONMENT

> Rambox: v0.5.3

> OS: macOS Sierra 10.12.2

> Arch: x64

Unread count badge on rambox:
<img width="71" alt="screenshot 2017-01-27 10 22 09" src="https://cloud.githubusercontent.com/assets/2160382/22370908/107b02a2-e47b-11e6-888e-3c6fb1d3dec7.png">

List of unread conversations (14) on Rambox:
<img width="35" alt="screenshot 2017-01-27 10 22 54" src="https://cloud.githubusercontent.com/assets/2160382/22370897/06b3cace-e47b-11e6-8f04-c1c15c6ba3f5.png">

In the cellphone's Whatsapp app you can see that the unread conversation count is really 14:
![img_1788](https://cloud.githubusercontent.com/assets/2160382/22370886/f7ee4348-e47a-11e6-838e-33533952e673.PNG)

What I've tried already:
1. Refresh Rambox
2. Reopen Rambox
3. Reattach service
4. Reinstall Rambox

**Comment by saenzramiro** [comment]
Rambox counts all the unmuted conversations. So if I count the unmuted in your screenshots, it's 25. Don't know why your iPhone shows 14.

**Comment by pedropapa** [comment]
@saenzramiro Huumm, even counting only unmuted conversations the number is still wrong, see:

Rambox's unread messages badge:
<img width="76" alt="screenshot 2017-02-07 11 48 19" src="https://cloud.githubusercontent.com/assets/2160382/22693791/eb18d962-ed2b-11e6-8826-993490b01ae4.png">

List of unread conversations:
<img width="48" alt="screenshot 2017-02-07 11 48 09" src="https://cloud.githubusercontent.com/assets/2160382/22693792/eb1d3bb0-ed2b-11e6-9289-35261074aa48.png">

iPhone's unread conversations badge:
![img_2315](https://cloud.githubusercontent.com/assets/2160382/22693837/1496baa2-ed2c-11e6-9dec-8ef1ac3cc3fc.PNG)


As you can see there are only one unmuted & unread conversation, but rambox shows that there are two unread & unmuted conversations. (yes, I've scrolled my conversations list all the way down to make sure none was left)

I've tried reload/reopen the app as well.

**Comment by saenzramiro** [comment]
I had reviewed again the image and is counting ok for me. See...
![eb1d3bb0-ed2b-11e6-9289-35261074aa48](https://cloud.githubusercontent.com/assets/2694669/22712997/82125d00-ed65-11e6-867c-f08e53b8e341.png)

RED CROSS: Don't counts.
BLUE CIRCLE: Counts.

The blue circle counts because that conversation is not silenced/muted and have unread messages. All the others are silenced/muted so the unread counter for each ones don't count.

**Comment by pedropapa** [comment]
@saenzramiro Ok, now I get it.. Rambox counts the number of unread messages of unmuted groups. Whatsapp desktop app and iOS app counts the number of unread & unmuted **conversations**, that's because I thought the number was wrong.

**Comment by saenzramiro** [comment]
Right, we changed that in latest release. There was a lot of users asking for counting only unread messages of unmuted conversations.
