### ISSUE TITLE
Issue with oAuth authentication

### ISSUE THREAD

**Issue by quentinus95** [saenzramiro/rambox#631]
I'm using a separate service to connect to a self-hosted Mattermost instance. oAuth authentication (using another website) is not working after upgrade to 0.5.3 (bad token type). This seems related to issue #626.

It is well working on any browser.

Issue reproduced using Rambox 0.5.3 on Linux.

**Comment by saenzramiro** [comment]
Are you trying to log in with Google, Facebook or another SSO?

**Comment by quentinus95** [comment]
Another SSO (GitLab). However, the issue seems fixed now (I don't really know why, I will reopen the issue if it happens again).

**Comment by yggi49** [comment]
I also have this issue, trying to log into my self-hosted Mattermost via the self-hosted GitLab instance—Rambox 0.5.3 on Gentoo Linux.

**Comment by saenzramiro** [comment]
@yggi49 Is Mattermost opening a popup for GitLab login or use redirecting?

**Comment by yggi49** [comment]
It did redirect to the GitLab login page.

That said, it is working now with Rambo 0.5.9.  Thank you for checking back!
