### ISSUE TITLE
[REQUEST] League of legends chat

### ISSUE THREAD

**Issue by Ansem93** [saenzramiro/rambox#632]
HI!
it's possible to add league of legends chat? There is a mobile app, so maybe it's possible!

**Comment by TriiNoxYs** [comment]
LoL friends is a mobile app and Rambox only works with website, not apps :/
Si unfortunately it's not possible :/

**Comment by saenzramiro** [comment]
Like @TriiNoxYs said, we cannot add it to Rambox until they release a web app.
