### ISSUE TITLE
Unable to login to Auth0

### ISSUE THREAD

**Issue by agharbeia** [saenzramiro/rambox#639]
After having removed my previous settings in ~/.config/Rambox and apt-get purged rambox, I installed version 0.5.3
The application launched well, and I re-created my service accounts.
But I'm still unable to login to Auth0. It stays at the turning connection circle forever

### Steps to reproduce

1. Install afresh
2.  Setup seocial accounts
3.  press login on Rambox

### Expected behavior

A prompt for credentials

### Actual behavior

Window having revolving circle keeps displayed

### ENVIRONMENT

Version: 0.5.3
Platform: linux (x64)
Electron: 1.4.15
Chromium: 53.0.2785.143
Node: 6.5.0

**Comment by quentinus95** [comment]
This may be related to #626 and #631.

**Comment by saenzramiro** [comment]
I had this problem before, but after removing a Rambox folder in my Windows 10, everything start working without problems. The path of the folder is `C:\Users\myuser\AppData\Roaming\Rambox`.

Inside that folder, you can see files related with Cache, Cookies, etc. I don't know where is that folder in Linux, but if you find it, please share with us the path.

I will investigate this and see why in some cases Auth0 is not working.

**Comment by agharbeia** [comment]
The configuration path for Rambox on Ubuntu 14.04 is ~/.config/Rambox/

I removed the directory, re-launched, and synchronised successfully this time.
I don't know what happened, but I remember having tried this before and it didn't work. Maybe because this time I logged in from another device with the new version as well.

**Comment by saenzramiro** [comment]
Ok, thank you @agharbeia for share the path.

**Comment by saenzramiro** [comment]
Just for the record, in macOS the path is `/Users/username/Library/Application Support/Rambox`.
