### ISSUE TITLE
Missing taskbar badge

### ISSUE THREAD

**Issue by Stanzilla** [saenzramiro/rambox#642]
### Steps to reproduce

1. Use WhatsApp as a service
2. Unfocus Rambox window
3. Get a WhatsApp message

### Expected behavior

The Windows taskbar icon should show a badge with the notification count
### Actual behavior

The badge is not showing since the update to 0.5.3

### ENVIRONMENT

> Rambox: v0.5.3

> OS: Windows 81

> Arch: x64

**Comment by saenzramiro** [comment]
Yes, I noticed this also.

I will fix it in next release.

Thanks!

**Comment by suamikim** [comment]
@saenzramiro Do you have any plans on when this next release will arrive? The absence of tray bar notifications is a really big deal for me and degrades Rambox a lot.

**Comment by saenzramiro** [comment]
Yes, I know. I will try to release next week or the next one.

**Comment by suamikim** [comment]
Thank you for this info! I hope my previous post didn't sound rude. I was just curious about an approximate timeframe.

I really appreciate all your effort and where you are going with Rambox!

**Comment by Stanzilla** [comment]
@saenzramiro will this be fixed in the release tomorrow?

**Comment by Stanzilla** [comment]
@saenzramiro any news here?

**Comment by saenzramiro** [comment]
We are working in next release. I'm working on it when I have free time, so please be patience.

**Comment by orschiro** [comment]
Hey guys, 

Just installed version 0.5.14 but don't see a WhatsApp tray icon count. Can you help me?

Thanks!

![image](https://user-images.githubusercontent.com/170947/36313982-ace2ca2a-1333-11e8-949c-9f664df632a0.png)

![image](https://user-images.githubusercontent.com/170947/36313995-b9c7934c-1333-11e8-9dc1-1ae9f3435357.png)

**Comment by Ash258** [comment]
@orschiro Go to https://github.com/saenzramiro/rambox/issues/1446#issuecomment-365288366

**Comment by orschiro** [comment]
@Ash258 you are my hero at the moment. ;-)
