### ISSUE TITLE
Tray icon no longer changes

### ISSUE THREAD

**Issue by Silent-Hunter** [saenzramiro/rambox#643]
### Steps to reproduce

1. Start Rambox
2. Recieve message
3. 

### Expected behavior

White part of tray icon should turn red like it used to.

### Actual behavior

Icon stays white.

### ENVIRONMENT

> Rambox: v0.5.3

> OS: Linux 4.4.39-gentoo

> Arch: x64

**Comment by saenzramiro** [comment]
What services are you using?

**Comment by Silent-Hunter** [comment]
Discord, Hangouts, ICQ, Inbox, Telegram, The Lounge, and Twitter.

The behavior has changed though, now it's only Telegram that doesn't turn
it red. Messages on the others do now. Which is odd because I haven't
changed Rambox at all.

**Comment by saenzramiro** [comment]
Did you check if Rambox settings for Telegram are ok? In latest release, we add it two new options for each service to change the badge count behavior.

**Comment by Silent-Hunter** [comment]
They were both already checked, yes. OK, and now it's working, that's
weird. Nevermind, I suppose, although I don't know what made it start
working.

**Comment by Sudiukil** [comment]
Same problem here and same "fix". The icon stayed white for any service (I use MySMS, TweetDeck, (Facebook) Messenger, Discord and Steam) and _Show notifications_, _Display tab unread counter_ and _Include in global unread counter_ where checked on every services.

I edited each service to uncheck and check again these options and now it's working.

**Comment by saenzramiro** [comment]
@Silent-Hunter @Sudiukil Great! Ok, I will investigate why you had to do that to fix it. Maybe I missed something!
