### ISSUE TITLE
No way to remove the "Ready" status bar on bottom of the app

### ISSUE THREAD

**Issue by notnsane** [saenzramiro/rambox#645]
This should be optional, not forced. I have no need for it and it's taking a bit of my vertical space.

**Comment by peterjuras** [comment]
It also clashes with the style of some services, I also like to see an option to hide it.

**Comment by saenzramiro** [comment]
Ok, but how can we handle if there are certification warnings?

**Comment by MrChick** [comment]
force-show that bar on certificate warnings and make it close-able?

**Comment by saenzramiro** [comment]
That could be a way...

**Comment by ivoanjo** [comment]
May I suggest it be hidden when it would say "Ready", but with any other status, it shows up?

**Comment by MrChick** [comment]
@ivoanjo that's pretty much what I meant, but still being able to close it manually like "yeah yeah I know leave me alone dude"

**Comment by notnsane** [comment]
Just include an on click event that globally hides the bar (via CSS or JS) when "Ready". Shouldn't be super hard?

I didn't know this was due to certificates, weird!

**Comment by saenzramiro** [comment]
@notnsane Yes, we can do that or just add a new option in Preferences.

**Comment by ibrokemypie** [comment]
+1

**Comment by Stanzilla** [comment]
Yup, imo just close/hide it when there is no error

**Comment by ellipticaldoor** [comment]
+1

**Comment by untom** [comment]
This is shown as "closed", but using rambox 0.5.13 on Ubuntu, I still get the "ready"-statusbar every time I start rambox. Is this a regression or have I overlooked the option to disable this status bar?

**Comment by Stanzilla** [comment]
@untom it's per service 
![rambox_2017-11-16_14-19-28](https://user-images.githubusercontent.com/75278/32893292-33d13ace-cad9-11e7-9846-c8b99b95c51e.png)

**Comment by untom** [comment]
Thanks! :)
