### ISSUE TITLE
Way to stop checking for updates?

### ISSUE THREAD

**Issue by moceap** [saenzramiro/rambox#647]
Hi,

I making Rambox package that suitable with Fedora, and doing it in Ojuba repo:
https://copr.fedorainfracloud.org/coprs/moceap/Ojuba/

Today update message shown on Rambox, is any way to disabling checking? because original Rambox package conflict with Ojuba one, also Rambox updating give the user a wrong package type !!!

**Comment by saenzramiro** [comment]
We have a ticket for downloading the right package to Fedora. See #635

Do you think if we fix that it will work ok in Ojuba?

**Comment by moceap** [comment]
No, Ojuba repo don't use RPM built by Rambox. Because it's useless and not compatible with simple RPM building guides!

So we build ours, and need to remove stupid update button ..

The idea of repos that offer updates for all programs same time, systemic , not one by one and random!

**Comment by saenzramiro** [comment]
Do I don't know how can I help you with that, because I don't want to have different builds for Rambox. One with the update button and other without.

What do you suggest?

**Comment by moceap** [comment]
I suggest that you enable some thing like:

Rambox --without-update

OR

RAMBOX_UPDAGTTE=false Rambox

**Comment by saenzramiro** [comment]
Ok, I will investigate that.

**Comment by moceap** [comment]
Hope to do that as soon as possible, I'm working for new release of Ojuba. Planned to install it by default if this bug closed.

**Comment by jsnfwlr** [comment]
@moceap if you are packaging Rambox from source yourself for Ojuba, you should just fork Rambox, make the changes you need to prevent this update, and then rebase it every time @saenzramiro updates the master ... That is how all the other package maintainers handle things for different systems.

**Comment by moceap** [comment]
I dont build Rambox package from scratch because rebuilding it cant done by shell. Also Rambox maintainer know the code more than others.

Tank you @saenzramiro that you listed this in milestone.
