### ISSUE TITLE
System Tray indicator is not working since 0.5.x upgrade

### ISSUE THREAD

**Issue by roizcorp** [saenzramiro/rambox#648]
### Steps to reproduce

1. Whatsapp account, renamed and aligned to the right (not sure if relevant)
2. define one or more of the whatsapp groups to mute
3. recieve a message from a non-muted account

### Expected behavior

System tray indicator should be colored in red

### Actual behavior

System tray indicator is white

### ENVIRONMENT

Linux, Gnome 3 

> Rambox: v0.5.2 and 0.5.3

> OS: Arch Linux 

> Arch: x64

**Comment by lroetzer** [comment]
Same under Windows 10, 64bit, Rambox 0.5.3. 
It would be nice to see if a new message arrived without having to avtivate popup messages.

**Comment by roizcorp** [comment]
yes, I forgot to mention that the setting of the pop up messages is off meaning that the red colored system tray icon is my only indication

**Comment by suamikim** [comment]
Same here! Windows 10, 64bit, Rambox 0.5.3

![image](https://cloud.githubusercontent.com/assets/2870365/22502331/b6d00a72-e86c-11e6-82b4-6774b7c7b343.png)

**Comment by Perliz** [comment]
Same on Windows 7 Enterprise SP1, 64 bits (same Rambox than Suamikim above).

**Comment by saenzramiro** [comment]
Duplicate #642

**Comment by roizcorp** [comment]
although it is not important at all but #642 copied my issue and changed the env. details
