### ISSUE TITLE
Drawing not available in Google Keep (Custom service)

### ISSUE THREAD

**Issue by Silent-Hunter** [saenzramiro/rambox#649]
I know it's not an official service (although maybe it should be?)

### Steps to reproduce

1. Add Google Keep as custom service
2. Hover over the pen icon
3. 

### Expected behavior

Should be clickable, and allow drawing a note

### Actual behavior

Is unclickable, changes cursor to circle with line through it.

### ENVIRONMENT

> Rambox: v0.5.3

> OS: Linux 4.4.39-gentoo

> Arch: x64

**Comment by saenzramiro** [comment]
Works for me in Windows 10. Are you still having this problem?

In the meantime, I will close this issue.

**Comment by Silent-Hunter** [comment]
No, it's still greyed out and unclickable. As it's not an officially supported service, I can understand not fixing it. I have no idea what's causing it, as it works in Chrome on same OS.

**Comment by Silent-Hunter** [comment]
Unfortunately not.
