### ISSUE TITLE
Protonmail always logging out after system reboot

### ISSUE THREAD

**Issue by cryptono** [saenzramiro/rambox#650]
### Steps to reproduce

1. Add protonmail account
2. Log in
3. Reboot system

### Expected behavior

Protonmail account is logged in

### Actual behavior

Protonmail is logged out

### ENVIRONMENT

> Rambox: v0.5.3

> OS: Ubuntu

> Arch: x64

**Comment by ElecM8** [comment]
That's normal ProtonMail behavior, they recently made it so that you'd have to login everytime you load the page as far as I know. I might be wrong though

**Comment by cryptono** [comment]
@ElecM8 Even then it could be realized to be relogged in - safe the login data in Rambox and automatically execute the login button on startup.

Anyone have a solution?

**Comment by saenzramiro** [comment]
Is not the idea of Rambox to save credentials, to do auto-login. Like @ElecM8 said, this is a behavior of ProtonMail, there are a lot of users asking for this and hopefully they will add it in a future version.
