### ISSUE TITLE
Unable to use Zimbra Service for french operator webmail Free

### ISSUE THREAD

**Issue by ToRuDev** [saenzramiro/rambox#652]
This webmail is know to run under Zimbra but the Zimbra Service don't seem to do the job.
- Expected
Credentials entered I can use the webmail and stay connected like with the Gmail, Rocket.Chat, ... Services.

- Actual behavior
After each Rambox launch, I need to entered the credentials again.

- Environment
> Rambox 0.5.3
> Electron 1.4.15
> win32 x64 6.1.7601

**Comment by saenzramiro** [comment]
If you try it outside Rambox (like Google Chrome), works ok?

**Comment by ToRuDev** [comment]
[no dev here] Yes but I have to say that I don't know how long the session is maintained ... SO is it a behaviour of the service or an issue?

**Comment by saenzramiro** [comment]
In Rambox we handle the sessions pretty the same as a normal web browser.

Did you try be logging in, then close the browser, open it again and finally go to the service URL to see if the session keeps alive?

**Comment by ToRuDev** [comment]
I tried what you suggest and the session is lost ... Good point Ramiro! But sad news for me. Any possible workaround? Anyway big thanks for your work ;)

**Comment by saenzramiro** [comment]
Thank you @ToRuDev!

You can try to inject JS code to that service by going to the settings of that service in Rambox, and write a code to enter credentials and making login automatically. Other way, I don't think so.
