### ISSUE TITLE
Simplify synchronisation context menu

### ISSUE THREAD

**Issue by HoracePGreeley** [saenzramiro/rambox#655]
### Description
Instead of nesting sync context menu points "backup" and "restore" into a sub folder, move them into the top level of the context menu. 

![image](https://cloud.githubusercontent.com/assets/11772186/22499370/ac8a8a3c-e85e-11e6-8c5c-060fff0ee1ef.png)

### Goal
Simplify the context menu structure. Enhance usability.

### Steps
1. Remove context menu item "Synchronize Configuration"
2. Add them to the top level context menu
![image](https://cloud.githubusercontent.com/assets/11772186/22499411/eb69ade6-e85e-11e6-9e10-929e237ba93c.png)

### ENVIRONMENT
> Rambox: v0.5.3

> OS: Windows 10

> Arch: x64

**Comment by saenzramiro** [comment]
I agree, but I did it like that because I want to be sure synchronization works as expected. So I split it in different options, but in a future release I will merge them in a single option.

Thanks!
