### ISSUE TITLE
Keep getting certificate errors for Tumblr tracking gif

### ISSUE THREAD

**Issue by mdellabitta** [saenzramiro/rambox#657]
### Actual behavior

Periodically, I receive a certificate error for the following URL, which appears to be a Tumblr tracking image: https://32.media.tumblr.com/cedexis/r17.gif?rnd=[TRACKING DATA REDACTED]

The text of the error states:

> The service with the following URL has an invalid authority certification.
>
> [URL FROM ABOVE]
>
> If it is a Custom Service, you have to remove it and add it again, enabling the "Trust invalid authority certificates" in the Options.

I only have 3 Slack instances configured in Rambox. Note that none of these are custom services, and should not involve requests to Tumblr as far as I know.

### ENVIRONMENT

> Rambox: v0.4.5
> OS: macOS 10.11.6 
> Arch: x64

**Comment by jbbr** [comment]
This is fixed since 0.5.2
Just upgrade to latest 0.5.3 and the error will be gone.

**Comment by mdellabitta** [comment]
I got pushed the 0.5.3 update shortly after filing this. You're right, it does seem to fix the issue. Thanks!
