### ISSUE TITLE
Feature request: Add option to hide menu bar

### ISSUE THREAD

**Issue by rummik** [saenzramiro/rambox#658]
Hiding the menu bar would be nice from an aesthetics point of view.  It's something I do with terminal windows, Firefox (when I occasionally use it), etc., as they wind up going unused for the most part, and it allows reclaiming a little screen real estate on small displays.

**Comment by saenzramiro** [comment]
There is an option to hide Menu Bar, but this is hide in Linux OS. Are you in Linux?

**Comment by saenzramiro** [comment]
There is an option to hide Menu Bar, but this is hide in Linux OS. Are you in Linux?

**Comment by rummik** [comment]
Yes
