### ISSUE TITLE
Notifications

### ISSUE THREAD

**Issue by paddyde** [saenzramiro/rambox#659]
1. There is no visible change at the tab or tray icon if there are any messages received.

2. The popups for a new message in the windows 10 action panel / notification area discard after 3 seconds and there is no possibility to hold that. In the Windows 10 notification settings for this application are all settings set to the right possibility.

-
> Rambox 0.5.3
> Electron 1.4.15
> win32 x64 10.0.14393

**Comment by facano** [comment]
The same problem (1) of notifications.
- Rambox 0.5.3
- OSX Yosemite

**Comment by bobson83** [comment]
I have this problems too: No bage in tray icon, notification in action center are very fast vanish.
Version: 0.5.3
Platform: win32 (x64)
Electron: 1.4.15
Chromium: 53.0.2785.143
Node: 6.5.0

**Comment by saenzramiro** [comment]
Duplicate #642
