### ISSUE TITLE
Creating account using google credentials

### ISSUE THREAD

**Issue by ounos** [saenzramiro/rambox#66]
I am trying to create an account using my google credentials but after providing email address and password I get a blank window.

I guess similar (not exactly the same) to #37.

-
> Rambox 0.3.0
> Electron 1.2.5
> linux x64 3.13.0-91-generic

**Comment by saenzramiro** [comment]
Ok, I will take a look on this.

**Comment by mehor** [comment]
Just to provide another potentially useful info which seems related to this issue: the blank window which appears after entering the password actually contains (at least in my case, not sure for OP's) authentication form, but it's invisible. If I press left mouse button and drag around, the form is clearly visible. Also, if I hover mouse around, the cursor changes shape when it comes over the field to enter 2FA code. Refreshing doesn't help.

Note that this happens with all Google services I tried: Gmail, Inbox, Hangouts.

> Rambox Version: 0.4.0
> Platform: linux (x64)
> Electron: 1.2.6
> Chromium: 51.0.2704.106
> Node: 6.1.0


![rambox-google-issue](https://cloud.githubusercontent.com/assets/2765439/16946352/3c30c4a4-4da9-11e6-9311-ad2a20fafa12.jpg)

**Comment by saenzramiro** [comment]
Seems to be an Electron bug. But in the meantime, I will try to find a solution of this.

Thanks guys.

**Comment by saenzramiro** [comment]
Related #181
