### ISSUE TITLE
BusyBotApp (For Slack) -- Can't Login

### ISSUE THREAD

**Issue by citizenc204** [saenzramiro/rambox#662]
I've added BusyBot (a task management app for Slack) as a custom service. However, I can't successfully login.

1) Click "login with slack"
2) Enter Slack team
3) Enter Slack user name/pass
4) Click "Authorize" to allow busybot access to my slack team

Busybot then loops back to "login with Slack"

-
> Rambox 0.5.3
> Electron 1.4.15
> win32 x64 10.0.14393

**Comment by citizenc204** [comment]
Workaround: Message busybot with "LOGIN". Copy that link. Use that link as the service URL.

**Comment by saenzramiro** [comment]
I think I mentioned to you in another issue related.

We have to find a way to fix SSO login using third party apps when they displays the login windows in a popup instead redirecting the main app. I will try to find a way to fix this in a future release, it's a very important issue.
