### ISSUE TITLE
Service Setting: Show Icon Only

### ISSUE THREAD

**Issue by dogancelik** [saenzramiro/rambox#666]
I usually have one tab open for each domain (messenger, whatsapp, irccloud, etc.)
I want to show service icon only for each tab (just like pinning a tab in a browser)
This is an optional setting for each service.

I could rename a service an empty string but it looks ugly on Rambox Services page.

**Comment by saenzramiro** [comment]
Ok, I can do something quick to add this in next release.

**Comment by HoracePGreeley** [comment]
Just leave the service name empty:
![grafik](https://cloud.githubusercontent.com/assets/11772186/22796194/bbcc498a-eef9-11e6-968e-d69d7d0f2669.png)

**Comment by Ionaru** [comment]
@HoracePGreeley I think he means this:

![screenshot_20170210_120434](https://cloud.githubusercontent.com/assets/3472373/22824673/2613e282-ef89-11e6-9dac-4e236f9b72ac.png)

**Comment by dogancelik** [comment]
I don't want to leave service name empty because it looks ugly on Rambox service list like @Ionaru shows, and there will be times where you have multiple Gmails and want to know which Gmail is personal, for work, etc.

**Comment by saenzramiro** [comment]
Yes, I understood. I will add an option for this in next release.

**Comment by Fire-Dragon-DoL** [comment]
Hey @saenzramiro I'll throw this in since it's related: Is possible to configure the service icon to a custom one? (URL is fine). With slack horrible way to handle teams, I'm required to have 5 different slack services opened and they all share the same icon, while I would love to use the team icon instead

**Comment by saenzramiro** [comment]
@Fire-Dragon-DoL Sorry but you can't. I will try to do something to fix this in a future release.

**Comment by Fire-Dragon-DoL** [comment]
Thanks ;)
