### ISSUE TITLE
Feature Request: Hide tab if service is disabled

### ISSUE THREAD

**Issue by dogancelik** [saenzramiro/rambox#667]
I don't use few services currently (FastMail, TweetDeck, ProtonMail) and these service tabs take up a lot of space when they are not used. I would like to hide these tabs without deleting the services (and enable/show them back when I need to).

**Comment by saenzramiro** [comment]
Sounds a good idea!

**Comment by rickkuilman** [comment]
There should be an option to also grey-out services (how it works now)

Perphaps a dropdown (aligned to the right) with "hidden services 🔽" will do?
