### ISSUE TITLE
Rambox with a lot of services enable doesn't organise them on new row

### ISSUE THREAD

**Issue by sergssm11** [saenzramiro/rambox#669]
I would like to move from Franz to Rambox but can't do that because of I am having a lot of services enabled(skype, slack, hipchat). It is about 30 services actual in same moment of time. The problem is that all they are stored in one line and do not move on another string. So I see only 10-12 services on the screen. To see others I need to click arrow in the right or left side of services panel. It would be very helpful to make the same way as Franz which moves services to new string when the resolution of monitor doesn't allow to see all of them

**Comment by saenzramiro** [comment]
You will have to wait for version 1.0.0. In that version, we will introduce groups of services.

Read more: www.rambox.pro/100
