### ISSUE TITLE
[Feature request] Link to service website on Rambox.pro

### ISSUE THREAD

**Issue by Trollwut** [saenzramiro/rambox#672]
Hi folks!

It's just a minor idea, but anyway...

How about linking to the service homepage on the service list on Rambox.pro?

I was about to decide between Franz and Rambox, as I heard the latter is open source, which is a big plus for me. Rambox did not only cover my services of Franz, but when googling the rest of them (which I didn't know or didn't recognize their logo), I also discovered two additional supported services. This helped me deciding to use Rambox.

Extra: Link "Add more services manually!" to a page where user can demonstrate their favorite custom services.

Maybe that also helps to convince new users. :-)

**Comment by Ash258** [comment]
Now it's already there: 

![Image](https://i.imgur.com/CewVIwl.png)
