### ISSUE TITLE
[Feature Request] minimize Hangouts call window

### ISSUE THREAD

**Issue by Jimi-James** [saenzramiro/rambox#682]
Having the Hangouts call in a little "window" within the window is a really nice feature, but now I can't access any Hangouts chats while I'm in a call without opening hangouts.google.com from another browser/device, which is pretty annoying when the people I'm in a call with do something like send a link. Any of the following would fix this, in order of how much I'd prefer it top to bottom:
1. Minimize button for that call "window" that minimizes it to, say, a little box in a corner or something.
2. The ability to resize the call "window" and get rid of the overlay under it so that chats can be accessed at the same time.
3. A setting in Rambox to open calls as external links like before.

> Rambox: v0.5.3

> OS: Linux

> Arch: x64

**Comment by saenzramiro** [comment]
I think I will remove the mask, so you can resize and move the window to wherever you like and continue interacting with the service.

**Comment by NNois** [comment]
Arggf no ! You merged my request for Slack window here. The hangout problem wasn't really the same as Slack. In Slack, video is a second window plus an overlay on top of the screen with a reduced video permitting to work while you're in visio, in this state (0.5.9) this is not handy at all.

Could you please find a solution, keeping in mind if apps are using popup maybe they have a very good reason ;-)

Thank you very much
