### ISSUE TITLE
No audio in Whatsapp channel

### ISSUE THREAD

**Issue by ktrls** [saenzramiro/rambox#685]
I am not able to get the Audio with audio and video post. 
No problem with Skype.

### ENVIRONMENT

> Rambox: v0.5.3

> OS: Linux

> Arch: x64

**Comment by Vuelos** [comment]
(Stupid question) Do you not have Whatsapp muted?

**Comment by ktrls** [comment]
I think no.
On the phone sounds work.

**Comment by saenzramiro** [comment]
I think @Vuelos meant is that if you check the "Mute all sounds" options in the Rambox service configuration.

**Comment by MelvinDRM** [comment]
Hello,

I have the same issue, I've tried with Mute All Sounds setting on or off, and nothing.

Just to be clear: the fact that you have the Mute All Sounds setting on shouldn't mean that you can't listen to audios.

**Comment by cjdg** [comment]
+1

**Comment by M0UL** [comment]
i can not get any sound from any of services

**Comment by miguelzabala** [comment]
Check if you have "Don't disturb: ON" on the Config Services Tab

**Comment by M0UL** [comment]
clearing the local storage fixed it for me
