### ISSUE TITLE
Show/Hide in tray icon doesn't work

### ISSUE THREAD

**Issue by ktrls** [saenzramiro/rambox#686]
I try to click with left button of the mouse on the tray icon, but nothing happens.
It works with a couple of click with right button on it

### ENVIRONMENT

> Rambox: v0.5.3

> OS: Linux Cinnamon Manjaro

> Arch: x64

**Comment by ibrokemypie** [comment]
Same on windows

**Comment by saenzramiro** [comment]
Duplicate #608
