### ISSUE TITLE
Application Freezes on WhatsApp Notifications

### ISSUE THREAD

**Issue by holycow131415** [saenzramiro/rambox#687]
If "show notifications" are enabled for WhatsApp, the whole application freezes until it "catches up". It usually takes 1-2 mins to unfreeze. If its disabled, the app works. Other services (hangouts, messanger, etc) are working fine. I also disabled hardware acceleration but it didnt have any affect. 

Running Windows 10 Pro 64 bit

-
> Rambox 0.5.3
> Electron 1.4.15
> win32 x64 10.0.14393

**Comment by mpkossen** [comment]
I'm having exactly the same issue. I'm running Windows 10 Home 64-bit, all updates installed.

**Comment by saenzramiro** [comment]
Some users are having this issue, but most of the users don't.

I think is related with Electron. We have to find what causes this behavior.

**Comment by saenzramiro** [comment]
Related with #402
