### ISSUE TITLE
Clicking on Link opens it more than once

### ISSUE THREAD

**Issue by wolfskaempf** [saenzramiro/rambox#69]
Rambox v0.3.0
OS X 10.11.5
Chrome in which links open: Version 51.0.2704.103 (64-bit)

When I click on a link in rambox, it sometimes opens several times in Chrome, the amount varies. I've seen between three and seven tabs open.

Awesome app generally though! 😍

**Comment by saenzramiro** [comment]
Thanks!

Duplicate #28 , #11 , #6 .
