### ISSUE TITLE
Need to double click in the entry box for the Rocket.Chat client.

### ISSUE THREAD

**Issue by mkenyon2** [saenzramiro/rambox#692]
When I go to type a message in the Rocket.Chat client I have to double click in the text box.
If I am in a different program/app in one part of the screen, and then click in the text entry area of Rambox for Rocket.Chat, the textbox is not active. I have to click a second time. It seems like when I first activate the Rambox window, the cursor is removed from the textbox, and thus I have to refocus on that textbox.

Clicking the Rambox icon on the Task bar does not have the same affect. Only if the textbox is still visible while working in another app do I have to double click. (I use two-three screens at a time so usually leave Rambox up on one.)

-
> Rambox 0.5.3
> Electron 1.4.15
> win32 x64 10.0.14393

**Comment by SimJoSt** [comment]
I can confirm this issue. But not only with Rocket.Chat but for all services.

**Comment by saenzramiro** [comment]
Yes, is related with focus. I will take a look.

**Comment by saenzramiro** [comment]
Yes, is related with focus. I will take a look.

**Comment by saenzramiro** [comment]
Let's merge with #483.
