### ISSUE TITLE
"typo" in wiki

### ISSUE THREAD

**Issue by SimJoSt** [saenzramiro/rambox#693]
On the [wiki page for adding a custom services](https://github.com/saenzramiro/rambox/wiki/Add-a-Custom-Service) there is an explanation on how to inject some JavaScript code, to fix possibly missing notification badges. The form to input it in is named `Unread Code field`:
> 6. In Advanced option, there is an Unread Code field. This field you will use it if the service you are adding is not notifying an activity (new messages, new emails, etc) throw the title of the page (Ex. "(2) Facebook Messenger"). The number 2 means there are 2 messages unread.

As this is titles `Custom Code` in Rambox, I would change it in the wiki aswell.
I also added some other improvements:
> 6. In the Advanced option, there is a Custom Code field. You can paste some code into this field for fixing notification badges, if the service you are adding is not notifying you on any activity (new messages, new emails, etc). You can remove the title of the page (Ex. "(2) Facebook Messenger"). The number 2 means there are 2 messages unread.

**Comment by saenzramiro** [comment]
Thank you! Fixed.
