### ISSUE TITLE
Fastmail Links don't open properly

### ISSUE THREAD

**Issue by Aktariel** [saenzramiro/rambox#695]
### Steps to reproduce

1. Create custom service
2. Add Fastmail (url: https://fastmail.com, icon url: https://www.fastmail.com/static/images/app-icon-256.png) with default options
3. Login (two factor auth works as expected, even if you have a YubiKey)
4. Click on a link in an email

### Expected behavior

Link opens up in system default browser.

### Actual behavior

- Link opens in an empty Rambox window called "_blank" with no options to redirect
- Links also cannot be right clicked on to copy -> paste to a browser, and if the link does not include the actual URL, it can't be copied with Cmd+C.

### ENVIRONMENT

> Rambox: v0.5.3

> OS: macOS 10.12.3

> Arch: x64

**Comment by Aktariel** [comment]
Appears to be related/the same as, https://github.com/saenzramiro/rambox/pull/636

**Comment by k1sul1** [comment]
Can confirm, same behaviour on Windows 10 and macOS Sierra. 

Referenced pull request didn't work either.

**Comment by mdbraber** [comment]
Possibly this would help: https://github.com/saenzramiro/rambox/pull/636#issuecomment-299284744

**Comment by Aktariel** [comment]
Can confirm, the code by dogancelik in https://github.com/saenzramiro/rambox/pull/636#issuecomment-299339697 works to open fastmail links in my default browser.
