### ISSUE TITLE
no more desktop notifications for discord on linux

### ISSUE THREAD

**Issue by pcuinty** [saenzramiro/rambox#696]
Since a while there are no more desktop notifications anymore. the official discord app (wich is also an electron app, I believe) however works fine.

### Steps to reproduce

1. enable desktop notifications in rambox and in discord
2. wait for new massages
3. no notifications

### ENVIRONMENT

> Rambox: v0.5.3

> OS: ubuntu 16.04

> Arch: x64

**Comment by saenzramiro** [comment]
Did you check if Discord settings itself have a Notification option? In some services like Facebook Messenger for example, you have to enable it manually.

**Comment by pcuinty** [comment]
yes, I just double checked. Notifications are enabled. The official discord linux client uses the same settings, since I use the same account, notifications work well there.

**Comment by saenzramiro** [comment]
I tested on Ubuntu 16.04 and works ok.

Please read here: https://github.com/electron/electron/blob/master/docs/tutorial/notifications.md#linux

**Comment by Maxime-M** [comment]
Not working for me either :( 

`libnotify` is installed and notifications work for all other services (Slack, Mattermost, Messenger, Hangouts)

Rambox version: 0.5.13
Plateforme: linux (x64)
Ubuntu 16.04.3
