### ISSUE TITLE
[Feature Request] Lock Rambox with master PW / move lock button

### ISSUE THREAD

**Issue by Bonez76** [saenzramiro/rambox#697]
Would be great that "Lock Rambox" button uses the master password, if one is set, not second (temporary one) and that you can disable this functionality on the settings. The lock button - in my opinion - should always be visible, not only in the "Add a new Service" tab (maybe add a keyboard shortcut function too).

**Comment by saenzramiro** [comment]
Shortcut to lock Rambox is F2 key.
