### ISSUE TITLE
[Feature Request] Left click on system tray icon to focus window

### ISSUE THREAD

**Issue by bddenhartog** [saenzramiro/rambox#700]
Environment: 64-bit Linux, Gnome 3

Currently, the only way to focus Rambox (which is not minimized, but just out of focus) when I'm in another application is to `alt-tab`, or right-click the system indicator and click the `show/hide` option twice (first to minimize/hide it, second to 'show' it) -- and then left click on the system notification that "rambox is ready". 

I propose that functionality be added such that a single or double left-click on the system indicator icon will bring the Rambox window into focus.

**Comment by ruihildt** [comment]
This would be indeed very nice to have. It's a pain to have to click twice every time.

**Comment by saenzramiro** [comment]
Good idea. 👍

**Comment by poisonborz** [comment]
+1, but I'd categorize this as a bug actually. In Windows this is a default app behaviour, and first I thought something is wrong, since I have only the tray icon (with minimize to tray option), and if there is already a window somewhere behind the current window, left-clicking the tray icon has no effect whatsoever. As with this option (?) the window is not in the alt-tab list, right now you have to minimize all windows in front of the Rambox window to get to the app.

**Comment by bddenhartog** [comment]
@poisonborz 
> I'd categorize this as a bug actually. In Windows this is a default app behaviour.

I don't think this is an accurate statement; while it is true that many applications have such a feature, I don't believe it is the "default action".

**Comment by poisonborz** [comment]
Well, not for me.
![clipboard01](https://cloud.githubusercontent.com/assets/1070611/23333856/a09ab2c2-fb93-11e6-9ab7-0010168dbbe3.jpg)

**Comment by nmat** [comment]
I did a rather minor patch, not sure if it helps though.

https://github.com/saenzramiro/rambox/pull/728

**Comment by poisonborz** [comment]
Could only test this now that the release is out. On Windows the window is now focused/brought in front properly on tray clicks 👍

**Comment by bddenhartog** [comment]
@saenzramiro this is still an issue under Gnome 3.

**Comment by pennybuster** [comment]
@saenzramiro It doesn't work correctly in Linux Mint 18.2 Sonya XFCE yet. Saludos desde Corrientes!

**Comment by saenzramiro** [comment]
@bddenhartog I will add this bug to do in next release.
@pennybuster ;)

**Comment by saenzramiro** [comment]
Let's continue with Linux bug in #942.

**Comment by bddenhartog** [comment]
@saenzramiro Wouldn't it have made more sense to mark #942 as a duplicate of this issue, given that it was created several months after?
