### ISSUE TITLE
No more Mightytext notifications.

### ISSUE THREAD

**Issue by chybaDapi** [saenzramiro/rambox#703]
Hi, 
I don't see notifications from Mightytext. I have checked option "Show notifications" in Rambox, and I also see notifications inside application tab, but not in Action Center. I also don't see unread messages counter.
I receive notifications from other apps (e.g. Messanger, Hangout). I working on Windows 10.

-
> Rambox 0.5.3
> Electron 1.4.15
> win32 x64 10.0.14393

**Comment by saenzramiro** [comment]
For now, Electron is not working correctly with Action Center. Some services, as you mention, works and others not. We will have to wait until Electron fix this.

Unread count it will be fixed in next release.
