### ISSUE TITLE
Strange behaviour with right-aligned tabs when navigating UI with keyboard shortcuts

### ISSUE THREAD

**Issue by ZaLiTHkA** [saenzramiro/rambox#705]
I have a single tab on the left and three tabs on the right, as follows:

* Left:
  * Outlook 365
* Right:
  * Skype
  * Gitter
  * TweetDeck

Navigating through the tabs with `ctrl + PgDn`, from the core configuration tab, I get:

1. Outlook 365
2. Skype
3. Gitter
4. Rambox config
5. Outlook 365
6. etc...

There are a few caveats to this behaviour:

* When I change the tab alignment and leave only a single tab right-aligned, then this shortcut does not skip the last tab. This only happens if there are 2 or more tabs set to right aligned.
* This does not appear to apply to the `ctrl + PgUp` shortcut, regardless of how many tabs are left aligned.

---

-
> Rambox 0.5.3
> Electron 1.4.15
> win32 x64 10.0.14393

**Comment by saenzramiro** [comment]
You are right, I just test it and is skipping last tab.

I will fix this in next release.

Thanks!
