### ISSUE TITLE
Rambox keeps spaming notifications

### ISSUE THREAD

**Issue by guillefar** [saenzramiro/rambox#710]
### Steps to reproduce

1. Receive a message (this happens with hangouts, not sure if with other messengers)

### Expected behavior

To notify just once 

### Actual behavior

Notifications keep arriving. 

### ENVIRONMENT

Cinnamon 3.2.8

> Rambox: v0.5.3

> OS: Linux 16.04

> Arch: x64

**Comment by guillefar** [comment]
The number of notifications that appear in the top right of the tab of hangouts keep turning on and off. Not sure if this was how it worked before, but seems to be connected with the the notifications spam.

**Comment by saenzramiro** [comment]
Yes, if the badge turns on and off it will cause notifications spam.

I will take a look.

**Comment by Rakaim** [comment]
I'm seeing this same issue with Google's app "Inbox". It says "You have 4 new emails" and keeps spamming that message until I change workspaces. After I change workspaces, the messaging notifications start a new.
Ubuntu 16.10

![screenshot from 2017-03-07 23-48-06](https://cloud.githubusercontent.com/assets/23176626/23691939/4445da46-0391-11e7-9cb4-6d004c38c0a0.png)
![screenshot from 2017-03-07 23-49-27](https://cloud.githubusercontent.com/assets/23176626/23691940/4447223e-0391-11e7-94a7-f9261367e409.png)

**Comment by jcolesio** [comment]
Updated to the latest version running Windows 10 1703   OS Build: 15063.332

Getting spammed from hang out notificaitons
