### ISSUE TITLE
Tutanota doesn't show incoming mail

### ISSUE THREAD

**Issue by fortran77** [saenzramiro/rambox#712]
I recently installed Rambox on an OS X machine. One of the sites that I configured into Rambox is Tutanota.

I received a new email message on Tutanota.com. The Android app for Tutanota showed me a notification for the email and showed me the email when I accessed it. But the email did not show up anywhere within the Tutanota tab within Rambox.  Then I logged into the tutanota.com website and saw the same email.

So, to summarize:

New email arrives.
Email is visible in the Android app for Tutanota.
Email is not visible in the Rambox tab for Tutanota.
Email is visible on the tutanota.com website.

This has happened only once so far (but I get very little Tutanota email).

I see that when I insert the [example JavaScript code](https://github.com/saenzramiro/rambox/wiki/Inject-JavaScript-Code) to cause a periodic website reload, I am asked if I want to reload the website to activate the JavaScript code. It might be helpful to have a button so we could manually cause the same website reload.

I didn't check to see if this reload would make the email visible. I will try that the next time this problem occurs.

> Rambox: v0.5.3
> OS: OS X
> Arch: x64 

Version: 0.5.3
Platform: darwin (x64)
Electron: 1.4.15
Chromium: 53.0.2785.143
Node: 6.5.0

**Comment by saenzramiro** [comment]
Did you check Tutanota in Google Chrome?

**Comment by fortran77** [comment]
1. Yes I did check in Google Chrome. It was my intent to say that when I wrote "Email is visible on the tutanota.com website" — sorry for the lack of clarity.
2. Tutanota seems to have some issues with not always showing the same content both on its website and in the Android app. So I am not at all sure that Rambox is at fault here.
3. At the time that I wrote "It might be helpful to have a button so we could manually cause the same website reload" I had not realized that on OS X the menu item View => Reload Current Service will in fact reload the website. So that part of my bug report can be ignored.

If I can collect better information I will add it here.

**Comment by fortran77** [comment]
I did some tests with Tutnota open both in a Rambox tab and in a Google Chrome browser, and i find that changes occurring in one are not always reflected in the other -- in both directions. Refreshing the Chrome or Rambox tab fixes the discrepancy. Also the Android app for Tutanota often gets of of sync, and there is no way to refresh its view, so it just stays out of sync.

So it appears that Tutanota is not causing clients to refresh their caches just like in the pre-Ajax days. It's probably not a Rambox-specific problem.

I think it would be helpful to change the meanings of the Rambox refresh keys at least in OS X. We will rarely refresh all of the Rambox tabs, but we may want to often refresh a single tab. So refresh of a single tab should require simpler key combinations. After the proposed change:

  ⌃R or ⌘R = control-R or command-R = Refresh current tab
  ⇧⌃R or ⇧⌘R= shift-control-R or shift-command-R = Refresh all tabs

Both ⌃R and ⌘R should be recognized — it will decrease confusion for users who use multiple platforms.

**Comment by saenzramiro** [comment]
What you are proposing is to switch shortcuts between Refresh all tabs and current tab. Because as you can see now in View menu, those options are already there.

**Comment by fortran77** [comment]
Yes, this is correct. The options exist in the View menu. The key combinations should be switched to make the more common one the easier one to type. This will also decrease the incidence of accidentally refreshing all tabs when only one was intended.


In fact it would be even better to not have any key combination to refresh all tabs. We rarely want to refresh all tabs, so it's better to prevent accidents by hitting the wrong keys. We can refresh all tabs via the View menu in the rare case that we need to do so.

**Comment by saenzramiro** [comment]
Ok, I will consider this for a future release. Thanks.
