### ISSUE TITLE
Chat windows within Hangouts can't be resized

### ISSUE THREAD

**Issue by CliffWade** [saenzramiro/rambox#713]
When you open up a chat window with a group or an individual, that window that pops open can't be resized at this time like it used to be. 

### Steps to reproduce

1. Click on a chat(person or group)
2. The window that appears should be a window that you can resize, but it can't be resized any longer.
3. 

### Expected behavior

This chat window should be a window you can resize.

### Actual behavior

The window can no longer be resized as it once used to be able to.

### ENVIRONMENT

> Rambox: Current version

> OS: Windows 10

> Arch: x64

**Comment by Kurre** [comment]
Apparently chat window isn't resizable even in https://hangouts.google.com anymore 😕 I'm also missing this feature. Maybe there's something that can be done in Rambox, but I dunno.

**Comment by saenzramiro** [comment]
We don't have an intention to allow resize chat windows. Maybe someone can make a PR to allow this.
