### ISSUE TITLE
crtl-w accidental shutdown

### ISSUE THREAD

**Issue by evancaldwell** [saenzramiro/rambox#715]
Sometimes when I have a browser open on one screen and Rambox on the other I accidentally press ctrl+w while Rambox is focused. Doing so closes Rambox but I can't get it to open again by clicking the menu icon or the tray icon. I have to open a terminal kill Rambox and then re-open it.

-
> Rambox 0.5.3
> Electron 1.4.15
> linux x64 4.4.0-64-generic

**Comment by saenzramiro** [comment]
What about right click in tray icon and select "Show/Hide Window"?

On the other hand, we have a bug to fix regarding with double click in tray icon to show window.

**Comment by evancaldwell** [comment]
Ah, didn't realize that feature existed, it did the trick. The first two times I clicked show/hide it didn't come up but that may have just been my machine being sluggish this morning.
