### ISSUE TITLE
Blank page in Slack

### ISSUE THREAD

**Issue by thiemol** [saenzramiro/rambox#717]
I add some services and everything works well, but Slack is not working. The browser can connect to Slack. Do I miss something?

### Steps to reproduce

1. Add a new service
2. Choose Slack
3. Insert URL
4. Get blank page

### Expected behavior

Seeing the Slack Team page.

### Actual behavior

We see a blank page.

### ENVIRONMENT

Rambox: v0.5.3
OS: ubuntu
Arch: x64

**Comment by freddurst1805** [comment]
Same problem here in windows 8.1 x64

**Comment by nmat** [comment]
interesting I did not get this on windows 10

**Comment by ltapparo** [comment]
Same problem in ubuntu 14.04

on Developer Tool shows the error

Uncaught ReferenceError: $ is not defined
checkUnread @ VM81:1

**Comment by ltapparo** [comment]
Resolved in my case removing the http of the url in configuration

**Comment by saenzramiro** [comment]
Like @Itapparo said, be sure to don't include the "https://" in the URL.

**Comment by thiemol** [comment]
I do not have a http or https in the url and still this error.

![bildschirmfoto vom 2017-04-04 09-06-47](https://cloud.githubusercontent.com/assets/6862898/24644927/48fd41ce-1916-11e7-9284-2adbccfb3425.png)

**Comment by saenzramiro** [comment]
Can you right click in Slack tab and click Reload?

You can try also to open the console of Slack to see what is loading.

**Comment by thiemol** [comment]
if i reload i get this error message:

```
Uncaught Error: Could not call remote function 'bound '. Check that the function signature is correct. Underlying error: callback can only be called for once
Error: Could not call remote function 'bound '. Check that the function signature is correct. Underlying error: callback can only be called for once
    at callFunction (/opt/Rambox/resources/electron.asar/browser/rpc-server.js:235:11)
    at EventEmitter.<anonymous> (/opt/Rambox/resources/electron.asar/browser/rpc-server.js:309:5)
    at emitThree (events.js:116:13)
    at EventEmitter.emit (events.js:194:7)
    at WebContents.<anonymous> (/opt/Rambox/resources/electron.asar/browser/api/web-contents.js:231:13)
    at emitTwo (events.js:106:13)
    at WebContents.emit (events.js:191:7)metaToValue @ remote.js:217remoteFunction @ remote.js:234(anonymous function) @ app.js:1apply @ callbacks-registry.js:48(anonymous function) @ remote.js:282emitThree @ events.js:116emit @ events.js:194
```

**Comment by saenzramiro** [comment]
Did you tried by reinstalling Rambox?

**Comment by maxime-helen-sb** [comment]
Same problem on Windows

**Comment by Kawohl** [comment]
Hmm same for me latest releases .deb and mac sierra 10.2.5 
I get the console error 
```
Uncaught ReferenceError: $ is not defined
    at checkUnread (<anonymous>:1:36)
```

**Comment by Kawohl** [comment]
never mind, i overlooked a `.`
