### ISSUE TITLE
no hangouts badge icon

### ISSUE THREAD

**Issue by skorbuly** [saenzramiro/rambox#718]
### Steps to reproduce

1. receive a new hangouts message 
2. desktop notification shows up 
3. dock badge icon doesn't show up

Version: 0.5.3
Platform: darwin (x64)
Electron: 1.4.15
Chromium: 53.0.2785.143
Node: 6.5.0

macOS Sierra 10.12.3

**Comment by saenzramiro** [comment]
Yes, we have a bug related with this. We will fix it in next version.

Thanks.
