### ISSUE TITLE
Disqus integration?

### ISSUE THREAD

**Issue by orschiro** [saenzramiro/rambox#719]
Dear all, 

What a fantastic application!

Thank you so much. :-)

Question: 

Can we somehow integrate the Disqus commenting system with its notifications?

**Comment by saenzramiro** [comment]
You can add Disqus as a [Custom Service](https://github.com/saenzramiro/rambox/wiki/Add-a-Custom-Service) with the following URL:

https://disqus.com/home/inbox/

**Comment by orschiro** [comment]
Fantastic, thank you!
