### ISSUE TITLE
Skype plugin installation failing

### ISSUE THREAD

**Issue by cukabeka** [saenzramiro/rambox#72]
Skype does not make calls. The Call buttons are disabled. When I tried to make a call for the first time, a dialog "you need to install the plugin" appeared. Nothing seemed to happen after I clicked "install" several times. So I clicked cancel. Now I'm not sure whether I canceled installation before it was ready. Or how re-access this possibility to install a plugin. 

-
> Rambox 0.3.0
> Electron 1.2.5
> darwin x64 14.5.0

**Comment by jbbr** [comment]
This will probably work with the next release, see issue #41

**Comment by saenzramiro** [comment]
As @jbbr said, I added audio calls to Skype for the next release, but for video I have to study more the case, because as you said, I don't know if chrome plugins can be used with Electron.

I will keep open this issue, because is for video issue.

**Comment by saenzramiro** [comment]
Ok, so after investigating Skype blocks audio and video calls intentionally.

More info [HERE](https://github.com/saenzramiro/rambox/wiki/Skype).

We will need to wait until they remove that restriction.
