### ISSUE TITLE
WhatsApp not unread tray icon Ubuntu 16.10

### ISSUE THREAD

**Issue by orschiro** [saenzramiro/rambox#720]
Dear all, 

Can someone reproduce the problem that the tray icon does not show unread status on Ubuntu 16.10 for WhatsApp messages?

Please see the following example:

![image](https://cloud.githubusercontent.com/assets/170947/23650235/b41c654e-0321-11e7-86d5-f2f526f24c90.png)

**Comment by DiegoRBaquero** [comment]
Happens to me in MacOS Sierra.

**Comment by cyberpunk627** [comment]
same here on win 7. no badge on tray icon.
I will add that I don't see notifications either (they're enabled in rambox AND in whatsapp service too).

**Comment by toXel** [comment]
Can confirm this on Windows 10

**Comment by saenzramiro** [comment]
Duplicate #642.
