### ISSUE TITLE
Auto-reload if internet connection error?

### ISSUE THREAD

**Issue by orschiro** [saenzramiro/rambox#721]
Dear all, 

My Rambox starts automatically on startup of my Ubuntu 16.10 system.

Sometimes, however, it launches even before Ubuntu established an internet connection. 

This means that all Rambox services don't  properly load.

Currently, I have to manually reload them. 

Can we automate this process somehow?

Yours,

Robert

![image](https://cloud.githubusercontent.com/assets/170947/23739326/48a7be2a-049e-11e7-846c-9a1c47ce8dbf.png)

**Comment by saenzramiro** [comment]
Just reload the entire Rambox with Ctrl + R, instead of reloading each service.
