### ISSUE TITLE
Pushbullet error screen with Google auth

### ISSUE THREAD

**Issue by stmyers** [saenzramiro/rambox#722]
### Steps to reproduce

1. Add new service for pushbullet
2. Login using google account

### Expected behavior

Access to pushbullet

### Actual behavior

Error screen:
![image](https://cloud.githubusercontent.com/assets/5650794/23750676/09e1167a-049c-11e7-9b1d-4a82d0bb2738.png)

### ENVIRONMENT

> Rambox: v0.5.3

> OS: both macOS 10.12.3 & Windows 10

> Arch: x64

**Comment by saenzramiro** [comment]
Duplicate #185.
