### ISSUE TITLE
Telegram no audio from audio messages

### ISSUE THREAD

**Issue by orschiro** [saenzramiro/rambox#724]
Dear all, 

Does someone else have the same problem of not having audio from audio messages in Telegram on Ubuntu 16.10?

**Comment by orschiro** [comment]
I now the problem.

I muted Telegram in the settings because I don't want to hear the new message notification sound.

However, I do want to hear the audio of received messages (e.g. audio messages or embedded YouTube videos). 

Any ideas how to distinguish between those two?

Yours,

Robert

**Comment by saenzramiro** [comment]
No, there is no way to do it unless Telegram add that option.
