### ISSUE TITLE
How to update panel indicator (Ubuntu)?

### ISSUE THREAD

**Issue by eudennis** [saenzramiro/rambox#729]
### Steps to reproduce

Use it on Ubuntu Unity ;)

### Expected behavior

Use status icon provided by Icon Theme

### Actual behavior

It use the default status indicator icon

### ENVIRONMENT

> Rambox: v0.5.3

> OS: Ubuntu 16.10

> Arch: x64 

My icon theme have icons for status indicator, but it doesn't works. Am I missing something?

![rambox_indicator](https://cloud.githubusercontent.com/assets/1117340/23837757/0d406bb8-076c-11e7-9f29-d71e1f05a654.png)

**Comment by eudennis** [comment]
Forgot that one:
![rambox_2](https://cloud.githubusercontent.com/assets/1117340/23837765/315006f8-076c-11e7-9228-7293ee728b3d.png)

**Comment by saenzramiro** [comment]
We will change icons for differents OS in version 1.x.

Thanks.
