### ISSUE TITLE
Add-ons on Gmail

### ISSUE THREAD

**Issue by andrsussa** [saenzramiro/rambox#731]
Hi, I would like to know if it'd be possible to add an easy way to install add-ons for Gmail. Or, maybe if you'd point me to a custom script that could do this?

Thank you.

**Comment by saenzramiro** [comment]
You can [inject custom JavaScript code](https://github.com/saenzramiro/rambox/wiki/Inject-JavaScript-Code) to any service, so that's the way for now. Or just install addons from Gmail Labs.
