### ISSUE TITLE
What is ClientID and Domain in env-sample.js 

### ISSUE THREAD

**Issue by qamonstir** [saenzramiro/rambox#733]
In the Quickstart there is a section Configure env-sample.js. What to input there ? Where can I get ClientID and Domain?

var auth0Cfg = {
	 clientID: ''
	,domain: ''
};

**Comment by nmat** [comment]
@qamonstir those are for auth0 login. I have managed to run the application without those credentials. You could always check on https://auth0.com/ for information.

If you check you can see it says: var auth0Cfg

**Comment by qamonstir** [comment]
@nmat great, thanks. So I can just rename the file without configure step? "Configure env-sample.js and rename it to env.js." https://yadi.sk/i/6WYLepk43FuLyM ?

**Comment by nmat** [comment]
@qamonstir I believe so yes. Because then you would use the system as if you where not going to use auth0. Try it. Like I said I am not sure how it behaves to 100%.
