### ISSUE TITLE
Clicking in the "send a message" area doesn't always register keystrokes in Hangouts

### ISSUE THREAD

**Issue by Gazoo** [saenzramiro/rambox#734]
### Steps to reproduce

Many times I have to click multiple times in the "send a message" area then begin typing otherwise Rambox doesn't register my keystrokes. This behavior doesn't happen when using Franz.

### Expected behavior

Clicking in the  "send a message" area should allow you to type right away.

### Actual behavior

Focus is not being handled correctly. To see it working correctly just use Franz for a while.

### ENVIRONMENT

Rambox: 0.5.3
OS: Windows 10 pro
Arch: x64

**Comment by saenzramiro** [comment]
Yes, this is a focus problem. Let's merge with #483.
