### ISSUE TITLE
PushBullet Sign In Error

### ISSUE THREAD

**Issue by timhyd** [saenzramiro/rambox#735]
Cannot sign in. Have checked there are cookies connected to PushBullet. This is the first time I have tried signing in.

![screenshot from 2017-03-14 09-17-33](https://cloud.githubusercontent.com/assets/12206481/23910521/43132a1a-0897-11e7-8084-d3befac33abb.png)

-
> Rambox 0.5.3
> Electron 1.4.15
> linux x64 4.9.0-kali3-amd64

**Comment by saenzramiro** [comment]
Thanks @nmat. 

Please follow #185.
