### ISSUE TITLE
Error during sencha:compile

### ISSUE THREAD

**Issue by qamonstir** [saenzramiro/rambox#738]
Hello guys, how to resolve this issue? I can't install rambox because of that.

![rambox error installation](https://cloud.githubusercontent.com/assets/14925879/23965719/928efbb6-09c1-11e7-9ac4-51030b0a709d.png)

**Comment by nmat** [comment]
Getting the same error here. Not sure why this happens though. :(

**Comment by nmat** [comment]
Hello again,

So to continue with this:

1. Install sencha again and makes sure you select "Compass extension" with the installation: see http://stackoverflow.com/questions/31249409/sencha-build-due-to-sass-target

2. Make sure you have ruby installed. The installer will ask to start a ruby way of building the package.

Can you try that?

**Comment by qamonstir** [comment]
@nmat Compass extension fixed the problem. Thanks

**Comment by nmat** [comment]
@qamonstir cool, I guess this ticket can be closed?
