### ISSUE TITLE
No sound out of Rambox

### ISSUE THREAD

**Issue by Arsgan** [saenzramiro/rambox#741]
Hi guys, just to report no sound comes out of Rambox when you are trying to reproduce the audios you receive with Whatsapp and/or Telegram services. I try both with and without headphones with no sucess. I check as well if sound card was working well. Can you double check on it please?

Thanks

-
> Rambox 0.5.3
> Electron 1.4.15
> win32 x64 10.0.14393

**Comment by Arsgan** [comment]
I'm so sorry, I enable the "don't disturb" funtion accidentally pressing F1. Taking off this funtion enable the sound at both services. Anyway, I'm eager to know as well details on #724 issue and if is possible to fix. Thanks and sorry again for my misunderstanding. Bye the way, this is a beautiful piece of software!

**Comment by ugogo** [comment]
My "don't disturb" is OFF, but I still have no sound when playing videos on a Slack tab 😞

**Comment by wranvaud** [comment]
On the service (Slack) configurations did you select "Mute all sounds"? 
There is no distinction now between notification sound and media sound. This is IMHO the issue here, one might not want notification sounds but still hear voice messages or videos.

Related issues:
https://github.com/saenzramiro/rambox/issues/724
https://github.com/saenzramiro/rambox/issues/685

**Comment by cfviotti** [comment]
Hey, just to report I had the same exact issue bothering me for days and this issue helped me solve it. I surely would have noticed that the "don't disturb" mode was on if there was a better indication in the UI. Most probably something like a persistent icon at the top bar, and not just in the Rambox tab. Just an Idea :)

**Comment by cryoff** [comment]
This issue is bothering me both in facebook and whatsapp chats. I see the sound stream in PulseAudio audio mixer but no sound really comes out :( I have no idea why. Probably it has to do with PulseAudio itself :(

**Comment by SalahAdDin** [comment]
@cryoff Where is the cache?

**Comment by hickscorp** [comment]
This is absolute gold. Didn't even know there was a DND mode, and always thought the "No sound" issue was a forever bug (Using RB for 2 years or so). Thanks!
