### ISSUE TITLE
The flowdock unread messages counter that appear on the app tabs is showing wrong information.

### ISSUE THREAD

**Issue by wranvaud** [saenzramiro/rambox#742]
It shows as if there were 2 unread messages when there are no messages and shows as if there were no messages when there are any number of unread messages. This only happens on one of the organizations, if I select another ogranization from the sidebar on the left, the counter is cleared.
This is tricky because mentions seem to be notified properly, regular messages don't. It seems to be working very inconsistently particularly when there are no new messages.
The other counters seem to work fine (inbox, gmail, roundcube, telegram...)
I have tried reloading the service, reload all, clear cache, clear local storage, clicking on the "Mark all read" from the flowdoc notification menu and uninstalling and re-installing the app.
![rambox-flowdoc](https://cloud.githubusercontent.com/assets/6908112/24048970/517539ee-0b09-11e7-996f-fe1926d0a2f0.png)

-
> Rambox 0.5.3
> Electron 1.4.15
> linux x64 3.13.0-112-generic

**Comment by saenzramiro** [comment]
Can you open Flowdock in your default browser (with the organization that have problems) and go to the same section you are in Rambox that is displaying the number 2 and copy and paste here the title of that page.

**Comment by wranvaud** [comment]
The page title is `<title>phase2 (phase2) - Flowdock</title>`.

**Comment by saenzramiro** [comment]
So that's why shows 2. There is a regex that get the number from title. Maybe renaming the channel will help for now.

**Comment by wranvaud** [comment]
Can you point me to where this is in the code and I improve the regex and create pull request? I can't change the company name just because of this bug.

**Comment by saenzramiro** [comment]
Flowdock don't have an special unread count. By default, they change the title of the page with the number of unread messages (like "Flowdock (3)").

https://github.com/saenzramiro/rambox/blob/master/app/store/ServicesList.js#L321

**Comment by LagrangianPoint** [comment]
This happens when you have a document title with a number within parenthesis. On my case, the name of my company was within parenthesis like "(companyname2)" . A fix for this would be to configure your application with the following JS code in the advanced options menu:
and `setInterval(function(){document.title = document.title.replace("(companyname2)", " ")}, 300);`
Replace **companyname2** with the name of your company which could be causing this issue.
