### ISSUE TITLE
Custom Service not accepting IP or localhost

### ISSUE THREAD

**Issue by wasimxe** [saenzramiro/rambox#744]
Custom Services is not accepting IP or localhost in domain input. 

-
> Rambox 0.5.3
> Electron 1.4.15
> win32 x64 10.0.14393

**Comment by FallenKN** [comment]
IIRC only http/s Adresses are allowed for now, but using an IP for custom services could be helpful

**Comment by saenzramiro** [comment]
You can use IP's or localhost by always use prefix "http://" or "https://".
