### ISSUE TITLE
Kik on rambox? 

### ISSUE THREAD

**Issue by Ansem93** [saenzramiro/rambox#745]
It's possible to add kik on rambox? Or since it doesn't have a web interface is not possible?

**Comment by TriiNoxYs** [comment]
It's not possible to add services without web interface :/

**Comment by gajus** [comment]
Sure it is possible. Just a lot more work. It would require building a UI and interacting with the Kik API.

**Comment by saenzramiro** [comment]
Both @TriiNoxYs and @gajus comments are right.

We don't have plans to build any UI to any service for now, because we want to be "neutrals".
