### ISSUE TITLE
Rambox problem with Pushbullet login.

### ISSUE THREAD

**Issue by natestokes** [saenzramiro/rambox#747]
Can't use pushbullet in Rambox:

Sorry, something went wrong.
Local Storage seems to be unaccessible to us.
Do you have cookies disabled?
Some browser extensions can conflict with our site. Temporarily disable them to test this.

I can't find any way to enable cookies in RAMBOX however. What's the solution to this?

-
> Rambox 0.5.3
> Electron 1.4.15
> linux x64 4.8.0-41-generic

**Comment by nmat** [comment]
Reported already in:

https://github.com/saenzramiro/rambox/issues/547

and

https://github.com/saenzramiro/rambox/issues/735
