### ISSUE TITLE
Switch service tabs with keyboard shortcuts

### ISSUE THREAD

**Issue by c0d1ng** [saenzramiro/rambox#75]
As you can use Ctrl + Page Up/Down in the browser to change tabs, this would also be nice in rambox.

**Comment by nahtnam** [comment]
I would love to see CTRL + TAB and CTRL + SHIT + TAB being implemented as all browsers support that keyboard shortcut as well.

**Comment by saenzramiro** [comment]
Yes, I did it and works like a charm! Using Ctrl + Tab and Ctrl + Shift + Tab.

It will be implemented in next release.

**Comment by nahtnam** [comment]
Awesome, thanks!

**Comment by bpetrynski** [comment]
Is it possible to add the Ctrl + Page Up/Down shortcut as well? It works in browsers and MS Excel, I am more used to use this one instead. Thank you very much!

**Comment by saenzramiro** [comment]
@bpetrynski Yes, I will try to add it for next release.
