### ISSUE TITLE
after installing 0.5.3 changelog for 0.5.2 is shown

### ISSUE THREAD

**Issue by SimJoSt** [saenzramiro/rambox#750]
### Steps to reproduce

1. install Rambox x64 0.5.3
2. wait for welcome screen with changelog

### Expected behavior
The changelog for the just installed version should be shown, which is 0.5.3

### Actual behavior
The changelog for 0.5.2 is shown.

### ENVIRONMENT
> Rambox: v0.5.3

> OS: win32

> Arch: x64

**Comment by saenzramiro** [comment]
Fixed, thanks!

**Comment by SimJoSt** [comment]
Sure :-)
Keep calm and keep improving/coding.
