### ISSUE TITLE
Open from notification pop-up plays havoc with window size and position

### ISSUE THREAD

**Issue by ZaLiTHkA** [saenzramiro/rambox#755]
I discovered a really interesting issue the other day: Displaying the Rambox window from a message notification does weird things to the window size...

### Steps to reproduce

1. Wait for notification
2. Click notification

### Expected behavior

Clicking on a notification pop-up, I would expect the Rambox window to be restored to the state I last left it in (maximized on my left monitor).

### Actual behavior

What actually happens depends on the current state of the Rambox application window:

**If the window is hidden**, as in minimized to the system tray, then the notification click opens it in a minute size in the top left corner of the screen. I use a top-aligned taskbar, so this actually hides the window behind it.

**If the window is visible**, or even minimised to the taskbar, then the notification click will "restore" the app to a windowed state. I use mine maximized all the time, so this is a notable change each time.

It's pointless showing what the not-maximized window looks like, but here is a screenshot of the app window after the notification pop-up click has "restored" the window from a hidden state:

![2017-03-23 09_44_37-rambox](https://cloud.githubusercontent.com/assets/2149312/24240552/ba2ea53c-0fba-11e7-9d17-cb2515fd0c34.png)

Interestingly, if it opens as described above, then I hide the window (titlebar close button), then double click on the system tray icon, it comes back maximized as I had it previously.

### ENVIRONMENT

> Rambox: v0.5.3
> OS: Windows 10 Pro 64-bit
> Arch: x64

**Comment by saenzramiro** [comment]
Thank you for this issue. I was struggling trying to find the steps to reproduce it!

I will take a look for next release.
