### ISSUE TITLE
Windows95 dejavu with popup windows in Linux

### ISSUE THREAD

**Issue by soulchainer** [saenzramiro/rambox#758]
### Steps to reproduce

1. Make any action that will open a draggable popup. I made it clicking the «Add images» (to a tweet) in Tweetdeck and the «Send file» icon in Telegram.
2. Drag the window over the desktop.

### Expected behavior

This shouldn't be W95 Desktop Art. That should stay in 20th century ;).

### Actual behavior

Congrats: you just created a master piece of W95 Desktop Art.
![2017-03-24-192550_1920x1080_scrot](https://cloud.githubusercontent.com/assets/169524/24308963/4e953de8-10ca-11e7-9116-abd20f227f62.png) Run to sale it, quickly! You're going to be famous (and rich, obviously) :D.

### ENVIRONMENT

> Rambox: v0.5.3

> OS: Arch Linux
> WM: Qtile, just in case it could be relevant.

> Arch: x64

**Comment by saenzramiro** [comment]
Did you try by changing the Hardware Acceleration ON/OFF in your preferences?

**Comment by soulchainer** [comment]
No. But I just tried (I have the setting in «disable»), relaunched Rambox and it keeps happening, @saenzramiro.

**Comment by saenzramiro** [comment]
I'm sure it is an Electron bug, so we cannot do anything. So consider to report it in Electron's repository.
