### ISSUE TITLE
Exaggerated memory usage and red icon in system tray

### ISSUE THREAD

**Issue by eduengler** [saenzramiro/rambox#760]
Three issues:

1) Rambox is using a lot of memory.
As can be seen in the attached images.

2) There is a persistent message that the version of the chomirum is out of date.

3) I am no longer being warned by the reddish icon when I receive messages by whatsapp, messenger and twiter. Only gmail warns me with the red icon on the system tray.

![captura de tela em 2017-03-25 15-06-33](https://cloud.githubusercontent.com/assets/24523987/24325853/1dc8d17e-1170-11e7-9486-7558162cbc33.png)

![captura de tela em 2017-03-25 15-06-51](https://cloud.githubusercontent.com/assets/24523987/24325854/2984cfcc-1170-11e7-85b4-34b5c185b61d.png)

-
> Rambox 0.5.3
> Electron 1.4.15
> linux x64 4.4.0-62-generic

**Comment by saenzramiro** [comment]
Related with #512.

Other two issues are already reported. Please search.
