### ISSUE TITLE
Wire message: This browser is not supported.

### ISSUE THREAD

**Issue by alekospantazis** [saenzramiro/rambox#763]
-
> Rambox 0.5.3
> Electron 1.4.15
> linux x64 4.4.0-70-generic

**Comment by fungs** [comment]
I can confirm this, I tried to use Wire just now.

**Comment by FallenKN** [comment]
#762 duplicate

**Comment by peterwilli** [comment]
I have the same. Should be ok to make some kind of user-agent header, then we're ok

**Comment by fungs** [comment]
is there a way to fake the user agent string by injecting some javascript code in the advanced setting (e.g. http://stackoverflow.com/questions/1307013/mocking-a-useragent-in-javascript)?

**Comment by saenzramiro** [comment]
Dublicate #762
