### ISSUE TITLE
Rambox instantly exits with status 0

### ISSUE THREAD

**Issue by NotAFile** [saenzramiro/rambox#765]
### Steps to reproduce

1. Install Rambox a month ago
2. ???
3. Try to start rambox

### Expected behavior

Rambox starts up normally, like always

### Actual behavior

Nothing happens, the command instantly exits.

```
(gdb) r
Starting program: /usr/local/bin/rambox 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[New Thread 0x7fffe8db0700 (LWP 21654)]
[New Thread 0x7fffe7aa7700 (LWP 21657)]
[New Thread 0x7fffe72a6700 (LWP 21658)]
[New Thread 0x7fffe6aa5700 (LWP 21659)]
[New Thread 0x7fffe62a4700 (LWP 21660)]
[New Thread 0x7fffe5aa3700 (LWP 21661)]
[New Thread 0x7fffe52a2700 (LWP 21662)]
[New Thread 0x7fffe4aa1700 (LWP 21663)]
[Thread 0x7fffe4aa1700 (LWP 21663) exited]
[Thread 0x7fffe52a2700 (LWP 21662) exited]
[Thread 0x7fffe5aa3700 (LWP 21661) exited]
[Thread 0x7fffe62a4700 (LWP 21660) exited]
[Thread 0x7fffe6aa5700 (LWP 21659) exited]
[Thread 0x7fffe72a6700 (LWP 21658) exited]
[Thread 0x7fffe7aa7700 (LWP 21657) exited]
[Thread 0x7fffe8db0700 (LWP 21654) exited]
[Inferior 1 (process 21650) exited normally]
```

### ENVIRONMENT

> Rambox: v0.5.3

> OS: Debian Sid

> Arch: x64

**Comment by NotAFile** [comment]
Any info or help debugging this? I can't use rambox because if this currently.

**Comment by NotAFile** [comment]
This has magically fixed itself for now, but I'll leave this open in case this happens again to somebody else. Seems to be a very rare bug.

**Comment by saenzramiro** [comment]
Very weird. :confused:

I'm glad it has fixed. Let's close it and if someone have the same problem, we will reopen it.
