### ISSUE TITLE
fleep does not authenticate using Google

### ISSUE THREAD

**Issue by edmundlaugasson** [saenzramiro/rambox#767]
### Steps to reproduce

1. start Fleep authentication using Google account
2. browser starts with URL` https://fleep.io/authenticate/google/callback?state=<hash>&code=<hash>&authuser=0&session_state=<hash>&prompt=none#` ... where <hash> was exact stream of letters and numbers...
3. website will display "Loading..." and so it remains - no authentication will happen

### Expected behavior
authenticated session

### Actual behavior
empty website displaying "Loading..."

### Workaround
Reset Fleep password in web and then log in using password. Then it worked.

### ENVIRONMENT

> Rambox: v0.5.3

> OS: Linux Mint 18.1 MATE

> Arch: x64

**Comment by saenzramiro** [comment]
Related with #428
