### ISSUE TITLE
more than 25 accounts not listed in front page

### ISSUE THREAD

**Issue by edmundlaugasson** [saenzramiro/rambox#769]
### Steps to reproduce

1. add more than 25 accounts
2. rest of accounts will not be listed in front page (dashboard)
3. it would be a bit challenging to handle more than 25 accounts

### Expected behavior
All added accounts are listed and grouped intelligently, e.g. multiple lists with numbers below, etc

### Actual behavior
More than 25 accounts were not listed.

### ENVIRONMENT
> Rambox: v0.5.3
> OS: Linux Mint 18.1 MATE
> Arch: x64

**Comment by saenzramiro** [comment]
Duplicate #768.
