### ISSUE TITLE
protonmail logged out on start

### ISSUE THREAD

**Issue by edmundlaugasson** [saenzramiro/rambox#771]
### Steps to reproduce

1. log in protonmail
2. close or reload Rambox
3. protonmail is logged out again

### Expected behavior
Protonmail remains logged in regardless Rambox reload or reopen

### Actual behavior
Protonmail is logged out.

### ENVIRONMENT
> Rambox: v0.5.3
> OS: Linux Mint 18.1 MATE
> Arch: x64

**Comment by simoniz0r** [comment]
Can confirm; same version of Rambox on KDE neon User Edition 5.9 x86_64 with the same issue.

**Comment by saenzramiro** [comment]
This is how Protonmail natively works. If you open it in your default browser, it will not keep sessions anyway.
