### ISSUE TITLE
occasionally cannot add account

### ISSUE THREAD

**Issue by edmundlaugasson** [saenzramiro/rambox#776]
### Steps to reproduce

1. click on any icon to add account
2. clicking on "Add ..." button just does not work
3. occasionally cannot add account

### Workaround
Refresh all app and then it would be possible again. Unfortunately some services will be then logged out.

### Expected behavior
Adding would be possible in all cases.

### Actual behavior
occasionally cannot add account

### ENVIRONMENT
> Rambox: v0.5.3
> OS: Linux Mint 18.1 MATE
> Arch: x64

**Comment by saenzramiro** [comment]
Seems like there is something that is causing a lot of issues in your Rambox. Try by starting over/reseting by going to Help menu and selecting both options there.

**Comment by edmundlaugasson** [comment]
It would be quite overwhelming to reset app and reconfigure all accounts. Quick export-import accounts would be appreciated.

**Comment by saenzramiro** [comment]
Seems like Rambox has an internal problem and cause all the problems you had.

Please go to Help menu, then Tools and Select each option in there. Then you will need to add each service again. Once you have all working, you can create a Rambox account to synchronize/save all your configuration.

**Comment by edmundlaugasson** [comment]
In Help->Tools there are two choices:
* Clear cache
* Clear local storage
Could not understand `Please go to Help menu, then Tools and Select each option in there.` Which option to check and when?

**Comment by olivierlefloch** [comment]
@edmundlaugasson you should select the first option, then the second option, then relaunch Rambox.
