### ISSUE TITLE
feature request: Viber

### ISSUE THREAD

**Issue by edmundlaugasson** [saenzramiro/rambox#778]
### Steps to reproduce

1. try to log in using Viber account
2. cannot find the Viber account
3. cannot log in

More information at https://www.viber.com/en/

### Expected behavior
Viber account option found

### Actual behavior
Viber account option NOT found

### ENVIRONMENT
> Rambox: v0.5.3
> OS: Linux Mint 18.1 MATE
> Arch: x64

**Comment by pztrn** [comment]
There is no web client for Viber, so it will not be possible to add it to Rambox.
