### ISSUE TITLE
feature request: Ricochet

### ISSUE THREAD

**Issue by edmundlaugasson** [saenzramiro/rambox#779]
### Steps to reproduce

1. try to log in with Ricochet account
2. cannot find it
3. cannot log in

More information - https://ricochet.im/

### Expected behavior
Ricochet account found

### Actual behavior
Ricochet account NOT found

### ENVIRONMENT
> Rambox: v0.5.3
> OS: Linux Mint 18.1 MATE
> Arch: x64

**Comment by pztrn** [comment]
There is no web client for Ricochet, so it will not be possible to add it to Rambox.
