### ISSUE TITLE
Save credentials for HipChat

### ISSUE THREAD

**Issue by stedekay** [saenzramiro/rambox#78]
When using HipChat with Rambox, I'll have to login every single time with my credentials (even when enabling the checkbox for saving credentials). Is it possible to save these settings?

**Comment by saenzramiro** [comment]
Thank you for the report. I will take a look, but saving your credentials is not the idea of Rambox (privacy first), but I can try to save the session so it will prevent login in every time.

**Comment by postadelmaga** [comment]
I think you should re open this bug.
- the login cookie is not stored, even selecting 'keep me login' is not working. ( as for above report )

**Comment by saenzramiro** [comment]
This will be fixed in v0.4.1.

**Comment by stedekay** [comment]
Thanks for your good work!
