### ISSUE TITLE
feature request: Retroshare

### ISSUE THREAD

**Issue by edmundlaugasson** [saenzramiro/rambox#780]
### Steps to reproduce

1. try to log in using Retroshare account
2. Retroshare option not found
3. Retroshare option cannot be used

More information at http://retroshare.net/

### Expected behavior
Retroshare option found.

### Actual behavior
Retroshare option NOT found

### ENVIRONMENT
> Rambox: v0.5.3
> OS: Linux Mint 18.1
> Arch: x64

**Comment by pztrn** [comment]
There is no web client for Retroshare that works with chat (yet), so it will not be possible to add it to Rambox.

**Comment by demolitionb** [comment]
Is there any plan to include custom code for apps, messengers which doesn't provide a web interface? Open source js code could be included right?

**Comment by saenzramiro** [comment]
Not for now.
