### ISSUE TITLE
feature request: Ring

### ISSUE THREAD

**Issue by edmundlaugasson** [saenzramiro/rambox#781]
### Steps to reproduce

1. try to log in using Ring account
2. Ring account not found
3. cannot use Ring account to log in

More information at https://ring.cx/en

### Expected behavior
Ring account found.

### Actual behavior
Ring account NOT found

### ENVIRONMENT
> Rambox: v0.5.3
> OS: Linux Mint 18.1
> Arch: x64

**Comment by pztrn** [comment]
There is no web client for Ring, so it will not be possible to add it to Rambox.
