### ISSUE TITLE
feature request: Tox Chat

### ISSUE THREAD

**Issue by edmundlaugasson** [saenzramiro/rambox#782]
### Steps to reproduce

1. try to log in using Tox Chat
2. Tox Chat not found
3. cannot use Tox Chat

### Expected behavior
Tox Chat found can be used.

### Actual behavior
Tox Chat found can NOT be used.

### ENVIRONMENT
> Rambox: v0.5.3
> OS: Linux Mint 18.1 MATE
> Arch: x64

**Comment by pztrn** [comment]
There is no web client for Tox, so it will not be possible to add it to Rambox.

**Comment by Blaiserman** [comment]
https://github.com/codedust/WebTox

**Comment by nmat** [comment]
@Blaiserman that seems to be a client ran on desktop side....don't think that is what @pztrn means. There is no _hosted_ webservice for it
