### ISSUE TITLE
Open and close Rambox with left click on the tray icon

### ISSUE THREAD

**Issue by pennybuster** [saenzramiro/rambox#783]
### Expected behavior

Open and close Rambox with left click on the tray icon. For reference, check WMail

### Actual behavior

"Close" button and "Show/Hide Window" option are the only way to do it now

### ENVIRONMENT

> Rambox 0.5.3
> Electron 1.4.15
> linux x64 4.4.0-70-generic
> Linux Mint 18.1 "Serena" - Cinnamon (64-bit)

Thanks a lot!

**Comment by saenzramiro** [comment]
Duplicate #748.
