### ISSUE TITLE
Double click system icon need improvement

### ISSUE THREAD

**Issue by wasimxe** [saenzramiro/rambox#786]
let says rambox is not minimized to systray but open on taskbar and I am currently have working in browser (means rambox is not focused currently), Now if I double click system tray icon of rambox, it should bring rambox in front on top of all other opened windows. 

It will be more friendly because everytime I used rambox I click close (corner click even without see) to minimize it to systray, now everytime I have to double click to bring rambox on top even its on taskbar (unconsciously I mean) but not on top of other windows.

I hope I explained well, that's really a bid headache when you are working with multiple clients on rambox/browser togather. 

-
> Rambox 0.5.3
> Electron 1.4.15
> win32 x64 10.0.14393

**Comment by nmat** [comment]
if you want you can test: https://github.com/saenzramiro/rambox/pull/728 and give feedback

**Comment by saenzramiro** [comment]
I will take a look #728. Thanks.

**Comment by justpusher** [comment]
Doubleclick doesn't work for me in Rambox 0.5.9 under XFCE. It just does nothing. 
Single click also does nothing.

**Comment by mxmehl** [comment]
> Doubleclick doesn't work for me in Rambox 0.5.9 under XFCE. It just does nothing. Single click also does nothing.

I can confirm that. You have to right-click on the tray icon to unhide it again.

Is there any issue we can attach this bug to, or should we open a new one?
