### ISSUE TITLE
v0.5.7?

### ISSUE THREAD

**Issue by ruiumbelino** [saenzramiro/rambox#787]
At Changelog page, we have the version 0.5.7, that could solve some current issues, like connect to Wire, but we can't download it...

Can you make it available?

Thanks

**Comment by MrChick** [comment]
0.5.7 was pulled due to some OSX problems - I have it installed on windows and it does NOT fix wire

**Comment by ruiumbelino** [comment]
I thought that having a new version of chromium could solve it...
