### ISSUE TITLE
Facebook Messenger Videochate

### ISSUE THREAD

**Issue by FrJCMaximilian** [saenzramiro/rambox#788]
I just started using Rambox and really like it.  I did try to start a video chat with someone on Messenger (Facebook) and nothing happened.  When they tried to initiate the video chat I received a message asking if I wanted to join, and clicked "Yes" but nothing happened.  Actually we were disconnected.  This is not a deal breaker for me, but I would like to be able to use video with Facebook Messenger.  I have been able to use Google Hangouts video chat via Rambox.  I have not tried Skype yet.

-
> Rambox 0.5.3
> Electron 1.4.15
> linux x64 4.4.0-67-generic

**Comment by saenzramiro** [comment]
Duplicate #678.
