### ISSUE TITLE
Whatsapp video has no sound

### ISSUE THREAD

**Issue by andrecavalcanti** [saenzramiro/rambox#789]
-
> Rambox 0.5.3
> Electron 1.4.15
> win32 x64 6.3.9600

**Comment by emanuelpoletto** [comment]
There's no sound for me at all, whatever the application is: WhatsApp, Messenger, Gmail, etc.

I'm using Rambox on macOS Sierra 10.12.4

- Version: 0.5.3
- Platform: darwin (x64)
- Electron: 1.4.15
- Chromium: 53.0.2785.143
- Node: 6.5.0

**Comment by saenzramiro** [comment]
Did you check if "Don't Disturb" mode is OFF and "Mute all sounds" is unchecked?

**Comment by andrecavalcanti** [comment]
"Don't Disturb" mode is ON.


Thanks very much for your help

________________________________

**Comment by SimJoSt** [comment]
As this mistake is made by people all of the time (and probably only a fraction of them are surfacing here) a better way of constantly reminding the user, that DNT mode is on should be implemented.
Probably as a modification to the logo in tray and app.

**Comment by saenzramiro** [comment]
Yes, I will think about it and try to implement it in a future release.
