### ISSUE TITLE
Notifications are not persistent

### ISSUE THREAD

**Issue by pkajaba** [saenzramiro/rambox#793]
### Steps to reproduce

1. Login to any service
2. Receive notification
3. Notification is lost after few seconds

### Expected behavior

It should be persistent in notification centre
### Actual behavior
It's lost

### ENVIRONMENT
Gnome 3.22, Fedora 25

> Rambox: v0.5.3

> OS: Fedora 25

> Arch: x64

**Comment by saenzramiro** [comment]
Duplicate #479
