### ISSUE TITLE
Endless Startup Animation on build from Master on Ubuntu 16.04

### ISSUE THREAD

**Issue by HarlemSquirrel** [saenzramiro/rambox#794]
### Steps to reproduce

1. Build from current master branch on Ubuntu GNOME 16.04 with `npm run build:linux64`
2. Install using dpkg `sudo dpkg -i dist/Rambox_0.5.3_amd64.deb`
3. Open Rambox to see endless startup animation

### Expected behavior

Startup animation runs for a few seconds and disappears. This works fine with the last stable release 0.5.3

### Actual behavior

Startup animation continues forever on top of functioning app. The rest of the app seems to function normally but the endless animation on top makes it very difficult to use. 

### ENVIRONMENT

System76 Kudu
Intel® Core™ i7-6700HQ CPU
Intel® HD Graphics 530
16GB RAM

> Rambox: Master branch as of April 3, 2017

> OS: Ubuntu GNOME 16.04 64-bit

> Arch: x64

**Comment by saenzramiro** [comment]
Did you follow [THIS](https://github.com/saenzramiro/rambox#compile-on-ubuntu) steps?

**Comment by HarlemSquirrel** [comment]
That does seem to work but I'd like to build the deb package. `npm run sencha:compile:build` from the [depolyment wiki page](https://github.com/saenzramiro/rambox/wiki/DEPLOYMENT) gives errors.

**Comment by saenzramiro** [comment]
Because that Wiki is for me when I release a new version, that's why it said *PRIVATE* at the top.

Do `npm run sencha:compile` instead.
