### ISSUE TITLE
Tencent QQ

### ISSUE THREAD

**Issue by baimafeima** [saenzramiro/rambox#796]
Does Rambox currently support QQ?

**Comment by saenzramiro** [comment]
Natively no, but you can add it using [Custom Service](https://github.com/saenzramiro/rambox/wiki/Add-a-Custom-Service) option.

**Comment by baimafeima** [comment]
Do you have any plans to add support for it in your list of protocols?

**Comment by saenzramiro** [comment]
Yes, follow #12
