### ISSUE TITLE
macOS Sierra 10.12 Beta (16A201w)

### ISSUE THREAD

**Issue by marcelocecin** [saenzramiro/rambox#8]
Hi there

The app does not work at macOS Sierra 10.12 Beta (16A201w)

It need it to be signed

Thank you

**Comment by saenzramiro** [comment]
As I know... Sierra is still in beta. But can you share a screenshot of the message?

**Comment by marcelocecin** [comment]
the difference is that macOS Gatekeeper does not have the option: allow applications downloaded from anywhere
workaround: -s -f codesign "Developer Application ID: Your Name" --entitlements Rambox.entitlements "Rambox.app" --deep
where Rambox.entitlements:
![captura de tela 2016-06-30 as 16 32 19](https://cloud.githubusercontent.com/assets/2955762/16501571/610100c8-3ee0-11e6-91c1-090dd00422c5.png)
now the app is opening but is not showing anything:
![captura de tela 2016-06-30 as 16 36 23](https://cloud.githubusercontent.com/assets/2955762/16501643/d130dfe4-3ee0-11e6-9537-0c19d403c18e.png)

**Comment by saenzramiro** [comment]
I think you need to sign it using "electron-builder" (https://github.com/electron-userland/electron-builder/wiki/Code-Signing) to generate a new Rambox.app and .dmg file.

**Comment by marcelocecin** [comment]
https://github.com/electron-userland/electron-osx-sign/wiki/3.-App-Sandbox-and-Entitlements
