### ISSUE TITLE
"Help -> About Rambox" not working

### ISSUE THREAD

**Issue by GoodSoulGermany** [saenzramiro/rambox#80]
Topic says it all.

-
> Rambox 0.3.0
> Electron 1.2.5
> win32 x64 10.0.10586

**Comment by nahtnam** [comment]
Can confirm on Rambox 0.3.0 on Ubuntu 16.04.

**Comment by JohaWeber** [comment]
Same here.

> OS: WIN 10 x64

**Comment by saenzramiro** [comment]
Thanks guys! But is duplicated. #33
