### ISSUE TITLE
Tipografía

### ISSUE THREAD

**Issue by arqnogues** [saenzramiro/rambox#801]
No sé por que razón se cambió la tipografía de mi Rambox antes era similar a Arial y ahora es similar a Avant Garde y me cuesta leer y escribir porque es muy fino el tipo de letra. Como volver a la configuración anterior? Gracias
Saludos desde Montevideo, Uruguay

-
> Rambox 0.5.3
> Electron 1.4.15
> win32 x64 10.0.14393

**Comment by saenzramiro** [comment]
La tipografía sigue siendo la misma de siempre. Creo que es un problema en tu ordenador.
