### ISSUE TITLE
Feature Request: Ability to script against app using Apple Script

### ISSUE THREAD

**Issue by mikeatdesk** [saenzramiro/rambox#802]
MacOS doesn't recognize Rambox as an app to target with AppleScript.

Would love to see that happen so I can script common things against the app using AppleScript.

**Comment by saenzramiro** [comment]
And what are the benefits of doing this?

**Comment by saenzramiro** [comment]
I'm not familiar with AppleScript.

**Comment by mikeatdesk** [comment]
Looks like this already works with AppleScript as of the last update (presumably unintentionally).

**Comment by saenzramiro** [comment]
Sweet! Can you share your idea for Rambox using AppleScript?

**Comment by mikeatdesk** [comment]
I run an Alfred workflow to automatically set my status in a handful of Slack communities I'm in at the end of the day.

So I tell Alfred "I'm gone" and it parses through my windows, inputting keyboard commands, one at a time, until it's done.

Then it pauses iTunes/Radium, mutes my computer, and turns off my screens.

**Comment by saenzramiro** [comment]
Holy sh**!

**Comment by crimsonsunset** [comment]
hey @mikeatdesk -- I'm looking to do something similar with alfred. I'd like to build a workflow that allows me to run something like `ram hangouts` to switch between rambox tabs. I'm a bit new to tying into native apps, so forgive my naiveté. Does this sound like something that would be possible? How would I find out the different parameters that rambox could take from applescript's CLI? Also, @saenzramiro any insight you have would be appreciated =) 

Love the product, btw! Keep up the good work!

**Comment by saenzramiro** [comment]
We don't have a CLI to interact with Rambox app and I don't think there is a way to do what you want to do. 😞

**Comment by crimsonsunset** [comment]
I think I've figured out a way to get it working... not the most elegant but it should fit my needs. gunna work on it a bit. I'll update here when I have something to show.

**Comment by crimsonsunset** [comment]
got it, @saenzramiro  -- https://github.com/crimsonsunset/alfred-rambox-switcher ![bitmoji](https://render.bitstrips.com/v2/cpanel/10212371-281193012_2-s1-v1.png?transparent=1&palette=1&width=246)
