### ISSUE TITLE
Icon in Dock on Mac shows 1 unread message while all messages are read

### ISSUE THREAD

**Issue by relgames** [saenzramiro/rambox#805]
### Steps to reproduce

1. I have WhatsApp, Telegram, Skype, Ryver, Gitter, HipChat
2. When there is a new message in WhatsApp, icon counter changes to 1, also, a counter in WhatsApp tab is changed to 1.
3. I read all messages, tab counter disappears, but icon counter still shows 1.

### Expected behavior

When I read all messages, icon counter should disappear.

### Actual behavior

Unread counter in Dock icon on Mac stays until I turn WhatsApp off and on.

### ENVIRONMENT

> Rambox: v0.5.3

> OS: Mac OS Sierra 10.12.4 (16E195)

> Arch: x64

![screen shot 2017-04-14 at 14 18 03](https://cloud.githubusercontent.com/assets/179605/25043178/49d42e22-211e-11e7-9dc1-41c1d029b293.png)
<img width="1179" alt="screen shot 2017-04-14 at 14 17 57" src="https://cloud.githubusercontent.com/assets/179605/25043181/4b53dff4-211e-11e7-853c-b33becfe8fc4.png">

**Comment by saenzramiro** [comment]
Can you confirm if this still happens to you?

Did you remove a service before? Because we know there is a bug when you have a service with unread messages and if you remove it, the counter remains in the dock.

**Comment by relgames** [comment]
It has not happened again so far.

I did not remove WhatsUp service before the bug. I removed it when I saw the bug and unread counter disappeared. 

I think it happened with WhatsApp group, not 1-to-1 chat.

**Comment by pozgo** [comment]
It's happening to me but a bit more than one message on the icon ;) 105 actually. Seems like it's not refreshing itself.
