### ISSUE TITLE
Pushbullet connection issue

### ISSUE THREAD

**Issue by astorlandi** [saenzramiro/rambox#807]
Hello.
I can't connect with Pushbullet using my account on Rambox.
Thanks.
Astor.

-
> Rambox 0.5.3
> Electron 1.4.15
> win32 x64 6.1.7601

**Comment by nmat** [comment]
This is known issue. Please see:

https://github.com/saenzramiro/rambox/issues/185

**Comment by saenzramiro** [comment]
Thanks @nmat.

It will be fixed in next release.
