### ISSUE TITLE
Wire support 

### ISSUE THREAD

**Issue by ColinLeverger** [saenzramiro/rambox#808]
Wire support seems to be broken - the built-in browser is apparently too old.

### Steps to reproduce

1. Activate Wire in Rambox app
2. Click on tab "Wire"...

### Expected behaviour

"This browser is not supported.

Download the latest version of Google Chrome, Mozilla Firefox, Opera or MS Edge. Wire for macOS and Microsoft Windows are available from get.wire.com."

### ENVIRONMENT

_OS_: macOS Sierra 10.12.3

_Computer_: MacBook Pro mid-2015

_Rambox_:
- Version: 0.5.3
- Platform: darwin (x64)
- Electron: 1.4.15
- Chromium: 53.0.2785.143
- Node: 6.5.0

**Comment by saenzramiro** [comment]
Duplicate #762
