### ISSUE TITLE
NaN on notification badge in slack

### ISSUE THREAD

**Issue by taniadaniela** [saenzramiro/rambox#810]
MacOS Sierra 10.12.4
Rambox Version: 0.5.3
Platform: darwin (x64)
Electron: 1.4.15
Chromium: 53.0.2785.143
Node: 6.5.0
![screen shot 2017-04-17 at 1 13 16 pm](https://cloud.githubusercontent.com/assets/5315791/25096863/14f8fc56-2370-11e7-9261-141e4841fd7a.jpg)

**Comment by saenzramiro** [comment]
This will be fixed in next release. Thanks.
