### ISSUE TITLE
Popup windows replaced by Modal windows is Blanking the rest of the app

### ISSUE THREAD

**Issue by NNois** [saenzramiro/rambox#816]
1. Open Slack
2. Make a call/visio
3. The call/visio window opens in a modal window of the slack tab, blanking the rest of the app !!!

On the Chrome Web browser or with the "Franz App" the call window opens in a separate window, leaving full access to the slack tab.

Displaying Popup windows in app and blanking the rest isn't good at all ;-)

**Comment by saenzramiro** [comment]
Let's merge this with #682.

It will be fixed in next release.
