### ISSUE TITLE
Sign into mySMS at every restart

### ISSUE THREAD

**Issue by cencio52** [saenzramiro/rambox#819]
### Steps to reproduce

1. Start Rambox

### Expected behavior

Automatically login/sign in to all services

### Actual behavior

Login to all, but mySMS that requires to sign in each time I restart Rambox

### ENVIRONMENT

> Rambox: v0.5.3

> OS: MAC OS Sierra

> Arch: x64

**Comment by saenzramiro** [comment]
Sorry but I can't test mysms because I can't register my phone number because I never receive the code.

Do you still have this problem?

**Comment by saenzramiro** [comment]
Let's merge this ticket with #629.

**Comment by LaurentBerder** [comment]
I also have this issue, and it is not fixed yet:

> Version: 0.5.12
Platform: win32 (x64)
Electron: 1.7.5
Chromium: 58.0.3029.110
Node: 7.9.0

I need to log in to mysms at each startup, or reload of the mysms tab

**Comment by LaurentBerder** [comment]
The way I fixed it was by removing Mysms service completely, then add a "`_Custom Service`" with `https://app.mysms.com/` as URL.
This even allowed me to login with google account (which was not possible with regular service), and to remain logged in.
