### ISSUE TITLE
Very low volume

### ISSUE THREAD

**Issue by forteller** [saenzramiro/rambox#820]
The volume on anything (video or Spotify embed is what I've seen) in at least TweetDeck and Slack is so low that I can barely hear anything. "Don't disturb" is off, and so is "Mute all sounds"

### ENVIRONMENT

Version: 0.5.3
Platform: linux (x64) (Ubuntu Gnome 16.10)
Electron: 1.4.15
Chromium: 53.0.2785.143
Node: 6.5.0

**Comment by saenzramiro** [comment]
Did you check the Volume Mixer settings? I don't know where it is in Ubuntu, but in Windows 10 is like:

![image](https://cloud.githubusercontent.com/assets/2694669/25400033/b73dcba6-29c7-11e7-8b31-d9a3d4dccd00.png)

**Comment by forteller** [comment]
OMG, that was it! I must've lowered it once and then forgotten about it. Feeling stupid now. Thank you! :)
