### ISSUE TITLE
New feature: themes

### ISSUE THREAD

**Issue by Izin** [saenzramiro/rambox#822]
Hello @saenzramiro ,

Is it possible to develop a dark theme for Rambox?

I'm using the dark theme on MacOS, and Stylish in Chrome in order to use darker websites.

But I can't do anything on Rambox like this. For example you could add an option in the start page "Use dark theme".

Do you want me to design the Dark theme and show you a screenshot with color codes below?

Thanks buddy, I'll bounty you if you do it :+1:

**Comment by saenzramiro** [comment]
Themes will be available in version 1.0, see www.rambox.pro/100

Any bounty will be appreciated.

**Comment by Izin** [comment]
Wow. Ok, 3 things:

 - I like the new landing page for v1.0 and the fact that you can chose between dark/light theme
 - I like the new dark theme for Rambox 1.0
 - I dislike the new Rambox's interface (where features are displayed, the big horizontal blue bar) :S...

I do want to bounty you for Rambox, but the visual way you are pushing it is not shared. For me, appearance is as more important as the core. I'm sure it's similar to you, but I like when interface is clean. We have to forgot that we use Rambox (in my opinion) in order to think "wow, such application! Simple, clean, beautifull!".

So, will it be possible to hide the left sidebar and the blue header bar? In order to have a clear interface that allows us to concentrate on your tasks, in fullscreen or in normal mode.

Thanks in advance for your consideration @saenzramiro
