### ISSUE TITLE
Mac app is not signed

### ISSUE THREAD

**Issue by danez** [saenzramiro/rambox#823]
### Steps to reproduce

1. Open Rambox.app on macOS the first time
2. 

### Expected behavior

Opens without warning

### Actual behavior

By default does not open and shows warning: "RamBox can´t be opened because the identity of developer cannot be verified"

### ENVIRONMENT

> Rambox: v0.5.3
> OS: macOS 10.12.4

It would be nice if rambox would be signed correctly for mac. If you do not have a mac to test I'm willing to test or help with this. Let me know
https://developer.apple.com/library/content/documentation/IDEs/Conceptual/AppDistributionGuide/DistributingApplicationsOutside/DistributingApplicationsOutside.html

**Comment by saenzramiro** [comment]
Thank you @danez, we are planning to sign the app for Windows and Mac in version 1.0.0.

**Comment by deyhle** [comment]
When will 1.0.0 be released then? It's really bad behavior to ship unsigned software on Mac. Apart from it being a security issue, which is quite relevant for an app with such sensitive date, it's also a really "low hanging fruit". I simply cannot see any reason not to sign the app.

**Comment by AndreBaumeier** [comment]
really stops us from using this. any plans on signing it / releasing a 1.0.0 signed version?
