### ISSUE TITLE
If minimized to tray, taskbar button doesn't open the app window (Windows 10)

### ISSUE THREAD

**Issue by dariuskolba** [saenzramiro/rambox#825]
I have Rambox pinned to taskbar in windows, But when i close it to tray, or run it minimized on startup, the taskbar button doesn't open the app. Have to open it from tray.

### Steps to reproduce

1.  Rambox pinned to taskbar in Windows.
2.  Run minimized on startup or close it to tray during use.

### Expected behavior

 Clicking the taskbar button should open the application window.

### Actual behavior

 Clicking the taskbar button does nothing. Have to open the app from the tray. 

 (I use the "keep in tray and taskbar" option during use, but the issue still effects startup)

### ENVIRONMENT

 Version: 0.5.3
 Platform: win32 (x64)
 Electron: 1.4.15 
 Chromium: 53.0.2785.143
 Node: 6.5.0

 Windows 10 (1703) x64

**Comment by nmat** [comment]
You could test what is commited in git:

https://github.com/saenzramiro/rambox/commit/6f049fa3077edce0a659de617f4336da43ca722a

**Comment by saenzramiro** [comment]
This problem is because clicking the taskbar button try to open a new Rambox, but we configure it to only have one opened (single instance). We can improve this to also activate the current instance.

**Comment by SimJoSt** [comment]
I would be very much in favor of that. Multiple instances don't work for me (through clicking the taskbar button) and should not be a common use case. All buttons with Rambox' icon on it should open it.
If it does nothing, it seems broken.
