### ISSUE TITLE
http content not displayed in https service (Windows)

### ISSUE THREAD

**Issue by Bebef** [saenzramiro/rambox#826]
### Steps to reproduce
Tested on Windows 10 Pro Version 1607 Build 14393.576
1. set up a Rocket Chat service provided via a https url
2. in a chat, post an image url with http://
3. for comparison, post an image url with https://

### Expected behavior
Both pictures should be displayed.

### Actual behavior
If the service is provided via https, only https images will be displayed.

### ENVIRONMENT
* Rambox: v0.5.3
* OS: Windows 10 Pro Version 1607 Build 14393.576
* Arch: x64

**Comment by Bebef** [comment]
I reckon this is an issue with Windows, not with Rambox itself, as I experience the very same issue in Franz. However, I tried to fiddle with internet options in Windows, allowing mixed content, but that didn't help 😦

**Comment by Bebef** [comment]
```
3ddab15….js?meteor_js_resource=true:238 Mixed Content: The page at 'https://chat.xxx.xx/channel/xxxx' was loaded over HTTPS, but requested an insecure image 'http://xxxxxxx.com/wp-content/uploads/2015/04/xxxxx.gif'. This request has been blocked; the content must be served over HTTPS.(anonymous function) @ 3ddab15….js?meteor_js_resource=true:238
3cgm.gss.cid:1 Mixed Content: The page at 'https://chat.xxx.xx/channel/xxxx' was loaded over HTTPS, but requested an insecure image 'http://xxxxxxx.com/wp-content/uploads/2015/04/xxxxx.gif'. This request has been blocked; the content must be served over HTTPS.
```

**Comment by Bebef** [comment]
Please see:
https://github.com/electron/electron/issues/971
https://github.com/electron/electron/issues/2076

**Comment by Bebef** [comment]
Just found #202 and #611

**Comment by saenzramiro** [comment]
Seems like we can fix this by adding `allowRunningInsecureContent` option in WebView config.

**Comment by MrChick** [comment]
@saenzramiro this was actually fixed with 0.5.7 and has been working ever since, also with 0.5.9

**Comment by saenzramiro** [comment]
@MrChick And not in v0.5.10? Seems like it's an Electron bug. :/

**Comment by MrChick** [comment]
I'm fairly certain I'm on 0.5.10 at work and it's still working. Wrote that comment before 0.5.10 was out and 0.5.9 was the current version ;)

**Comment by MrChick** [comment]
Just checked, I'm on:

Version: 0.5.10
Platform: win32 (x64)
Electron: 1.7.4
Chromium: 58.0.3029.110
Node: 7.9.0

Working perfectly.

**Comment by saenzramiro** [comment]
Ok, so let's close this one.
