### ISSUE TITLE
Telegram unread messages do not affect MacOS Dock unread counter

### ISSUE THREAD

**Issue by relgames** [saenzramiro/rambox#827]
### Steps to reproduce

1. Add Telegram
2. Receive message in Telegram

### Expected behavior

Dock icon should show unread message counter

### Actual behavior

Dock icon does not change

### ENVIRONMENT

> Rambox: v 0.5.3

> OS: MacOS Sierra 10.12.4 (16E195)

> Arch: x64 

<img width="504" alt="screen shot 2017-04-26 at 11 34 43" src="https://cloud.githubusercontent.com/assets/179605/25427919/60149cb2-2a74-11e7-8c86-38a957f82d03.png">
<img width="155" alt="screen shot 2017-04-26 at 11 31 40" src="https://cloud.githubusercontent.com/assets/179605/25427924/626975e6-2a74-11e7-9080-9dedfb5e128b.png">

![screen shot 2017-04-26 at 11 31 43](https://cloud.githubusercontent.com/assets/179605/25427926/637a8614-2a74-11e7-952a-83ab11e16152.png)

**Comment by saenzramiro** [comment]
I just tested and works as expected. Please check if you have the "Show System Tray indicator on unread messages" option checked in the Preferences of Rambox.
