### ISSUE TITLE
No dialog in Sandstorm (and probably elsewhere)

### ISSUE THREAD

**Issue by ntnsndr** [saenzramiro/rambox#831]
In general I find that Rambox and Sandstorm (oasis.sandstorm.io) work really well together. But one major problem is that Sandstorm relies on a pop-up dialog to name a "grain" (any kind of file). This requires me to repeatedly exit Sandstorm. Is there a way to add dialog capability to Rambox?

I love this tool, thank you so much all of you for your work.

### Steps to reproduce

1. Use Sandstorm in Rambox
2. Click on the name of the "grain" to change it
3. No dialog comes up

### Expected behavior

A dialog would come up enabling the user to change the name of the "grain"

### Actual behavior

Nothing happens on click.

### ENVIRONMENT

> Rambox: v0.5.3

> OS: Ubuntu GNOME 17.04

> Arch: ia32

**Comment by saenzramiro** [comment]
We will take a look on this for next release.

**Comment by saenzramiro** [comment]
Sandstorm use `prompt` to input the name of the Grain, but Electron doesn't support prompts. Check: https://github.com/electron/electron/issues/472

For now you will have to use default browser to name it until Sandstorm change the way the user named the Grain or Electron adds the support to `prompts`.

BTW, we will add Sandstorm natively for next release. ;)
