### ISSUE TITLE
Opening Yahoo mail shows prompt to upgrade browser

### ISSUE THREAD

**Issue by aravindhp** [saenzramiro/rambox#833]
### Steps to reproduce

1. Click Yahoo mail reload button
2. 
3. 

### Expected behavior

Show the new Yahoo mail interface
### Actual behavior
Shows browser upgrade prompt
![ramboxyahoo](https://cloud.githubusercontent.com/assets/11638995/25593724/ca7e0618-2e72-11e7-931e-cf3fe9d04397.png)
Clicking "Try Later" takes you to ancient Yahoo mail interface.

### ENVIRONMENT

> Rambox: v0.5.3
> OS: Ubuntu 16.04
> Arch: x64
> Electron: 1.4.15
> Chromium: 53.0.2785.143
> Node: 6.5.0

**Comment by kevshocker** [comment]
having same issue - very annoying... seems like Rambox needs update for gmail and yahoo mail - getting ready to stop using

**Comment by aravindhp** [comment]
The issue seems to be that the "new Yahoo Mail" performs a user agent check and rejects whatever user agent Rambox is returning. So I think this issue can be solved by providing an option to set a custom user agent.

**Comment by jaylenw** [comment]
Same issue for me.

**Comment by fevangelou** [comment]
Just installed - confirmed as well. Perhaps consider an option to choose a user agent in the "advanced" block for each service configured.

**Comment by antzpantz** [comment]
I've had this happen to me quite recently as well. I had chosen to try the 'new' Yahoo Mail and now I can't go back... only using 'classic'.

**Comment by Canis-Enigmas** [comment]
This bug needs to be a top priority fix as Yahoo seems to have updated their code and the "Try it later" bypass button does not work any more.

**Comment by antzpantz** [comment]
This hasn't been looked at for a few months?!

**Comment by saenzramiro** [comment]
Seems like they are blocking the user agent we use in Rambox. And like you said, "Try it later" seems like is not working anymore.

I will release a minor version today or tomorrow fixing this.
