### ISSUE TITLE
Disable service function does not work (The service keeps activated)

### ISSUE THREAD

**Issue by chmercesmoreira** [saenzramiro/rambox#835]
### Steps to reproduce

1. Uncheck "Service Enabled" box from some service (I tested on Whatsapp Web)
2. The box is now named: "Service Disabled", but after switching back to the service tab it is still activated.

### Expected behavior

The service should be disabled after unchecking that box.

### Actual behavior

The service keeps activated.

### ENVIRONMENT

> Rambox: v0.5.3

> OS: Arch Linux

> Arch: x64

**Comment by saenzramiro** [comment]
Can you confirm this in latest version? v0.5.9.

**Comment by chmercesmoreira** [comment]
The problem was fixed in this new update probably.
