### ISSUE TITLE
Feature: keep slack default notification sound

### ISSUE THREAD

**Issue by BenGamma** [saenzramiro/rambox#836]
Hi and first of all thanks for creating rambox service !
I'm using it since a few days now, and it's a really nice alternative to franz ✊ 

One thing is a bit confusing to me thought, it's the custom notification sound on slack, who's like a msn messenger notification. Pretty funny at the beggining but in fine a bit annoying 😅 

Is there any way to disable it ? Using a custom script maybe ? Thanks !

**Comment by saenzramiro** [comment]
Sounds are not handled by Rambox. Probably you will hear two sounds, one from Slack and the other from the OS (because of the notification).
I think Slack have an option to change the sound, and then you will have to configure your OS to change the sound.
