### ISSUE TITLE
This version of Chrome is no longer supported. Please upgrade to asupported browser.

### ISSUE THREAD

**Issue by Saboteur777** [saenzramiro/rambox#837]
### Steps to reproduce

1. Login to Gmail account
2. There it is: `This version of Chrome is no longer supported. Please upgrade to asupported browser.`

### Expected behavior

No error message. 

### Actual behavior

Gmail warns about not supported browser version. 

### ENVIRONMENT

Version: 0.5.3
Platform: linux (x64)
Electron: 1.4.15
Chromium: 53.0.2785.143
Node: 6.5.0

> Rambox: v0.5.3

> OS: Manjaro 17.0.1 Gellivara

> Arch: x64

**Comment by TiEul** [comment]
See #673. I am also still waiting for a new release, the repository maintainer has been a bit quiet on the matter in the last couple of weeks.

**Comment by Saboteur777** [comment]
Thanks TiEul, didn't notice the other open issue, so closing this over as it is a duplicate.

**Comment by saenzramiro** [comment]
Fixed in latest release.
