### ISSUE TITLE
Chrome version not longer supported

### ISSUE THREAD

**Issue by thimmy687** [saenzramiro/rambox#838]
### Steps to reproduce

1. open rambox
2. go to your gmail account
3. 

### Expected behavior

everything should work fine

### Actual behavior

everything works fine, but on top is a message: 
"this version of google chrome is not longer supported" 

### ENVIRONMENT

> Rambox: v0.5.3

> OS:  win10 

> Arch:  win32 (x64)

From rambox about screen:
> Version: 0.5.3
> Platform: win32 (x64)
> Electron: 1.4.15
> Chromium: 53.0.2785.143
> Node: 6.5.0

**Comment by TiEul** [comment]
#673
