### ISSUE TITLE
Cannot click anything on new Google login screen.

### ISSUE THREAD

**Issue by abaustin1** [saenzramiro/rambox#839]
### Steps to reproduce

1. Add Gmail as a service.
2. Enter email, click "next" to proceed to password entry.
3. The button does the material design click animation, but nothing else happens.

### Expected behavior

The login flow should progress to the password entry stage.

### Actual behavior

Button animations run, but the screen doesn't actually progress to the password entry field. In addition, the forgot your password link doesn't work.

### ENVIRONMENT

Version: 0.5.3
Platform: win32 (x64)
Electron: 1.4.15
Chromium: 53.0.2785.143
Node: 6.5.0

**Comment by FallenKN** [comment]
#832

**Comment by abaustin1** [comment]
@FallenKN I opened this separate issue because I thought #832 was more focused on the `This version of Chrome is no longer supported. Please upgrade to a supported browser.` error.

**Comment by adamwoodnz** [comment]
👍

**Comment by Gatherix** [comment]
Had the same issue. Changing the language (and then back to English) fixed it for me.

**Comment by piersjones** [comment]
Same issue here. Using the tab key and hitting enter allows me to use the 'Next' button.

**Comment by abaustin1** [comment]
I was able to get in by changing the language to Spanish, but hitting enter
didn't work. And after I changed the language to Spanish, if I put it back
to English it stopped working again.

**Comment by saenzramiro** [comment]
That was a Google issue, they fixed a few weeks ago. Please check again.

**Comment by Faixifk** [comment]
https://www.youtube.com/watch?v=PUNvi1Y5-ek
watch this video for the solution! :D
