### ISSUE TITLE
Glitches in discord

### ISSUE THREAD

**Issue by averrin** [saenzramiro/rambox#840]
Maybe same bug as #443 

### Steps to reproduce

1. Just use discord

![image](https://cloud.githubusercontent.com/assets/426007/25748006/339580b2-31b2-11e7-82b6-5830f655d834.png)

### ENVIRONMENT

> Version: 0.5.3
> Platform: linux (x64)
> Electron: 1.4.15
> Chromium: 53.0.2785.143
> Node: 6.5.0

> OS: Xbuntu 16.04.2 LTS

> Arch: x64

**Comment by FallenKN** [comment]
Try disabling hardware acceleration.
This does not seem to be a rambox related thing tbh..

**Comment by averrin** [comment]
@FallenKN this glitches appearing only in discord. Can i disable it in rambox?

**Comment by FallenKN** [comment]
@averrin to disable hardware acceleration click on the rambox logo then on tge settings whell thendisable it and restart

**Comment by saenzramiro** [comment]
Any news on this? What about in latest version 0.5.9?

**Comment by averrin** [comment]
If i remember right, im ENABLE acceleration and it works nice.
