### ISSUE TITLE
Ability to search an incomplete string in messages ?

### ISSUE THREAD

**Issue by taliesinpenbardd** [saenzramiro/rambox#842]
### REQUEST 

Hey, I'd like to know if there are patterns to search into messages, for a string in particular. If I want to find the occurrences of "daddy123", looking for "123" doesn't match, nor "\*123\*", "%123%", etc.

Is there a placeholder, a wildcard to search for incomplete strings ? Thanks by advance.

### ENVIRONMENT

> Rambox: v0.5.3

> OS: OS X El Capitan 10.11.6

> Arch: x64

**Comment by saenzramiro** [comment]
Rambox don't have any search functionality. Maybe the service itself have a search.
