### ISSUE TITLE
Rambox does not close properly using ALT+F4

### ISSUE THREAD

**Issue by severila** [saenzramiro/rambox#845]
### Steps to reproduce

1. Open Rambox
2. Close Rambox using Alt+F4

### Expected behavior

Rambox is properly closed.

### Actual behavior

Open Taskmanager and see: The app is closed but the background processes are still running. 
Rambox can not be started again until the background processes are manually all killed.

### ENVIRONMENT

> Rambox: v0.5.3

> OS: Microsoft Windows 10 Pro, 10.0.10586 Build 10586

> Arch: x64

**Comment by Rakaim** [comment]
I'm having this issue as well on Ubuntu Desktop 17.04.

I can do a `ps -ef | greo ambox` and there's a host of processes still running. If I attempt to kick off the application again, it halts and doesn't recreate the UI - as if Rambox is already running. (And it seems to still be running, just headlessly). I continue getting notifications for new messages coming in.

**Comment by saenzramiro** [comment]
I couldn't reproduce this error. One thing that I didn't mention is that by default, Rambox minimises to system tray on close window. Did you check that?
