### ISSUE TITLE
Slack Chat shows no new messages

### ISSUE THREAD

**Issue by david-camden** [saenzramiro/rambox#846]
### Steps to reproduce

1. send a private message to someone in Slack
2. wait at the receiving computer with rambox minimized
3. control after a time if messages received - find messages although no new messages where announced

### Expected behavior

get a note when a new private message arrives

### Actual behavior

there is no new messages note although new messages arrived. in the userlist the new message is noted

### ENVIRONMENT

> Rambox: v0.5.3

> OS: Windows 10

> Arch: x64

**Comment by dmetzler1988** [comment]
I thought its only on my pc.
Same problem here. But only on status-bar icon - not on tabs.

**Comment by david-camden** [comment]
yes, same here. at the tabs i see the note, when i open rambox. but if it is minimized or hidden by other windows i dont get the statusbar info.
just tested the error with yahoo mail and saw, that i also dont get noticed when a new mail arrives, only in the tabs.

**Comment by saenzramiro** [comment]
This will be fixed in next release. Thanks!
