### ISSUE TITLE
Request: Add Viber service

### ISSUE THREAD

**Issue by babluboy** [saenzramiro/rambox#847]
Please add Viber service to Rambox
Can viber be enabled manually? If yes, please provide the instructions

**Comment by justpusher** [comment]
I think it's totally impossible, because Viber does not have a web version.

**Comment by TriiNoxYs** [comment]
Rambox only supports webversion. It is impossible to add an app on it :/

**Comment by TriiNoxYs** [comment]
Rambox only supports webversion. It is impossible to add an app on it :/
