### ISSUE TITLE
Semcha task “x-compass-compile” does not exist

### ISSUE THREAD

**Issue by flying-sheep** [saenzramiro/rambox#849]
relevant section of sencha output:

```
[INF] appending sass content to /home/phil/Dev/PKGBUILDs/rambox/src/rambox-0.5.3/build/temp/production/Rambox/sass/Rambox-all.scss.tmp
[ERR] The following error occurred while executing this line:
/home/phil/Dev/PKGBUILDs/rambox/src/rambox-0.5.3/.sencha/app/build-impl.xml:285: The following error occurred while executing this line:
/home/phil/Dev/PKGBUILDs/rambox/src/rambox-0.5.3/.sencha/app/sass-impl.xml:189: The following error occurred while executing this line:
/home/phil/Dev/PKGBUILDs/rambox/src/rambox-0.5.3/.sencha/app/sass-impl.xml:235: Problem: failed to create task or type x-compass-compile
Cause: The name is undefined.
```

**Comment by pmgouveia** [comment]
You have to install Sencha with extJS. Download it directly from their [website](https://www.sencha.com/products/extjs/cmd-download/)

[stackoverflow - install sencha with compass extension](https://stackoverflow.com/questions/39227994/senchacmd-silent-install-with-compass-extension-component)
[AUR - sencha cm 6](https://aur.archlinux.org/packages/sencha-cmd-6/)

**Comment by flying-sheep** [comment]
i was using the latter

**Comment by pmgouveia** [comment]
yeah me too... that's why I bumped into that error ;)

**Comment by flying-sheep** [comment]
Oh, I thought you meant the AUR package was a way to install it correctly.

I’m about to take it on, but i can’t prevent that fucking awful installer from writing to my .zshrc yet

**Comment by flying-sheep** [comment]
OK, I fixed the PKGBUILD: `-Dall=true` installs e.g. compass and `-VaddToPath=No` prevents it from tampering with my .zshrc
