### ISSUE TITLE
Pop-up windows when manually adding services

### ISSUE THREAD

**Issue by thniels** [saenzramiro/rambox#85]
Feedly opens a new browser window for entering credentials. I tried adding Feedly as a service but was met with a message from Feedly that a window was blocked. I am sure there are other services that use new windows like this.

The concept is rather cool and the implementation slick. I liked it.

**Comment by saenzramiro** [comment]
Yes, there're a lot. I have to find a way to allow SSO that opens a new window. Because there are others that works ok because use redirection process.

**Comment by saenzramiro** [comment]
Merged with #193
