### ISSUE TITLE
Request: Add Trello

### ISSUE THREAD

**Issue by MatheusRV** [saenzramiro/rambox#853]
Please add Trello project manager.  https://trello.com/

**Comment by 1beb** [comment]
This is already supported as a custom service.

**Comment by TriiNoxYs** [comment]
Actually, Rambox goals are mostly messaging and mail apps.
There is a Pull Request wich adds Trello, but it's not merged: #266 
@saenzramiro Added it to 1.0.0 milestone, so it's not for now...

Waiting, you can add it as a custom service, this is very easy.
