### ISSUE TITLE
Invalid certificate for rambox.pro

### ISSUE THREAD

**Issue by Ryuno-Ki** [saenzramiro/rambox#858]
### Steps to reproduce

1. Open your web browser.
2. Navigate to https://rambox.pro/

### Expected behavior

I can browse the website securely without having to fear, that a man in the middle tampered the site.

### Actual behavior

I'm presented an Unsecure Certification Warning, because HTTPS is issues for github pages.

### ENVIRONMENT

> Firefox v53.0 (64bit)

> OS: Ubuntu Linux 16.04

> Arch: x86_64

**Comment by saenzramiro** [comment]
Right, as you mention, we hosted rambox.pro in GitHub Pages and we don't have any SSL certification and we don't need it for now.
