### ISSUE TITLE
Microsoft Teams not loading

### ISSUE THREAD

**Issue by vTide** [saenzramiro/rambox#859]
I have added a new Microsoft Teams service.  A new tab get created for it, but after I login using my Microsoft work account, I only get a blank blue/purple (the official Teams colour) background.

-
> Rambox 0.5.3
> Electron 1.4.15
> linux x64 4.8.0-51-generic

**Comment by rand0me** [comment]
Hello! I have noticed that this is because User Agent header, Rambox provided. To temporarily fix this issue, you can Right-click on "Teams" tab, choose "Toggle developers tools", then click on three dots in top-right corner, and choose "Network conditions". In this panel, you can choose custom User Agent, such as "Windows Chrome 52" and reload with opened dev-tools.

**Comment by tommica** [comment]
Works on the 0.5.8 release

**Comment by nmat** [comment]
@saenzramiro might be closed in version 0.5.8/.9?

**Comment by saenzramiro** [comment]
@nmat Yes, let me close it.

**Comment by vTide** [comment]
Hi Daniil

I still cannot get this to work.

I am running Rambox on Zorin, if that helps...

Regards,

Paul

**Comment by nmat** [comment]
@vTide can you maybe check what version you are using of rambox and also what the developer console says during the load of teams?

if possible can you try to run teams with a fresh install? (clearing cache etc)

**Comment by vTide** [comment]
Just updated to 0.5.13, and still have not managed to use Teams sucessfully at all.
![screenshot from 2017-10-09 09-17-06](https://user-images.githubusercontent.com/16246453/31328066-498b650c-acd3-11e7-9276-a78eb2b90639.png)

**Comment by bierbo** [comment]
Hello @vTide, I had the same problem with Teams. Have you tried it on a clean install? It works for me on a clean install.
When I want to use Teams on a Upgrade install i have to check "Disable Cache" on the network conditions tab. After a reload, It works as it should.

**Comment by rodneyrod** [comment]
@vTide You might want to open the issue again?

**Comment by vTide** [comment]
The latest version of Rambox now works great with Teams.  I have switched
from Franz.

Thank you.

**Comment by saenzramiro** [comment]
Seems like Microsoft blocks Electron apps now, so we will fix it in next release. Please see here: #1354
