### ISSUE TITLE
Discord Notifications Not Going Away

### ISSUE THREAD

**Issue by livejamie** [saenzramiro/rambox#861]
### Steps to reproduce

1.  Use Discord
2. Clear your notifications

### Expected behavior

Regular tab without a red notification box

### Actual behavior

![image](https://cloud.githubusercontent.com/assets/49513/26176270/29441e3a-3b1b-11e7-8135-f53d498a08ba.png)

### ENVIRONMENT

> Rambox: v0.5.3

> OS: Windows 10

> Arch: x64

**Comment by saenzramiro** [comment]
That means you have unread messages in a channel/group. Can you check that?

**Comment by rnyberg** [comment]
It should only display if we have unread mentions? Not general chat messages on channels we participate in.

**Comment by rnyberg** [comment]
Or if it's not the wished default behaviour, there should be an option to only show the red notification box for mentions (stuff that trigger a highlight in Discord itself). Like @everyone, @here and @yourname.

**Comment by saenzramiro** [comment]
That will be difficult because we can't know when you were mentioned unless Discord do something in the UI to notice that (ex: add a badge in the channel title).
Can you check if there is an option in Discord to configure it only to show you a badge when you were mentioned?

**Comment by rnyberg** [comment]
`document.querySelectorAll(".badge").length` will show you the amount of @username mentions currently unread.

**Comment by saenzramiro** [comment]
I just tested and works ok for me. If I configure the channel to silence, it will not show unread badge in the app.

@rnyberg If you want, you can inject your own JS code overriding the default `checkUnread` function. So you can do something like this:

`function checkUnread() {
    updateBadge(document.querySelectorAll(".badge").length);
}`

**Comment by rnyberg** [comment]
Thanks @saenzramiro, works well.
