### ISSUE TITLE
Rambox uses 100% of system resources

### ISSUE THREAD

**Issue by Ionaru** [saenzramiro/rambox#863]
### Steps to reproduce

1. Install Rambox on Kubuntu 16.10 (Plasma 5.8.5)
2. Run Rambox
3. Add Gmail 

### Expected behavior

Rambox loads and performs normally

### Actual behavior

The rambox-service-api process takes a core to 100% and multiple gigabytes of RAM is used. When having multiple tabs, this slows the system down to a crawl.

This happened after I upgraded from v0.5.3 to v0.5.8. I have also tried a clean install of version v0.5.8, which had the same issue.

### ENVIRONMENT

> Rambox: v0.5.8

> OS: Kubuntu 16.10

> Arch: x64

![screenshot_20170519_094307](https://cloud.githubusercontent.com/assets/3472373/26239175/3ae9dad2-3c7c-11e7-8e71-eee2c4d87591.png)

![screenshot_20170519_094244](https://cloud.githubusercontent.com/assets/3472373/26239180/3e79601e-3c7c-11e7-9fdb-95d7cb8a407f.png)

**Comment by toalex77** [comment]
I have same issue on openSUSE Leap 42.2 (Plasma5 desktop environment).
Rambox clogs system saturation all the RAM and then it continue to fill up the swap partition.
On openSUSE the package has been update today to a 0.5.8 version. With 0.5.3 version this issue is never verified.

**Comment by gotlaufs** [comment]
Can confirm.
Just upgraded from 0.5.3 to 0.5.8 and whenever I start Rambox I have 2 rambox processes in `top` running at 100 % CPU and the free memory of the system (~6 GB) disapperas literally in 10 seconds.
I have Gmail, Hangouts, Skype, WhatsApp and Messenger tabs set up.

**Comment by nlenkowski** [comment]
I'm seeing the same issue on macOS 10.12.5 w/ Rambox 0.5.8. Regardless of what services are enabled Rambox shows 100% CPU usage. Currently I have WhatsApp, Hangouts and Messenger configured, I've tried removing them to no affect.

![image](https://cloud.githubusercontent.com/assets/1290235/26318866/ed587348-3f1c-11e7-90fa-766820688168.png)

**Comment by mruckli** [comment]
I have the same issue. macOS 10.12.5. Downgraded to 0.5.3 as 0.5.8 is unusable like this

**Comment by nmat** [comment]
Can you please test this using version 0.5.9 where there are lots of fixes for hangouts etc.

**Comment by mruckli** [comment]
It seems to be better now. My fans are no longer running on highspeed :)
It still uses approx 40% cpu but I think this is the same as in 0.5.3.

**Comment by nmat** [comment]
If possible can you create a diagnostic of what process there might be that causes the CPU load? It might help narrow down if there is anything else that can be looked at further.

**Comment by M0UL** [comment]
my rambox is using more then a 1gb of ram. 

![](https://image.prntscr.com/image/3f09da9614024536b6c20d6ec598b221.png)

**Comment by Ionaru** [comment]
@M0UL those values look perfectly acceptable for an application that has Chromium under the hood.
You will use about the same amount if you were to open all those as tabs in a Chrome browser.

Not related to this issue.

**Comment by Ionaru** [comment]
@nmat 0.5.9 seems to have resolved this issue.
