### ISSUE TITLE
Slack is not showing up

### ISSUE THREAD

**Issue by ElCampeon** [saenzramiro/rambox#866]
My slack account is just showing a black screen. I have tried deleting and reloading the account, but it is not helping. See attached. The same Slack account is working fine on Slack.com
![rambox 2017-05-19 11-51-23](https://cloud.githubusercontent.com/assets/26015813/26253546/25e4f942-3c8a-11e7-81c9-e55de86aa118.png)

-
> Rambox 0.5.3
> Electron 1.4.15
> darwin x64 16.5.0

**Comment by nmat** [comment]
Could you please test 0.5.8 pre-release to see if it helps?

**Comment by nmat** [comment]
https://github.com/saenzramiro/rambox/releases/tag/0.5.8

**Comment by ElCampeon** [comment]
Which is the correct download link for Mac?

**Comment by nmat** [comment]
https://github.com/saenzramiro/rambox/releases/download/0.5.8/Rambox-0.5.8.dmg ? 

All links are a bit further down that page...

**Comment by ElCampeon** [comment]
I tried it, but it is the same exact behavior. Slack still has a blank page.

**Comment by nmat** [comment]
hmmm I tested it on my mac and on windows 10. I can login and use it without any problems at all.

**Comment by Kurre** [comment]
Try to enable 'Disable Hardware Acceleration' in Preferences. That worked for me.

![image](https://cloud.githubusercontent.com/assets/1389199/26304806/677c4c3a-3ef5-11e7-9ec6-f6788434a3f0.png)

If it works for you (as it did for me) there's probably some compatibility issues with rendering engine..or something like that.

**Comment by ElCampeon** [comment]
@Kurre 
I just tried this, restarted, and still no change.

**Comment by dmetzler1988** [comment]
i think you maybe do the same mistake than i.
Slack now needs only the name on url. `https://` and `slack.com` stands there and don't need to be filled in.

**Comment by ElCampeon** [comment]
@dmetzler1988 That was it! Can't believe it was such a silly mistake. Thanks.

**Comment by NgoHuy** [comment]
in my slack, one private channel is missing line, then I cannot read lastest message as picture
![102305171023](https://cloud.githubusercontent.com/assets/1238112/26337309/f5625376-3fa1-11e7-9f95-b2103db1b63a.jpg)

**Comment by nmat** [comment]
Maybe this can be closed?
