### ISSUE TITLE
Problem visual in Slack when mute a channel

### ISSUE THREAD

**Issue by gnavarroco** [saenzramiro/rambox#867]
- Configure Slack:
- In a Channel, press Mute Channel in Menu
- A white bar appears

In service Slac, when i mute a channel a white bar appears that does not leave the lower screen and stays there forever unless i take off the mute mode
![image](https://cloud.githubusercontent.com/assets/18214996/26258336/517825e0-3c92-11e7-9712-b9ba02837c29.png)
![image](https://cloud.githubusercontent.com/assets/18214996/26258358/68055062-3c92-11e7-8af3-1d3f21c28b9e.png)

-
> Rambox 0.5.3
> Electron 1.4.15
> win32 x64 10.0.15063

**Comment by saenzramiro** [comment]
Can you confirm if this still happens in v0.5.9?

**Comment by saenzramiro** [comment]
Duplicated #815
