### ISSUE TITLE
WhatsApp videos won't load or play

### ISSUE THREAD

**Issue by jamy015** [saenzramiro/rambox#869]
When clicking the load button on a WhatsApp video, a loading icon shows up for a moment and then goes away again, so downloading is impossible.

If the video has already been automatically loaded by WhatsApp, when clicking the play button, the video thumbnail just flashes white for a moment and doesn't play.

> Rambox 0.5.3
> Electron 1.4.15
> win32 x64 10.0.15063

**Comment by saenzramiro** [comment]
Works for me in latest version 0.5.9. Can you check again please?

**Comment by jamy015** [comment]
Looks like it works for me too in v0.5.9 🎉

**Comment by wilwad** [comment]
Experiencing status video not playing after playing once - next replay video flashes once then status closes.Version v2.17.395
