### ISSUE TITLE
Allow single instance mode

### ISSUE THREAD

**Issue by brwolfgang** [saenzramiro/rambox#87]
Hi there, I would like to suggest a "single instance mode".
I often open the app from a keyboard shortcut and it is loading
a new instance every time - instead of simply showing the current opened one.

Thanks for the great app

-
> Rambox 0.3.0
> Electron 1.2.5
> linux x64 4.6.0-040600-generic

**Comment by saenzramiro** [comment]
Yes, I have to take a look on this. Thanks!
