### ISSUE TITLE
Rambox creates terminal window pop up every time I restart MacOS

### ISSUE THREAD

**Issue by brunorsini** [saenzramiro/rambox#870]
### Steps to reproduce

1. Install Rambox 0.5.3 on MacOS Sierra
2. Reboot
3. 

### Expected behavior

Nothing happens at login

### Actual behavior

Ugly terminal window pops up every time I reboot my Mac, have to manually close it : /

**Comment by JamesValero** [comment]
I would get this too when it's set to open at login. It would work for me but closing terminal also kills the app.

**Comment by nmat** [comment]
I can reproduce this on my MacOS also

**Comment by nmat** [comment]
This is fixed in version 0.5.9, you might have to go to System Preferences -> Users -> Startup applications for the user and remove the terminal helper there if it does not get removed when upgrading. Can you please try this?

**Comment by Ash258** [comment]
Is this issue still relevant?

**Comment by brunorsini** [comment]
Doesn't occur to me anymore.

**Comment by Ash258** [comment]
Close it then please.
