### ISSUE TITLE
GMail doesn't load with 5.3.8 pre-release

### ISSUE THREAD

**Issue by r2d2leboss** [saenzramiro/rambox#873]
### Steps to reproduce

1. Update to Rambox 5.3.8
2. Open your GMail tab(s)

### Expected behavior

GMail home page

### Actual behavior

GMail is loading indefinitely. Reload current service doesn't change the result. RamBox is also using 100% of CPU.

<img width="1282" alt="loading" src="https://cloud.githubusercontent.com/assets/14126507/26346013/282b49ea-3fa5-11e7-94e4-63c230f0799a.png">

### ENVIRONMENT

> Rambox: v0.5.8

> OS: macOS

> Arch: x64

**Comment by saenzramiro** [comment]
Yes, we noticed that also and fixed. We will publish a new pre-release today or tomorrow.
