### ISSUE TITLE
Multiple services show a blank white page

### ISSUE THREAD

**Issue by ptoro** [saenzramiro/rambox#874]
### Steps to reproduce

1. Add multiple services.
2. Restart computer.
3. Click on one of the added services.

### Expected behavior

That service shows.

### Actual behavior

All that shows is a white page. Services where I've had this issue include Hangouts, Slack, Facebook Messenger.

### ENVIRONMENT

> Rambox: ?

> OS: Windows 10

> Arch: x64

**Comment by mayurdw** [comment]
I have faced similar issues, it is solved by refreshing the service.

Maybe the solution can be to autorefresh the pages on startup?

**Comment by nmat** [comment]
Can you please check if this is fixed in version 0.5.9? there are lots of fixes for problems with sign in etc

**Comment by mayurdw** [comment]
@nmat at the moment, I can't see the problem. It was mostly persisting on Skype and now it isn't
