### ISSUE TITLE
Request: Tinder

### ISSUE THREAD

**Issue by eitchtee** [saenzramiro/rambox#875]
Tinder now has a webapp at tinder.com, would be nice to have it at the selection of app on rambox.

I've tried adding it as a custom service, but it hangs at the facebook auth, giving me a infinite loading screen.

**Comment by jacoblo** [comment]
Anyone have a fix for this one?

**Comment by saenzramiro** [comment]
We have problems with services that use SSO with popup options, like Tinder.

Hopefully we will fix it in a future release, but for now, you can't use it. Sorry. ='(

**Comment by TimKraemer** [comment]
They do have a phone-number login now, which works perfectly fine inside rambox as a custom service
