### ISSUE TITLE
How to hide the menu?

### ISSUE THREAD

**Issue by mpkh** [saenzramiro/rambox#877]
I want to hide the menu alike on screenshot in Readme, how to do it?

**Comment by Grizaster** [comment]
You mean the menu File|Edit|View... ? just go to the preferences and check "Auto-hide Menu bar (Alt key to display)" 
![image](https://cloud.githubusercontent.com/assets/3832799/26424670/589ffa02-40d2-11e7-80e1-961a68dcff68.png)

**Comment by mpkh** [comment]
@Grizaster weak, in 0.5.8 on linux I had no this option...
