### ISSUE TITLE
WhatsApp error

### ISSUE THREAD

**Issue by Stanzilla** [saenzramiro/rambox#878]
### Steps to reproduce

1. Get a new whatsapp message while the window is not focused
2. 
3. 

### ENVIRONMENT

> Rambox: v0.X.X
0.5.8
> OS: XXXX
Win8.1
> Arch: x64 or ia32
x64

https://i.imgur.com/WHJym5r.png

**Comment by nmat** [comment]
Can you please test using version 0.5.9?

**Comment by Stanzilla** [comment]
Yeah still happens from time to time

**Comment by nmat** [comment]
I believe there is a ticket about this and error searching is being done by ramiro. I am using windows 10 and rambox with whatsapp and have had no javascript error.

If possible can you create a different account on the machine and install 0.5.10 there and see if you get the same error if the rambox install is fresh and latest version of 0.5.10?

**Comment by NotYannis** [comment]
I use the latest version (v 0.5.10) and I still have the error (on Windows 8.1)

**Comment by jsanta** [comment]
Latest version (v0.5.13) still has this problem.

**Comment by simontong** [comment]
I'm getting this message when switching to whats app.

![image](https://user-images.githubusercontent.com/1494859/31263427-05fe048c-aa5a-11e7-80a3-fc276457fed5.png)
