### ISSUE TITLE
Self signed certs

### ISSUE THREAD

**Issue by Slind14** [saenzramiro/rambox#88]
Add a service with self signed certs and only a white will show. In this case it is self signed cert + non default port (9000)

![image](https://cloud.githubusercontent.com/assets/3914677/16734605/715ff38a-4786-11e6-9dfa-25b469fd637d.png)

-
> Rambox 0.3.0
> Electron 1.2.5
> win32 x64 10.0.10586

**Comment by saenzramiro** [comment]
Hi @Slind14, 

Can you help me to reproduce this bug? I'm also in Windows 10 x64.

**Comment by Slind14** [comment]
sure, try adding this:
https://lounge.mym.li:9000/

**Comment by Slind14** [comment]
Thanks

**Comment by jbbr** [comment]
@saenzramiro I really don't like "fixing" this by just skipping ssl validation for every page. This is a serious security/privacy vulnerability.

Option 1: Add a checkbox when adding a custom service like "Trust all certificates" to explicitly set this option for specific services

Option 2: Show warning/confirm prompt when certificate is invalid. Allow skipping warning for this service once/always.

**Comment by saenzramiro** [comment]
@jbbr You are right, I will take Option 1 and try to implement it. :wink:

**Comment by Slind14** [comment]
@jbbr I could, but what is win, there? I use lounge via. a docker container and even setting up letsencrypt is probably 1-3 hours of work.

**Comment by jbbr** [comment]
@Slind14 Without validation SSL is pretty useless. It adds an overhead but little security (man-in-the-middle attack is still possible). So without a proper validation you could also just disable https.

Self-signed certificates have valid use cases and when comparing fingerprints, it's possible 
to use them securely. So it's not always a bad idea - but skipping validation entirely without verifying the cert manually is like skipping ssl security completely.

In your case the data transferred might not be very sensitive and I assume it's your private service - so it's legit to skip ssl of course.

But if you would want valid ssl easily you could use Caddy web server (e.g as reverse proxy in your docker setup) https://caddyserver.com/ It automatically get's a valid certificate from letsencrypt.

Other optional: letsencrypt containers for nginx or other webservers like https://github.com/JrCs/docker-letsencrypt-nginx-proxy-companion - just start a container in addition to nginx as a reverse proxy and get valid ssl termination.

@saenzramiro Thanks!

**Comment by Slind14** [comment]
yeah, I only care about the encryption.

**Comment by jbbr** [comment]
Thats my point: You don't really get useful encryption if you'r not verifying the certs. Someone could do a man-in-the-middle attack, read all your traffic in clear text and you wouldn't notice it.

But I assume this is out of the scope of this issue so with a "trust all" checkbox during service creation you can use your service as you want without verifying certs and other services can still be used securely :)

**Comment by Slind14** [comment]
why, the traffic is still encrypted. The browser is still warning me if the cert changed. Ofc rambox isn't with the way it currently works, therefor the second suggestion might be better with additional warning about changed certs or being able to whitelist certs.

**Comment by jbbr** [comment]
Yes, if your check the certificate on the first connection and make sure it's really the certificate you expected then it's safe as long as the client informs you about a cert change.

What I wrote was primarily referred to rambox - But is also valid for other clients, especially automated ones.
For example: Many Android/iOS apps use https to communicate with a backend server but don't check certificates. It's very easy to act as a man-in-the-middle and get passwords and more of app users in clear text.
