### ISSUE TITLE
No context menu in Slack

### ISSUE THREAD

**Issue by PauloGDPeixoto** [saenzramiro/rambox#880]
Right clicking on a link in a slack conversation does not bring a menu to allow you to copy the link, as happens in the slack app, or in the browser.

**Comment by nmat** [comment]
Context menu is a common request. You can see some information here.

https://github.com/saenzramiro/rambox/pull/297

**Comment by PauloGDPeixoto** [comment]
I'm sorry, I didn't find that. I'm closing this ticket then.
