### ISSUE TITLE
Microsoft teams

### ISSUE THREAD

**Issue by areal060781** [saenzramiro/rambox#881]
I got a blue screen when I sign in my microsoft teams account...

-
> Rambox 0.5.3
> Electron 1.4.15
> linux x64 4.4.0-78-generic

**Comment by nmat** [comment]
Hello,

The microsoft teams sign in is fixed in upcoming release of 0.5.8 (next release)

**Comment by nmat** [comment]
@saenzramiro this is fixed in 0.5.8/.9?

duplicate of: https://github.com/saenzramiro/rambox/issues/859

**Comment by nmat** [comment]
I tested this with rambox 0.5.9 and it works flawless here. Please give it another run to see if you can login.

**Comment by saenzramiro** [comment]
@nmat Yes, it's fixed in v0.5.9.
