### ISSUE TITLE
Adding Jira OnDemand+Google Auth leads to "OpenID response was invalid"

### ISSUE THREAD

**Issue by olivierlefloch** [saenzramiro/rambox#882]
### Steps to reproduce

1. Add a custom service for https://CUSTOM_DOMAIN.atlassian.net
2. Try to login using Google Auth to log in
3. After going through the auth process, end on a login failure page that claims "The OpenID response was invalid or malformed." and reloads endlessly

### Expected behavior

End up logged into Jira.

### Actual behavior

Infinite redirection into an error 400 page: "The OpenID response was invalid or malformed."

### ENVIRONMENT

> Rambox: v0.5.3
> OS: Mac OS X 10.12.5
> Arch: x64

**Comment by saenzramiro** [comment]
Can you confirm this for latest version 0.5.9?

**Comment by olivierlefloch** [comment]
It's fixed thanks a lot!
