### ISSUE TITLE
'Download' button on Arch Linux links to .deb file

### ISSUE THREAD

**Issue by bartduisters** [saenzramiro/rambox#887]
If there is an update available, you get a message on the GUI of Rambox with a 'Download' button. If the button is clicked, it tries to download a .deb file.

I was able to update through AUR.

OS: Arch Linux: x64

**Comment by mbroadhead** [comment]
This also happened to me on Fedora 25 (Workstation Edition)
The rambox version where I clicked install: Rambox-0.5.3-94.x86_64 (rpm)
The rambox file that downloaded: Rambox_0.5.9-x64.deb

**Comment by saenzramiro** [comment]
For any Linux distro, the Download button in the UI will open the Releases section in GitHub to download it manually.
