### ISSUE TITLE
Screen Resolution doesn't fit the window

### ISSUE THREAD

**Issue by Daywalker7754** [saenzramiro/rambox#888]
I updated to the new version and now the screen resolution doesn't fit into the window anymore. So now the complete program is useless cause I can't see anything anymore. I will now delete it and try it again in the next version.

	
	-
	> Rambox 0.5.9
	> Electron 1.7.1
	> win32 x64 6.1.7601

**Comment by nmat** [comment]
@Daywalker7754 did you zoom the outside of the actual window?

Can you try go to View -> Actual Size

Then make sure you zoom inside the window (service) instead of the electron part of the window.

I did see this today also. There seems to be 2 different areas of Zoom.

**Comment by Daywalker7754** [comment]
Okay I got it. It's only possible to see the complete page when the outside zoom is set to "Actual Size". You have huge service buttons but you can see the page :). @nmat Thanks for your help
![screenshot](https://cloud.githubusercontent.com/assets/3886633/26622104/950f47ba-45e9-11e7-80c6-f8043df5e764.jpg)

**Comment by tiredofit** [comment]
I am seeing this same issue - The service icons are huge!
Hoping we can get the same style of icons in place as they were in 0.53 in new release.

**Comment by saenzramiro** [comment]
@tiredofit Did you tried what @nmat said?

**Comment by tiredofit** [comment]
Yes, I am running 5.10 now, but each time I start the application I have to adjust all font sizes all over again. I am dealing with it, or just trying not to restart the app :)

**Comment by saenzramiro** [comment]
@tiredofit Try version 0.5.13, we fixed a problem with HiDPI monitors.
