### ISSUE TITLE
Whatsapp service is not showing writing box

### ISSUE THREAD

**Issue by titojimenez1986** [saenzramiro/rambox#889]
Whatsapp service is not showing writing box because rambox is not loading whatsapp web full page

	
	-
	> Rambox 0.5.9
	> Electron 1.7.1
	> win32 x64 10.0.14393

**Comment by nmat** [comment]
is it possible that you have zoomed in to the UI in rambox? There are 2 types of zooms.

Can you please try to:
1. Go to View -> Actual Size
2. Check the login page again

**Comment by titojimenez1986** [comment]
I have already tried to reduce the zoom to the minium and I still have the same problem

**Comment by titojimenez1986** [comment]
It happens also with another services and it didn't happened on previous versions.

**Comment by titojimenez1986** [comment]
I have already tried to reduce the zoom to the minium and I still have the same problem

**Comment by titojimenez1986** [comment]
I have the same problem and configuration that related in https://github.com/saenzramiro/rambox/issues/895

**Comment by SolveSoul** [comment]
I also have the same issue. Not only WhatsApp but also Ryver and Slack. I'm using macOS Sierra v10.12.5

**Comment by saenzramiro** [comment]
Are you using special resolution/monitor?

**Comment by GaboFDC** [comment]
I have the same issue, i'm in macOS Sierra 10.12.5.
And also gmail is out of bounds, the right part is cut, can't see the config and profile buttons.

<img width="586" alt="screen shot 2017-07-04 at 09 41 28" src="https://user-images.githubusercontent.com/1425500/27834639-55e73c4a-609d-11e7-944f-24c0ce0da50e.png">

I switched different resolutions, but always have the same issue.

**Comment by titojimenez1986** [comment]
Solved on version 0.5.10

**Comment by bsander** [comment]
Is it? I'm still seeing the same issue.

**Comment by titojimenez1986** [comment]
With 0.5.10 versión I see perfectly the services I've added. New version solved my issue

**Comment by saenzramiro** [comment]
@bsander Did you tried what @nmat said?

**Comment by bsander** [comment]
Yes, but that doesn't work. I tried the latest current version (.12) and also tried re-adding my services. Still the apps think the viewport is bigger than the actual window size (both horizontal and vertical).

**Comment by ivoanjo** [comment]
Just had the same problem with 0.5.13 on one of my machines. Removing all Rambox files for my user (I'm on linux, so they were in `~/.config/Rambox/`) fixed it.

**Comment by mudit2103** [comment]
I had the same issue, but I just figured it out. If the applications don't fit horizontally, this is probably NOT because of the application being in the wrong zoom, but rather, the Rambox tab itself is in the wrong zoom. The fix for me was to go to the Rambox tab and then set it to Actual Zoom. Setting the applications to Actual Zoom didn't help.

**Comment by mecorre1** [comment]
You are the man @mudit2103 thanks so much!

**Comment by grouh** [comment]
Thanks A LOT @mudit2103 , i was close to give up after trying all kind of manipulations, until a landed here.
