### ISSUE TITLE
Upgrade to nodejs 8

### ISSUE THREAD

**Issue by TwizzyDizzy** [saenzramiro/rambox#890]
Hi folks,

rambox currently uses nodejs 7.9.0. As nodejs 7 is only supported (in maintenance mode = only critical bugs, critical security fixes) until June 2017 it might by wise to already transition to nodejs 8 (which is also the new LTS version).

For details, see https://github.com/nodejs/LTS#lts-schedule1.

Cheers
Thomas

**Comment by saenzramiro** [comment]
We will do it. Thanks!

**Comment by TwizzyDizzy** [comment]
Unfortunately, you haven't, see #857.

Cheers
Thomas

**Comment by TwizzyDizzy** [comment]
For further information, see: https://github.com/saenzramiro/rambox/issues/857#issuecomment-335108869

Cheers
Thomas
