### ISSUE TITLE
Telegram Showing Blank Screen

### ISSUE THREAD

**Issue by Foggalong** [saenzramiro/rambox#891]
### Steps to reproduce

1. Install Rambox 0.5.9
2. Add Telegram service
3. Switch to Telegram tab

### Expected behavior

Shows the Telegram login screen

### Actual behavior

Shows a blank white screen which persists on refresh

### ENVIRONMENT

> Rambox: v0.5.9

> OS: Ubuntu 17.04

> Arch: x64

**Comment by modulebaan** [comment]
Works fine here, I heard that were a problem with Telegram their Web client.

**Comment by Foggalong** [comment]
Oh shoot, nm then! Just an bad coincidence that I upgraded Rambox at the same time this happened
