### ISSUE TITLE
Rendering out of window

### ISSUE THREAD

**Issue by aLagoG** [saenzramiro/rambox#895]
### ISSUE
Since the new version came out the services get rendered a little bit outside of view (the render space seems to continue 100px right from the end of the window) making it impossible to view the rightmost part of the page

### ENVIRONMENT

> Rambox: v0.5.9

> OS: Windows 10

> Arch: x64

>Also I have an HDPI display with windows scale on 125%

**Comment by saenzramiro** [comment]
Seems to be an Electron bug, but I will take a look and see if we can fix it for next release.
