### ISSUE TITLE
Mac: window doesn't show until I click on either dock icon or 'show window' menuitem

### ISSUE THREAD

**Issue by Daij-Djan** [saenzramiro/rambox#898]
The app's window doesn't show until I manually click on either dock icon or 'show window' menuitem. This is annoying with autostart but also relevant/true when manually starting the app

### Steps to reproduce
1. start the app on a Mac with 10.12.5 - happens with 0.5.9 (but also with versions before)
==> see window not appearing
3. click dock icon or 'show window' menu item (CMD+TAB is not enough!)
==> see how window appears 

### Expected behavior
window shows right away without any manual interaction

### Actual behavior
window doesn't show until I click on either dock icon or 'show window' menuitem

### ENVIRONMENT
Mac osx 10.12.5
rambox 0.5.9
MBP late 2015
wifi
6 services configured in the app

from about box:
Version: 0.5.9
Platform: darwin (x64)
Electron: 1.7.1
Chromium: 58.0.3029.110
Node: 7.9.0

**Comment by saenzramiro** [comment]
Please check if "Start minimized" option in Preferences is unchecked.

**Comment by Daij-Djan** [comment]
super thanks.

didnt even think to search for this as it is HIGHLY un-mac like... I mean it should show at least when launching manually.

so I vote for removing this option ;)
