### ISSUE TITLE
BUG: Clicking on link opens multiple tabs of the same thing in browser

### ISSUE THREAD

**Issue by Deygus** [saenzramiro/rambox#90]
I found a problem.

I added Google Inbox but when I click on the link to one of my emails to open it in my browser to see more such as an advertisement or a link to go to a website from an email campaign it is opening up 4 tabs in Google Chrome of the same exact thing.

Screenshot of problem:
[http://i.imgur.com/8iVchNQ.png
![2016-07-11_12h11_00](https://cloud.githubusercontent.com/assets/4062943/16737820/138ee9ac-4761-11e6-8627-eb76e950da97.png)
](http://i.imgur.com/8iVchNQ.png)

**Comment by Deygus** [comment]
Testing this further it seems to happen when any link is clicked on and not just in emails..

**Comment by samuba** [comment]
I can confirm this for Google Inbox.
But Telegram and WhatsApp don't have this issue for me.

**Comment by saenzramiro** [comment]
#6 #28 #18
