### ISSUE TITLE
Rambox can't be installed via Chocolatey

### ISSUE THREAD

**Issue by justpusher** [saenzramiro/rambox#900]
Rambox currently can't be installed via Chocolatey package manager because Chocolatey refers to 0.5.8 Rambox release, and this release is removed from github. 

Please don't remove previous releases from github. 

[Chocolatey ](https://chocolatey.org/)is a great package manager for Windows. 

Currently I get such error: 

> ERROR: The remote file either doesn't exist, is unauthorized, or is forbidden fo
> r url 'https://github.com/saenzramiro/rambox/releases/download/0.5.8/Rambox-0.5.
> 8-x64-win.zip'. Exception calling "GetResponse" with "0" argument(s): "The remot
> e server returned an error: (404) Not Found."

	-
	> Rambox 0.5.9
	> Electron 1.7.1
	> win32 x64 6.1.7601

**Comment by MrChick** [comment]
> Please don't remove previous releases from github.

Why not if there's issues with them?

**Comment by justpusher** [comment]
> Why not if there's issues with them?
New release may contain even more significant issues than previous one. 
For example, after the last update I receive endless popup notifications when using Hangouts. 
I would like to revert to previous version, but I can't even download it.

**Comment by rodneyrod** [comment]
@justpusher It's up to the devs who manage the Chocolatey entry to update it themselves.
You can contact them via this link:
https://chocolatey.org/packages/rambox/ContactOwners

**Comment by nmat** [comment]
0.5.9 seems to be in the repo now. Maybe you can test it again?

**Comment by saenzramiro** [comment]
And now they updated to 0.5.10.

@justpusher Endless notifications for Hangouts was fixed in latest release.
