### ISSUE TITLE
Hangouts never-ending notifications

### ISSUE THREAD

**Issue by grberk** [saenzramiro/rambox#904]
Looks like the issue with Hangouts constantly notifying me of new alerts until I give it focus is back with the latest update. This is really annoying. :-/

	
	-
	> Rambox 0.5.9
	> Electron 1.7.1
	> win32 x64 10.0.14393

**Comment by chwagssd** [comment]
![image](https://cloud.githubusercontent.com/assets/294938/26728736/16ecdce4-4760-11e7-95cf-05ed66abc8e1.png)

Similar issue here, after resuming my mac from sleep it keeps toggling between no notifications and 818. I click the hangouts tab, click the desktop notification, go back and forth, nothing resolves it for me except exiting all together. It's only the hangouts integration that I see doing this, not the others (for me skype and 2 slack)

![image](https://cloud.githubusercontent.com/assets/294938/26728836/69c1c02e-4760-11e7-9436-24ba3242b40c.png)

**Comment by jcolesio** [comment]
currently experiencing the same issue

**Comment by Zuela** [comment]
Same here...

Version: 0.5.9
Platform: darwin (x64)
Electron: 1.7.1
Chromium: 58.0.3029.110
Node: 7.9.0

**Comment by evandroalb** [comment]
Same here!

Version: 0.5.9
Platform: win32 (x64)
Electron: 1.7.1
Chromium: 58.0.3029.110
Node: 7.9.0

**Comment by MrTomato** [comment]
Same issue - super annoying 😢 
Version: 0.5.9
Platform: darwin (x64)
Electron: 1.7.1
Chromium: 58.0.3029.110
Node: 7.9.0

**Comment by piaccarino** [comment]
I notice that it only does this to me when I get a voicemail from google voice.  It seems like a parsing error, I will get a voicemail from (456) 123-4567 and it will tell me I have 1 message, 456 messages, 1 message, 456 messages, repeating until I read the message.  If I have time I will look at the code.

**Comment by servaasd** [comment]
Same issue -

Version: 0.5.9
Platform: win32 (x64)
Electron: 1.7.1
Chromium: 58.0.3029.110
Node: 7.9.0

**Comment by 127001** [comment]
Adding another +1 on this one with the following client:

Version: 0.5.9
Platform: linux (x64)
Electron: 1.7.1
Chromium: 58.0.3029.110
Node: 7.9.0

**Comment by oscar-juarez** [comment]
Having the same issue here.

Version: 0.5.9
Platform: win32 (x64) /  linux(x64)
Electron: 1.7.1
Chromium: 58.0.3029.110
Node: 7.9.0

**Comment by agreen** [comment]
Same 

Rambox 0.5.9
Electron 1.7.1
darwin x64 15.6.0

**Comment by chybaDapi** [comment]
Same issue here :(

	> Rambox 0.5.9
	> Electron 1.7.1
	> win32 x64 10.0.15063

**Comment by Jimi-James** [comment]
I just upgraded to 0.5.9 from 0.5.3 and I'm now having this issue, too.

Electron 1.7.1
Arch Linux x64 (kernel version 4.11)

**Comment by guedressel** [comment]
annoying

**Comment by thatgeek95** [comment]
I am also having this issue. Rambox install info:

Version: 0.5.9
Platform: linux (x64)
Electron: 1.7.1
Chromium: 58.0.3029.110
Node: 7.9.0

**Comment by chwagssd** [comment]
Thank you @saenzramiro - just downloaded 0.5.10 because I saw this was fixed, now I can re-enable audio notifications for Hangouts :) 🥇

**Comment by Jimi-James** [comment]
Just upgraded. Well, I'm not getting continuous notifications forever, and that's great, but I'm actually not getting any notifications at all. I can't say for sure that I'm not getting the popup notifications, but the fact that I've been messaged a bunch and haven't noticed implies I'm probably not. More importantly, I'm not getting any unread count on the Hangouts tab.

Electron 1.7.1
Arch Linux x64 (kernel version 4.11)

**Comment by Jimi-James** [comment]
And suddenly that issue went away. Actually, not suddenly, but right after I finally logged into the cloud (now that that other issue is fixed) and synced my tabs.
