### ISSUE TITLE
Rambox process getting killed on ubuntu 17.04

### ISSUE THREAD

**Issue by rendel** [saenzramiro/rambox#907]
### Steps to reproduce

1. Launch Rambox
2. Browse services
3. Wait a while

### Actual behavior

Rambox process is getting killed (if I run it on the command line, I can see the "Killed" log displayed on stdout) by OOM Killer.

I can fix the issue by creating an OOM exclusion for the rambox process (see https://backdrift.org/oom-killer-how-to-create-oom-exclusions-in-linux)

### ENVIRONMENT

> Rambox: v0.5.9

> OS: Ubuntu 17.04

> Arch: x64

**Comment by rendel** [comment]
In fact, the cause might not be the OOM killer, as I encounter another unexpected killed even with the OOM exclusion rules. In its current state, it is not really usable as it is getting killed every few minutes (at best). 
I was not encountering such issue in previous version of Rambox.

**Comment by rendel** [comment]
Is there a way to enable some king of debug log that could provide more information on what is happening when it is getting killed ?

**Comment by nmat** [comment]
@rendel can you test using the "Disable Hardware Acceleration (needs to relaunch)" to see if that does anything to help?

**Comment by rendel** [comment]
@nmat I have tried that already, and this does not change anything unfortunately.

**Comment by rendel** [comment]
Still happening on 0.5.10.

**Comment by saenzramiro** [comment]
@rendel I will investigate about this. Do you more info you can provide?

**Comment by rendel** [comment]
@saenzramiro unfortunately no, I was not able to find any system log (dmesg, syslog, kern.log) indicating why this process is getting killed.

**Comment by rendel** [comment]
It seems that the issue is fixed in 0.5.13. I haven't seen the rambox process getting killed since I installed 0.5.13.
