### ISSUE TITLE
Rambox starts hidden and can't be unhidden

### ISSUE THREAD

**Issue by kuteninja** [saenzramiro/rambox#909]
### Steps to reproduce

1. Disable the System Tray Icon (I want it to show on the Taskbar)
2. Start Rambox hidden (minimized)
3. Open Rambox, it works, it makes sounds when you receive messages, but it's unaccessible

### Expected behavior

The taskbar icon should unhide Rambox if it's already running, also it should always minimize to taskbar of the system tray option is disabled.

### ENVIRONMENT

> Rambox: v0.5.9
> OS: Windows 10 Home 1703
> Arch: x64

**Comment by kuteninja** [comment]
Is there a way to un-hide the window, or to clear my preferences so that I can leave the default setup which works fine?

**Comment by kuteninja** [comment]
I just found the config file after uninstalling it and searching on Windows, it's saved on C:\Users\kuteninja\AppData\Roaming\Rambox\config.json

Here's the config that causes this issue:
```javascript
{
	"always_on_top": false,
	"hide_menu_bar": true,
	"window_display_behavior": "show_taskbar",
	"auto_launch": true,
	"window_close_behavior": "keep_in_tray_and_taskbar",
	"start_minimized": true,
	"systemtray_indicator": false,
	"master_password": false,
	"disable_gpu": false,
	"proxy": false,
	"proxyHost": "",
	"proxyPort": null,
	"locale": "en",
	"x": 268,
	"y": 12,
	"width": 1000,
	"height": 800,
	"maximized": true,
	"master_password1": "",
	"master_password2": ""
}
```

Changing "start_minimized" to false and "systemtray_indicator" to true, fixes the issue

**Comment by epaumier** [comment]
Hello everyone !
Thanks kuteninja for the fix :) it worked for a while but now the problem is back. I think I fudged up the file zeus knows how. For anyone out there as silly as me: delete config.json, uninstall rambox then reinstall it. This will also fix this issue.

**Comment by Jimi-James** [comment]
I just changed the way I use the program and now I'm dealing with this issue as well. I'd like to be able to start it minimized to the taskbar without having a tray icon.

**Comment by saenzramiro** [comment]
I will take a look on this for next release.

**Comment by Gaudenz77** [comment]
kuteninja tipp helped!
