### ISSUE TITLE
Javascript error occured during the main process"

### ISSUE THREAD

**Issue by tbondois** [saenzramiro/rambox#910]
JavaScript popup everytime I click on "Save" on preferences, since I changed a certain option one day (see details below)

### Steps to reproduce

1.  Go to Preferences
2. When closing windows : set to "Keep tray and taskbar"
3. Popup : "Javascript error occured during the main process", about an exception on a property "destroy"
4. After that : no more tray icon. Same popup again everytime I go on preferences and click "save". Even if I put by the default option. Even after restarting Rambox or complete PC. I noticed that if i change a option, it's correctly saved

### ENVIRONMENT

> Windows 10

> Rambox: very last version

> Arch: x64
![rambox error](https://cloud.githubusercontent.com/assets/11269723/26749146/05375dca-4806-11e7-961c-80ca10bcef9c.png)

**Comment by saenzramiro** [comment]
Is this also happening in latest version?

**Comment by tbondois** [comment]
saenzramiro Yes. But the option is saved anyway.

**Comment by saenzramiro** [comment]
Ok, I will investigate this for next version.

**Comment by npichot** [comment]
Hi 
I'm still experiencing this issue on windows 10 with the latest version 5.14.
Any ideas ?
Best regards
