### ISSUE TITLE
Bitdefender 2017 detects the app as malicious since new version

### ISSUE THREAD

**Issue by Kyosfonica** [saenzramiro/rambox#911]
Just have installed the AV and start the app.

	> Rambox 0.5.9
	> Electron 1.7.1
	> win32 x64 10.0.15063

**Comment by saenzramiro** [comment]
We contacted Bitdefender to fix this, because it's a false positive.

**Comment by Kyosfonica** [comment]
Please flag the issue as solved. 
Bitdefender has updated the database and the false positive is gone.
Thanks.

**Comment by saenzramiro** [comment]
Great! They just sent me an email saying that.

**Comment by FabianBeiner** [comment]
Bitdefender 2018, latest update, removes the latest version (0.5.12) again.

**Comment by dulichan** [comment]
Any update on this? Did BitDefender do an update?
