### ISSUE TITLE
Skaling whatsapp and telegramm

### ISSUE THREAD

**Issue by captain-o** [saenzramiro/rambox#912]
Window is not scaling when changing the items size with "strg -" or "strg shift +".
The bottom of the window is disappearing.

	
	-
	> Rambox 0.5.9
	> Electron 1.7.1
	> win32 x64 10.0.14393

**Comment by saenzramiro** [comment]
Is this also happening in latest version?

**Comment by captain-o** [comment]
Seems to work perfectly now
