### ISSUE TITLE
feature request: reload keyboard shorcut.

### ISSUE THREAD

**Issue by M0UL** [saenzramiro/rambox#914]
### Expected behavior

using the keyboard shortcut f5 and  crtl+r to reload a tab/page.

### Actual behavior

this does nothing.

### ENVIRONMENT

> Rambox: v0.5.9

> OS: windows 10

> Arch: x64

**Comment by saenzramiro** [comment]
There is a shortcut to reload only the current tab, it's Ctrl + Shift + R.

**Comment by MrMinos** [comment]
This is a small request and I am curious how people feel about this.

What if:
Ctrl + Shift + R reloads globally
Ctrl + R reloads that specific tab

I think from typical broswer user experience, Ctrl + R reloading one tab is more intuitive.

**Comment by saenzramiro** [comment]
If we change it right now, a lot of users will start screaming!

**Comment by MrMinos** [comment]
It could be something like taking off the bandage :)

**Comment by adavidzh** [comment]
I tend to agree woth @MrMinos as I, e.g., knew nothing about `Ctrl+Shift+R` and was doing `Ctrl-R` all the time. Also if one things of this as `Ctrl-r` vs. `Crtl-R`, it would make sense that the capitalised version has a wider scope.
