### ISSUE TITLE
"Do not disturb" blocks all audio, not notifications

### ISSUE THREAD

**Issue by ErinMoriarty42** [saenzramiro/rambox#916]
I was attempting a skype call and could not hear the other person. Discovered the issue was that I had do not disturb on. 

-
> Rambox 0.5.3
> Electron 1.4.15
> linux x64 4.4.0-78-generic

**Comment by saenzramiro** [comment]
That's what Don't disturb do, mute all sounds and notifications. If you want to blocks only notifications, there is a service setting for that.

**Comment by SimJoSt** [comment]
You are right, but I would need to disable notifications for every service, right?
It would be great to have a global toggle for that, but still be able to use other audio like videos and voice memos in that mode.
