### ISSUE TITLE
Rambox appears Offscreen if Monitor configuration is changed while Rambox is closed

### ISSUE THREAD

**Issue by DWSR** [saenzramiro/rambox#920]
### Steps to reproduce

1. Connect computer to multiple monitors.
2. Place Rambox on a secondary monitor (i.e. not the laptop panel)
3. Shutdown the computer (and Rambox)
4. Connect the computer to another set of monitors in a different configuration
5. Start Rambox

### Expected behavior

Rambox appears on the default (primary) monitor

### Actual behavior

Rambox appears offscreen and requires keyboard shortcuts to move back into the visible viewport

### ENVIRONMENT

**OS:** Windows 10 Enterprise 1703 Build 16199
**Rambox:** 0.5.9
**Arch:** x64

**Comment by nmat** [comment]
Hello, I believe this could be a electron issue. I have the same type of effect from atom. Can you test to use atom also to see if the display problems happens there also?

**Comment by nmat** [comment]
I have checked the electron issues a bit and seems like this one here is related: https://github.com/electron/electron/issues/4045 or I might be wrong

**Comment by DWSR** [comment]
Hi @nmat,

I'm using VSCode (also Electron based) and haven't had this issue. Perhaps they have some code that handles this case?

**Comment by nmat** [comment]
They could be using a different version of electron also. AFAIK this occurs on windows 10 mostly because of calculations. I have had similar issues with for example slack etc. So not 100% certain it is actually a issue with rambox itself.

**Comment by DWSR** [comment]
I'm not having an issue with the UWP Slack app, nor any of the several Electron based MSFT application that I run. Either they have specific code for this problem (possible) or there is a problem with the way that Rambox calculates window position.

Related #323

**Comment by Bruce17** [comment]
I had the same problem on my Win10 machine and I was not able to move the window at all. Close Rambox, open its config file (windows: `C:\Users\mir\AppData\Roaming\Rambox\config.json`) and alter the attribute `x: ...` to a positive value. I altered it to `x: 0`. Now my window is in view again. I don't know how this happened, but it is really annoying.

**Comment by driehle** [comment]
Thanks @Bruce17 for the hint to the config.json. Worked well for me! All the mentioned screenshots do not work when you are using a remote desktop connection, so editing the config.json seems to be the only soulution then.

**Comment by DWSR** [comment]
You can also Shift+Right click the application on the SuperBar and select Move. Then, tap an arrow key a couple of times, then move your mouse. The window should come back into focus.

**Comment by Bruce17** [comment]
@DWSR This was the first thing I tried, but it didn't work either in my case.

**Comment by Casyi** [comment]
Nothing worked, except @Bruce17 config.json solution. Thank you.
