### ISSUE TITLE
Javascript error when switching between Skype and Slack tabs

### ISSUE THREAD

**Issue by zurbergram** [saenzramiro/rambox#921]
### Steps to reproduce

1. Updated to newest version 
2. Move between tabs of Skype and Slack, maybe type in them.  Also reloading tabs causes an error to occur as well
3. A popup with attached image will show up several times

### Expected behavior

No error popup

### Actual behavior

See attached image of popup error

### ENVIRONMENT

> Rambox: v0.5.3

> OS: linux

> Arch: x64
![image](https://cloud.githubusercontent.com/assets/1094999/26789115/47384184-49dd-11e7-8043-148d8dfc8250.png)

**Comment by saenzramiro** [comment]
Seems like is trying to update the tray icon with unread messages count. Try by reinstalling Rambox.
