### ISSUE TITLE
Don't flash icon for notfications when do not disturb mode is on

### ISSUE THREAD

**Issue by jamy015** [saenzramiro/rambox#922]
Since Rambox 0.5.9, when a notification comes in, a little badge is added to the Rambox icon on the taskbar and it flashes orange.

This also happens when do not disturb mode is switched on. It seems to me that this makes do not disturb mode essentially useless (after all, you turn on do not disturb mode because you don't want to be disturbed by a lot of notifications, and this is exactly what happens with the flashing orange icon).

**Comment by olivierlefloch** [comment]
Same symptoms on the mac: I've disabled notifications for all channels, and turned on do not disturb mode, and yet the app icon bounces (sometimes multiple times) each time a channel receives a notification…

**Comment by ajacobs21e** [comment]
Same issue. Please fix this!

**Comment by saenzramiro** [comment]
I will do it in next version.
