### ISSUE TITLE
Slack Notifications Never Work

### ISSUE THREAD

**Issue by ccentofo** [saenzramiro/rambox#926]
1. Add Slack Service
2. Make sure Notifications are turned on and Unread counters are turned on

I expect to get a Rambox notification, and unread badge counters for the slack service and global unread to be increased 

I get no Rambox notifications or any unread badge counters being increased. Hangouts and Discord do these just fine.

> Rambox: v0.5.9

> OS: macOS 10.12.5

> Arch: x64

**Comment by dmetzler1988** [comment]
same constellation here (macOS, rambox, arch) but i havn't this problem. notification still shown every time.

**Comment by saenzramiro** [comment]
@ccentofo Did you check Slack configuration to enable Desktop Notifications?

**Comment by modulebaan** [comment]
Works fine here except when the unread counter should be 1 a '-' is shown. A higher number works OK.

OpenSUSE Tumbleweed
Rambox v0.5.9
Arch: x64

**Comment by ccentofo** [comment]
Every possible configuration to show notifications whether its the Slack configuration or the Rambox configuration are turned on. Still no badges/counters/banners for slack messages received through Rambox

**Comment by modulebaan** [comment]
Today I experience the same issue on the configuration above.

**Comment by saenzramiro** [comment]
In what option you have the Sidebar preference enabled?

**Comment by modulebaan** [comment]
Slack notifications are enabled in settings of Slack

**Comment by johanbrandhorst** [comment]
Same problem here, on the linux client version 0.5.10. I think they were appearing to start with but now I never see them. I'm wondering if I pressed to disable desktop notifications at some point when Slack started, but I can't seem to trigger that question again. All notifications are enabled in Slack settings and I've tried reinstalling Rambox and also deleting `~.config/Rambox` to no effect. Any thoughts? Is there some way to trigger the Slack client asking me if I want to enabled Desktop Notifications again?

**Comment by TimJarvis** [comment]
I have the same situation here - Windows 10 prof - Slack desktop notifications are on, I do see notifications in the Windows Action Center. But no badges on the slack tab(s) and no increment of the global badge count.

**Comment by PeetBrits** [comment]
Same for me. The unread counters showed for about the first month, but over the past week it stopped working. Win 10, Rambox v0.5.10.

**Comment by nmat** [comment]
There is a fix for notifications for slack: bc85177

This is not yet released thought but there is a workaround until the release that is in:
#1072

Please try the workaround to see if it works better for you.

**Comment by Ash258** [comment]
Fixed in #1076
