### ISSUE TITLE
User interface is small: difficult to read and click

### ISSUE THREAD

**Issue by gingerbeardman** [saenzramiro/rambox#930]
I would appreciate it of the user interface text and controls were larger.

As it is right now they are difficult to read and click.

Thanks!

**Comment by saenzramiro** [comment]
Are you talking about Rambox itself or a service in it?

Please check that you don't zoomed the page.

**Comment by gingerbeardman** [comment]
rambox itself

my services are fine

**Comment by saenzramiro** [comment]
You can use the options to zoom in and zoom out in the Menu.

**Comment by saenzramiro** [comment]
To zoom Rambox itself, please be sure to be in Rambox tab.

**Comment by gingerbeardman** [comment]
Last time I tried zoom it affected all tabs?

**Comment by nmat** [comment]
@gingerbeardman there is a 2 part zoom...one is for the interface where the rambox interface and tabs are zoomed. (only noticed when the "wrong" item is being focused so it zooms the interface)

The other is the inside service zoom. 

Its hard to see what is being focus. When zooming the interface it effects everything while the other service zoom is per tab zoom.

That is what @saenzramiro means I believe.

**Comment by gingerbeardman** [comment]
How do i do each type of zoom? 

I usually do Cmd+

**Comment by nmat** [comment]
its the same command. just that the focus needs to be correct. You can try using the scroll on the mouse while holding either Ctrl or Cmd

**Comment by gingerbeardman** [comment]
Please let me know how to set the focus correctly. Screenshots or video would help greatly @nmat
