### ISSUE TITLE
Settings dialog does not close after changes are made and saved

### ISSUE THREAD

**Issue by gingerbeardman** [saenzramiro/rambox#931]
WORKS
1. Setup a service
2. Click cog
3. Make no changes
4. Click save button ("Edit <service name>")
= dialog closes

DOES NOT WORK
1. Setup a service
2. Click cog
3. Change service name
4. Click save button ("Edit <service name>")
= dialog does not close (though changes are saved)

**Comment by nmat** [comment]
I can reproduce this.

If I edit the service one time with a different name....then click Edit it closes the tab.

Editing another name just the same way the window does not close.

**Comment by saenzramiro** [comment]
Ok, I will take a look.
