### ISSUE TITLE
App should open on last used tab, not rambox settings

### ISSUE THREAD

**Issue by gingerbeardman** [saenzramiro/rambox#932]
App should open on last used tab, not rambox settings

**Comment by nmat** [comment]
I have never experienced that it does not open the last used tab. Can you please explain a bit more of how you encounter this?

**Comment by gingerbeardman** [comment]
I will take a video.

But I open it and use Gmail tab, then I quit it. When I reopen it, it's on
Rambox Settings.

**Comment by M0UL** [comment]
for me it always opening the settings tab when i start rambox. it always has done that for me.

**Comment by nmat** [comment]
oh you mean first start of app after running it? I thought you meant when it was minimized or something.

**Comment by gingerbeardman** [comment]
yes, of course, first start

**Comment by nmat** [comment]
that explains it a bit more.

You should fill in the part of how to reproduce etc. it helps developers quite a lot. :)

**Comment by gingerbeardman** [comment]
Will do so in future

**Comment by jacoblo** [comment]
Same here and have thought about it many times as well. Franz sent you right into first tab and much more intuitive.

**Comment by gingerbeardman** [comment]
@jacoblo Franz takes you to the tab that was being viewed when the app was closed (not always th first tab)

**Comment by saenzramiro** [comment]
This is not a bug, it's a new feature. We will consider to add it in next release.

**Comment by brendanjones** [comment]
Just came here to make the same issue, and found this. So +1 to this!

**Comment by Ash258** [comment]
Already implemented `File -> Settings -> Default service to display when Rambox starts -> Last Active Service`
