### ISSUE TITLE
[Add custom service] Zalo but don't show counter on tab

### ISSUE THREAD

**Issue by qspeed** [saenzramiro/rambox#936]
### Steps to reproduce

1. Add custom service "Zalo": https://id.zalo.me/account
2. Add custom code: 

function checkUnread() {
    var e = document.getElementsByClassName("unread_countValue");
    var t = 0;
    for( i = 0; i < e.length; i++ ) t += parseInt(e[i].innerHTML.trim());
    updateBadge(t);
}

function updateBadge(e) {
    e >= 1 ? document.title = "(" + e + ") " + originalTitle : document.title = originalTitle
}
var originalTitle = document.title;
setInterval(checkUnread, 3000);  

### Expected behavior

I want it can show notice and counter on tab and tray icon, or add Zalo for next version.

### Actual behavior

Zalo is a free, cross-platform instant messaging and VoIP application as Viber, Whatsapp, ... It's popular in Vietnam.

When I add custom service Zalo, it works but doesn't show counter on tab and tray icon when having a new mess.

### ENVIRONMENT

> Rambox: v0.5.9

> OS: Mac OS Sierra 10.12.5

> Arch: x64

**Comment by hungmtuci** [comment]
Please consider to add this service soon. It is quite popular in Vietnam

**Comment by tdchien** [comment]
![image](https://user-images.githubusercontent.com/1614393/41452970-45a9cf34-709e-11e8-93bc-09fffe98897f.png)
I just created an script for display unread message. You can try with it https://gist.github.com/tdchien/5f0a3c7d65202c047392a9a7197d9187

**Comment by saenzramiro** [comment]
Hey guys,
Consider making a pull request to add Zalo with @tdchien unread code.
