### ISSUE TITLE
No icon in Linux

### ISSUE THREAD

**Issue by michel-slm** [saenzramiro/rambox#94]
On Ubuntu 16.04 with Budgie desktop installed and Plank as a dock, Rambox shows up with a generic icon in the dock:

![selection_028](https://cloud.githubusercontent.com/assets/85603/16753950/69011966-4818-11e6-9c19-a6b75f1dbfc6.png)

also, the installation tarball does not come with a stand-alone png logo file, so it's harder to create a desktop launcher.

**Comment by jrhenderson1988** [comment]
I have more or less the same problem on Ubuntu 15.10. The only difference being that the icon I get instead is the default grey question mark one.

**Comment by janpansa** [comment]
Just to confirm, this is only on certain distros. It works fine on Arch Linux 64 bit together with cinnamon.
![screenshot from 2016-07-13 11-47-17](https://cloud.githubusercontent.com/assets/1931549/16799420/0e5203d4-48f1-11e6-861d-cb6aa7a5f110.png)

**Comment by rummik** [comment]
I'm using Unity, and it doesn't seem to create a cached icon.  I'm not sure if this is because Rambox doesn't have the icon in an unpacked location, or if it isn't built with the icon packed in a way that Unity can see it.  Downloading https://github.com/saenzramiro/rambox/blob/master/resources/Icon.png and editing `~/.local/share/applications/rambox.desktop` fixes it.  Rambox may need to have a `.desktop` file included with it to resolve this in Ubuntu

**Comment by saenzramiro** [comment]
Ok, guys. I will take a look on this for the next release. Is a priority right now. :wink:

**Comment by Pablohn26** [comment]
Hi,

debian 9 and xfce here. Icon is on status bar but no in window selector and window frame:

![selection_002](https://cloud.githubusercontent.com/assets/1228418/17018307/89757e8c-4f37-11e6-9a98-75e650103e79.png)

**Comment by rummik** [comment]
Spotting this in KDE now.  Currently trying to figure out why.  I'm using the .deb for Rambox 0.4.2 on Kubuntu 16.04 / KDE 5.6

**Comment by abumalick** [comment]
I have a this bug on LinuxMint 18 (based on Ubuntu 16.04 LTS) I use Rambox 0.4.5 .
Shouldm't this bug be fixed ?

**Comment by jbbr** [comment]
@janpansa are you using the [rambox-bin](https://aur.archlinux.org/packages/rambox-bin/) AUR package? This does add an .desktop-file for rambox together with an icon.
This might confirm that having a .desktop file does fix the problem (Or does provide a workaround).

I can confirm that I don't have any issues with the Rambox icons in Arch Linux using i3 WM

**Comment by abumalick** [comment]
yep, deb file.
I am under XFCE desktop
I dont have a rambox.desktop file

**Comment by tivervac** [comment]
In the latest 64bit deb this is still an issue. The Icon.png is not included in the tarball.

**Comment by kiview** [comment]
Same problem on Fedora 26 when using the AppImage version.

**Comment by Israphel** [comment]
No icon in Xubuntu 16.04, with version 0.5.12

**Comment by diegombeltran** [comment]
Same here, Debian x64 and XFCE

**Comment by alp82** [comment]
Same problem here, Arch Linux with XFCE, installed `rambox-bin` from AUR.

**Comment by zyphlar** [comment]
I originally installed by downloading from github and manually extracting to a folder, so maybe that's why I didn't have an icon. My `~/.local/share/applications/rambox.desktop` file specified `Icon=application-default-icon` and it needs to point to the rambox executable.

Since installing the .deb package, `which rambox` now returns `/usr/local/bin/rambox` and changing my .desktop file to below has fixed the problem.

```
[Desktop Entry]
Encoding=UTF-8
Version=1.0
Type=Application
Name=Rambox
Icon=rambox
Exec=rambox
StartupNotify=false
StartupWMClass=Rambox
OnlyShowIn=Unity;
X-UnityGenerated=true
```

**Comment by francescocadei** [comment]
no icon also in ubuntu 17.10

**Comment by gospel91** [comment]
the same as in @francescocadei 
17.10 x64

**Comment by verzola** [comment]
Installing Rambox using the .deb from Releases on GitHub instead of .tar.gz that is downloaded on the website when you click on .deb option solved for me:

![screenshot from 2018-03-09 17-50-48](https://user-images.githubusercontent.com/2985522/37229338-75aec8f2-23c2-11e8-98d6-c3844665b1b8.png)

**Comment by willydee** [comment]
I had the same issue with 0.5.16 AppImage on Ubuntu Artful/Bionic, and Solus Budgie 3 as well; only a generic icon was shown in panels.
As a remedy, add the following line to `~/.local/share/applications/appimagekit-rambox.desktop`:
```
StartupWMClass=Rambox
```
The file might be named differently for the .deb package.
