### ISSUE TITLE
GIFs in Telegram are too small and can't enlarge them

### ISSUE THREAD

**Issue by Burt93** [saenzramiro/rambox#940]
### Steps to reproduce

1. Receive GIFs in Telegram.

### Expected behavior

See GIFs bigger, click to enlarge.

### Actual behavior

GIFs way too small.

### ENVIRONMENT

Version: 0.5.9
Platform: linux (x64)
Electron: 1.7.1
Chromium: 58.0.3029.110
Node: 7.9.0

> Rambox: v0.5.9

> OS: OS: 
Solus x86_64 
Kernel: 4.9.30-29.lts 

> Arch: x64

**Comment by notnsane** [comment]
It happens for most images, not just gifs, you need to reload Telegram (the tab) every ime you start it.

#644

**Comment by saenzramiro** [comment]
Like @notnsane said, let's marge this to #644
