### ISSUE TITLE
Settings Remember Services included in tabs but does not remember sign-on information.

### ISSUE THREAD

**Issue by pjcreese** [saenzramiro/rambox#941]
From an active Rambox session, backup the configuration.
From a new Rambox, restore backup.
Services are remember, but login information for each service is required to complete on new workstation.

	
	-
	> Rambox 0.5.9
	> Electron 1.7.1
	> win32 x64 10.0.15063

**Comment by nmat** [comment]
you should try to use auth0 for that purpose. Its a security messure to not be able to copy login information like that I believe

**Comment by pjcreese** [comment]
Care to expand on your comment?  I don't follow.

Further, why would I, for instance, setup, say, 10 different services on the first PC only to have to do the same thing over again on a separate PC? What steps have you saved me? Just so I know which ones I had setup before?  Doesn't seem like it saves that many steps.

And since I have a password-protected log-in, why wouldn't the credentials be saved using an encryption/hash that relies on my method of login?

**Comment by procyyon** [comment]
i would like to have the option to save the passwords too. So i can install rambox easily to every computer of mine.

**Comment by edmundlaugasson** [comment]
Same problem with certain services. This might be related also with those services. Currently Unseen and Zyptonite are such what I have been discovered.
Using:
Version: 0.5.9
Platform: linux (x64)
Electron: 1.7.1
Chromium: 58.0.3029.110
Node: 7.9.0

**Comment by saenzramiro** [comment]
@pjcreese @edmundlaugasson We don't store credentials (users and passwords), only configurations like services used and their configurations.
