### ISSUE TITLE
I Don't Understand How Rambox Works...

### ISSUE THREAD

**Issue by tb75252** [saenzramiro/rambox#944]
I just installed Rambox 0.5.9 (64-bit) on my Windows 7 laptop.  I also entered all the credentials for my Yahoo Mail account.  Using a different email address, I sent a test message to my Yahoo Mail account.
I was expecting some sort of notification window to pop up on my screen letting me know that my Yahoo Mail account had a new message.
But nothing happened...  Does Rambox not handle such notifications?  Am I missing a setting somewhere?

### ENVIRONMENT

> Rambox: v0.5.9

> OS: Windows 7, 64-bit

> Arch: x64 or ia32:  x64

**Comment by saenzramiro** [comment]
Do you have enabled desktop notifications inside Yahoo! Mail? You have to go to the cog at the top-right, then Settings. You will see an option there to enable desktop notifications.

**Comment by tb75252** [comment]
Yes, I did turn on desktop notifications in Yahoo Mail.  So, I don't understand why I never saw a note on the screen about the incoming email...

Another question:  Is Rambox capable of automatically logging into an email account, or do I have to enter my credentials every time I want to access the email account?

**Comment by Ash258** [comment]
See explanation here https://github.com/saenzramiro/rambox/issues/425#issuecomment-256108518
