### ISSUE TITLE
Cannot remove proxy because I mis-set the proxy

### ISSUE THREAD

**Issue by betsythefc** [saenzramiro/rambox#946]
### Steps to reproduce

1. Set proxy in settings to an incorrect proxy
2. Close and re-open
3. Rambox closes because it doesn't have any internet connection.

### Expected behavior

Even if no internet connection, I should be able to modify settings, and view the "home" page.

### Actual behavior

Rambox closes with an error that it has no internet connection

### ENVIRONMENT

> Rambox: v0.5.9

> OS: macOS 10.12.5

> Arch: x64

**Comment by saenzramiro** [comment]
Please check this wiki: https://github.com/saenzramiro/rambox/wiki/Edit-configuration-manually

**Comment by betsythefc** [comment]
Thanks!
