### ISSUE TITLE
PLEASE DISABLE ICON BOUNCE IN DOCK

### ISSUE THREAD

**Issue by twhite96** [saenzramiro/rambox#948]
### Steps to reproduce

1. Receive notification
2. Rambox icon bounces
3. Annoyed

### Expected behavior

Respect my system preferences for **no notifications**.

### Actual behavior

This did *not* happen with the prior version. I have all notifs off for Rambox and it *still* bounces. It is annoying.

### ENVIRONMENT

> Rambox: v0.X.X

0.5.9

> OS: macOS 10.12.5

> Arch: x64 or ia32

x64

**Comment by jvale** [comment]
Or just make it configurable.

**Comment by twhite96** [comment]
@jvale yeah, that. It also nags me for a donation. I already donated but it comes up every time I reopen the app.

**Comment by Radioreve** [comment]
Also annoyed by this :/ 
It only happens with some apps. Slack doesn't make the icon bounce, but Messenger does. Unless I silence the whole conversation, but then I don't see any notification at all.

**Comment by saenzramiro** [comment]
I will check this for next version.
