### ISSUE TITLE
White Page only

### ISSUE THREAD

**Issue by pcdog** [saenzramiro/rambox#95]
Using herbstluftwm as window manager, some tabs stay empty white after loading another page. Can be reproduced e.g by clicking the login button on tweetdeck.

update: Also happened with LXDE 
as soon as I navigate away from the first page, the rendered page will stay BLANK

seems to happen with Franz too, so I assume some incompatiblity with chrome rendering engine?

-
> Rambox 0.3.0
> Electron 1.2.5
> linux x64 4.4.0-28-generic

**Comment by pcdog** [comment]
it's a 64bit issue.

Downloading the 32bit version for a test from your website still silently sent me the 64bit version. I had to manually guess the deep link from herokuapp.com and fetch it and unzip it. 

complained about this:

./Rambox: error while loading shared libraries: libnss3.so: cannot open shared object file: No such file or directory

which was easy to fix:
sudo apt-get install libnss3:i386                                                                                 :(
[sudo] Passwort für pcdog: 
Paketlisten werden gelesen... Fertig
Abhängigkeitsbaum wird aufgebaut.       
Statusinformationen werden eingelesen.... Fertig
The following additional packages will be installed:
  libnspr4:i386
Die folgenden NEUEN Pakete werden installiert:
  libnspr4:i386 libnss3:i386
0 aktualisiert, 2 neu installiert, 0 zu entfernen und 72 nicht aktualisiert.
Es müssen 1'326 kB an Archiven heruntergeladen werden.
Nach dieser Operation werden 4'231 kB Plattenplatz zusätzlich benutzt.
Möchten Sie fortfahren? [J/n] J
Holen:1 http://ch.archive.ubuntu.com/ubuntu xenial-security/main i386 libnspr4 i386 2:4.12-0ubuntu0.16.04.1 [121 kB]
Holen:2 http://ch.archive.ubuntu.com/ubuntu xenial-security/main i386 libnss3 i386 2:3.23-0ubuntu0.16.04.1 [1'204 kB]
Es wurden 1'326 kB in 0 s geholt (14.7 MB/s).
Vormals nicht ausgewähltes Paket libnspr4:i386 wird gewählt.
(Lese Datenbank ... 564373 Dateien und Verzeichnisse sind derzeit installiert.)
Vorbereitung zum Entpacken von .../libnspr4_2%3a4.12-0ubuntu0.16.04.1_i386.deb ...
Entpacken von libnspr4:i386 (2:4.12-0ubuntu0.16.04.1) ...
Vormals nicht ausgewähltes Paket libnss3:i386 wird gewählt.
Vorbereitung zum Entpacken von .../libnss3_2%3a3.23-0ubuntu0.16.04.1_i386.deb ...
Entpacken von libnss3:i386 (2:3.23-0ubuntu0.16.04.1) ...
libnspr4:i386 (2:4.12-0ubuntu0.16.04.1) wird eingerichtet ...
libnss3:i386 (2:3.23-0ubuntu0.16.04.1) wird eingerichtet ...
Trigger für libc-bin (2.23-0ubuntu3) werden verarbeitet ...
sudo apt-get install libnss3:i386  5.46s user 0.40s system 56% cpu 10.355 total
pcdog@ws-silvan-ubuntu /opt/rambox % ./Rambox 
Gtk-Message: Failed to load module "overlay-scrollbar"
Gtk-Message: Failed to load module "gail"
Gtk-Message: Failed to load module "atk-bridge"



and suddenly tweetdeck goes past the login button and does not end up stuck in a whitescreen

there is something *NOT* working on the 64bit version on my ubuntu:
pcdog@ws-silvan-ubuntu /opt/rambox % uname -a
Linux ws-silvan-ubuntu 4.4.0-28-generic #47-Ubuntu SMP Fri Jun 24 10:09:13 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
pcdog@ws-silvan-ubuntu /opt/rambox % 


should be a 16.04 I think, mostly updated. 

and it affects Franz too (sorry but since both are using similar tech I tried to compare if it's related to the chrome or so)

**Comment by saenzramiro** [comment]
Hey @pcdog 

Sorry about the links, I fixed it today. 

So to clarify the problem, did you fixed it by installing the library missing or keep not working? 

Seems to be an Electron bug.

**Comment by pcdog** [comment]
Hey, 

I noticed there was a new version in the meantime so I updated.

When I opened it up I saw that there are still tabs missing (I think It was tweetdeck) so it did not sync the config

I logged out, upon re-login it will just spend forever "connecting" please wait .... configuration

so nothing happens, and my line is definitely not any bottleneck. That's ruled out...

I erased .config/Rambox, logged in again, still does seem like the thing is not downloading anymore

I'll try the 32bit version again on this box in a bit.

**Comment by pcdog** [comment]
32bit Version works and upon login, fetched the proper config. Obviously all my sessions are gone ;)

**Comment by saenzramiro** [comment]
Really weird. I don't know what can cause the problem.

**Comment by saenzramiro** [comment]
Related #181

**Comment by sknat** [comment]
I'm getting the same issue on my configuration:
Ubuntu Mate 16.04 (4.4.0-34-generic) 64bits

blank screen on skype, mightytext, hangouts & tweetdeck (same issue with Franz)

I installed the lib as stated above $ sudo apt-get install libnss3:i386
It only made thing worse... (although I get Mightytext loading visible from time to time)

Weird issue, still investigating

**Comment by saenzramiro** [comment]
@sknat As I mention in https://github.com/saenzramiro/rambox/issues/181#issuecomment-237327164, is an Electron bug. So it will be fixed in next release.
