### ISSUE TITLE
popup dialog upon server authentication not present

### ISSUE THREAD

**Issue by jaylenw** [saenzramiro/rambox#950]
### Steps to reproduce

1. I added a custom service providing an url to my website.
2. The website requires authentication through the server.
3. When adding the service I received no popup to login in. I refreshed Rambox and no change.

Possible useful links:
* https://developer.mozilla.org/en-US/docs/Web/HTTP/Authentication
* https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/WWW-Authenticate
* https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/401
It appears Rambox may not be able to support "401 Authorization Required" from servers?

### Expected behavior
Picture taken from Chrome Browser (Version 59.0.3071.104 (Official Build) (64-bit))

![screenshot from 2017-06-16 22-38-05](https://user-images.githubusercontent.com/6505395/27251166-3161c53e-52f6-11e7-8c13-8563ebb54a75.png)

### Actual behavior

![screenshot from 2017-06-16 22-37-48](https://user-images.githubusercontent.com/6505395/27251092-4c58a904-52f4-11e7-83d3-2a47041afc8a.png)

### ENVIRONMENT

> Rambox: v0.5.9

> OS: Ubuntu 16.04

> Arch: x64

-----
I would like to thank the developers and contributors for all the work that has gone into making this wonderful application.

**Comment by LiaoHongzheng** [comment]
duplication of issue  #378
https://github.com/saenzramiro/rambox/issues/378

**Comment by saenzramiro** [comment]
Let's merge this with #378
