### ISSUE TITLE
tweetdeck not possible to log in

### ISSUE THREAD

**Issue by M0UL** [saenzramiro/rambox#951]
### Steps to reproduce

1. make a new tweetdeck services
2. fill in username and password
3.  press login. 
4.  does not go to the next screen

### Expected behavior

allow me to login

### Actual behavior

does not work

### ENVIRONMENT

> Rambox: v0.5.9

> OS: win 10

> Arch: x64

**Comment by Pierlo1** [comment]
+1

**Comment by stinhambo** [comment]
I just left a tweet about this, sorry!

**Comment by saenzramiro** [comment]
The problem was regarding Electron. Updating to latest version fix the problem.

**Comment by M0UL** [comment]
thanks for fixing it
