### ISSUE TITLE
Proxy configuration reset

### ISSUE THREAD

**Issue by ParinVachhani** [saenzramiro/rambox#953]
### Steps to reproduce

1.  Install Rambox, set a master password and add proxy configuration.
2.  Now close it and try to use it on a proxy-less network.
3.  After entering the master password, it directly shows the error box with no internet connection available instead of at least letting me go to the settings and remove proxy.   

### Expected behavior
It should at least open the initial window even if I am offline so that I can add/remove proxy settings according to my network setup. Also, the proxy configuration for Rambox should be reset on uninstalling and reinstalling it but even that doesn't work.

### Actual behavior
It only shows the "no internet connection available" box. Uninstalling and reinstalling doesn't help either as somehow the configuration is persisted.

### ENVIRONMENT
> Rambox: v0.5.9
> OS: Linux Mint 18 Sarah 64-bit
> Arch: x64

**Comment by Bebef** [comment]
The same is true the other way round.

Rambox doesn't seem to be able to detect the corporate proxy settings, so I can't start it to enter the proxy settings.

However, changing the proxy settings directly in the config.json worked for me as a workaround.
