### ISSUE TITLE
Service bar as vertical

### ISSUE THREAD

**Issue by Mte90** [saenzramiro/rambox#954]
I switched to Rambox very happy but the service bar as horizontal use so many space and today the monitor are 16:9 so it will be better have that bar with all the services vertical like slack do.

**Comment by nmat** [comment]
Hello Mte90,

Would: http://rambox.pro/100/ be of interest?

From what I know there are plans to do a better interface which is planned more for 1.0.0

**Comment by Mte90** [comment]
Seems in the right way but the bar in that screens is always on the top in horyzontal and I am asking if it possible to have vertical

**Comment by saenzramiro** [comment]
We can think in a future release to add an option to switch...

**Comment by RYRNRY** [comment]
I would also like to see this feature.   An option could be added to the PREFERENCES section 
TABS POSITION : Left / Right / Top / Bottom
TABS DISPLAY : Show / Hide

**Comment by KTOmega** [comment]
I've done some work on this issue that lets any user select whether they want their tab bar to show up horizontally or vertically. It defaults to horizontal (no changes here) and simply changes the tab bar's position and rotation when the user changes something in their preferences.

Still needs some polish, though - the change only takes place after a full reload of Rambox, and service names don't play very well when vertical.

Will see how far I get by the end of the weekend and send a PR if I think it's sufficient work for the feature. You can see what I have so far over in [my fork](https://github.com/KTOmega/rambox/commits/left-service-bar). Screenshots below.

Preferences screen:
![screenshot_2018-04-28_17-35-12](https://user-images.githubusercontent.com/2063153/39402077-df06374e-4b0a-11e8-8bd2-59673419d0cc.png)

Vertical service bar:
![screenshot_2018-04-28_17-35-23](https://user-images.githubusercontent.com/2063153/39402115-d68baec2-4b0b-11e8-83dd-aeccb7e85158.png)

**Comment by reelism** [comment]
Has this been committed? Can't see in latest

**Comment by KTOmega** [comment]
This was committed in 3a4c89bd65c23284640d3f098c0b449f96ab6075. However, I am unsure if a release was created that includes this change.

**Comment by reelism** [comment]
So committed back in May. Any insights on the delay?

**Comment by Mte90** [comment]
No, there are no new release also if there are new changes in trunk since months...

**Comment by t00** [comment]
To be honest vertical icon bar in Franz looks much better and is more elegant. Rambox logo icon which sticks out on the UI makes the tabs look great in comparison (which they don't).
So much vertical space is lost due to window frame, menu, tabs with excessive padding and a label - it does not feel modern too.
Feature icons scattered around the window do not help too - why Help us / Follow us / facebook etc need to be always visible? It just adds clutter to already cluttered web realm of 2018.
With over a year wait for a feature which is already at least partially implemented just asks to look for an alternative - or a fork :( Or writing own implementation without the electron dependency - just pure webkit. Anybody knows such alternative or close match already exists?

**Comment by talha131** [comment]
> With over a year wait for a feature which is already at least partially implemented just asks to look for an alternative - or a fork :( Or writing own implementation without the electron dependency - just pure webkit. Anybody knows such alternative or close match already exists?

You can try https://wavebox.io/ It already has spellcheck, vertical bar and support for extensions like Markdown here. Pricing might be an issue though.

**Comment by KTOmega** [comment]
@saenzramiro, any updates on whether a new release will be created soon based on the latest of `master`? Seems like there's been a lot of features over the last few months that still need to be released.

**Comment by vraravam** [comment]
@saenzramiro - this preference seems to be on the top of many issues. Would you be able to release a new version with the latest fixes?

**Comment by Mte90** [comment]
There is a lot of people waiting for a new release...
