### ISSUE TITLE
Hide the menu bar of electron

### ISSUE THREAD

**Issue by Mte90** [saenzramiro/rambox#956]
Actually I get the menubar with File, Edit, View etc. will be useful to disabile to save space.

**Comment by nmat** [comment]
Hello Mte90,

In preferences you can set: "Auto-hide Menu bar (Alt key to display)"

That will hide the menubar and show it when you click Alt key.

hope this helps

**Comment by Mte90** [comment]
I cannot find that settings in the preference :-/

**Comment by nmat** [comment]
Go to: File -> Preferences

look 4 rows down. And you will have the value there.

**Comment by Mte90** [comment]
![screenshot_20170621_110137](https://user-images.githubusercontent.com/403283/27375995-1c43a6e4-5671-11e7-9457-b749d09c70db.png)
I have that window

**Comment by nmat** [comment]
that looks weird what version of rambox are you using?

Almost like new preferences or translation problem causing the preference not being there.

Can you tell me:

1. What is the operating system?
2. Does it change the preferences when changing the language?
3. Rambox version

**Comment by Mte90** [comment]
Version 0.5.9 on Debian Sid. nodejs 7.9.0 and electron 1.7.1.
on changing language to english is the same.

**Comment by V3XATI0N** [comment]
"Me too" comment. The menu bar is useless and looks terrible.

**Comment by V3XATI0N** [comment]
This was raised in #500 and the response from the dev was that this is intentionally hidden on Linux because some DEs don't allow menubars to be hidden (although I haven't found one yet where that's actually true). Anyway, you can manually hide the menubar by editing ~/.config/Rambox/config.json and setting "hide_menu_bar" option to true.

**Comment by Mte90** [comment]
I have the problem also in the latest one and I am on linux not OSX (darwin)
