### ISSUE TITLE
Prompted to log in, even though I am logged in

### ISSUE THREAD

**Issue by janpansa** [saenzramiro/rambox#96]
When I open Rambox, I am logged in automatically, however, there is still a message that tells me to login.

![screenshot from 2016-07-12 14-08-44](https://cloud.githubusercontent.com/assets/1931549/16766649/8d46edb4-483b-11e6-859d-823ad83993e3.png)

My PC details:

OS: Arch Linux 
Kernel: x86_64 Linux 4.4.1-2-ARCH
Uptime: 6h 0m
Packages: 1110
Shell: bash 4.3.42
Resolution: 3072x2048
DE: Cinnamon 2.8.6
WM: Muffin
WM Theme: Numix-Cinnamon Gideon (The days of grays)
GTK Theme: Mire v2_Grey [GTK2/3]
Icon Theme: Faenza
Font: Nimbus Sans L Condensed 9
CPU: Intel Core i7-3632QM CPU @ 3.2GHz
GPU: AMD/ATI Thames [Radeon HD 7500M/7600M Series]
RAM: 4644MiB / 7863MiB

**Comment by saenzramiro** [comment]
Seems like you have problems with sessions in your PC, because they are all related and all your tickets are about this. :confused:

**Comment by janpansa** [comment]
@saenzramiro It's weird, because Google Chrome seems to remember my sessions and I dont have to re login everytime with chrome.

I have tested at my house and it works fine on my house pc and remembers my credentials. This only happens on my work pc. I would like to get to the root of the problem though :/

**Comment by saenzramiro** [comment]
Did you check if there's a antivirus/process that is cleaning all your sessions?
