### ISSUE TITLE
Gmail: Wrong unread number of emails

### ISSUE THREAD

**Issue by socceric** [saenzramiro/rambox#963]
### Steps to reproduce

1. The unread number is wrong for gmail.
2. Given example. For 31 important unread emails and 70 more unread emails in the inbox gmail displays Inbox (31 : 70).
3. However the unread number in the Rambox bar shows 3,170

### Expected behavior

 101 or (31 : 70)

### Actual behavior

 3,170

### ENVIRONMENT

 

> Rambox: v0.5.9

> OS: Both Windows and MacOS

> Arch: x64

![screen shot 2017-06-22 at 20 14 01](https://user-images.githubusercontent.com/1143144/27451586-63868028-5787-11e7-9caf-ddf2115c5379.png)

![screen shot 2017-06-22 at 20 14 39](https://user-images.githubusercontent.com/1143144/27451600-72dae85c-5787-11e7-9829-adb2a7ed1993.png)

**Comment by saenzramiro** [comment]
Right, we focus Rambox to work with the default Gmail configuration on unread messages. So, for now you can switch back to default to make it work.

Maybe in a future release we can improve it to work with all configs.
