### ISSUE TITLE
Rambox Account login/registration not working

### ISSUE THREAD

**Issue by michal-borek** [saenzramiro/rambox#964]
I clicked "Login" button to setup Rambox account to sync my setup between computers and a popup was opened with message:

Rambox Account
Something went wrong.
Please contact technical support.

What is wrong? I use Linux (deb) version.

**Comment by michal-borek** [comment]
It seems to be the problem when I was at "Polish" language. I've changed language to "English" and it works fine... Strange.

**Comment by saenzramiro** [comment]
I will take a look.

**Comment by weits** [comment]
The same happens to me, when selected Czech language. Switched to English, created account and it worked. Then I can switch back to Czech and everything works.

**Comment by michal-borek** [comment]
Thats right. Same to me.

**Comment by Moosh-be** [comment]
ah my  very good,  I had same problem with french.  switch to english  works fine,  and  back to french after sync is also wroking.

**Comment by edmundlaugasson** [comment]
I have to admit that still not working. Using 64-bit .deb version 0.5.17 and cannot log in. Even switching to English does not help. Looks like cannot use Rambox anymore as I cannot log in :(

**Comment by WhittlesJr** [comment]
Furthermore, neither Google nor GitHub signup / login is working for me (Windows). I was able to get through the GitHub signup procedure, and authorized my account with GitHub, but then it dumped me back into Rambox and I'm still not logged in. Google was even less successful: I just get a blank window and then it closes itself.
