### ISSUE TITLE
Skype For Business doesn't work with Rambox

### ISSUE THREAD

**Issue by JeffSaret** [saenzramiro/rambox#966]
Hello Rambox Support,

Is there any way for me to get my Skype For Business account added into/working with Rambox? I tried logging in via the Skype connector, but it failed to work.

Thanks,

-Jeff Saret

	
	-
	> Rambox 0.5.9
	> Electron 1.7.1
	> win32 x64 10.0.14393

**Comment by saenzramiro** [comment]
Skype for Business is not a supported service because I couldn't find a way to try it.

If you can create us a test account so we can test it and help you, it will be appreciated. Please contact us to rambox@protonmail.com if you agreed with this.
