### ISSUE TITLE
Rambox login /registration not working locally

### ISSUE THREAD

**Issue by greenred123** [saenzramiro/rambox#968]
### Steps to reproduce

1. Cloned repo, followed quick start instructions
2. signed up for a trial of auth0, entered client id & domain in env.js
3. ran project
4. tried to sign up to rambox with a new account and then login. 

### Expected behavior

Should be able to login into new account

### Actual behavior

Cannot login, get message:
WE'RE SORRY, SOMETHING WENT WRONG WHEN ATTEMPTING TO LOG IN.

In terminal output I see this when first starting the app 
(node:99722) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: 36:64: execution error: System Events got an error: Can’t get login item "Electron". (-1728)

(node:99722) DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

after i type in the username and before i type in the password i see failed get calls (404) to gravatar. If I try to sign up for a new account the auth0_signup_popup is just a blank white screen. 

### ENVIRONMENT

> Rambox: latest

> OS: macos sierra

> Arch: x64

**Comment by saenzramiro** [comment]
No, if you want to run Rambox locally you will have to create an account in Auth0 and fill the .env file.

**Comment by lierdakil** [comment]
Wait, what? Why is this closed?

**Comment by lierdakil** [comment]
For the record, I'm running into the same problem currently.
