### ISSUE TITLE
Blank page after logging in to gmail

### ISSUE THREAD

**Issue by janpansa** [saenzramiro/rambox#97]
I only see a blank page after logging in with gmail.

![screenshot from 2016-07-12 14-13-17](https://cloud.githubusercontent.com/assets/1931549/16766713/f6b20e00-483b-11e6-96ad-635c723c790a.png)

my pc details:

OS: Arch Linux 
Kernel: x86_64 Linux 4.4.1-2-ARCH
Uptime: 6h 0m
Packages: 1110
Shell: bash 4.3.42
Resolution: 3072x2048
DE: Cinnamon 2.8.6
WM: Muffin
WM Theme: Numix-Cinnamon Gideon (The days of grays)
GTK Theme: Mire v2_Grey [GTK2/3]
Icon Theme: Faenza
Font: Nimbus Sans L Condensed 9
CPU: Intel Core i7-3632QM CPU @ 3.2GHz
GPU: AMD/ATI Thames [Radeon HD 7500M/7600M Series]
RAM: 4644MiB / 7863MiB

**Comment by saenzramiro** [comment]
That's weird. Try to reload Rambox going to "View -> Reload".

**Comment by janpansa** [comment]
@saenzramiro When I do a "View -> Reload" , the tabs also dissapears and I just see a completely blank window. The underlying controls on the page loads, because when I move my mouse around, the cursor changes it's type to a hand and back to a cursor, as if I'm hovering over links, however I just see white. Could it be the ati drivers ?

**Comment by saenzramiro** [comment]
Oh, I know what you are talking about. The other day I tested in a PC with Ubuntu 16 and happened the same. I think if you close it and open Rambox again, will work.

Also I noticed the bug that @Huaba mention in #100.

I will check this bug, but I think is an Electron bug.

**Comment by janpansa** [comment]
@saenzramiro thx haha ! I have tested at my house and do not get any blank screens at my house. The only major difference is the hardware between amd and nvidia drivers. At my house I use nvidia drivers and at work on my laptop, I use amd drivers. I think it has to do with amd drivers.

**Comment by saenzramiro** [comment]
Great! If all your tickets related to sessions are fixed, please close it but before explain what was the problem.
