### ISSUE TITLE
[Feature Request] Allow for data URI in the "Logo" field for custom logo

### ISSUE THREAD

**Issue by Sam-Hall** [saenzramiro/rambox#973]
Some validation on the Edit screen for a service prevents me from entering a data: URI into the Logo field. If it's not going to break anything, could you please permit this URL format?

**Comment by Sam-Hall** [comment]
I notice I can edit local storage with the developer tools to get the URI in the config as a workaround. It seems to work just fine.

**Comment by saenzramiro** [comment]
We don't have plans to allow data URI because almost all users don't know what is it.
