### ISSUE TITLE
Need to enter my password every time for all my services

### ISSUE THREAD

**Issue by janpansa** [saenzramiro/rambox#98]
For some reason my passwords are not stored, even though I said remember my credentials on this computer for every account.

![screenshot from 2016-07-12 14-17-02](https://cloud.githubusercontent.com/assets/1931549/16766863/c3a69598-483c-11e6-82c7-e65600e8c99b.png)
![screenshot from 2016-07-12 14-16-17 - 2](https://cloud.githubusercontent.com/assets/1931549/16766864/c3ade302-483c-11e6-8771-43be0a88c4f0.png)

My PC details:

OS: Arch Linux 
Kernel: x86_64 Linux 4.4.1-2-ARCH
Uptime: 6h 0m
Packages: 1110
Shell: bash 4.3.42
Resolution: 3072x2048
DE: Cinnamon 2.8.6
WM: Muffin
WM Theme: Numix-Cinnamon Gideon (The days of grays)
GTK Theme: Mire v2_Grey [GTK2/3]
Icon Theme: Faenza
Font: Nimbus Sans L Condensed 9
CPU: Intel Core i7-3632QM CPU @ 3.2GHz
GPU: AMD/ATI Thames [Radeon HD 7500M/7600M Series]
RAM: 4644MiB / 7863MiB

**Comment by saenzramiro** [comment]
I think is something with your PC. :confused: 

If you enter your credentials, once you are logged in you close Rambox, and open it again... It ask you for your credentials again?

**Comment by janpansa** [comment]
@saenzramiro yes. This only happens on my work pc. At home, running almost the same distro of Arch Linux, it works fine. Probably something on my pc, but Google Chrome remembers all of the passwords I asked it to remember.

If I logout and re-login, slack sometimes remembers my details, but everything google related forgets my password. Could it be because I use two step verification ? But again, I dont think so as it works from home.

**Comment by Oikio** [comment]
Same problem on arch here. Reopening rambox logs out from all services.

**Comment by bpetrynski** [comment]
I have the same problem on Windows 10 x64. After quitting application and relaunch all the services are logged off, even if I clicked "Remember me". Just reloading a single tab works well, I stay signed in.

**Comment by abhimanyu003** [comment]
I have same issue on Xubuntu 16.04 on multiple systems.

Few additional details

```
Version: 0.4.4
Platform: linux (x64)
Electron: 1.4.1
Chromium: 53.0.2785.113
Node: 6.5.0
```

**Comment by saenzramiro** [comment]
@abhimanyu003 Please, try to reset Rambox. and start again. For that, you can go to Help->Tools->Clear Cache and LocalStorage. Reboot Rambox and try adding one service to check it remembering session works.

**Comment by abhimanyu003** [comment]
@saenzramiro Ok, I did as per your instructions.
After that I logged in to slack and messenger and after re-boot ( restarting Rambox ) I need to login again. Do I have start Rambox with `sudo` user ?

**Comment by saenzramiro** [comment]
@abhimanyu003 I don't think so. Did you check if you have some process in your machine that can be affecting this? Like clearing sessions, etc.

**Comment by abhimanyu003** [comment]
@saenzramiro I just completely re-installed the Rambox and it started working perfectly well. I will let you know you if this happens again.

Many many thanks for your support and great software. :+1:

**Comment by stormy1777** [comment]
I suspect this happens if one runs 'ccleaner' or similar disk cleanups that clears temporary files.
