### ISSUE TITLE
Place all cache directories within ~/.cache

### ISSUE THREAD

**Issue by justpusher** [saenzramiro/rambox#982]
My ~/.config/rambox directory is very large (1.4GB). Most of space is wasted by Partitions/*/Cache directories.   
All cache should be stored within a special cache directory, which is ~/.cache under Linux, and ~/AppData/Local in Windows. All my linux browsers do this way, and that's very convenient, I can delete .cache directory anytime I need to clean up the space. 

### ENVIRONMENT

Version: 0.5.10
Platform: linux (x64)
Electron: 1.7.4
Chromium: 58.0.3029.110
Node: 7.9.0

**Comment by justpusher** [comment]
UPD: maybe this is rather Electron issue, because Slack also stores its cache within ~/.config

**Comment by saenzramiro** [comment]
Right, it's related with Electron. If you want to clean the cache of Rambox, there is an option in Help->Tools menu.
