### ISSUE TITLE
Video stops playing with latest version of Rambox is open 

### ISSUE THREAD

**Issue by jcolesio** [saenzramiro/rambox#983]
### Steps to reproduce

1. Start Rambox
2. Open browser and start a video.
3. Close Rambox to verify video starts to play.

### Expected behavior

Rambox should be running and be able to watch a video on any web browser.

### Actual behavior

All flash based video stops working on all browsers , chrome/chrome based , I.E. and Edge. Video starts to work instantly when Rambox is closed.
### ENVIRONMENT

> Rambox: v0.5.10

> OS: windows 10 Version 1703 Build 15063.447 64-bit

**Comment by saenzramiro** [comment]
Flash is not supported anymore, so please use HTML5 to play videos.
