### ISSUE TITLE
Malware alert on 0.5.10

### ISSUE THREAD

**Issue by dluciv** [saenzramiro/rambox#986]
### Steps to reproduce

(for example)

1. Windows 7,8 or 10 x64
2. Try to install `Rambox.Setup.0.5.10-x64.exe`
3. You'll get malware alert

Or just take a look on https://virustotal.com/en/file/6725a52fcfbbe5a4dc7d2854af229ca9013cea06404e4de4ee99da0aabf0fa89/analysis/ 

### Expected behavior

It should either pass checks or we should have a note about possible false alerts

### Actual behavior

No info about all this

### ENVIRONMENT

> Rambox: v0.5.10
> OS: Many versions of up to date Windows x64
> Arch: x64

**Comment by fweb** [comment]
Resubmitted to virustotal last night. Same outcome.

Metadefender shows all good though:
https://www.metadefender.com/#!/results/file/ZTE3MDcxNHJKdHhaaFlISFdyeXFnWmhZQlMt/regular/analysis

Any ideas on what's going on?

**Comment by dluciv** [comment]
Most likely false heuristic alert on one of standard bundled binaries...

**Comment by saenzramiro** [comment]
It's a false positive. We had that before, it's the way "electron-builder" build the executable. Soon we will have executables signed.

Be sure that it's clean.
