### ISSUE TITLE
Threema messenger WIn 10 not Working

### ISSUE THREAD

**Issue by meikwald** [saenzramiro/rambox#990]
When trying to use the Threema messenger (Win 10 - all updates), i only got a blanc white screen (also no Loading circle), with the blue line at the botten with the text ready. There is no QR code and nothing else in the window ... :-/ (Facebook, xing, whatsapp are working fine)

Using Manjaro (ArchLinux) it is working :-D 

Thanks 4 your Work 

Greetinx
Meikwald

	
	-
	> Rambox 0.5.9
	> Electron 1.7.1
	> win32 x64 10.0.15063

**Comment by SimJoSt** [comment]
I'm using 0.5.10 at the moment, but the rest of the configuration is similar. I have no Rambox-specific problems with Threema Web. All other versions before also worked properly.

**Comment by saenzramiro** [comment]
I will take a look at this...

**Comment by bronoman** [comment]
for me, using Rambox version shown below, Threema QR code shows up but is apparently unreadable by iOS app...

```
Version: 0.5.12
Platform: win32 (x64)
Electron: 1.7.5
Chromium: 58.0.3029.110
Node: 7.9.0
```

**Comment by saenzramiro** [comment]
I think it was a Threema bug because now is working and we didn't do anything. I will close this then.
