### ISSUE TITLE
JavaScript injection works only for custom services

### ISSUE THREAD

**Issue by gnidorah** [saenzramiro/rambox#991]
Is it only for me?

### Steps to reproduce

1. Add some JS like alert( "Hello" ) to injection field of standard service;
2. Wait until service loads
3. Bang! JS code is not executed

### Expected behavior

It should execute

### Actual behavior

It works only for custom service, not standard one

### ENVIRONMENT

> Rambox: v0.5.10

> OS: Linux

> Arch: x64

**Comment by MrChick** [comment]
I'm using KiwiIRC as integrated service with custom server, and I have custom JS working fine

**Comment by saenzramiro** [comment]
Works for me also... =S

**Comment by gnidorah** [comment]
I'm no more need this functionality. Perhaps issue with my distro. Closing for now. Sorry :S
