### ISSUE TITLE
Feature request: Add an option to deactivate the statusbar by default, not "until the next time"

### ISSUE THREAD

**Issue by RMorgado30** [saenzramiro/rambox#996]
### Steps to reproduce

1. Show an option in the settings to deactivate the statusbar by default.

### Expected behavior

Statusbar will not show every time in each service whenever Rambox is launched.

### Actual behavior

there is always a blue bar called the statusbar at the bottom of the screen wich I don't like, and tend to close everytime it appears, which could be avoided with the suggested feature.

### ENVIRONMENT

> Rambox: v0.5.10

> OS: GNU/Linux, Fedora 26

> Arch: x64

**Comment by saenzramiro** [comment]
There is an option in the services settings to remove it permanently.

**Comment by nmat** [comment]
@saenzramiro is it possible though to have a main option that would  disable it globally for all services without having to disable it per service?
