### ISSUE TITLE
Issue: Can't download media on whatsapp web

### ISSUE THREAD

**Issue by FerdinandoLM** [saenzramiro/rambox#998]
### Steps to reproduce

1. Open a media (picture, video) on a whatsapp conversation
2. Click the arrow down symbol on the top bar of whatsapp interface to download the media

### Expected behavior

A yellow text on a darker background should appear on the bottom left part of the window, also the file should be downloaded in the download directory

### Actual behavior

Nothing happens

### ENVIRONMENT

> Rambox: v0.5.10

> OS: Windows 10 Pro 

> Arch: x64

**Comment by saenzramiro** [comment]
Works for me with the same environment. =S

Maybe was a WhatsApp error at that time. Can you check it now?

**Comment by FerdinandoLM** [comment]
At the current time i'm able to download media correctly.

**Comment by adityamhatre** [comment]
Try disabling any ad blockers if any

**Comment by Rickybk** [comment]
@adityamhatre Thanks mate that solve it for me.

**Comment by s10wen** [comment]
Where is the default WhatsApp 'Save Image' location for Mac please?

**Comment by adityamhatre** [comment]
@s10wen , The Downloads folder. 
Or more specifically `~/Downloads`

**Comment by s10wen** [comment]
@adityamhatre cheers, I assumed it was, but I'm not seeing any files there after clicking 'Save Image'. Instead, I opted to use the WhatsApp on my phone and sync to Dropbox to use on Desktop.

**Comment by dESourcesra** [comment]
Unable to download any file from the web whatsapp. Once clicked on the download button, it shows the notification at the bottom but files never downloads.

**Comment by 12ma** [comment]
same thing happening with me dESourcesra...you got the solution??

**Comment by dESourcesra** [comment]
@12ma nope but what I have seen, it happens when you are trying to download some forwarded file. If you forward it to someone and then download it from there it works
